### ISSUE TITLE
[Feature Request] Browser source finished loading web page condition

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#1002]
**Is your feature request related to a problem? Please describe.**
I have a Macro where it shows a user's Twitch channel in the OBS browser source. But I would like the source to only be displayed after the page is completely loaded. Hence this suggestion.

**Describe the solution you'd like**
I would like a new option in the conditions to run a macro after a web page in a browser source is loaded.

**Describe alternatives you've considered**
Currently I only use an action of waiting 30 seconds. Which is not practical at all, as this time can vary greatly depending on what is running on the machine.

**Comment by WarmUpTill** [comment]
I don't think something like this is possible.
The browser source does not seem to offer any "signal" which could indicate that the web page finished loading as far as I can tell.

**Comment by themegaxandy** [comment]
Oh, okay. If it's something out of reach, I understand. And thanks for the alternative idea, I'll try that!
