### ISSUE TITLE
Source "Setting value changed" condition doesn't quite make sense

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1003]
**Describe the bug**
There's no setting to choose when using "Setting value changed" source condition:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/3606072/bccc48db-41f6-4f78-a31c-165005323ea8)

"Setting value matches" shows dropdown correctly:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/3606072/393d9cdd-2eef-4cee-a81f-ddc4417cc2b6)

**To Reproduce**
1. Add source condition
2. Switch to "Setting value changed"
3. No setting dropdown to be seen

**Expected behavior**
There should be a setting to choose from.

**Logs**
Don't think they're needed as the issue is obvious

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: some master version before big directory structure change

**Additional context**
\-

**Comment by WarmUpTill** [comment]
Ah right, thanks for pointing that out!
Should be fixed with the linked PR.

**Comment by Destroy666x** [comment]
Thanks, seems to work fine now.
