### ISSUE TITLE
[Bug] Twitch commands doesn't work

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#1005]
**Describe the bug**
Using the "Send chat message" Twitch action with an command on the message text box, always returns an "Twitch chat notice: Unrecognized command" error on the console.

**To Reproduce**
1. Create a macro with any name.
2. Create a Twitch action.
3. Set your account on the first drop down menu.
4. Set "Send chat message" on the second drop down menu.
5. Set your channel on the third drop down menu.
6. On the text box, put any Twitch command.
7. Check the OBS console, and see that it returned an error: Twitch chat notice: Unrecognized command: /<your command>

**Expected behavior**
Twitch commands should work, and there is a lot of them ([see here](https://help.twitch.tv/s/article/chat-commands?language=en_US)), and since it acting upon the streamer's behalf, all of them should work. If this is not possible to implement commands that way, consider at least adding the /shoutout command. I would love to automate that when others streamers shows up on the chat.

**Version information**
 - OS: Windows 11 22H2
 - OBS Version 29.1.3
 - Plugin Version 498bf31

**Comment by Destroy666x** [comment]
Shoutouts and lots of other missing actions are coming soon™

**Comment by themegaxandy** [comment]
Understandable, have a great day
