### ISSUE TITLE
Feature request: Trigger recording / Start replay buffer based on active scene.

### ISSUE THREAD

**Issue by Aidiah** [WarmUpTill/SceneSwitcher#101]
Allow settings flags per scene on what is auto activated or deactivated when the scene is switched to.

```
Example:
  Scene 1:
    Start recording,
    Start replay buffer,
    Unmute audio source x,
  Scene 2:
    Start replay buffer,
    Disable recording,
  Scene 3:
    Disable recording,
    Disable replay buffer,
```

Streaming could be an option here, by default if no preference is set the property should be left alone.

**Comment by WarmUpTill** [comment]
Sorry about the late reply.

Fist of all thanks for the suggestion!
I added a first version of that functionality with the linked PR.

You can find a test build here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/523901781

Would love to get some feedback! :)

(I haven't implemented any audio source control there yet, but might do so in the future)

**Comment by WarmUpTill** [comment]
I now also implemented the muting of audio sources.
A build will be available here in a couple of minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/524048417

**Comment by Aidiah** [comment]
You're a saint, where can I send you coffee/beer money?

**Comment by WarmUpTill** [comment]
No need, but thanks for the offer! :)

FYI:
The most recent release does contain these changes also.
