### ISSUE TITLE
Twitch actions not showing you're not authenticated anymore

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1011]
**Describe the bug**
~~It briefly appears and then disappears. Nothing appears in the dropdown. Search "works" but the results are added to that popup.~~ See comment below

**To Reproduce**
~~Steps to reproduce the behavior:~~
1. ~~Attempt to pick a Twitch category~~
2. ~~Nothing appears in dropdown~~

**Expected behavior**
~~Dropdown should be filled~~

**Logs**
https://obsproject.com/logs/tf1ZNope8LYLflFH

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: latest template one

**Additional context**
~~I'll check quickly what it could be as I really need this functionality, but a lot changed so not sure I'll find the culprit.~~

**Comment by Destroy666x** [comment]
Never mind. Just noticed this is a different bug. I was not authenticated (I guess loading backup removed the token or it expired). But it showed that nowhere in the UI. I remember there was a red warning for insufficient permissions. I think it should also cover the case of losing authentication.

**Comment by WarmUpTill** [comment]
I added more warnings in the linked PR.

**Comment by Destroy666x** [comment]
Ah. I see we made PRs with different approaches:
- yours has better UX and messages
- mine has better coverage as there are more places that use those functions

Something in the middle would probably be best

**Comment by WarmUpTill** [comment]
I would simply merge both.
I can't see any obvious conflicts.
