### ISSUE TITLE
Source "Setting value matches" and "Setting value changed" are broken for variable source choice

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1015]
**Describe the bug**
If you pick a variable for Source condition and then switch to `Setting value matches` or `Setting value changes`  actions, there's nothing to pick for value dropdown

**To Reproduce**
1. Pick a variable for Source condition
2. Switch to `Setting value matches` or `Setting value changes`  actions
3. Check value dropdown, nothing there

**Expected behavior**
Not sure what the best solution here is. Would be easier to handle if there were more variable types - string, int, QImage and in this case obs source. But that's a whole another proposal. Probably disabling those actions for variables would make the most sense now. Or maybe showing variables in the dropdown like in e.g. Filter action.

**Logs**
Shoiuldn't be needed

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: latest template version

**Additional context**
\-

**Comment by WarmUpTill** [comment]
The setting value selection will be based on the value the variable currently has when the widget is created.
If it has a value which does not match any source name the settings selection cannot be populated.

I added a "refresh" button to enable manually refreshing the selection based on whatever value the variable has at the moment the button is pressed. (https://github.com/WarmUpTill/SceneSwitcher/pull/1008/commits/67354837207dad8cdcb987619e40097a84f294f0)

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/8b3ef107-ef6a-40d7-8851-1269e03b5499)

**Comment by Destroy666x** [comment]
I'd also recommend using vars there, but closing for now
