### ISSUE TITLE
Audio fading fail

### ISSUE THREAD

**Issue by ogmkp** [WarmUpTill/SceneSwitcher#1016]
**Describe the bug**
When I set in a macro that when a source appears it must do an audio fade over a duration of 5 seconds or a rate of 20% per second, when the source appears the volume bar goes from 0 to 100 immediately without progression.

**To Reproduce**
1. Go to 'Macro'
2. Choose If source X is active, choose audio action and define volume source X to fade for a duraction of X seconds.
3. Switch to the scene or use downstream keyer from exeldro.
4. The progress bar jumps from 0 to 100 (-inf to 0 dB)

**Expected behavior**
That the volume bar gradually increases as set.

**Logs**
```
03:13:16.643: [adv-ss] performed action "AdvSceneSwitcher.action.audio.type.sourceVolume" for source "Mic/Aux" with volume 100 with fade 0 5.000000
03:13:16.643: [adv-ss] performed action "AdvSceneSwitcher.action.audio.type.sourceVolume" for source "MEDIAPLAYER" with volume 100 with fade 0 5.000000
```

**Version information**
 - OS: Linux Debian 12 Bookworm
 - OBS Version 30.0.0
 - Plugin Version 1.24.2

**Additional context**
You're doing a fantastic job! Thank you for this project.

**Comment by WarmUpTill** [comment]
According to the log lines you shared the fade option was not checked:

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a4d8a7d4-6e78-4cb0-b352-4bdf38f6c54e)

That is my bad!
I should have disabled the inputs for the fade options if the fade checkbox is not checked to avoid this.

**Comment by ogmkp** [comment]
There's a box to tick! Ha ha, on my theme it's invisible but I can tick it!

![Capture du 2024-02-10 03-30-22](https://github.com/WarmUpTill/SceneSwitcher/assets/17526713/414002c0-f8cb-458a-a2a2-a74334439429)
![Capture du 2024-02-10 03-32-45](https://github.com/WarmUpTill/SceneSwitcher/assets/17526713/5494f5cd-b141-4129-9f08-c84323814e58)
I checked and it works ;D
