### ISSUE TITLE
Variable rename switches variable in other actions

### ISSUE THREAD

**Issue by filiphanes** [WarmUpTill/SceneSwitcher#1018]
**Describe the bug**
When I rename variable in some first action, it is correctly renamed in other actions. But some actions switch their variable this renamed variable, which brakes macro, and manual fix is required.

**To Reproduce**
1. Import macro from additional content
2. Rename loopCount, via Cog wheel > Rename
3. Watch how loopIndex in other actions is replaced with loopCount's new name
4. Now I can't reproduce it every time, but I can reproduce it with high probability.

**Expected behavior**
Rename should rename only uses of the same variable.

**Before rename:**
<img width="692" alt="Snímka obrazovky 2024-02-12 o 13 56 25" src="https://github.com/WarmUpTill/SceneSwitcher/assets/33264909/8504da37-0252-4d9b-a144-dc547bdaafb3">
**After rename:**
<img width="692" alt="Snímka obrazovky 2024-02-12 o 13 58 15" src="https://github.com/WarmUpTill/SceneSwitcher/assets/33264909/75e4ad6c-ebe0-4076-8703-96fe0b4401c4">

**Version information**
 - OS: MacOS
 - OBS Version 30.0.2
 - Plugin Version 1.24.2

**Additional context**
Exported macro:
`AAAPg3ic5VdtbyI3EP4rltVK7RU4lrxcyzdCczpOScOFNFJVRSdn1ywWXnu19hIo2v/eGe96X45c0lT90DZIGHs8b555Zmz2NGFhpg0d/76niiWcjumF1ikRlieG9mjKcgPEJZOG4ypjUnJJxzbLYa3VdMVUzP3arEV6vuXhlVpYltlaLs50ntarSIfrBbdWqBgM72nGY2Esz7yWFTPXuTrLrdWqRZujKwdUMGRzc8Hu0avKwErEKwlfO1tOtYqEFVqZG5CoOTKv/4ZvwU0K9vxhO3RnE3Zydbj3a0mD3bBjpPSoYmrsE5Zxgm4POhLv0aGnRJzHKCPMe6kZRs0fX5hbYcS9bM4FAoyOhxBxrhNusx3om0Tq0+5h8vPEfS6mMJydxjAer2H4iLPpA47LIQxXH3H926T5nPG4lnv7qZGjRa9EzyREb2u3F6kUFtI518atHbZSxNhP74peNT0dHhV3lfw5uF7q+LroyelJLTtESQ+aD9qu+c60IAo5KYkgfVenrk2yOo4ln39JbpLi7IZaSpYaHtW6BUypFQlAtUeljkXoYh3lGUOxSx2JpUAc7x3XZ1BobMaEso7PcLTgIL9hEtFYT4YD2Le7FKcF+ixKkQ3PjItDUBQ1Q2PxMVU/Dk6eU9UoGP1NZzD+CRzMgdFZNGzDrxtaOxtNALXiZqWbvtDSCPFn4bPB37BMMAR8j3KFk8jXgt/5pWxiEppYSBvyqKLPFBxSRMTR5T0nhkvu7AIzJOu2DAGFlcqT21ZAanSAt0eYzDjhys6iLR33A1jn9wubwdmrzjdsk8QfZd4AtHw7ZwhxUEMHb2hFu2Q2XDldwLUUKgJBYMCOQKwmSHGsqWQh7+5VRPIg7Mqrg1pcihhTWkap3cAtnLvu32kV8aGrZbs636YZN2VO6HckID+QEXlDjsj35C05xkZo+DQ3VifzTCdpk0mh0tx6Gp2AilgRhyf00WdhXGqYOWb0eqVlhAXT0dLeoP0+RJlnxMJx+32X943ItMLg33Zz/uHq8hyzGHLFF3VasRh93VQ33DVfS5bssIHBNZeCmg6X8Dl1kKMFNp6v4NHZ+rzBLiygde0OcfkibxzzDHx6ROCo9Oym4yX+qohvW9UbNKCv6mDmOHxJu07CKuXBE2d7Ua15G/9IvQVf1tvwVdTbN/s6kgX5lpTLqc6VLaAOg/9L9V3m0oqN4A+P1l/QQrarsOrSfKoK/z1IffdKgJr4HGKzaiG2QzevDbsHd8dfAe9//Qpxr3FeP+Hx+XaHJK+h89+yrQtfjBN/D/W8bTqCrYgvGUTal1xAMX6VCvxn6tLW1TA8kGoLbYKXsY9exO4fm89J3LVevDQYjI4HI1r8CR4GRJc=`

**Comment by WarmUpTill** [comment]
Thanks for pointing that out!
The problem should be fixed with the linked PR.

A build with the fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7944691854?pr=1024

I would appreciate if you could give this a try and report back if everything works as expected on your end as well.
But before doing so please make sure to [back up your settings](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) just in case.

**Comment by WarmUpTill** [comment]
Changes were merged to master, so I will be closing this for now.
Let me know if you should run into any issues! :)
