### ISSUE TITLE
Action Audio Set source volume not enough resolution

### ISSUE THREAD

**Issue by filiphanes** [WarmUpTill/SceneSwitcher#1019]
**Describe the bug**
When setting source volume using action Audio Set source volume, it is not possble to set volume between -40 dB and -96 dB.

**To Reproduce**
1. Create Audio action
2. Try to set volume to -50dB
3. Not possible because 1% is -40dB and 0% is -inf dB

**Expected behavior**
Source volume should be configurable in range [0.0, 1.0] exactly as it is in Condition Audio Configured volume level value.
It would even help to control via midi using calculated variables because their results are decimal numbers.

**Logs**
<img width="615" alt="Snímka obrazovky 2024-02-13 o 17 37 36" src="https://github.com/WarmUpTill/SceneSwitcher/assets/33264909/e41fafb0-916b-431a-9a43-4d1ed680d405">

**Version information**
 - OS: Windows 11, MacOS 14
 - OBS Version 30.0.2
 - Plugin Version 1.24.2

**Comment by WarmUpTill** [comment]
The master branch releases have the option to specify the desired db value directly:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/7d659d0d-e73d-4f80-bf19-3e6050d99e31)

A build with this functionality is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7857723928

Let me know if that solves your problem or if I should make further adaptions! :)

**Comment by filiphanes** [comment]
Great, that is usable, dB units are linear with faders, so no need to calculate logarithms :)

And would it be possible to use same value from Condition Audio Configured volume level and this?

P.S: dB unit should be written with capital B ;)

**Comment by WarmUpTill** [comment]
>And would it be possible to use same value from Condition Audio Configured volume level and this?

Sure I will look into it.

>dB unit should be written with capital B

Ah cheers! :)
I will fix that!

**Comment by WarmUpTill** [comment]
I added the option to use dB values in the audio condition with the linked PR.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/f32bae1d-4aab-4675-a977-8065b60140d0)

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7942704609?pr=1021

Let me know if everything works as you expect!

**Comment by filiphanes** [comment]
it works great, thanks
