### ISSUE TITLE
Copying macro with Source Set settings action doesn't copy setting name

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1022]
**Describe the bug**
As title says, e.g. for Text source it gets reverted to Font.

**To Reproduce**
1. Add a macro with Source `Set settings` action
2. Copy macro
3. Setting name is not copied

**Expected behavior**
Should be

**Logs**
Not needed

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: latest new template

**Additional context**
\-

**Comment by WarmUpTill** [comment]
I am probably just missing some obvious step, but I am not able to reproduce it.
Tried with variables and without.

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/838683ef-c686-4a01-a0b2-63cd74973a99)

Do you have any idea what I am missing / doing differently?

**Comment by Destroy666x** [comment]
Ye I can't reproduce anymore on latest master with the same macros either - maybe it got fixed by something. Unless it's some random edge case like newly added macros/actions, but from our gif it seems those are new. So no idea = closing.
