### ISSUE TITLE
Suggestion : Macro action to print to log

### ISSUE THREAD

**Issue by Penwy** [WarmUpTill/SceneSwitcher#1042]
**Is your feature request related to a problem? Please describe.**
The obs log is a very helpful tool both for troubleshooting stuff, and for tracking what happened in a session.
Adv-ss has a verbose mode but it is *very* verbose, so not necessarily easy to navigate for such purposes

**Describe the solution you'd like**
I'd suggest adding a macro action that allows printing a user-defined message or variable to the OBS log.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WarmUpTill** [comment]
Good point / good idea!

I introduced a new log level to chose from which only prints the action logs:
![Log](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/ec943ef3-91f0-43a7-bf80-e836a747f4c7)

I added the "Log" action which lets you write custom logs to the OBS log (with the `[adv-ss]` prefix just to avoid potential confusion with logs from other areas of OBS):
![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/05df1852-7da5-4b31-8e9e-5c26c36f4816)

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8122388368?pr=1039

But I plan on releasing a new version later today (?) any way and I don't expect any issues with such a simple action.
