### ISSUE TITLE
Regarding macos builds for 1.25.0

### ISSUE THREAD

**Issue by adithyasunil26** [WarmUpTill/SceneSwitcher#1046]
I noticed that the `macos-x86_64` and `macos-arm64` builds are not available for the latest release. Are the builds pending or will the `macos-universal` remain the only `macos` build available for version 1.25.0?

**Comment by WarmUpTill** [comment]
The `macos-universal` variant will remain the only one.
It happened too frequently that MacOS users installed the wrong variant for their system.
The space requirements are a bit higher with the universal variant, but I guess that should be acceptable for most.

**Comment by adithyasunil26** [comment]
@WarmUpTill Thanks for the info!
