### ISSUE TITLE
Crash when open plugin in obs

### ISSUE THREAD

**Issue by azultax2123** [WarmUpTill/SceneSwitcher#1047]
OBS version 30.0.2(64 bit)
Crash log:

[Uploading Crash 2024-03-03 14-52-25.txt…]()

**Comment by WarmUpTill** [comment]
I think something went wrong when you attached the crash log.
The link only links back to this issue page and not to the crash log file.

**Comment by ASchneiderBR** [comment]
Hello @WarmUpTill, long time no see :) I'm also having a crash, just after clicking OK on this:

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/25224882/0c73612d-cb76-4f18-860e-eae2c75918ac)

Here's the log file: 
[2024-03-03 14-28-29.txt](https://github.com/WarmUpTill/SceneSwitcher/files/14473918/2024-03-03.14-28-29.txt)

Crash log:
[Crash 2024-03-03 14-29-07.txt](https://github.com/WarmUpTill/SceneSwitcher/files/14473924/Crash.2024-03-03.14-29-07.txt)

Congratulations on keeping this great project always with new fresh tools, really powerful stuff!

Thanks.

**Comment by WarmUpTill** [comment]
Thanks a lot @ASchneiderBR for sharing the crash log!
I think I was able to identify the issue.

A build with a fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8132316260?pr=1048

Can you please confirm that this build fixes the issue on your side also?
If so, I will release an update right away! :)

**Comment by ASchneiderBR** [comment]
Hello!

Working great now:

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/25224882/f139ba33-32b5-4ccf-86d6-807f83e1addd)

Thanks for the quick fix :) Have a great day!

**Comment by azultax2123** [comment]
https://pastebin.com/CNKP7vM7

**Comment by azultax2123** [comment]
1.25.1 works fine
