### ISSUE TITLE
"Macro already exists" error if you rename group to the same name as some macro

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1054]
**Describe the bug**
Not sure if intended, but if so, the error message could be improved, as it's conflict between 2 different types of entities, not the same one.

**To Reproduce**
1. Add a  macro called "Test"
2. Group it and rename group to "test"
3. It won't let you

**Expected behavior**

**Logs**
\-

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: latest master

**Additional context**
\-

**Comment by WarmUpTill** [comment]
> the error message could be improved

Indeed.
The error message dialogs should be improved with the linked PR.
