### ISSUE TITLE
Send Websocket message to OBS Browser Source

### ISSUE THREAD

**Issue by UUoocl** [WarmUpTill/SceneSwitcher#1064]
**Is your feature request related to a problem? Please describe.**
The [OBS Browser Source](https://github.com/obsproject/obs-browser?tab=readme-ov-file#obs-websocket-vendor) includes integration with obs-websocket's Vendor requests. The vendor name to use is obs-browser.  
I could not figure out how to configure Advanced Scene Switcher to send messages to a Browser Source.  I tried various settings, but none worked.  

External connections work using calls like this.  
``` javascript
obs.call('CallVendorRequest', {
     'vendorName': 'obs-browser',
     'requestType': 'emit_event',
     'requestData': {
         'event_name': 'custom-event',
         'event_data': {msgContent}
         }
     })
```

**Describe the solution you'd like**
The requested solution is a websocket action setting to send a message to all OBS Browser Sources.  The Browser could listen for the event using the integrated obs-websocket custom vendor event.   

**Describe alternatives you've considered**
I've used Lua scripting to send Keyboard and Mouse events to OBS Browsers.  I've used external apps to send messages to an OBS Browser. An Advanced Scene Switcher solution would have advantages over these alternative solutions. 

**Additional context**
No web socket server connection is needed for the Browser to use the integrated websocket events. The custom events use the vendor name "obs-broswer". 

Thank you

**Comment by WarmUpTill** [comment]
I think something like this should do the trick:
```
{
    "d": {
        "requestData": {
            "requestData": {
                "event_name": "custom-event",
                "event_data": "my-custom-data"
            },
            "requestType": "emit_event",
            "vendorName": "obs-browser"
        },
        "requestId": "someUniqueIdHere",
        "requestType": "CallVendorRequest"
    },
    "op": 6
}
```

So the macro action would look something like this:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/f2dc056c-a99f-4f34-b537-925a7f3c4185)

Does that not work?
