### ISSUE TITLE
Bug - 'Set to environment variable value' with wrong variable crashes OBS

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#1067]
If I use `Set to environment variable value` and input an invalid environment variable such as `DATE `or `TEST` then OBS always crashes when the Macro is run.
Tested on two Windows 11 machines.

Log file
[2024-03-20 15-04-00.txt](https://github.com/WarmUpTill/SceneSwitcher/files/14662248/2024-03-20.15-04-00.txt)

Crash log
[Crash 2024-03-20 15-04-20.txt](https://github.com/WarmUpTill/SceneSwitcher/files/14662249/Crash.2024-03-20.15-04-20.txt)

**Version information**
 - OS: Windows 11
 - OBS Version 30.1.0
 - Plugin Version 1.25.3-20 (also tested with 1.25.3)

**Additional context**
I believe `%DATE%` is a valid environment variable so it should work.
Ultimately what I was trying to do was run something like `%DATE:~-4%` or even use OBS's own filename formatting variable `$Y` to get the current year as a variable. Another method would be to store the results of cmd.exe via the run command as a variable, but that's not supported so I can open that as a separate feature request once this is fixed.

**Exported Macro**
`AAAGh3icfVRNc9owEP0rGp3aNKYGkkyHW0rolJk2pSHJpeQg7MXWIEseSSakDP+9K8k2dtPm4Bnv037p7VsdaMESrQyd/DpQyQqgEzqTO66VLEBa8sg0Z2sBZKqZyek5LVll0GnDhAFnaSYEiBZQcpozmaGH1RXaZsvL2R6SH3Jpmbatn7GqvE4sV9LMN7fK3ih5ypppVZWtlapkuwRrucywzQPVkHFjQbcOOTN3lfxcWatkUxexhev0FYpt2Mp8Y+tO0znPcoGfnW+mSqbct3WPEa2HbvLfwx4vQbFew0UP9zXxpJKvzx4ChqdJr0joqHY61SdMA3FtD3oRX1xDb4X4jgf0eB4mG0hufZal4BbJWyjjbT/30s1/fHF1PO/8P9UJZpguJHkjNv7UxsYuspnRV2W38GI6ekEGAojRTy1RXciqLBOw+Bs+URBsljTGAc+EYKWBtC3E8ZfuavEigSDdT9oIoTm5DYq3YCw9oaManssdEzwlHhdrIAYE+LLUKVg/MuE0QtGSVVFb8SDuNEsnwxH6Qua2aZ7u6SQaol2tl1ajoOuliLsQ/w0eQQ5hv2COcUxDB2e0xr4zm+Q+F3ptuEzvHOpWI9yyu50WGz8tZ1lTFh9DIFbEzE5HxCriEF+jFCyB/lkNkmdu86YPFNWGZ2/VDWT3yhbM5rN9qcEYTw99R4bkAxmRMzIm78lHcuHWx8C0wieiWGhVlKdXg8uysg1GrzFFJnE6yLvrsRnfJGSYe2fXda5E2nkv+KsDGkU4HtDE4nWjyOulfQMf+1q5ub6fufEnIGHZ6gFJsC9lGFz9jLoVtFCUGN875o0KvEadl881R9+5TMMgd0FL6FSHHd1WQbuKfgcc1Ny594A/A2xdi2xXu/tMdU7qCE5hwyphWwG77ZW9XfhP8HSyWj0Y0Ga12vL1+uVfudrl/FlBBfW67jAmDHw4GF0OxtEojjK4urpML8b0+AfpPz8C
`

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

A build with a fix for the crash will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8380841186

But what you probably want to do is set up a macro like this to set up variables containing the date specific data:

![1707002475935](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/27dfff4f-7df3-41a0-a97c-4a159e7ee554)

You can import it using this code:
```
AAAVXnic7VhbbyI3FP4rlp/abaAMm220vG2zRIu0aVDIpqqqqDIzhxmLwR7ZHhYa8d97jj03GnVLSx4HgTT+zsXn8tmD/cw3Ijba8snvz1yJDfAJX4BjH4UD9iiMFMscLL/ghSgtClcit0AjI/Ic8gbQ6joTKm017FoW0x3Ed2rhhHENnhpdFs0o0fEap3NSpRjCMzeQSuvANAqZsPel+rl0Tis+caYM2JyieYHiTK60n8WyE1gm0yzHn5utrrVKpJNa2Qe0aDRM7f8Bdhgnx/nqfI9wPydKSvVS9iVgKI2PJgkRVUrt/EwYYBT28MjihgL6lomPeMgPF6FrH2ISNTqLIpcOizfX1o99TwvqbfT+3eGier56d3V4qhxM0V1w8s+2V9H7xnZElnWPPmm3hr3tcAIrEEC0fmoK1YWcTtMc5n+H2xL4eWOd56KwkDS+JT7yBDmJ9cp1KmOMBdlTGkFWtzqRK0mseeZObuAP9GedEVI5r2eBJvAE24qcWt88jIYod/uCHg8UsgwmWzDWlyE6IJyI/d3qV4C1lzXRhiAwqgcZFk6p2A0s2SUbjSbR28koYuPR+JK3SuNvaslUaQO09NrEPRT8B54bKEC066ksyPeduq/goFRX5n+m3Mn4OoN4XbstBHEEVfgQP+z4y4kcIv7XNm6rXQUTBkUPSe2+lvwS9qHfQBjeouMKnilMRCbM4/kSmIUc/LSojG1/DGlyHKly89hJutO46CeiRboB5WbJjk8GEY7L5cIZ3IqqHWvUheSf4BFkP+zmbR3e8Aq7FS7OvC/UWkmVoCEq0EJmTjNCvGqRixiOZRXIvkqX1e5wVa9kSm0LRepuvQ7zrmumi6rgI78ruGy6KwzY0En+HYvYD2zM3rC37Hv2IyOW4dq7Lq3Tm7nRm6JlklRF6WqMf0AXqWKeMxRj3YVJ8DDzyhR1pvOks2HLFwI+GGCVwTCH6Q4Gvu1babSi4j8et/zLYno/v7+7mX2eUjNjULBoukurO9D2on5V0VboYFOgm1YcEdFCHzzh9sSjA21i5zLyVivfoZ6SPSXPouTGE+lVOPlR7HtG9ow8l5H4wn8dPn7SZf/W7gl5NiEz4tHrvLWlKv3Joedkz8nzXtuBSa/CyoU/lPas7Fl5LivD9QayEs/f0Nzo0Bn8iaA6s6M7vupsbcW2Ug93GbASZe4ahhHP1fHR53SL8Mf0dP3qj8N/CKne1083aRbd6SYPYN0JBk+dCxQeDceXwzE//AVvTSre
```

**Comment by BenJamesAndo** [comment]
Tested and no more crashes. Thank you.
Excellent solutions to grab date values as variables, cheers.
