### ISSUE TITLE
[Bug] The queue system runs disabled actions.

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#1074]
**Describe the bug**
I noticed a bug, which I don't know if it's intentional or not. But when a macro is added to a queue, all actions for that macro are executed, including those that are disabled.

So, if you make a macro 1 in which there are actions where you deactivate some actions of a macro 2, and then add macro 2 in a queue, the actions of deactivating the actions of macro 2 will have practically no effect because all Macro 2 actions will be run anyway.

Again, I don't know if this is intentional behavior, but it would be useful to be able to activate or deactivate actions in a macro before adding the activated actions to a queue. And also that the queue remembers which actions were activated in case another macro modifies them later (assuming that the run macro in parallel toggle for the macros involved is deactivated).

**To Reproduce**
1. Create a Macro 1 and a Macro 2.
2. Add an action in Macro 1 to add the actions from Macro 2 into a queue.
3. Add a disabled action in Macro 2 to create a toast saying "Action 1 performed". Also add an action in Macro 2 to create a toast saying "Action 2 performed".
4. Manually run Macro 1.
5. Note that all Macro 2 actions, including those disabled, were executed.

**Expected behavior**
In the example above, only the toast action saying "Action 2 performed" should appear.

**Version information**
 - OS: Windows 11 23H2
 - OBS Version 29.1.3
 - Plugin Version 1.25.3

**Comment by WarmUpTill** [comment]
Good catch!
That is not intended.

A build with a fix (and the other issue you raised) will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8473184858?pr=1072

**Comment by themegaxandy** [comment]
Tested and working as expected.
