### ISSUE TITLE
[Bug] Stopping a queue within a queue's execution causes OBS to crash.

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#1075]
**Describe the bug**
If the action of stopping a queue is performed while running a queue, it causes OBS to crash. See the steps for more details.

**To Reproduce**
1. Create a Macro 1 and a Macro 2.
2. Add an action in Macro 1 to add Macro 2 actions into a queue.
3. Add an action in Macro 2 to stop the queue.
4. Manually run Macro 1.
5. OBS will crash.

**Expected behavior**
OBS shouldn't crash. Queue actions should be paused normally until they are continued by an external macro. The intention in doing this would be to create a control for the queue, so that it is only executed when a condition is met.

**Logs**
A crash log file cannot be generated because the obs crash folder remains empty even after the crash. 

**Version information**
 - OS: Windows 11 23H2
 - OBS Version 29.1.3
 - Plugin Version 1.25.3

**Additional context**
Here is the export of the macros from the example above.
```
AAAGoXic7VVLTyMxDP4rVc6lKlNe2xuv1SLxKNuylxWHMONOo4ZkSBwEqvrfcZJJ2gHtavfGgUOl8Wd/9mfHVlfskZdGWzb+vWKKPwIbsyuP9HZZnzXcWULmXFrwluFSgsyAVqcLrmqKQOPItkvRnL9AeaOmyA3mOIu6OS5RaGUv5tcaz7TaZK2Ndk22Kl0up4AoVE2aVsxALSyCyQELbn86deIQtUp1CZt4pR9QkoHOXvKHLdELUS8k/fBifqpVJYKsGTFyhEn5Z/BCTTCql2bRwUNN8jj10XcXMfKWnSJRURu0qd/jBnpe9qDD+O4F/Y0SFA/Yuh+fMQ45x0wbKZCGN9E22OGRG//Yw3W//Rp921vft/RzShZT/Jk52j/I3KFnphf6oXEJr3ZrW6j/CBL7Po9pG0Jd1xIm7+HNAKLNy2SsyCclbyxUuZCgT/bkwPlpg+IP0jvjDoS28koXLOUi7f2WM2YzsMh8K5D7D4V9n52TKP7nJNLuf93E1018qptIF1D8wwUQ9MyN8PxO3VtP7PxphBRhT9pN9wscCxqwWj7Dr5ToRh1XrZpQAIwNgtjuoNgfjHaKYqc+3KvKYXnE1m+kQFnD
```

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
I did indeed not handle the case of the queue being stopped from an action within the queue itself.

A build with a fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8472923869?pr=1072

**Comment by themegaxandy** [comment]
Tested and working as expected.
