### ISSUE TITLE
Checkbox icons, instead of collapse/expand icons on macro groups

### ISSUE THREAD

**Issue by Tpal12** [WarmUpTill/SceneSwitcher#1078]
**Describe the bug**/**Expected behavior**
Since I updated to OBS 30.1.1, there are checkboxes instead of expand/collapse icons on the macro group visibility switches.
![wrong icons for groups](https://github.com/WarmUpTill/SceneSwitcher/assets/164423469/eb35b5ca-255b-45de-aa96-f0ef54a31dfb)
**Version information**
 - OS: Windows 10 22H2
 - OBS Version 30.1.1
 - Plugin Version 1.25.3

**Comment by WarmUpTill** [comment]
Should be fixed with the linked PR.
A build is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8590528717

Thanks for reporting the issue! :)

**Comment by Tpal12** [comment]
Thank you! :) 
I can confirm, that the correct icons are now displayed.
