### ISSUE TITLE
Source Index Range sets end value to start value when saved

### ISSUE THREAD

**Issue by HawkAtreides** [WarmUpTill/SceneSwitcher#1081]
**Describe the bug**
When creating a macro action that uses the "Sources in index range" selector, the index range is not saved properly; the end value is set equal to the start value

**To Reproduce**
1. Create a macro action using the "sources in index range" selector
2. Change the start and end values of the range, either to other numbers or other selectors
3. Close OBS and reopen it
4. See that the range is reset to an equal start and end value

**Expected behavior**
The end value of the range should be persisted properly

**Version information**
 - OS: Windows 11
 - OBS Version 30.0.2
 - Plugin Version 1.25.4

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
A build with a fix is available here thanks to @Destroy666x:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8641927997
