### ISSUE TITLE
OBS Forum Page minimum Version is outdated

### ISSUE THREAD

**Issue by BlazingTwist** [WarmUpTill/SceneSwitcher#1085]
**Describe the bug**
On the Forum Page, the listed minimum OBS version is 28.0.0 for SS-1.25.4.
However, the GitHub releases page lists OBS 30 as the minimum Version, starting with SS-1.25.0

**To Reproduce**
Open https://obsproject.com/forum/resources/advanced-scene-switcher.395/
Observe `Minimum OBS Studio Version: 28.0.0` and Title: `Advanced Scene Switcher 1.25.4`

**Expected behavior**
Listed minimum version is 30.0.0

**Logs**
```
06:34:34.142: Skipping module '../../obs-plugins/64bit/advanced-scene-switcher-lib.dll', not an OBS plugin
```
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/39350649/c364073e-d0f7-4954-9d67-0aa399df8779)

**Version information**
 - OS: Windows 10
 - OBS Version 28.1.2
 - Plugin Version 1.25.4

**Comment by WarmUpTill** [comment]
Thanks I have updated the plugin page! :)

Unfortunately, the minimum supported OBS version differs for the different platforms.
But it's probably best to mention the version supported on _all_ platforms.
