### ISSUE TITLE
[FEATURE REQUEST]: QUEUE PAUSE & RESUME

### ISSUE THREAD

**Issue by MinecraftNight4** [WarmUpTill/SceneSwitcher#1089]
I'm experimenting with Queues and I have found a limitation.

I have a trigger which starts the Queue and plays a video, what is the problem? The videos that I use, have a different duration, making it difficult to have a way to set the wait time to an exact amount of time.

What do I propose? Have two new actions available in the "Queue" tab:
- PAUSE: Allow the Queue to not be able to continue, but allow to continue accepting new triggers.
- RESUME: Allows to continue the Queue from where it has been paused.

**Comment by WarmUpTill** [comment]
I apologize if I am misunderstanding something, but you can already pause queues using the "Stop" action.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/179d9f60-c617-4000-a026-1212d6130a97)

While a queue is stopped / paused it will still accept new elements and add them to the end of the queue.

Similarly it should also be possible to resume the queue execution using the "start" action.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/1c66d68d-12ef-41d9-99c7-342c368c3b8d)

Is this what you were looking for?

**Comment by MinecraftNight4** [comment]
Okay, I was trying to create an example where the queue stopped adding accepting content, but...
Now it seems to be working as I had planned... I don't know how to recreate this problem xP

I will keep this thread open for a little while longer if I can recreate this issue, but everything seems to be fine now.

**Comment by MinecraftNight4** [comment]
Okay, I'm more confused than before. Now the macros I made work. 
I guess I can close this, maybe some extension is causing problems to Scene Switcher or something.

Thanks for the help!
