### ISSUE TITLE
buildnumber file is a problem for Debian (Salsa)

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#1090]
**Describe the bug**

Dear @WarmUpTill,

When building the package obs-advanced-scene-switcer on Salsa (the GitLab with CI for Debian), I got the following message:

```
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_PROJECT_NAME is advanced-scene-switcher
-- advanced-scene-switcher configured for out-of-tree build
CMake Error at cmake/common/buildnumber.cmake:15 (if):
  if given arguments:
    "true" "AND"
  Unknown arguments specified
Call Stack (most recent call first):
  cmake/common/bootstrap.cmake:67 (include)
  CMakeLists.txt:16 (include)
-- Configuring incomplete, errors occurred!
	cd obj-x86_64-linux-gnu && tail -v -n \+0 CMakeCache.txt
==> CMakeCache.txt <==
# This is the CMakeCache file.
# For build in directory: /builds/debian/obs-advanced-scene-switcher/debian/output/source_dir/obj-x86_64-linux-gnu
# It was generated by CMake: /usr/bin/cmake
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
```

So, I commented out all code from cmake/common/buildnumber.cmake and Salsa was able to build the package. The faled pipeline will be available here some days[1]. Salsa runs Debian Unstable.

Thanks in advance.

[1] https://salsa.debian.org/debian/obs-advanced-scene-switcher/-/pipelines/669168

**Comment by WarmUpTill** [comment]
It should be fixed with the linked PR / commit.

Alternatively you could circumvent this defining a value for `PLUGIN_BUILD_NUMBER` during the cmake configure step. 
For example: `-DPLUGIN_BUILD_NUMBER=1`
But that is probably not desired.

A bit off topic, but I spotted it in the build logs:
Is this workaround still required on your side or is this just a left over from past workarounds?
`[ -d deps/libremidi ] && rm -rf deps/libremidi || true`

**Comment by eribertomota** [comment]
> A bit off topic, but I spotted it in the build logs: Is this workaround still required on your side or is this just a left over from past workarounds? `[ -d deps/libremidi ] && rm -rf deps/libremidi || true`

Thanks! Testing without this workaround. I think this is no longer needed.
