### ISSUE TITLE
"[Notification System] action" have the text rows out of place

### ISSUE THREAD

**Issue by MinecraftNight4** [WarmUpTill/SceneSwitcher#1093]
**Describe the bug**
I'm currently using OBS with Spanish settings, and I'm not sure if this issue only affects on Spanish version or other langs are affected too. But here is the issue:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/f9e1f9bb-d86f-4537-b305-547f5f894a5c)
For some reason the first row of **text input** have an empty space.

**To Reproduce**
1. Open Advanced Scene Switcher.
2. Create a macro
3. Create a new action
4. Select "Notification" option
5. Tadaa!!

**Version information**
 - OS: Windows 10
 - OBS Version 30.1.2
 - Plugin Version 1.25.4
 - Log files: https://obsproject.com/logs/nbEZY8epDL8PECb2

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue! :)
This does indeed not only affect the Spanish version of the plugin and was a regression I introduced a while ago. (A typical off-by-one error)

A build with a fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8822233015?pr=1094

**Comment by MinecraftNight4** [comment]
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/5e32e98e-99b8-4540-8125-cf13cb4d2e13)
I can confirm that the issue was fixed!
