### ISSUE TITLE
OBS Crashes after creating an action

### ISSUE THREAD

**Issue by MinecraftNight4** [WarmUpTill/SceneSwitcher#1096]
**[+] Describe the bug**
I'm not sure if this is due to the freeze that occurs because Scene Switcher changes the selected macro preview or if it may be due to something else. I only know that this happens when I try to create a new action or trigger.

**[+] To Reproduce**
I don't have an exact way to reproduce this problem, I only know that it occurs when trying to create a new action or trigger.

**[+] Logs**
[OBS LOG](https://obsproject.com/logs/NelCFOFNhHa80WdW)
[OBS CRASH](https://obsproject.com/logs/vBLZv42iZ2hmNppk)

**[+] Version information**
 - OS: Windows 10
- OBS 30.12.1
- Plugin Version [1.25.5]

**[+] Additional context**
N/A

**Comment by WarmUpTill** [comment]
Thanks for reporting the crash!

Can you share the settings you are using, which are causing this crash?
You can [export](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) them to a file on the general tab.
Do you remember what type of action or conditions you created or which macro was selected during the crash?

**Comment by MinecraftNight4** [comment]
CRASH REPORT: https://obsproject.com/logs/edaMy28ScnsMGl95
OBS LOG: https://obsproject.com/logs/ANwLxzB0n4azzmlK
CLIP: https://www.youtube.com/watch?v=yHk2lOPY4Nk

Exported Config: [adv-ss-twitch_overlay_v5-2024.06.02.23.55.40.txt](https://github.com/user-attachments/files/15528265/adv-ss-twitch_overlay_v5-2024.06.02.23.55.40.txt)

**Comment by WarmUpTill** [comment]
Thanks for providing the crash log and video!
I think I was able to identify the problem.
The crucial step in triggering the crash was closing and re-opening the settings window.

A build with a fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9356302490

I would appreciate if you could give this a try and test it on your side also.
