### ISSUE TITLE
[Bug] Lag in OBS when plugin window is open

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#1105]
**Describe the bug**
I was exploring some updates in the actions tab of this repository, and I noticed that the plugin started to lag OBS after a plugin update. I downloaded some PRs, and noticed that it was the connection tab plugin update that started to have this behavior.

Below is how the plugin window behaves before this update I mentioned (PR #1094). Note that the behavior is normal.
![Normal](https://github.com/WarmUpTill/SceneSwitcher/assets/7902295/516068b6-df04-4518-80a8-ec4633d0b07c)

And below is what it looks like after this update I mentioned (PR #1097). Note that the behavior is laggy.
![Laggy](https://github.com/WarmUpTill/SceneSwitcher/assets/7902295/56bebcc6-f90d-43e5-8cba-fef05a4211db)

Note that this laggy behavior only persists when the plugin window is open, and it affects the entire OBS UI. And it also only happens when you have several macros, as you can see in the examples above. I don't believe that some of my macros are causing this behavior, as in PR #1094 the behavior is normal. This laggy behavior happens even if you deactivate the plugin in the plugin settings.

Let me know if you need more information.

**Version information**
 - OS: Windows 11 23H2
 - OBS Version 29.1.3

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

Are you using a lot of variables and do they contain a lot of data?

Would it be possible that you [export](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) your settings to a file and share them with me so I can try to reproduce and investigate the issue?
Doesn't have to be publicly - you can also contact me directly on the OBS forums and send me a link to the file there.

**Comment by themegaxandy** [comment]
Sure, I'll send a private message on the OBS forum with the exported file attachment.

Meanwhile, I discovered that it is the Twitch connections tab. As soon as I delete a connection in this tab, the lag disappears completely. I haven't tested whether the lag returns if I re-add the connection, as I already have a lot of macros accumulated at this point. But this should give you an idea of the cause of the problem.

**Comment by WarmUpTill** [comment]
>Meanwhile, I discovered that it is the Twitch connections tab. As soon as I delete a connection in this tab, the lag disappears completely. I haven't tested whether the lag returns if I re-add the connection, as I already have a lot of macros accumulated at this point. But this should give you an idea of the cause of the problem.

Thank you! That is a very valuable hint! :)

I think the lag might be introduced when the Twitch API is used to query the status of the Twitch connection.
Instead of performing this operation every second it will now only be performed when switching to the Twitch tab.

A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9042775616?pr=1106

I would appreciate if you could give this a try and report back if this change helped to reduce the lag! :)

**Comment by themegaxandy** [comment]
The lag is gone! The UI is now as responsive as the first gif I uploaded. That was a clear shot on the first try.
