### ISSUE TITLE
1.26.1 Update breaks volume conditions

### ISSUE THREAD

**Issue by 1265775896** [WarmUpTill/SceneSwitcher#1108]
**Describe the bug**
After updating to 1.26.1, the previous conditional judgment using audio volume breaks

**To Reproduce**
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/7c608e16-5a35-447f-9a4a-594f6ea897b5)

Before update, this works fine, when no volume, switch the scene

After update, nothing happens even volume gone to zero

HOWEVER, when change condition to a random bigger number like "below 0.8%", sometimes it works again, even volume is 0% for the whole time

**Comment by WarmUpTill** [comment]
Thanks for reporting the problem!

While I cannot reproduce the issue on my end I have an idea what the issue might be.
A build with a potential fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9067286896?pr=1109

Can you please give this a try and report back, if this resolves your issue?

**Comment by 1265775896** [comment]
Thank you for the quick fix! 
But sadly, problem still remain. I started a new scene collection for example:

1. create a video source
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/3e76fe41-5b08-4a89-b7df-fe4d60f590a5)

2. set up 2 macros to control it
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/3050d256-d3fd-4874-a207-dd94a4fc9b88)
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/9b619baa-e40a-4d0b-80b7-4afd81bbe95a)

3. Start the scene switcher
4. Play something
5. Works fine for now
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/e077e1d4-05ab-4dbe-a215-63d10263d8dd)

6. Pause video, No Audio output, but video source not go hide as expected
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/c670ce38-a1f3-476e-89f8-e5e3202d7513)

7. Try manual hide Video source, no turning back on itself, which means Macro "on" is not running, which is right. then turn it back to show
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/09dfbe04-dbac-449f-b422-abb700728d97)

8. Go to "off" Macro, change condition gradually to higher volume. 
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/df6ec632-e63c-4629-8dad-f58cf7dac0bb)

9. Suddenly, at a random volume (Different each time), macro started and hide the video source
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12364598/844e37aa-1bdc-4016-99d0-331f1acc847b)

And same settings above works fine before update, so I believe it's not because of wrong configuration, please help.

**Comment by WarmUpTill** [comment]
Thank you for the quick feedback!

Unfortunately, judging by the screenshots you have not yet installed the build from the link I shared above.
So, the change I mentioned is not yet included.

I would have expected the version number to be the following:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/583d2408-5d08-41eb-9912-7fcb7d765d24)

Can I ask you to download the build from the link I shared above and try again?
Sorry about that - where to click to download them can be a bit tricky to find.

![Devdrop](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/b1875128-8e67-4ae0-9577-064ac31a042f)

**Comment by 1265775896** [comment]
Conclusion: The fix is **working as charm** right now!

Sorry I was busy on other things, and forgot that I didn't change version, using the old version by mistake.
And just mention it, this version crashed OBS if I go Import/Export its settings.

Thank you for all the work!
