### ISSUE TITLE
[Feature request] Colored status on dock.

### ISSUE THREAD

**Issue by da411d** [WarmUpTill/SceneSwitcher#1115]
**Is your feature request related to a problem? Please describe.**   
I do streaming in church and I'm not always in front of the screen, so sometimes I can't see if the switcher is active and have to come closer to read the tiny word on the dock.

**Describe the solution you'd like to see**  
I'd like the "active"/"inactive" label to have a coloured background so it's clearly visible from a distance. Also it would be cool if there was a table of all the macros and maybe an even a control to toggle them from the dock.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/12462454/f2f7b002-b23a-4506-8cf1-ef618d64d730)

Also the dock layout could look better if the label was below the text, not on the right

**Comment by WarmUpTill** [comment]
Thanks for the suggestion! :)
I will add it to the list.

Just to mention it in case it is already helpful for your setup.
You can already create docks for _individual_ macros like this:

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/e90e019b-dbce-460a-9710-1fd10dcf6460)

**Comment by WarmUpTill** [comment]
A build of the plugin in which the background of the status dock also flashes red when the plugin is not running will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9245918054

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/8e5ee419-8a9d-49f2-9b04-11421e6bcb96)

**Comment by johnczer** [comment]
Awesome plugin-thank you for creating and sharing this!  Per the above comments and your changes to the Active/Inactive button.  Could you also make it possible to change the button's background color. As it is, if I "Disable UI hints" the button color is black when inactive and appears background is theme's color when active. Thanks for considering:)
