### ISSUE TITLE
Process empty when I have WezTerm window focused

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1118]
**Describe the bug**
I don't know why, but there's no process name when some windows are focused. Yet e.g. OBS Studio manages to detect the window and executable correctly in Window source. This might be on the side of WezTerm, but not familiar with Windows process APIs and can't identify the real cause.

**To Reproduce**
1. Add Process condition
2. Check foreground process for WezTerm, nothing is displayed

Similarly, condition of focus for the executable doesn't work.

**Expected behavior**
Process name should be shown and condition for wezterm-gui.exe process focus should work.

**Logs**
\-

**Version information**
 - OS: Windows 10
 - OBS Version: 30.1.2
 - Plugin Version latest master

**Additional context**
\-

**Comment by WarmUpTill** [comment]
I am not really familiar with WezTerm, but on first glance it seems to function as expected:

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/ae7e8c73-70b8-47de-a401-dd741a31e008)

Or am I using the tool incorrectly / are you referring to a different scenario?

**Comment by Destroy666x** [comment]
Thanks for checking. I think the problem is when WezTerm (or any app) is launched as admin.

**Comment by Destroy666x** [comment]
@WarmUpTill so this is impossible I assume? Would be nice to at least add the note about the process elevation in that case
