### ISSUE TITLE
Crash when adding (saving) variable through Variable action

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1120]
**Describe the bug**
As title says

**To Reproduce**
1. Add Variable action
2. Add new variable from the action
3. Save

**Expected behavior**
No crash

**Logs**
I'll provide tomorrow if needed, now going to sleep

**Version information**
 - OS: Windows 10
 - OBS Version: 30.1.2
 - Plugin Version:  latest master
 
**Additional context**
\-

**Comment by WarmUpTill** [comment]
I think I was able to identify the root cause.
Should be fixed by https://github.com/WarmUpTill/SceneSwitcher/pull/1119/commits/c26ceef88e37c80008246e4a75dad33efd4fcd5c in the linked PR.

Thanks for pointing it out and sorry for taking so long to get around to fixing it!

**Comment by Destroy666x** [comment]
No worries. I clicked through quick and noticed no issue with the fix
