### ISSUE TITLE
Process name as a macro property never receive any value.

### ISSUE THREAD

**Issue by zhbanok** [WarmUpTill/SceneSwitcher#1122]
**Describe the bug:**
 Current focused window's process name as a macro property never receive any value.

I am using hotkey macro to get focused window title and process name and then set current capture source with that values. For a base of macro i took that https://github.com/WarmUpTill/SceneSwitcher/wiki/Change-capture-window-of-Window-Capture-source
I made macro working, but for focusing works only window title and name, because Process name never receive anything. I tried run OBS with and without admin privileges.

**To Reproduce:**
1. Create trigger with Process that looking for running and focused.
2. Create Variable and set to macro property with custom name and "connect"  Process name connected in step 1.
3. Run macro with hotkey or by button 'Run Macro' and then check Variables window to see any change.

**Expected behavior:**
I expect to receive current focused process name as a value in Proc name and then use it. 

**Logs**
Exported settings from general tab:
[adv-ss-MyMainTheme-2024.06.01.16.17.13.txt](https://github.com/user-attachments/files/15521950/adv-ss-MyMainTheme-2024.06.01.16.17.13.txt)
Exported single macro:
[test_macro.txt](https://github.com/user-attachments/files/15521954/test_macro.txt)

 ![Screenshot 2024-06-01 153134](https://github.com/WarmUpTill/SceneSwitcher/assets/46106228/e53776be-9d0b-44cb-84a2-caf07eee460d)

![Screenshot 2024-06-01 164639](https://github.com/WarmUpTill/SceneSwitcher/assets/46106228/f82ef088-8f8a-4e90-a8ef-f01d359eeb7c)

 ![Screenshot 2024-06-01 152839](https://github.com/WarmUpTill/SceneSwitcher/assets/46106228/17d09885-b877-4312-9bea-37636cf0ff70)

On screenshot you can see obs64.exe, but still dont have any value for Process name

**Version information**
 - OS: Windows 10 22H2
 - OBS Version: 30.1.0 
 - Plugin Version: 1.26.2

**Additional context**

**Comment by WarmUpTill** [comment]
You will have to enter a process name.
If you want to match all process names enable the regular expression support and add `.*` as the name.

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a22ebe7b-f492-4bc2-b21d-306aa8f3bdc3)

**Comment by zhbanok** [comment]
My apologies, it work as intended and I am not so smart...
