### ISSUE TITLE
[Feature request] *Transition To* additional setting

### ISSUE THREAD

**Issue by johntaxmi** [WarmUpTill/SceneSwitcher#1123]
**Is your feature request related to a problem? Please describe.**
The feature request is not related to a problem. It would just be a great addition.

**Describe the solution you'd like**
When using the condition for Transition and more more specifically the "Transition To" option.
Let us be able to choose the PREVIOUS SCENE that the one we are currently transition to.

Currently I can only do this
If Transition
Transition To `Scene_Name1`

By doing that, everytime I transition to `Scene_Name1` it will always perform the actions in the action tab.

I would like to be able to select the scene that I am transition from -> to the `Scene_Name1, aswell`

Example of my logic
If Transition
Transition To `Scene_Name1` from `Scene_Name2`

Now it will only perform the actions in the action tab when transitioning to the `Scene_Name1` ONLY when the PREVIOUS SCENE was the `Scene_Name2`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by WarmUpTill** [comment]
Sorry if I am misunderstanding your request, but can't you just do something like this?
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/085e8618-ee0b-499a-a3ca-7a2e1b621ff1)

Here are a few more examples:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Performing-actions-only-when-transitioning-from-A-to-B

**Comment by johntaxmi** [comment]
That could work only in this way, but if I add more checks it seems to does not work properly, coz the latest overlaps the first.

I want to do the following
![Screenshot_1](https://github.com/WarmUpTill/SceneSwitcher/assets/32601829/670dae65-bd41-49c0-be43-a5146465207a)

But I am missing what I want.
The 3 first checks are simple, but I want at the last one to have the following

And not transitioning to INTERMIDIATE SCENE from HALFTIME SCENE.
Is it possible to implement that check?

In the way I have it, evertime I transition to the INTERMIDIATE SCENE it does not do the actions, but I want to not do the actions only when I transitioned to INTERMIDIATE SCENE from HALFTIME SCENE.


Thanks in advanced.

**Comment by Destroy666x** [comment]
Order matters. Did you try moving `And not` below `If`? The conditions are read from left to right or top to bottom.

**Comment by WarmUpTill** [comment]
Just as mentioned by @Destroy666x the order of the conditions matter.
Conditions are evaluated from the top to the bottom.

So at the moment you have setup the following logic: 
`(((from halftime OR from timeout) OR from end) AND NOT to intermediate)`

If you want to setup the following logic ...:
`(((NOT to intermediate AND from halftime) OR from end) OR from timeout)`
... I would suggest moving that into its own macro and relying on the Macro condition type like this:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/b0940081-6605-42bf-91a1-cbbe0754ccd0)

**Comment by johntaxmi** [comment]
Yea, I guess I somehow made it work as indeed.
So this request can now close.

But either way, I think that, if we were able to check the transition "to" and "from" in a single check would be a great addition.

Thanks again! Have a nice day.
