### ISSUE TITLE
Add option to set variable values when executing other macros

### ISSUE THREAD

**Issue by WarmUpTill** [WarmUpTill/SceneSwitcher#1124]
**Is your feature request related to a problem? Please describe.**

Add the option the set variable values when executing a macro using the `Macro` action to simplify the execution of steps that are repeated frequently.

**Comment by WarmUpTill** [comment]
@FiniteSingularity you mentioned a while ago that it might be useful to be able to treat macros as functions for which you can set parameters.
I finally got around to implementing something like it.

In the example below I have a macro which uses the variables `Duration` and `Text`.
The content of the `Text` variable will be displayed in a Text source for `Duration` seconds.

In the settings of the macro you have the option to specify that the `Text` and `Duration` variables shall be used as possible inputs.
Those input variables can be set when executing executing the Macro using the `Macro` action type.

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/51911985-4010-4c9c-b402-2afcafb4caef)

Is this roughly what you had in mind?

**Comment by FiniteSingularity** [comment]
Yes! This is exactly what I was asking for, and will be incredibly useful.

**Comment by WarmUpTill** [comment]
FYI: An update which includes this functionality was just released :)

**Comment by mxdmedia** [comment]
Thank you for your work on this! It is going to greatly simplify/streamline some of my macros.

**Comment by FiniteSingularity** [comment]
Thank you for your work on this!  It is going to greatly simplify/streamline some of my macros.
