### ISSUE TITLE
OBS Crashes when fiddling with variables

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#1125]
It seems that OBS crashes when I start fiddling around with variables, without being able to know exactly what triggers it.

Crash report: https://obsproject.com/logs/qcbpF3Z9HekcLHuo
Log: https://obsproject.com/logs/UkTdgGrmBksy7HtG

**Version information**
 - OS: W11
 - OBS Version: 30.1.2 Portable
 - Plugin Version: 1.26.2

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

This was fixed recently with https://github.com/WarmUpTill/SceneSwitcher/commit/b7516cac5b37b644d159966d710460a2ef2b1627.

A build with a fix is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9375402235

I will try to release an update with a fix for this crash during the weekend.
Sorry about the crash and I hope it didn't cause too much trouble!

**Comment by WarmUpTill** [comment]
I will close this for now - feel free to reopen / let me know if the problem should still persist.
An update with this fix will be released officially soon.
