### ISSUE TITLE
Fails to build over i386 (x86)

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#1135]
**Describe the bug**

Hi @WarmUpTill,

The plugin version 1.26.4 fails to build on Debian Sid i386. The relevant lines are:

```
/builds/debian/obs-advanced-scene-switcher/debian/output/source_dir/lib/utils/log-helper.hpp:7:43: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'std::vector<std::weak_ptr<advss::Variable> >::size_type' {aka 'unsigned int'} [-Werror=format=]

[...]

/builds/debian/obs-advanced-scene-switcher/debian/output/source_dir/lib/utils/log-helper.hpp:7:43: error: format '%lld' expects argument of type 'long long int', but argument 5 has type 'qsizetype' {aka 'int'} [-Werror=format=]
```

A complete log can be viewed here: https://salsa.debian.org/debian/obs-advanced-scene-switcher/-/jobs/5849569

Regards,

Eriberto

**Comment by WarmUpTill** [comment]
Hello @eribertomota,
Sorry about that!
A fix should be available in the linked PR / on the `debian` branch.

**Comment by eribertomota** [comment]
@WarmUpTill 

Please don't apologize! You do a wonderful work and I am grateful for that and for your attention to me and Debian.

The source code is building fine now on i386. Thanks!!!

Eriberto
