### ISSUE TITLE
Free Disk Space Condition 

### ISSUE THREAD

**Issue by DanielLester83** [WarmUpTill/SceneSwitcher#1136]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

When I sometimes start recording I sometimes don't notice that I'm low on disk space.

**Describe the solution you'd like**

I would like a variable (probably under stats) that returns the amount of free disk space in TB, GB, MB and percentage of total overall space of a disk, so I can trigger an alert pop up or some other action.

**Comment by Destroy666x** [comment]
This is fairly easily doable with CLI on any system. Which are you on? I assume Windows, so e.g.: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psdrive?view=powershell-7.4

```(Get-PSDrive C).Free```

Then use standard output temp var in this plugin

**Comment by DanielLester83** [comment]
> This is fairly easily doable with CLI on any system. Which are you on? I assume Windows, so e.g.: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psdrive?view=powershell-7.4
> 
> `(Get-PSDrive C).Free` or in GB `(Get-PSDrive C).Free / 1073741824` (1024^3)
> 
> Then use standard output temp var in this plugin for retrieving the value and using it in condition

While your right, I'd prefer it to be more abstracted and rhobust. Your suggestion seems to assume Windows OS and drive C, which wouldn't consider if the action changed the output folder to a different drive.

**Comment by Destroy666x** [comment]
Regardless of implementation, you'll have to store the disk letter in a variable if it's supposed to be dynamic, nothing changes with an in-built disk checking method. Unless you expect a condition that checks based on OBS recording save path specifically, but I think that's way too specific to include.

**Comment by WarmUpTill** [comment]
A build with the option to check the available disk space of the drive OBS is using will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9571585848?pr=1142
Let me know if you face any issues! :)

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/2795b121-0ba7-4591-bd09-4557ab49be97)

>a condition that checks based on OBS recording save path specifically, but I think that's way too specific to include.

Usually I would agree but since it was already implemented in the OBS stats dock it was trivial to implement.

**Comment by DanielLester83** [comment]
The new feature works, but the build causes other dll files to not load.




`23:21:54.972: [adv-ss] version: 1.26.4-9-g23a5920
23:21:54.972: [adv-ss] version: 23a59208ac34a4d2f32f6fd694fbd996c4c37dcc
23:21:54.972: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-base.dll"
23:21:54.974: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-base.dll"
23:21:54.974: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-midi.dll"
23:21:54.994: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-midi.dll"
23:21:54.994: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll"
23:21:55.795: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\advanced-scene-switcher-opencv.dll: A dynamic link library (DLL) initialization routine failed.
23:21:55.795: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
23:21:55.797: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
23:21:55.797: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-twitch.dll"
23:21:55.801: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-twitch.dll"
23:21:55.801: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/libcrypto-1_1-x64.dll"
23:21:55.801: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/libcrypto-1_1-x64.dll"
23:21:55.801: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/libssl-1_1-x64.dll"
23:21:55.801: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/libssl-1_1-x64.dll"
23:21:55.801: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d4100.dll"
23:21:56.573: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_calib3d4100.dll: A dynamic link library (DLL) initialization routine failed.
23:21:56.574: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d453.dll"
23:21:56.578: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d453.dll"
23:21:56.578: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
23:21:56.583: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
23:21:56.583: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core4100.dll"
23:21:57.392: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_core4100.dll: A dynamic link library (DLL) initialization routine failed.
23:21:57.392: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core453.dll"
23:21:57.392: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core453.dll"
23:21:57.392: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
23:21:57.392: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
23:21:57.392: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d4100.dll"
23:21:58.233: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_features2d4100.dll: A dynamic link library (DLL) initialization routine failed.
23:21:58.233: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d453.dll"
23:21:58.233: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d453.dll"
23:21:58.233: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
23:21:58.233: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
23:21:58.233: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann4100.dll"
23:21:59.078: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_flann4100.dll: A dynamic link library (DLL) initialization routine failed.
23:21:59.078: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann453.dll"
23:21:59.078: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann453.dll"
23:21:59.078: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
23:21:59.078: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
23:21:59.078: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc4100.dll"
23:21:59.952: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_imgproc4100.dll: A dynamic link library (DLL) initialization routine failed.
23:21:59.952: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc453.dll"
23:21:59.952: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc453.dll"
23:21:59.952: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
23:21:59.952: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
23:21:59.952: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect4100.dll"
23:22:00.859: [adv-ss] failed to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect4100.dll": Cannot load library C:\Program Files\obs-studio\obs-plugins\64bit\adv-ss-plugins\opencv_objdetect4100.dll: A dynamic link library (DLL) initialization routine failed.
23:22:00.859: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect453.dll"
23:22:00.860: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect453.dll"
23:22:00.860: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
23:22:00.861: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
23:22:00.861: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
23:22:00.861: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
23:22:00.9`

**Comment by WarmUpTill** [comment]
This _shouldn't_ be related to the changes performed in this test build.

If you are notified that some plugin functionality might not be available, you will have to install the latest version of the [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170), which can be found [here](https://aka.ms/vs/17/release/vc_redist.x64.exe).

This is due to a change done by GitHub in the build environment.

**Comment by DanielLester83** [comment]
Thanks, Reinstall DirectX

> This _shouldn't_ be related to the changes performed in this test build.
> 
> If you are notified that some plugin functionality might not be available, you will have to install the latest version of the [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170), which can be found [here](https://aka.ms/vs/17/release/vc_redist.x64.exe).
> 
> This is due to a change done by GitHub in the build environment.

Thanks, that fixed it.
