### ISSUE TITLE
Projector macro: Target display selections disappear when disconnected

### ISSUE THREAD

**Issue by andteklin** [WarmUpTill/SceneSwitcher#1140]
### Problem
Upon opening OBS with all target displays connected, executing the macro associated with opening a fullscreen projector on the target display does not work properly.

Checking the settings for the macro to open fullscreen projectors shows “select display” as the selected option in the drop-down menu rather than the names of the target display.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/93839101/d364c2d9-6f7e-45ab-a5ee-14c3c80b7170)

### To Reproduce
When all target displays are connected, the target display is selected for fullscreen projector to appear on. Then OBS is closed.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/93839101/8e2671d2-9ea4-415f-874e-071c5222c3cc)

Then a new instance of OBS is opened when the target display is not connected. Upon checking settings for the Advanced Scene Switcher in this first instance, the “select display” option appears for opening a fullscreen projector in the execution statement.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/93839101/a71a2a7c-c9bf-4007-a758-ba1ebc04f8a8)

Closing OBS saves the Advanced Scene Switcher settings with the target display deselected (as the Advanced Scene Switcher does not detect the target display). 

Upon opening OBS the next time with all target displays connected, the settings from the previous session are restored and the “select displays” option still appears when checking the execution statement in the Advanced Scene Switcher macro settings.

The desired state for the fullscreen projector to open on the target display is no longer attained.

### Temporary Solutions
**Temp Solution 1**
Export the Advanced Scene Switcher settings to a file while all displays are connected and the target display is selected to have a fullscreen projector opened on in the macro execution statement.

Upon encountering the above problem, reconnect the target displays and import the settings file saved from the desired state. 

The macro should execute properly and the fullscreen projectors are opened on the target displays, as desired.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/93839101/0cfe9a0f-9fc5-4c2e-b994-baffd684527e)

**Temp Solution 2**
Reconnect the target displays.

Then go to the Advanced Scene Switcher settings edit the macro execution statement: select the target display from the drop-down menu for which to open a fullscreen projector.

The macro should execute properly and the fullscreen projectors are opened on the target displays, as desired.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/93839101/8bb50e60-772c-4906-bd55-7ebec4f8dd2a)

**Temp Solution 3**
Make Advanced Scene Switcher or scene collection file read-only, but not preferred as this doesn’t allow for easy changes to files across instances. Would have to disable read-only to edit.

### Expected behavior
Retain the selection of the target displays for the untouched execution statements that open a fullscreen projector on the target displays.

That is, when the target displays are disconnected, the macro settings remain the same and do not deselect the target displays. When OBS is re-opened with the target displays connected, the target displays should be selected for fullscreen projectors to be opened on.

### Logs
Log in desired state: 
[2024-06-16 09-59-23.txt](https://github.com/user-attachments/files/15858804/2024-06-16.09-59-23.txt)

Log when target display disconnected:
[2024-06-16 11-12-45.txt](https://github.com/user-attachments/files/15858805/2024-06-16.11-12-45.txt)

Log when target display reconnected:
[2024-06-16 11-13-43.txt](https://github.com/user-attachments/files/15858806/2024-06-16.11-13-43.txt)

Currently used plugin settings: 
[adv-ss-test-2024.06.16.11.10.58.txt](https://github.com/user-attachments/files/15858796/adv-ss-test-2024.06.16.11.10.58.txt)

Plugin settings after target display disconnected (settings were not touched):
[adv-ss-test-2024.06.16.11.15.23.txt](https://github.com/user-attachments/files/15858812/adv-ss-test-2024.06.16.11.15.23.txt)

**Version information**
 - OS: Windows 11 Home, Version 23H2 with OS Build 22631.3593.
 - OBS Version 30.1.2
 - Plugin Version 1.26.4

**Additional context**
The attached plugin settings are isolating the issue with test displays, scenes, and settings.
In non-test context, this macro executes the opening of fullscreen projectors on the target displays when the target displays are connected. Then, a hotkey can be used to re-execute the macro to reopen the fullscreen projectors on the target displays when, for example, if the fullscreen projectors have not saved from the previous instance using OBS' fullscreen projector save setting in the General settings.

**Comment by WarmUpTill** [comment]
A build which should solve your issue should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9537632901?pr=1141

Instead of discarding the monitor selection when a monitor setup change was detected, it will now just skip the execution of the action until the expected monitor setup is detected again (or a new monitor selection was made).

Let me know, if you run into any issues!

**Comment by andteklin** [comment]
Thank you for your quick response WarmUpTill. I have downloaded the build from the pull request #1141 and it works perfectly. Appreciate your assistance.
