### ISSUE TITLE
[Feature request] Replay Buffer Actions to change its duration.

### ISSUE THREAD

**Issue by Raxyz0** [WarmUpTill/SceneSwitcher#1143]
### The Problem:

If it helps at all to know why I would benefit from this feature, here's the thing: I'm making fighting game tutorials. I'm good at learning and theory-crafting mechanics, but I'm bad at actually _executing_ them. I also don't use a hard script, just a few bullet points. So if I just record everything in one session, it'll probably be an hour long video file for a tutorial that's gonna be 10min long once it's edited. Finding the good takes and merging the correctly executed combos is really time consuming.

So I took to AdvSS to help me here. I tried a few solutions and settled on this one:
One hotkey macro to turn on replay buffer. One to disable it (therefore discard a bad take). And one to save it and then disable. This is working fine, but there's something else that I have to do from time to time. When I'm just talking and explaining mechanics I set the buffer to 2min max. But if I'm trying to do a high-execution or specific positioning combo, it might take me several tries to get it right. So what I do is reduce the buffer to 20s so that I don't have to keep turning the buffer on and off so that I don't have to comb through more than a minute of footage to find the successful combo when editing.

### The suggestion:

Adding an option to the Replay buffer actions that allow for the setting "Maximum Replay Time" in "Settings->Output->Replay Buffer" to be modified through macro conditions.

**Comment by WarmUpTill** [comment]
A build with the option to change the replay buffer duration will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9617240315?pr=1144

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/01676737-63b5-4527-a271-252e4ce224d6)

Let me know if everything works as expected! :)

**Comment by Raxyz0** [comment]
> A build with the option to change the replay buffer duration will be available here in a few minutes: https://github.com/WarmUpTill/SceneSwitcher/actions/runs/9617240315?pr=1144
> 
> ![grafik](https://private-user-images.githubusercontent.com/19472752/341838558-01676737-63b5-4527-a271-252e4ce224d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDEyNzUsIm5iZiI6MTcxOTAwMDk3NSwicGF0aCI6Ii8xOTQ3Mjc1Mi8zNDE4Mzg1NTgtMDE2NzY3MzctNjNiNS00NTI3LWEyNzEtMjUyZTRjZTIyNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIwMTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNzBjNjMwOWNhODJiYjEzNTVlMTNmNjQwNjlhZTE1ZGJhZDU1YTA0NWFjZjAzMjVhOThlYmI5MDk3Njg3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2kb-Q6RL1gGOeMSvizAsn0AuI5BT_5yRfPrgKT_cstg)
> 
> Let me know if everything works as expected! :)

That was a quick update, thanks!

The functionality itself is working fine. But in every Replay Buffer option there's now a dialog box with numeric input. I haven't fiddled with the numbers to see if it breaks anything.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/96501888/52b075b5-94dd-4243-800f-23482fd66798)

I'm using Windows 10 Pro. Ver 22H2 and build 19045.4529. I'm a bit inexperienced when it comes to technical details, but let me know if there's any logs or info that could help.

**Comment by WarmUpTill** [comment]
>The functionality itself is working fine

Thanks for the confirmation!

> But in every Replay Buffer option there's now a dialog box with a numeric input.

Ah thanks!
I will clean that up before merging it.
