### ISSUE TITLE
Every OTHER twitch points redeem if-statement triggers actions

### ISSUE THREAD

**Issue by ErenBlack** [WarmUpTill/SceneSwitcher#1152]
**Describe the bug**
Weird issue.. with this specific setup on my Advanced Scene Switcher, it only trigger the actions every *other* time. There is only one if statement, and the if statement lights up green, but none of the actions light up, and the actions arent triggered.

They only light up and trigger every *other* time.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/29548224/2dbb97c5-d50c-4dce-95a1-b0a076fb4bd9)

For context, I do have a second action that pauses the playback of the same source when the media reaches a certain point, and sets it to invisible, but I am not sure that would be related or not. You can see an image of this second action below:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/29548224/d1ba5159-62da-46ce-8c3c-7ec0238548c4)

**To Reproduce**
1. Have channel points macro setup:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/29548224/cdea031a-88a7-4b09-a8c0-b604aa6db407)

2. Have action set scene visibility and variable value:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/29548224/ed0487a9-61d7-4d6f-9b0d-3b3b89c82649)

3. Redeem points on twitch to trigger the action, it only should trigger every second time.

**Expected behavior**
When if-condition triggered, should trigger actions every time, not every other time.

**Logs**

[2024-07-05 16-09-43.txt](https://github.com/user-attachments/files/16113468/2024-07-05.16-09-43.txt)

[adv-ss-Main-2024.07.05.16.12.20.txt](https://github.com/user-attachments/files/16113483/adv-ss-Main-2024.07.05.16.12.20.txt)
Here is a video of the issue in action:

https://drive.google.com/file/d/1VXhldEka_Km8bZfnHFPjh0hCs-wqxUTU/view?usp=sharing

**Version information**
 - OS: Windows 11 Home 21H2
 - OBS Version 30.1.2
 - Plugin Version 1.26.4

**Comment by WarmUpTill** [comment]
According to the log you have - most likely accidentally - configured the plugin to skip executing actions for a certain amount of time after an action was executed.

You will have to set this setting on the General tab to "0" to resolve your issue:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/774f2318-6a63-4d82-9f51-04558bd2b6f9)

This issue pops up every now and then.
I will think of a way to prevent users accidentally configuring something there while scrolling through the general tab for the next release.

Sorry about that!

**Comment by MinecraftNight4** [comment]
> According to the log you have - most likely accidentally - configured the plugin to skip executing actions for a certain amount of time after an action was executed.
> 
> You will have to set this setting........

How about a button asking to apply the settings or undo it?

**Comment by ErenBlack** [comment]
> According to the log you have - most likely accidentally - configured the plugin to skip executing actions for a certain amount of time after an action was executed.
> 
> You will have to set this setting on the General tab to "0" to resolve your issue: ![image](https://private-user-images.githubusercontent.com/19472752/346279569-774f2318-6a63-4d82-9f51-04558bd2b6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTQ4NDUsIm5iZiI6MTcyMDI5NDU0NSwicGF0aCI6Ii8xOTQ3Mjc1Mi8zNDYyNzk1NjktNzc0ZjIzMTgtNmE2My00ZDgyLTlmNTEtMDQ1NThiZDJiNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjRlMDcyMGE1MzIxMGE2YTViMmIyY2I0MGJmZTFhZWFkNGYzMzJjNjE4YmM3MjQ2ZWU2YWQ2NWMxNGQ4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hlF6yYE6o2ImfTmSQ5rg8veiVJlMnMNQ5JMZ6SOj_Lo)
> 
> This issue pops up every now and then. I will think of a way to prevent users accidentally configuring something there while scrolling through the general tab for the next release.
> 
> Sorry about that!

I.. feel like such an idiot. totally not your fault, and thank you so much for this!!! your plugin is life changing :)

**Comment by WarmUpTill** [comment]
> > According to the log you have - most likely accidentally - configured the plugin to skip executing actions for a certain amount of time after an action was executed.
> > You will have to set this setting........
> 
> How about a button asking to apply the settings or undo it?

Thanks for the suggestion!
I went a slightly different route and added a checkbox which has to be ticked before this setting can be changed.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/1884b460-abf3-45bc-b473-5e6fe285b928)

The checkbox will automatically be set if a user has already set a time which is not equal to zero, so it should be backwards compatible.
