### ISSUE TITLE
[adv-ss] spent X ms in video condition check of macro 'macro name'!

### ISSUE THREAD

**Issue by therentabrain** [WarmUpTill/SceneSwitcher#1156]
**Describe the bug**
I've been getting this message constantly.  My status bar has been showing encoder overloaded.  I don't know if it's related.

**To Reproduce**

Create a macro that checks for the current scene being a video scene "And" inspects that video's playing state.
Start streaming a different scene, so the Current Scene is not the one that the macro applies to.
The macro appears to check the video condition anyway, and is having some kind of error trying to do so. 

I did some searching and I don't see anything that explains what this message means or what to look for, or whether it's actually important.

**Expected behavior**
Not seeing this error throughout my log. :)  
I assumed that if the Current Scene is not the one in the first Condition, it was harmless to check the video state in the second Condition.  

**Logs**
Please let me know if you need them.  

**Version information**
 - OS: Windows 10
 - OBS Version 30.1.2
 - Plugin Version 1.26.2

**Comment by WarmUpTill** [comment]
The message indicates that you might have configured something which is taking an unusual amount of time to check.
In this case the "Video" condition type.
This may not necessarily always be a problem.
But as you are also observing `encoder overloaded` messages this is worth looking into / resolving.

The checks performed by the "Video" condition type can be _very_ expensive in terms of CPU resources required to run them.

As you mentioned that you want to _only_ run the "Video" condition check if you are on a particular scene you might want to set up a helper macro which "pauses" the Macro containing the "Video" condition check, when you are not on the relevant scene.

This might look something like this:
![image](https://github.com/user-attachments/assets/e0faeab6-68d5-405d-839a-9522857b51ef)


A few general tips:
* I would advise to minimize the use of the "Video" condition type's more expensive operations - the pattern matching, object detection, and sometimes OCR - unless you have plenty of resources to spare.
* It might also be worth reducing the area a Video condition has to look at or the size of the images it has to compare to.
* You can further reduce the load on the system by performing those types of checks not as frequently
* Depending on what you have set up you might be able to combine multiple "Video" condition checks into one check.
(E.g. if you have two "Video" conditions checking the inverse of each other, checking the condition only a single time might suffice, and you can "reuse" the result of the previous check)

This wiki entry goes other a few of those points as well:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Activate-overlay-to-hide-parts-of-the-screen

I hope this helped at least a bit!
Let me know if you need further support!

**Comment by WarmUpTill** [comment]
I was under the impression that you were using one of the more resource intensive operations I mentioned.
The "has no output" check should be very "cheap" in terms of resources used.

So I would _assume_ that _something_ (maybe the VST plugin you mentioned?) is causing very high CPU load and the plugin is also affected by that and thus takes much longer than expected to complete its tasks.

Unfortunately, it is difficult to say what exactly might be causing this.
It might also be worth checking if it is maybe a process completely unrelated to OBS, which could be causing the high system load.

**Comment by WarmUpTill** [comment]
I will close this for now.
But feel free to continue the discussion, if you need further support! :)
