### ISSUE TITLE
Slideshow doesn't show up in OBS 30.2.2

### ISSUE THREAD

**Issue by NaGeLBaileyVT** [WarmUpTill/SceneSwitcher#1166]
**Describe the bug**
I'm creating a macro that should watch a slideshow, but i cant select the slideshow because it doesn't populate the list.
![image](https://github.com/user-attachments/assets/046f1e97-deab-4b54-b402-544575ad9a64)

**To Reproduce**
1. new OBS 30.2.2
2. add Slideshow
3. try to create macro

**Expected behavior**
to select a slideshow

**Logs**
https://pastebin.com/HP7NGSmN

**Version information**
 - OS: Windows 10
 - OBS Version 30.2.2
 - Plugin Version1.26.4

**Comment by WarmUpTill** [comment]
This issue was fixed with 70415cd8 but not yet released officially.

A build with a fix can be found here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10235662186

Sorry for not being able to release this fix earlier!

**Comment by NaGeLBaileyVT** [comment]
Coolio! when's the next release? 

also thank you for that build!

**Comment by WarmUpTill** [comment]
No worries :)

I am not sure yet.
Maybe in a week or so.

**Comment by WarmUpTill** [comment]
An official release, which contains this fix, was now published, so I am closing this issue :)
