### ISSUE TITLE
Macros not working

### ISSUE THREAD

**Issue by jmm1995** [WarmUpTill/SceneSwitcher#1169]
Hello,
I have a homemade television channel, and every time Advanced Scene Switcher needs to make changes, this error appears:

15:22:25.585: QCoreApplication::postEvent: Unexpected null receiver
15:22:25.789: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
15:22:35.933: QCoreApplication::postEvent: Unexpected null receiver
15:22:36.136: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
15:26:55.940: QCoreApplication::postEvent: Unexpected null receiver
15:26:56.144: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
15:54:50.237: QCoreApplication::postEvent: Unexpected null receiver
15:54:50.441: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'

W10
OBS 30.2.2
Advanced Scene Switcher 1.26.4
I can't find the problem.

Thank u for your help

**Comment by WarmUpTill** [comment]
You can safely ignore those messages :)

As the title says `Macros not working` is there anything else, which is not working as you expect it to?

**Comment by WarmUpTill** [comment]
I will close this for new - let me know if I can help with anything else!
