### ISSUE TITLE
I can't perform instructional actions

### ISSUE THREAD

**Issue by Wayne102124** [WarmUpTill/SceneSwitcher#1170]
Why is the page I open according to the operation different from the instructions on the webpage?
<img width="733" alt="image" src="https://github.com/user-attachments/assets/843e6b66-9440-4f44-b727-4af1a5e553ef">
I don't know how to create a macro like the tutorial
Maybe my question sounds stupid but I don't know how to use
Sorry if my English is not fluent, I don't use English as my native language

**Comment by WarmUpTill** [comment]
This is not the UI of this plugin.
You are looking at the UI of the _automatic_ scene switcher, which is a tool directly built into OBS.

I assume you have not installed the _advanced_ scene switcher or something went wrong during the installation.

**Comment by Wayne102124** [comment]
<img width="733" alt="image" src="https://github.com/user-attachments/assets/329a8c6a-eebd-46f7-82dd-7fa1467b808b">
My computer uses macOS. I tried downloading two files that seemed to be related to macOS.
But I can only open the .pkg file. I don’t know what the other one is. I tried to open the .pkg and installed it according to the program. Finally, it showed that the installation was successful. I also restarted OBS. Maybe you can tell me how to install it correctly. Thanks

**Comment by WarmUpTill** [comment]
In most scenarios using the *.pkg file is the correct approach on MacOS.

Would you mind sharing an OBS log file? (Help > Log Files)
this might give a hint what the issue could be.

**Comment by Wayne102124** [comment]
Thank you very much for your help, I found a file, I hope it is this.

**Comment by Wayne102124** [comment]
08:41:56.734: [macOS] Permission for audio device access granted.
08:41:56.738: [macOS] Permission for video device access granted.
08:41:56.747: [macOS] Permission for accessibility denied.
08:41:56.752: [macOS] Permission for screen capture granted.
08:41:56.752: CPU Name: Apple M1
08:41:56.752: Physical Cores: 8, Logical Cores: 8
08:41:56.752: Physical Memory: 8192MB Total
08:41:56.752: OS Name: macOS
08:41:56.752: OS Version: Version 15.0 (Build 24A5320a)
08:41:56.752: Rosetta translation used: false
08:41:56.752: Kernel Version: 24.0.0
08:41:56.754: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:41:56.754: Current Date/Time: 2024-08-17, 08:41:56
08:41:56.754: Browser Hardware Acceleration: true
08:41:56.754: Qt Version: 6.4.1 (runtime), 6.4.1 (compiled)
08:41:56.754: Portable mode: false
08:41:58.378: OBS 29.0.0 (mac)
08:41:58.378: ---------------------------------
08:41:58.384: ---------------------------------
08:41:58.385: audio settings reset:
08:41:58.385: 	samples per sec: 48000
08:41:58.385: 	speakers:        2
08:41:58.385: 	max buffering:   960 milliseconds
08:41:58.385: 	buffering type:  dynamically increasing
08:41:58.494: ---------------------------------
08:41:58.494: Initializing OpenGL...
08:41:58.589: Loading up OpenGL on adapter Apple Apple M1
08:41:58.589: OpenGL loaded successfully, version 4.1 Metal - 89.3, shading language 4.10
08:41:58.830: ---------------------------------
08:41:58.831: video settings reset:
08:41:58.831: 	base resolution:   4480x2520
08:41:58.831: 	output resolution: 2240x1260
08:41:58.831: 	downscale filter:  Area
08:41:58.831: 	fps:               30/1
08:41:58.831: 	format:            NV12
08:41:58.831: 	YUV mode:          sRGB/Partial
08:41:58.831: NV12 texture support not available
08:41:58.831: P010 texture support not available
08:41:58.852: Audio monitoring device:
08:41:58.852: 	name: 預設裝置
08:41:58.852: 	id: default
08:41:58.852: ---------------------------------
08:41:59.007: No AJA devices found, skipping loading AJA UI plugin
08:41:59.007: Failed to initialize module 'aja-output-ui'
08:41:59.162: No AJA devices found, skipping loading AJA plugin
08:41:59.162: Failed to initialize module 'aja'
08:41:59.215: Failed to load 'en-US' text for module: 'decklink-captions'
08:41:59.264: Failed to load 'en-US' text for module: 'decklink-output-ui'
08:41:59.299: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
08:41:59.299: Failed to initialize module 'decklink'
08:42:00.469: [VideoToolbox encoder]: Adding VideoToolbox encoders
08:42:05.747: [obs-browser]: Version 2.19.0
08:42:05.748: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
08:42:06.370: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
08:42:06.370: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.1 | Qt version (run-time): 6.4.1
08:42:06.370: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
08:42:06.381: [obs-websocket] [obs_module_load] Module loaded.
08:42:06.653: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 0x0101): tried: '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (no such file), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (no such file)
08:42:06.653: 
08:42:06.653: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
08:42:07.942: os_dlopen(/Users/wayne/Library/Application Support/obs-studio/plugins/advanced-scene-switcher.plugin/Contents/MacOS/advanced-scene-switcher->/Users/wayne/Library/Application Support/obs-studio/plugins/advanced-scene-switcher.plugin/Contents/MacOS/advanced-scene-switcher): dlopen(/Users/wayne/Library/Application Support/obs-studio/plugins/advanced-scene-switcher.plugin/Contents/MacOS/advanced-scene-switcher, 0x0101): Library not loaded: @rpath/obs-frontend-api.dylib
08:42:07.942:   Referenced from: <4B61AE5E-549B-3BDA-BF3F-6E64207C7CB1> /Users/wayne/Library/Application Support/obs-studio/plugins/advanced-scene-switcher.plugin/Contents/MacOS/advanced-scene-switcher
08:42:07.942:   Reason: tried: '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/usr/lib/obs-frontend-api.dylib' (no such file, not in dyld cache)
08:42:07.942: 
08:42:07.942: Module '/Users/wayne/Library/Application Support/obs-studio/plugins/advanced-scene-switcher.plugin/Contents/MacOS/advanced-scene-switcher' not loaded
08:42:07.942: ---------------------------------
08:42:07.942:   Loaded Modules:
08:42:07.942:     vlc-video
08:42:07.942:     text-freetype2
08:42:07.942:     rtmp-services
08:42:07.942:     obs-x264
08:42:07.942:     obs-websocket
08:42:07.942:     obs-vst
08:42:07.942:     obs-transitions
08:42:07.942:     obs-outputs
08:42:07.942:     obs-filters
08:42:07.942:     obs-ffmpeg
08:42:07.942:     obs-browser
08:42:07.942:     mac-virtualcam
08:42:07.942:     mac-videotoolbox
08:42:07.942:     mac-syphon
08:42:07.942:     mac-capture
08:42:07.942:     mac-avcapture
08:42:07.942:     image-source
08:42:07.942:     frontend-tools
08:42:07.942:     decklink-output-ui
08:42:07.942:     decklink-captions
08:42:07.942:     coreaudio-encoder
08:42:07.942: ---------------------------------
08:42:07.944: ==== Startup complete ===============================================
08:42:08.117: All scene data cleared
08:42:08.117: ------------------------------------------------
08:42:08.356: coreaudio: Device 'iMac的麥克風' [44100 Hz] initialized
08:42:08.357: [Loaded global audio device]: '麥克風'
08:42:08.357:     - filter: '噪声抑制' (noise_suppress_filter_v2)
08:42:08.395: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: 麥克風)
08:42:08.395: 
08:42:09.014: [Media Source '媒體來源 3']: settings:
08:42:09.014: Set FFmpeg options: 
08:42:09.014: 	input:                   /Users/wayne/Downloads/綜合音樂.MP3
08:42:09.014: 	input_format:            (null)
08:42:09.014: 	speed:                   100
08:42:09.014: 	is_looping:              yes
08:42:09.014: 	is_linear_alpha:         no
08:42:09.014: 	is_hw_decoding:          no
08:42:09.014: 	is_clear_on_media_en08:42:09.014: 	is_clear_on_media_end:   no
08:42:09.014: 	restart_on_activate:     yes
08:42:09.014: 	close_when_inactive:     no
08:42:09.014: 	ffmpeg_options:          
08:42:09.014: [Media Source '媒體來源 2']: settings:
08:42:09.014: 	input:                   
08:42:09.014: 	input_format:            (null)
08:42:09.014: 	speed:                   100
08:42:09.014: 	is_looping:              no
08:42:09.014: 	is_linear_alpha:         no
08:42:09.014: 	is_hw_decoding:          no
08:42:09.014: 	is_clear_on_media_end:   yes
08:42:09.014: 	restart_on_activate:     yes
08:42:09.014: 	close_when_inactive:     no
08:42:09.014: 	ffmpeg_options:          
08:42:09.038: coreaudio: failed to find device uid: default, waiting for connection
08:42:09.038: coreaudio: no device found
08:42:09.067: coreaudio: Device 'iMac的麥克風' [44100 Hz] initialized
08:42:09.480: adding 106 milliseconds of audio buffering, total audio buffering is now 149 milliseconds (source: macOS 螢幕擷取)
08:42:09.480: 
08:42:09.795: [Media Source '媒體來源']: settings:ng, total audio buffering is now 1
08:42:09.795: [Media Source '媒體來源']: settings:ng, total audio buffering is now 1
08:42:09.795: 	input:                   /Users/wayne/Downloads/摸摸鯊魚第二代(1).gif
08:42:09.795: 	input_format:            (null)
08:42:09.795: 	speed:                   100
08:42:09.795: 	is_looping:              yes
08:42:09.795: 	is_linear_alpha:         no
08:42:09.795: 	is_hw_decoding:          no
08:42:09.795: 	is_clear_on_media_end:   no
08:42:09.795: 	restart_on_activate:     yes
08:42:09.795: 	close_when_inactive:     no
08:42:09.795: 	ffmpeg_options:          
08:42:09.995: [Media Source 'Stinger (Stinger)']: settings:
08:42:09.995: 	input:                   
08:42:09.995: 	input_format:            (null)
08:42:09.995: 	speed:                   100
08:42:09.995: 	is_looping:              no
08:42:09.995: 	is_linear_alpha:         no
08:42:09.995: 	is_hw_decoding:          yes
08:42:09.995: 	is_clear_on_media_end:   yes
08:42:09.995: 	restart_on_activate:     yes
08:42:09.995: 	close_when_inactive:     no
08:42:09.995: 	ffmpeg_options:          
08:42:09.997: Switched to scene '超級神伺服器狀態'
08:42:09.997: ------------------------------------------------
08:42:09.997: Loaded scenes:
08:42:09.998: - scene '直播':
08:42:09.998:     - source: 'macOS屏幕捕獲（音訊）' (screen_capture)
08:42:09.998:     - source: 'https://studio.youtube.com/live_chat?is_popout=1&v=Tpmdkt8vfOY' (browser_source)
08:42:09.998: - scene '錄製':
08:42:09.998:     - source: 'macOS 螢幕擷取' (screen_capture)
08:42:09.998:         - filter: '銳化' (sharpness_filter_v2)
08:42:09.998:     - source: '擷取音效輸入' (coreaudio_input_capture)
08:42:09.998:     - source: '視窗擷取' (window_capture)
08:42:09.998:     - source: '擷取音效輸出' (coreaudio_output_capture)
08:42:09.998: - scene '新聞台':
08:42:09.998:     - source: '色彩來源 ' (color_source_v3)
08:42:09.998:     - source: '螢幕擷取' (screen_capture)
08:42:09.998:     - source: '色彩來源' (color_source_v3)
08:42:09.998:     - source: '瀏覽器' (browser_source)
08:42:09.998:     - source: '色彩來源 2' (color_source_v3)
08:42:09.998:     - source: '文字' (text_ft2_source_v2)
08:42:09.998:     - source: '文字 (FreeType 2)' (text_ft2_source_v2)
08:42:09.998:     - source: 'https://studio.youtube.com/live_chat?is_popout=1&v=Tpmdkt8vfOY' (browser_source)
08:42:09.998: - scene '測試 教學':
08:42:09.998:     - source: 'macOS 螢幕擷取 ' (screen_capture)
08:42:09.998: - scene '超級神伺服器狀態':
08:42:10.020:     - source: '色彩來源 3' (color_source_v3)
08:42:10.020:     - source: 'https://www.mcsv.top/server/supergodminecraft.ddns.net' (browser_source)
08:42:10.020:     - source: '瀏覽器 2' (browser_source)
08:42:10.020:     - source: '視窗擷取 2' (window_capture)
08:42:10.020:     - source: '媒體來源' (ffmpeg_source)
08:42:10.020:     - source: '文字 (FreeType 2) 2' (text_ft2_source_v2)
08:42:10.020:     - source: '視窗擷取 3' (window_capture)
08:42:10.020:     - source: '文字 (FreeType 2) 2 2' (text_ft2_source_v2)
08:42:10.020:     - source: '文字 (FreeType 2) 5' (text_ft2_source_v2)
08:42:10.020:     - source: '視窗擷取 5' (window_capture)
08:42:10.020:     - source: 'Group' (group)
08:42:10.020:     - source: '文字 (FreeType 2) 6' (text_ft2_source_v2)
08:42:10.020:     - source: '圖片' (image_source)
08:42:10.020:     - source: '媒體來源 2' (ffmpeg_source)
08:42:10.020:     - source: '媒體來源 3' (ffmpeg_source)
08:42:10.020:     - source: '瀏覽器 3' (browser_source)
08:42:10.020:     - source: '文字 (FreeType 2) 7' (text_ft2_source_v2)
08:42:10.020:     - source: '視窗擷取 4' (window_capture)
08:42:10.020:     - source: '視窗擷取 6' (window_capture)
08:42:10.020: - scene '等待':
08:42:10.020:     - source: '色彩來源 4' (color_source_v3)
08:42:10.020:     - source: '文字 (FreeType 2) 3' (text_ft2_source_v2)
08:42:10.020:     - source: '文字 (FreeType 2) 3 2' (text_ft2_source_v2)
08:42:10.020:     - source: '文字 (FreeType 2) 3 2 2' (text_ft2_source_v2)
08:42:10.020: - scene '超級神伺服器重啟':
08:42:10.020:     - source: '色彩來源 3' (color_source_v3)
08:42:10.020:     - source: '色彩來源 5' (color_source_v3)
08:42:10.020:     - source: 'https://www.mcsv.top/server/supergodminecraft.ddns.net' (browser_source)
08:42:10.020:     - source: '瀏覽器 2' (browser_source)
08:42:10.020:     - source: '媒體來源' (ffmpeg_source)
08:42:10.020:     - source: '視窗擷取 3' (window_capture)
08:42:10.020:     - source: '視窗擷取 5' (window_capture)
08:42:10.020:     - source: 'Group' (group)
08:42:10.020:     - source: '文字 (FreeType 2) 6' (text_ft2_source_v2)
08:42:10.020:     - source: '圖片' (image_source)
08:42:10.020:     - source: '媒體來源 2' (ffmpeg_source)
08:42:10.020:     - source: '媒體來源 3' (ffmpeg_source)
08:42:10.020:     - source: '瀏覽器 3' (browser_source)
08:42:10.020:     - source: '文字 (FreeType 2) 7' (text_ft2_source_v2)
08:42:10.020:     - source: '圖片 2' (image_source)
08:42:10.020:     - source: '文字 (FreeType 2) 8' (text_ft2_source_v2)
08:42:10.020: ------------------------------------------------
08:42:13.603: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:42:13.861: [obs-browser: 'https://studio.youtube.com/live_chat?is_popout=1&v=Tpmdkt8vfOY'] Error: Uncaught SyntaxError: Unexpected end of input (https://studio.youtube.com/live_chat?is_popout=1&v=uQC1P_oXAeI:13)
08:42:13.922: [obs-browser: 'https://studio.youtube.com/live_chat?is_popout=1&v=Tpmdkt8vfOY'] Error: This document requires 'TrustedHTML' assignment. (:1)
08:42:13.923: [obs-browser: 'https://studio.youtube.com/live_chat?is_popout=1&v=Tpmdkt8vfOY'] Error: Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment. (https://studio.youtube.com/live_chat?is_popout=1&v=uQC1P_oXAeI:1)
08:42:16.001: [obs-browser: '瀏覽器 2'] Error: Hydration completed but contains mismatches. (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:14)
08:42:20.529: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:42:27.176: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:42:27.225: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:27.225:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:27.227: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:27.227:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:27.227: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:42:27.227: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:42:27.228: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:27.228:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:27.229: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:42:32.233: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:42:35.617: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:42:37.026: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:42:43.470: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:42:43.574: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:43.574:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:43.575: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:42:51.212: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:42:58.097: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:58.097:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:58.097: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:42:58.097:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:42:58.097: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:42:58.097: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:43:12.481: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:43:17.725: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:43:17.904: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:43:29.102: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:43:29.102:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:43:29.105: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:43:29.105: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:43:29.105:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:43:29.105: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:43:38.958: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:44:01.127: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:44:01.127:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:44:01.128: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:44:01.128:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:44:01.128: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:44:01.129: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:44:09.647: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:44:09.721: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:44:15.893: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:44:31.098: [obs-browser: '瀏覽器 2'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:44:31.098:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:44:31.099: [obs-browser: '瀏覽器 2'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:44:31.101: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:44:31.101:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:44:31.102: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:44:38.486: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:44:49.521: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'
08:44:53.662: hotkeys-cocoa: Using layout 'com.apple.keylayout.ZhuyinBopomofo'
08:45:00.093: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: [UMAMI]: Uhm... Something went wrong and I have no clue. 
08:45:00.093:  (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:78)
08:45:00.094: [obs-browser: 'https://www.mcsv.top/server/supergodminecraft.ddns.net'] Error: TypeError: Failed to fetch (https://www.mcsv.top/_nuxt/s-PFL9Xk8o.js:79)
08:45:00.947: hotkeys-cocoa: Using layout 'com.apple.keylayout.ABC'

**Comment by WarmUpTill** [comment]
The minimum supported OBS version for this plugin is OBS 30.
Unfortunately, you seem to be using OBS 29 still and thus the plugin fails to load.

**Comment by WarmUpTill** [comment]
As far as I remember the last version of the plugin supporting OBS 29 on MacOS was the following:
https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.23.1

I will close this for now, let me know if you need further support! :)
