### ISSUE TITLE
OBS crash when Twitch IRC server closes for maintenance

### ISSUE THREAD

**Issue by StreetCatLove** [WarmUpTill/SceneSwitcher#1178]
**Describe the bug**
OBS crash when Twitch IRC server closes for maintenance

**To Reproduce**
1. Set up macro based on twitch chat
2. Twitch IRC closes connection
3. OBS crashes

**Expected behavior**
OBS does not crash

**Logs**
01:58:33.681: [adv-ss] The Twitch IRC server is about to terminate the connection for maintenance.
01:58:33.682: [adv-ss] Received RECONNECT notice! Twitch chat connection will be terminated!
*obs crash*

01:13:28.649: [adv-ss] The Twitch IRC server is about to terminate the connection for maintenance.
01:13:28.649: [adv-ss] Received RECONNECT notice! Twitch chat connection will be terminated!
*obs crash*

01:46:35.974: [adv-ss] The Twitch IRC server is about to terminate the connection for maintenance.
01:46:35.974: [adv-ss] Received RECONNECT notice! Twitch chat connection will be terminated!
*obs crash*

03:14:46.597: [adv-ss] The Twitch IRC server is about to terminate the connection for maintenance.
03:14:46.597: [adv-ss] Received RECONNECT notice! Twitch chat connection will be terminated!
*obs crash*

**Version information**
 - OS: win 11
 - OBS Version 30.2.3, 30.2.2
 - Plugin Version 1.27.1, 1.26.4

**Additional context**

**Comment by StreetCatLove** [comment]
[2024-08-20 03-37-37.zip](https://github.com/user-attachments/files/16667078/2024-08-20.03-37-37.zip)
Here's a verbose log, doesn't seem like it has any addl info

**Comment by WarmUpTill** [comment]
Thanks for reporting the crash!
Do you also happen to have a crash report?

**Comment by StreetCatLove** [comment]
there are no crash reports that correspond to these crashes

**Comment by WarmUpTill** [comment]
Hm, that is unfortunate, but thanks for checking!

Just so I understand correctly:
When you say "crash" do you mean...

* OSB freezes up / is not responding / can no longer be interacted with.
* OBS immediately closes on its own.

**Comment by StreetCatLove** [comment]
OBS was immediately closing on its own and would ask to be restarted in safe mode upon relaunching

**Comment by WarmUpTill** [comment]
Sorry about the delay in getting back to you.
I think I was able to track down the problem.

A build with a fix should be available here in a few minutes, if you should need one urgently:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10515194739?pr=1179

I will clean up the code a bit more and release an official hotfix during the weekend.

Thanks again for reporting the issue!

**Comment by StreetCatLove** [comment]
thanks!! i've installed the new build and re-enabled the chat macros
