### ISSUE TITLE
Text matches but nothing happens

### ISSUE THREAD

**Issue by Synextesia** [WarmUpTill/SceneSwitcher#1180]
**Describe the bug**
I want to set a macro for when I die in a Game a Text source display the number of deaths. The game always shows "YOU DIED" text on screen (yes, it's Elden Ring), so when it displays that text, the counter takes the variable (current number), adds 1 and changes the text source. The problem is that the plugin perfectly detects the text displayed on screen, but when it does nothing happens. I tried running the macro with the "Run Macro" button and it works fine, but when it runs alone nothing happens.

**Expected behavior**
I expected the macro to run when the conditions are met. In other words, when the plugin detects the "YOU DIED" text, it should run the macro.
**Version information**
 - OS: Windows 11
 - OBS Version: 30.2
 - Plugin Version 1.26.4

**Comment by WarmUpTill** [comment]
Can you please share the macros you have set up? (E.g. by exporting them to a file on the General tab)
If you can, please also provide a log file with [verbose logging](https://github.com/WarmUpTill/SceneSwitcher/wiki/Troubleshooting#logging) enabled, of a startup where the issue was happening.

**Comment by WarmUpTill** [comment]
I will close this for now - feel free to reopen / open a new issue if you need further help :)
