### ISSUE TITLE
Feature request: Add title condition "if in view"

### ISSUE THREAD

**Issue by OzakIOne** [WarmUpTill/SceneSwitcher#119]
I use this plugin to switch from scene A to B when the active window of my browser contains "twitter"

I use these settings:

![obs](https://user-images.githubusercontent.com/29860391/107554235-f6ef0e00-6bd5-11eb-9869-ea634865fc32.png)

Normal behavior

https://user-images.githubusercontent.com/29860391/107552311-9e1e7600-6bd3-11eb-8a4b-3ab41bce72c8.mp4

"Bugged" behavior

https://user-images.githubusercontent.com/29860391/107552320-a1b1fd00-6bd3-11eb-9a4b-fc1c642387aa.mp4

And the problem is on the second video where it switched when twitter wasn't in view
I don't know if this is possible to implement such a condition or if i'm doing it in the wrong way

**Comment by WarmUpTill** [comment]
Ok, let me explain what these three options mean, but using Notepad++ as an example window.


- "if maximized" means the application with the specified window title needs to be maximized.
Meaning its window needs to cover the whole screen including the window header, but excluding the task bar.
You can usually reach this mode by pressing the square symbol in the windows header.
![max2](https://user-images.githubusercontent.com/19472752/107556104-4a625b80-6bd8-11eb-8225-4078cb453c7a.PNG)
Example:
![max](https://user-images.githubusercontent.com/19472752/107556117-4e8e7900-6bd8-11eb-91e0-3888945fd369.png)

- "if fullscreen" means the application with the specified window title needs to be in fullscreen mode, covering the whole screen.
In some applications you can enter fullscreen mode by pressing the F11 key.
Example:
![full](https://user-images.githubusercontent.com/19472752/107555608-a8427380-6bd7-11eb-822f-3e3f77722181.png)
Note that compared to the maximized case the task bar and window header is no longer visible.
A fullscreen window is automatically in the maximized state also.

- The "if focused" checkbox means that the window needs to be the front most window, usually being the one you are currently using.
Example of a window that is currently not focussed (the OBS window is in focus):
![no-focus](https://user-images.githubusercontent.com/19472752/107556540-d4122900-6bd8-11eb-9eef-bfea112b3a08.PNG)
Example of a window that is currently in focus:
![focus](https://user-images.githubusercontent.com/19472752/107556584-e2f8db80-6bd8-11eb-9c30-19fd911c564b.PNG)

The latter might be the option you are looking for.

**Comment by OzakIOne** [comment]
I understood it after, I thought when you had "focus" and "fullscreen" it was an "or" statement but its an "and" statement.
Maybe my setup is wrong and I shouldn't have a scene per monitor. Thanks a lot for this plugin it's really useful !

**Comment by WarmUpTill** [comment]
If you have your browser window only on the same monitor you could maybe use the pause tab to prevent window-title based scene switching on the other two scenes.

**Comment by OzakIOne** [comment]
Oh thanks I didn't think about this ...
