### ISSUE TITLE
No OCR features building - CMake files not detected

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1195]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### Advanced Scene Switcher Version

latest master

### Expected Behavior

Tesseract and other tools should build to make certain features like OCR available

### Current Behavior

```
Found OpenCV 4.10.0 in D:/Dev/Repositories/git/OBS-AdvancedSceneSwitcher/.deps/advss-build-dependencies/x64/vc17/lib
-- You might need to add D:\Dev\Repositories\git\OBS-AdvancedSceneSwitcher\.deps\advss-build-dependencies\x64\vc17\bin to your PATH to be able to run your applications.
CMake Warning at plugins/video/CMakeLists.txt:19 (find_package):
  By not providing "FindLeptonica.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Leptonica", but CMake did not find one.

  Could not find a package configuration file provided by "Leptonica" with
  any of the following names:

    LeptonicaConfig.cmake
    leptonica-config.cmake

  Add the installation prefix of "Leptonica" to CMAKE_PREFIX_PATH or set
  "Leptonica_DIR" to a directory containing one of the above files.  If
  "Leptonica" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at plugins/video/CMakeLists.txt:20 (find_package):
  By not providing "FindTesseract.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Tesseract", but CMake did not find one.

  Could not find a package configuration file provided by "Tesseract" with
  any of the following names:

    TesseractConfig.cmake
    tesseract-config.cmake

  Add the installation prefix of "Tesseract" to CMAKE_PREFIX_PATH or set
  "Tesseract_DIR" to a directory containing one of the above files.  If
  "Tesseract" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at plugins/video/CMakeLists.txt:36 (message):
  OCR capabilities of video condition disabled!

  Leptonica or Tesseract dependencies were not found!



  Sources are available under:
  D:/Dev/Repositories/git/OBS-AdvancedSceneSwitcher/deps/leptonica
```

### Steps to Reproduce

1. Sync submodules
2. Run `.github/scripts/Build-Windows.ps1` or `.github/scripts/Build-Deps-Windows.ps1`

**Comment by Destroy666x** [comment]
I also got this after cleaning everything: https://pastebin.com/wfuMqSK3 Then, on consecutive runs, errors above repeat.

**Comment by WarmUpTill** [comment]
Were there any build issues during the step building the dependencies?

Can you try if removing the `.deps` folder and then rebuilding via `.github/scripts/Build-Windows.ps1` resolves the issue?
(Sorry if you did this already when you mentioned "cleaning everything", just want to exclude this as the root cause)

**Comment by Destroy666x** [comment]
CMake 30.3.3

**Comment by WarmUpTill** [comment]
I think I _migth_ have found the root cause.
Are you using the `cleanup` branch?

If so, I think it broke with https://github.com/WarmUpTill/SceneSwitcher/pull/1184/commits/08e4fefeddfa6d8ad91775305a08d91c48f7d749.
Can you try reverting that commit locally and see if that makes a difference on your side?

**Comment by Destroy666x** [comment]
That was it, thanks. I think I had `.deps` leftover from that branch on master when I tested.

**Comment by andreaxhearts** [comment]
I'm attempting to compile the latest master, I have this exact issue, except on Linux. I'm running Ubuntu 25.04.

```
$ tesseract -v
tesseract 5.5.0
 leptonica-1.84.1
  libgif 5.2.2 : libjpeg 8d (libjpeg-turbo 2.1.5) : libpng 1.6.47 : libtiff 4.5.1 : zlib 1.3.1 : libwebp 1.5.0 : libopenjp2 2.5.3
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.4 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
 Found libcurl/8.12.1 OpenSSL/3.4.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.8 libpsl/0.21.2 libssh2/1.11.1 nghttp2/1.64.0 librtmp/2.3 OpenLDAP/2.6.9

$ ./.github/scripts/build-deps-linux.sh --target linux-x86_64 --config RelWithDebInfo
...
```
The dependencies should be installed. I purged everything Tesseract related and reinstalled too.
Also tried [1.30.0-beta1](https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.30.0-beta1)

**Comment by WarmUpTill** [comment]
If you want to compile the plug-in with ocr support on Linux please fine using the "dev" branch a try.

**Comment by andreaxhearts** [comment]
Yep that's all I had to do, all the Video condition options are available now. Thanks!
