### ISSUE TITLE
Crashes whenever I switch between macros

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1199]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### Advanced Scene Switcher Version

cleanup branch

### Expected Behavior

No crash URL/file, I can only copy it, so pasting it here: https://pastebin.com/AR9dKuu9

### Current Behavior

Crash

### Steps to Reproduce

Don't know. I added few macros related to OCR/variables/text sources and it started happening quite regularly. Let me know if you need more info.

**Comment by Destroy666x** [comment]
From what I see that's related to saving and that makes sense as it crashes each time I do action that could save now. E.g. importing a scene collection backup I have also doesn't work due to that. I have no setting backups unfortunately. So no idea what to do. I'll send you my settings privately as they may contain sensitive data

**Comment by WarmUpTill** [comment]
I don't really see any involvement of the plugin in the call trace.
So it really just seems to crash in OBS' code handling the saving of data.

>I'll send you my settings privately as they may contain sensitive data

Thank you.
Will be very interesting to see if I can reproduce it.

>I have no setting backups unfortunately

Not sure if it helps, but some backups are saved automatically under:
C:\Users\<your user name>\AppData\Roaming\obs-studio\plugin_config\advanced-scene-switcher

**Comment by Destroy666x** [comment]
Something extremely weird is going on:
- now after PC reset the scene collection reverted itself to some older one. Works fine for now, I made the same (I think) missing changes to it, we'll see if it works
- the scene collection had a missing font in one of text sources, everything else seems fine in terms of being saved
- macro switching is very slow in general, I assume due to saving, it was 2-4x faster for non-Twitch macros before though

So maybe it was the font bugging things out. I'll send you the old scene collection in a bit.

**Comment by Destroy666x** [comment]
It crashed again after a bit. Perhaps one thing that should exist is a way to disable the saving on macro switching in case of weirdness like this.

**Comment by Destroy666x** [comment]
As mentioned in PMs, this was a random mistake of assigning a numeric value to Font property of text sources instead of Text.

I'll close this one and I'll open a feature request for disabling the autosaving temporarily as it made debugging this obnoxious, with wrong crashing save on each macro switch.
