### ISSUE TITLE
Allow disabling autosaving macros on switching

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1200]
### Background

See https://github.com/WarmUpTill/SceneSwitcher/issues/1199
Another reason is that it notably slows down opening of macros if you got a lot of stuff.

### Solution

Add a switch to general settings to disable autosave on macro switching

### Alternatives

\-

### Anything else we should know?

\-

**Comment by WarmUpTill** [comment]
Implemented with [e119510](https://github.com/WarmUpTill/SceneSwitcher/pull/1184/commits/e119510d9d527b0c5b95a7b2ac85e86d9e977a45).

**Comment by Destroy666x** [comment]
Just tested and switching is still very very slow, hmm. Weird. Since the slowness started happening more or less when saving was introduced.

**Comment by Destroy666x** [comment]
I'll close this since I'm 99.99% sure the feature is implemented well and will be merged. But any idea what could cause the slowness @WarmUpTill ?

**Comment by WarmUpTill** [comment]
>But any idea what else could cause the extreme slowness @WarmUpTill ?

Difficult to say to be honest.
Usually, the most amount of time is spent in creating all of the required widgets.

How large are the affected macros?

**Comment by Destroy666x** [comment]
All the macros, no matter how large. Any way to debug it?
