### ISSUE TITLE
Audio delay is set but not working

### ISSUE THREAD

**Issue by Helmarok** [WarmUpTill/SceneSwitcher#1208]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.27.2

### Plugin settings

AAAG7XicvVTNTttAEH6VyEeURHFIGuAGBFQkKLSOeqlQNVmPnW02u9b+pERR3qc8By/W2XXs2NBy6KEHS7vz+803n3cbrYBpZaKzb9tIwgqjs+iOk6WTooBN1I0KcIasGQiD/qZBCBS1QcnLBcicIqx2dDdLXlw9IbuXiQVt6zhjVXHOLFfS3GSflJ0qeaiaa+WK+pYqtkzQWi5zwrWNNObcWNR1wALMFycvnLVKVn3J9uCRvrESDOvMLcwboBc8Xwj67E12qWTKA6wZZdQRuqo/wycaIrp6enlmzoPYM9Lyhs7kcfKtb/rybIAGX6PuCOgU+1DW6luC3Gfcoukc3B2jpO1oXBWCo+m3Uq892PdyJZbpBZhWCU/xTUrxkK6N6QUN9LyxNz4ZnaRxOukNsxH2RvHktAds9KE3nJzCPB5PjtPhCRWgaQz3PMe7bimhcrk1nQn1ssTXgzLhHgRWeKHFk9Guuz8PB5Pd477AFc1SFnkvd1znDnxmpY2Pyi5xYxo6JZpLI2U/1qtpmqzKc4EPr80H+kJfg/kKpW0KkikhoDCY1u2oxKUjia/aOmNNW3S3IQH4I1HGPfmGofRaECrnjAaivTgNvvWdSnnGveS3keUr/E6gjNXApQ1xBj3KAGYNwuu2Pgz65Lebwh93fm5epjQ2RubQOkGBrCR4W6V0q1cgYS+/SD4/0Hm8pTceeGb9aigl6h8lvkr/KAoEzDTIcl8z0Dna4KypaLQnjoH9F4LBpVwROpQwF75a+SpULP8jfd2ybqKcZvgn6sID6kHAnt0RSVxRJaXL7W0ku88yg7bROB4NWp3nIECyNrRxM4DkwJbNAk3nWgm3aiU3vTR+0xcPXk2dQXrYnL/Mqgl/Aj+86TBX2p6Ht+26mUHLms4Pmw9Qphd/J7nm9thrA+t3wJQ/JJeFs19Bc7/EYPNh66ahovqzQ1dZ6qpR3B9O+sNo9xtTU2Fn

### Expected Behavior

I was expecting my microphone to be delay by 1400 ms when switching on a specific scene, and then my voice to be delayed so it can match my webcam that is purposly delayed by 1400 ms on the scene.

### Current Behavior

I can see that the delay of my microphone is "visually" delayed by 1400 ms when I open the advanced audio settings of the microphone, the value is 1400 ms, so that seems correct, but my microphone doesn't take into account this delay. If I manually re-write 1400 ms and press enter, the delay of my microphone is OK. It looks like the macro change the delay but don't really apply it.

### Steps to Reproduce

1. if condition "the actual scene is" the scene with the mic to be delay
2. then condition "audio", "define the delay of synchronisation", "microphone", "1400ms"
3. sorry if labels of menu doesn't match what I say, my OBS and plugins are in french
...

### Anything else we should know?

Is this suppose to work...? Thanks !

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
Hm ... I would have thought it is as straight forward as calling `obs_source_set_sync_offset()` as I am doing it in the audio action.
I will try to look into it.

**Comment by WarmUpTill** [comment]
Seems like this is a [known issue](https://github.com/obsproject/obs-studio/issues/7912) on OBS side.

A build with a workaround will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/11031630703/job/30638804599?pr=1212

The workaround seems to work fine in my tests.
But just in case please let me know if that solves the issue on your side, too. :)

**Comment by WarmUpTill** [comment]
I will merge the workaround / close this issue for now.
If it should not help please let me know :)

**Comment by Helmarok** [comment]
Sorry didn't see your message about the workaround. I let you know asap if the patch is OK. Thanks by the way and keep up the good work!
