### ISSUE TITLE
Size the settings window size

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#1211]
### Background

Every time the Advanced Scene Switcher is opened from tools, the window has to be resized.

### Solution

Save window settings to be reused next time it is open.

**Comment by WarmUpTill** [comment]
There is an option for this on the General tab:
![image](https://github.com/user-attachments/assets/3c066824-a1fa-43fa-b4c3-edaa1efdbebb)

**Comment by nospam2k** [comment]
Sorry! I didn't think to check for a setting. Thanks!
