### ISSUE TITLE
Stream deck broke WebSocket

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1219]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

latest master

### OBS Studio Log URL

https://obsproject.com/logs/Ec9CB9y74is8mvY6

### Expected Behavior

WebSocket messages should be received as previously

### Current Behavior

```
received unexpected stream deck message: {"message":"Plonked Germany, Thuringia, Saale-Orla-Kreis, Döblitz, 07819 (https://spoo.me/nJEK38) in 00:04. Result: 213 points, 334.80km away. Correct loc: Germany, North Rhine-Westphalia, Herne, 44623 (https://spoo.me/w55Sq7)"}
```

This is a WebSocket message, not Stream Deck message

### Steps to Reproduce

1. Add a simple websocket plugin message condition
2. Condition never is true, while logs speak about Stream Deck

**Comment by Destroy666x** [comment]
I don't have any Stream Deck conditions BTW, which makes it even more weird

**Comment by WarmUpTill** [comment]
Thanks for pointing that out!
Should be fixed with the linked PR.
