### ISSUE TITLE
Detect user joining/leaving chat in Twitch

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1229]
### Background

I know some bots are able to do so, e.g. Streamlabs Chatbot. It'd be useful to welcome certain users or types of users, notify yourself to be more/less talkative if more people join, etc.

### Solution

Add Twitch "User joined chat" and "User left chat" conditions, with some similar temp vars to the message ones.

[Docs](https://dev.twitch.tv/docs/chat/irc/#part-command) - I see Twitch chat sends `JOIN`/`PART` commands, but they're not too well documented, so not entirely sure if they're what the bots use.

**Comment by WarmUpTill** [comment]
Should be implemented with the linked PR.

**Comment by Destroy666x** [comment]
Seems to work fine, thanks. I assume no other undocumented tags or anything were present? Too bad
