### ISSUE TITLE
Scene item order - place after/before

### ISSUE THREAD

**Issue by erickskrauch** [WarmUpTill/SceneSwitcher#1234]
### Background

Sometimes I need to change an order of scene items before performing some animation with "Move" extension. But I need to keep steam notifictions on top. It would be much easier for me to do so by selecting "Move after" rather than calculating position of related elements.

### Solution

Introduce an "Move after" and "Move before" in addition to exists options.
<img src="https://github.com/user-attachments/assets/2fce51f0-5548-4227-acb6-8920fa856101">

**Comment by WarmUpTill** [comment]
A build with the requested functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/11353758600?pr=1239
![image](https://github.com/user-attachments/assets/044cd7bd-b22e-4d25-a383-3a9f5380c59f)

Please let me know if you run into any issues :)
