### ISSUE TITLE
Scenes changes in a loop and randomed playlist

### ISSUE THREAD

**Issue by jpuigs** [WarmUpTill/SceneSwitcher#1235]
First of all, let me explain what I have.
I have one folder which has 400 music videos, and have another folder which has promo videos.
I have 2 scenes, one called Music Videos and the other one called Promos
The Music Video scene has a VLC source, which I set to play videos located on Music Folder, and has both repeat and shuffle options enabled.
With these scene, I play continously music videos.
The Promos scene, has currently one promo video (will add more).

What I would like to do, and I can't get a right behaviour, is creating two macros to switch scenes from one to another.
First Macro is the one that switches from Music to Promo, and Second Macro from Promo to Music again.

First Macro says : If Media: Source (Music Videos) state matches ended  **AND** Fixed duration on 8 minutes has passed
==>
Switch Program Scene to Promos

Second Macro says: If Media: Source (Promos) state matches ended
==>
-Switch Program Scene to Music Videos
-Timer : Reset timers on switch to Promos

With these two macros, every 9 minutes (and when music video has finished) I see the promo, and the go back to some Music videos more.
Music, Music, Music, Promo, Music, Music, Music, Promo, Music ...

I have on problem.
When scene has to change, (every 3-4 music videos, depends on their lenght) I see some frames, let's say 1 second  (and hear audio) from next video, and then the promo starts, and when promo is finished, I see music videos again, but it's not from the beginning, it has one or two seconds from start.
I've tried to change: _pause when not visible, unpause when visible_ to other options (restart) but then shuffle mode on music videos doesn't work fine and repeat same video.

What could I do to get a perfect scene change, exactly when a video finishes, not on first frames from next one ?

**Comment by jpuigs** [comment]
I've tried If Media: Source (Music Videos) _**time restriction matches time remaining shorter than 1 sec.**_ instead of state _**matches ended**_  but result isn't good.

Besides, audio from first instants is not always played

**Comment by WarmUpTill** [comment]
It is a bit difficult to say what the proper solution for your particular setup will be without being much more familiar with you setup, so here a few general suggestions, which might not all be applicable:

One thing you could try to mitigate this issue, is to lower the "Check conditions every ... ms" value so the plugin can react faster.

![](https://github.com/user-attachments/assets/29f1de09-cedb-4280-bdfb-f88cd26cf54e)

Additionally you could try to explicitly pause the VLC source responsible for playing back the video source before switching scenes.
This should ensure that the source does not continue playing while the scene transition is still active.

![](https://github.com/user-attachments/assets/7a21afc0-80af-4fc4-9f86-11213459d639)

Another thing you could try is to seek the music video VLC source back to be beginning before switching back to the music video scene using the "Media" action.

![grafik](https://github.com/user-attachments/assets/ab40ddfc-a571-4572-a30b-6f1c97cfeef5)

>I've tried If Media: Source (Music Videos) time restriction matches time remaining shorter than 1 sec. instead of state matches ended but result isn't good.

Maybe values smaller than a second might work?

And in general a combination of all of the suggestions can of course be used as well.

>Besides, audio from first instants is not always played

I _think_ this is likely not related to the advanced scene switcher.
At least I would not know how the audio playback of a media source would be affected by what you described.

I hope that helped! :)
If you have further questions do not hesitate to ask!

**Comment by jpuigs** [comment]
Thank's !
I'll try as soon as possible !

**Comment by WarmUpTill** [comment]
I will close this for now as you have seem to have found a workaround. :)
