### ISSUE TITLE
Add "streamkey" condition

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#1247]
### Background

I'd like to be able to trigger something based on what the streamkey is. Unless I'm missing something, it's not possible to do that.

### Solution

Add streamkey condition :)

**Comment by Destroy666x** [comment]
How do you change the streamkey? Normally you use multiple profiles and there's a profile condition.

**Comment by nacalai** [comment]
@Destroy666x In many cases it does not make sense to use different profiles, since we're using one profile with all the settings we need, but each show will generate a new streamkey which we copy/paste in, (in the streaming settings).

 There's already a 'set streamkey' action which I requested earlier that was implemented, so now I'm just hoping for the equivalent part for the condition :)
