### ISSUE TITLE
Filter Settings Buttons nested within property groups are not found in filter actions

### ISSUE THREAD

**Issue by Bemjo** [WarmUpTill/SceneSwitcher#1250]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.28

### Plugin settings

AAAHmnic1VVNb9pAEP0raE+thJH5CCXcGpq0SKFNS5pLFEXLerBXmF1rP1AixH/v7HptbGhz6KVqpEj223kzb9/MmD3ZUqakJtPHPRF0C2RKFg7p9EmXpEragkzXNNfQJQW1GpZ0B1eQ0R2XikzjgDZiFM1zyGtAillGRYoRRll81xteXL8A+yaWhipTx2kji4/McCn0fP1Vmk9SHLO6uplUZsYVs9xc72huqYttRsws5tjOpEi4O5plwDZzYUBhdB3H3gzaE5cZGg9xb3B58tcl5rVwRwcsK7jxLuxAaa+nj2gi2WYJxnCRapdLQco11qhVZFT/sOLKGuMopTGI3Tkrz1D0yVh9S1cNVzOeZjn+m/m6vou+V/Zomary38MLSiRYj4RmtXBfk7ibnJ/9LDE8Za0ipaIQdKzfoQo6Tnavxbhxgt6ieMWO43ybJxhAk53WkZ/MyIHRanIxGq9XccTiSxqNxuNhtBrSccRW/ckABv31hDJy0gVPL0eqLrgscm6wE3dS83J+cOwLN/4XHw7d8DgcDQ5PgX+N0socf6YO+3HNjR2z6vcXaTbwqqteejNLDMlPtedNyMg0zeHuFD66Wb5TVr3siYZ0C8I0B47JPKeFhuR8P9pzxJoYWbx2cv+I7nHXhzXP3dh2CQi6yl26sMTSKubXJKxCt/p2LBng3iI/UH8TspA76Dz49TpUNyHTEZYUhTULMJlMfHxZJdzLZWprSkAzxYuSTm483Hl3i86/J779wtI8sMtyU4I0A9vigbaV8eSFTKN+uPXpIOnaWXfUUlUta9C2xas9lwKftf+8ncosP3qHdoX/tIfLMsPfNDEUP3Xn8TNWxh+Qp5D7H7fzTN9J43ARof4+hM3090dB3JntMRe2awKVX98t2Aqps5J+bzDpxeTwC2bRnVg=

### Expected Behavior

Creating a macro with a filter action that presses a settings button inside a filter that triggers the filter functionality.

Adding a filter onto a Source/Scene that has a button to activate functionality in the filter. The button is found, and triggering the macro triggers the button.

Adding a filter onto a Source/Scene that has a nested button inside a group to activate functionality in the filter. The button is found, and triggering the macro triggers the button.

### Current Behavior

Creating a macro with a filter action that presses a settings button inside a filter that triggers the filter functionality.

Adding a filter onto a Source/Scene that has a button to activate functionality in the filter. The button is found, and triggering the macro triggers the button.

Adding a filter onto a Source/Scene that has a nested button inside a group to activate functionality in the filter. The button is not found,

### Steps to Reproduce

1. Install [Move Transition plugin](https://github.com/exeldro/obs-move-transition)
2. Add Move Value Filter to a Scene.
3. Add Move Source Filter to a Scene.
4. In Advanced Scene Switcher, add new macro.
5. In actions, add a filter action, for this action, choose the Scene. Choose Press Settings Button, choose the Move Value filter, and select the {move_filter_start} Start button.
6. In actions, add another filter action, for this action choose the Scene. Choose Press Settings Button, choose the Move Source filter. No buttons are found.

### Anything else we should know?

In the Move Value filter, the section at the bottom where this settings button Start is located is not nested within a property group. The Advanced Scene Switcher can locate this button.

![image](https://github.com/user-attachments/assets/589012b8-da2f-4512-8b1b-7ce1a1226ec6)

In the Move Source filter, the section at the bottom where this settings button Start is located, it is nested inside a group named Actions. The Advanced Scene Switcher cannot locate this button.

![image](https://github.com/user-attachments/assets/fc3c8b87-e7ea-4394-bcaa-424ea6202583)

![image](https://github.com/user-attachments/assets/81165383-97b4-4092-9981-d417d71e6f9e)

For super quick reference related to this, even though I'm sure you're using at least the property_get_type function, here are related API calls that can probably be of use.

API function [obs_property_group_content](https://docs.obsproject.com/reference-properties#c.obs_property_group_content)

API function [obs_property_get_type](https://docs.obsproject.com/reference-properties#c.obs_property_get_type)

**Comment by WarmUpTill** [comment]
Thanks for pointing out the issue and the detailed problem description!

A build with a fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/11592095581?pr=1251

![image](https://github.com/user-attachments/assets/92a35a54-3340-4488-b2d1-12e0e4f091f9)

**Comment by Bemjo** [comment]
I can confirm that this is discovering the buttons correctly, and that a macro can trigger their effects.
Thank you for the quick fix!
