### ISSUE TITLE
Hotkeys to run macros

### ISSUE THREAD

**Issue by ibelieveinwhatileaveinthewaybehind** [WarmUpTill/SceneSwitcher#1258]
### Background

absolutely love this plugin, i've been using it for my school and it works wonders. i have a little macropad bound to F13, F14, etc that i'd like to use to run hotkeys on a keypress. it doesn't seem like advanced scene switcher supports this already, i've dug as deep as i can into the settings and can't find anything relevant to actually running a macro.

### Solution

it'd be nice if there was a way to add "run X macro" to the hotkeys settings page in OBS so that hotkeys can be used to run macros. maybe this could also be an option per-macro to enable it showing up in the hotkeys settings page?

**Comment by nacalai** [comment]
Did you _**really**_ dug deep as you can?

![image](https://github.com/user-attachments/assets/16130be4-5fd5-4709-b0be-c94b93125509)


😃

**Comment by ibelieveinwhatileaveinthewaybehind** [comment]
> Did you _**really**_ dug deep as you can?
> 
> ![image](https://private-user-images.githubusercontent.com/4357694/382603712-16130be4-5fd5-4709-b0be-c94b93125509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjczMTYsIm5iZiI6MTczMDY2NzAxNiwicGF0aCI6Ii80MzU3Njk0LzM4MjYwMzcxMi0xNjEzMGJlNC01ZmQ1LTQ3MDktYjBiZS1jOTRiOTMxMjU1MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMjA1MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNmMzYyZTNiZmQ3NGQzNmMxY2I3ZGY5MDhkZGI1MGJiZGQ3ZGUxMDdmN2FmYmM3ZDQ2NjA0ODdjMWY0ZjcwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mgIKIgZgeIAtYL7p--k7JU5YpmiPDymhVIjeUQR78L8)
> 
> 😃

thanks for pointing that out... i looked everywhere BUT there. i couldn't find anywhere online where this was explained so i assumed it just wasn't a thing after looking through the settings pages
