### ISSUE TITLE
"Current time" and "Duration" macro properties for Media condition don't work

### ISSUE THREAD

**Issue by Insurgent-X** [WarmUpTill/SceneSwitcher#1264]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.28.1

### Plugin settings

AAAJ9nicvVZdb9s2FP0rBJ+2zvIsx2scv6WeiwlIWi9O/TIUAy1eSUQkUiAp11mQ/75L6jtusmEPM2BAOrxfPPdcUk+0YLFWhq7+eKKSFUBX9NYhJKQTmmpVlXSVsNzAhJasMrBjR/gAGTsKpelq1qADG83yHPIOUHKdMZn2FuZBlJsTxJ/lzjJte9yq8jq2QkkTJZ+U/VXJ3sklzpS2a6HjStjNkeUVc7ZDi3WFMYq1kly4pXUG8UMkLWi07uziN42eqIsMg4fZdH714jeh9rF0S8+YVgrraTiCNr6eEFGu4ocdWCtkalwsDakwmKOrImPmrpIfKmudi9VVjW0dl2co8mQrc8MOA1ozkWY5/m2UdHsx97rqKdNt/Hs4YYkU89GmWyPc56RuJ+drX2oMV+NRkrqixqjPT5gG4sqejjw+uoLecvEVOx/HW8TRgPGjMYGXZuDA4JdwfrFMFu8DFs+XweJyNg+uODsEcbLg4ZwnyeXyQF90wbvXkuoS7spcWOzEVhlR6wd1Xzr9z2fYz+Y5vLp6/toE2GBtdZDXfcP3l53vzHm2Df9N2Qd4NOMRqkH0/tqxPoSsStMcti/hnk+f10BagLRDlcUqz1lpgJ8PxVg88RCjt48k949ImXDkF8AFQzJzlYrYi5tX2k/breIiEU7HT9SKAv7EoozVTMh6CAy4Ks3352j2T3ODsFGVjr1bYzppD6X9zZrsBQdFdrWNs45Bwg5yiOt2nHvRLuZ9uxK7ie/eDMoSn0LXMtyJaCJd9Hv+j5sZvWD7WPy/9O7ItGCH3I0sSPfA24OkXfnUHPKuyZFMFO2X5s1aJHGfghOP5wcgpuPYMab3NQsU32RV7N8mp9OtG5NJu/eIn+gqQNpNddgh7zJtboM+zDBIbyX+gteMcOjgtGVuRDEZnb6jDXbLbJz5jN93TITkd87QGdS0DS80Kwb3hyqbPraOWBcmcwcbsYo4xKctcxbDeK0ByTdhs7Y0PJgSkb6Vt+7eKG3BbLY5lajYWmD0BxKSn8icvCMX5EfyM1nQgX62WhVlf88KWVa2xeg1hkgl8ay4GlsprOoIkTd2VWcq54MLTJwt0CAAd48Si9sNAi/Ao9BKunbvx+L7stvcbe8+f4xuNvTfjrGFosQw/XLoJH/yZl763cC+mEMfPkL3SHIYaiAcaoAL3eb3x4IT2w3IFFv1ikfJOEcj/LzBohZLVDoz/TEznn7oLhFTn+aev5YVjzmz4wDoP8cGk2rw6+u6L5NDwqrcdvPYHzS/V1BBk6srhYbT+XIa0ue/AQxaZrg=

### Expected Behavior

When I changed a setting of a Media condition in a macro, I realized that two new macro properties came up, "Current time" and "Duration". So I decided to try to use a variable to retrieve the total duration of a media source (in my case, a VLC source).

### Current Behavior

The variable does not change. Also, the "State" macro property disappears and is replaced with the two aforementioned properties.

### Steps to Reproduce

1. Create a macro with a Media condition.
2. Change "state matches" to "time restriction matches", then set it back to "state matches".
3. Add a Variable action with the option to set the variable to the macro property. Set it to either "Current time" or "Duration".
4. Allow the macro to run.

**Comment by WarmUpTill** [comment]
Thanks for pointing out the problem!

The intention was that for state related properties to only be available when the state of the media source is checked.
The the duration related properties were only supposed to show when the timing related check were selected.

When initially opening the macro the correct selection would be shown, but when changing the check type from state to time related the wrong selection is shown instead.

A build with a fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/11898256140?pr=1265

**Comment by WarmUpTill** [comment]
I have merged the changes for now - let me know if you should still be facing issues :)
