### ISSUE TITLE
Variable condition has misspelling when invalid selection occurs

### ISSUE THREAD

**Issue by andreaxhearts** [WarmUpTill/SceneSwitcher#1269]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.28.1

### Expected Behavior

"Invalid variable selection" text

### Current Behavior

It shows as "Invalid varialbe selection".

An easy mistake to make, to be sure. 😆

### Steps to Reproduce

Create new macro, add Variable condition type. Click the --select variable-- drop down box. Click on "Add new variable", and hit cancel on the popup that opens. "Invalid varialbe selection" is shown.

**Comment by WarmUpTill** [comment]
Thanks for pointing it out! :)
It will be fixed with the linked PR.
