### ISSUE TITLE
Screenshot Save Custom Location Broken

### ISSUE THREAD

**Issue by emmafaye** [WarmUpTill/SceneSwitcher#1279]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.27.2

### Expected Behavior

Ideally, this should allow you to have similar functionality to the "Change filename formatting" under Recording. It should allow you to use a format like `%YY-%MM-%DD/%I.%mm %p` where you can also add in folder locations with slashes. It should also auto-pick a file type like png for screenshots or allow you to change that setting somewhere in the Advanced Scene Switcher settings.

### Current Behavior

When trying to set the custom location for taking screenshots of sources the "Save As" dialog won't allow you to pick a location unless you enter a filename. This doesn't follow the same behavior of "Change filename formatting" under Recording.

Instead, it saves to a single file location or won't save at all. I've also tried manually entering the file format, something like `%YY-%MM-%DD/%I.%mm %p` in the browse path, but that doesn't work either.

**Comment by WarmUpTill** [comment]
Unfortunately, the "Custom file path" option does not support the placeholders used OBS internally.
If you want to use such placeholders with this option you will have to use [variables](https://github.com/WarmUpTill/SceneSwitcher/wiki/Variables).

You can set up a helper macro like this to populate variables with the current date and time:

![1707002475935](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/2d4155cb-da00-4d02-83f7-03cde3ff654a)

You can [import](https://github.com/WarmUpTill/SceneSwitcher/wiki/Exporting-and-importing-individual-macros) this example using this code:

```
AAAVXnic7VhbbyI3FP4rlp/abaAMm220vG2zRIu0aVDIpqqqqDIzhxmLwR7ZHhYa8d97jj03GnVLSx4HgTT+zsXn8tmD/cw3Ijba8snvz1yJDfAJX4BjH4UD9iiMFMscLL/ghSgtClcit0AjI/Ic8gbQ6joTKm017FoW0x3Ed2rhhHENnhpdFs0o0fEap3NSpRjCMzeQSuvANAqZsPel+rl0Tis+caYM2JyieYHiTK60n8WyE1gm0yzHn5utrrVKpJNa2Qe0aDRM7f8Bdhgnx/nqfI9wPydKSvVS9iVgKI2PJgkRVUrt/EwYYBT28MjihgL6lomPeMgPF6FrH2ISNTqLIpcOizfX1o99TwvqbfT+3eGier56d3V4qhxM0V1w8s+2V9H7xnZElnWPPmm3hr3tcAIrEEC0fmoK1YWcTtMc5n+H2xL4eWOd56KwkDS+JT7yBDmJ9cp1KmOMBdlTGkFWtzqRK0mseeZObuAP9GedEVI5r2eBJvAE24qcWt88jIYod/uCHg8UsgwmWzDWlyE6IJyI/d3qV4C1lzXRhiAwqgcZFk6p2A0s2SUbjSbR28koYuPR+JK3SuNvaslUaQO09NrEPRT8B54bKEC066ksyPeduq/goFRX5n+m3Mn4OoN4XbstBHEEVfgQP+z4y4kcIv7XNm6rXQUTBkUPSe2+lvwS9qHfQBjeouMKnilMRCbM4/kSmIUc/LSojG1/DGlyHKly89hJutO46CeiRboB5WbJjk8GEY7L5cIZ3IqqHWvUheSf4BFkP+zmbR3e8Aq7FS7OvC/UWkmVoCEq0EJmTjNCvGqRixiOZRXIvkqX1e5wVa9kSm0LRepuvQ7zrmumi6rgI78ruGy6KwzY0En+HYvYD2zM3rC37Hv2IyOW4dq7Lq3Tm7nRm6JlklRF6WqMf0AXqWKeMxRj3YVJ8DDzyhR1pvOks2HLFwI+GGCVwTCH6Q4Gvu1babSi4j8et/zLYno/v7+7mX2eUjNjULBoukurO9D2on5V0VboYFOgm1YcEdFCHzzh9sSjA21i5zLyVivfoZ6SPSXPouTGE+lVOPlR7HtG9ow8l5H4wn8dPn7SZf/W7gl5NiEz4tHrvLWlKv3Joedkz8nzXtuBSa/CyoU/lPas7Fl5LivD9QayEs/f0Nzo0Bn8iaA6s6M7vupsbcW2Ug93GbASZe4ahhHP1fHR53SL8Mf0dP3qj8N/CKne1083aRbd6SYPYN0JBk+dCxQeDceXwzE//AVvTSre
```

And then you can use these variables like this in the screenshot action:
![image](https://github.com/user-attachments/assets/f4ebd58b-ba79-4b8e-af02-d7898a594fa6)

I hope that helps!

**Comment by emmafaye** [comment]
This is really helpful!! Thank you for such a detailed response, I'll give this a try!

**Comment by emmafaye** [comment]
I was able to get this working with the following format: `R:/Screenshots/${SS-Year}-${SS-Month}-${SS-Day}_${SS-Hour}.${SS-Minute}.${SS-Second} Facecam.png`. The only caveat is that you can't set an additional subpath using variables, so a folder structure of `Date/Time.png` wouldn't work for me. Not perfect but at least it's a functioning solution! :)

For anyone coming across this in the future, I'd recommend adding another condition to the "Set Date Variables" macro for when you press whatever button you use for your screenshot hotkey. This will avoid running the macro constantly until you need it to run. Just make sure the "Set Date Variables" macro is ordered above the macro where you set the custom file path so that it can set the variables prior. Also, if you run into issues getting this to work, try clicking browse and set the filename to be `${Year}-${Month}-${Day} ${Hour}.${Minute}.${Second}.png`.

Thanks for the help @WarmUpTill, I'll go ahead and close this out as won't fix.
