### ISSUE TITLE
Idea: switch based on content-match of screen rect

### ISSUE THREAD

**Issue by jeske** [WarmUpTill/SceneSwitcher#13]
Idea: A mechanism to switch to a Scene while a certain set of screen pixels match a reference image. 

One way to do this would be to add a "Content Check" video source filter which would content check vs a reference image for a source. This way the existing filter stack could be used before the match check to Crop/Chroma/Mask the contents.  The configure UI for the Content Check filter could have a "capture refernece" button, which would capture the current reference pixels and store as the match pattern in the config. It would also be helpful to have a "capture refernece to file" button, which would save the current exact image source pixels to a file so one could construct a pixel correct mask image.
 
The decision result of the content check could be written to the (0,0)  pixel as specific red/green values -- or perhaps just communicated to scene switcher in an out-of-band way... 

Also so the Content-Check filter could be used for other things, it would be nice if the filter could "pass content only on match (alpha black otherwise)" on setting, and have a configurable "linger time" after the match occurance, and either linger the "static match image" or linger the "live video"... So if there was some fun in-game announce, people could configure it to automatically make it bigger and centered on the screen, and "linger" longer.

The "content check" source would be at the bottom of the viewport stack so it would not be visible, and just about the only caveat I can see is if OBS does something "too smart" about not processing a video source if it's not visible.. but I don't think it does this.

-----

What would this be used for?

A problem that frequently comes up is the need to block out certain game UI elements while streaming. Such as in open world PvP games, where one wishes to block out information that could lead to someone knowing where you are.

In some games this can be done with static coverups that stay on the screen all the time. However, in other games this is impractical, as there are dialogs and many different screens/overlays which need blocking. (such as Albion Online)

An excellent solution to this problem would be the ability to specify an automatic scene switch when a certain rectangle of the screen matches a certain pixel pattern. (with some error tolorance). While this sounds limiting, in practice most of the blocking situations have static UI HUD elements which could easily be detected to determine a blocking scene switch is necessary.

**Comment by bradtem** [comment]
Let me describe a similar but simpler function and what it would be used for -- simply switching based on the colour of a pixel.    The application is streaming slide presentations and screen demos where you are mixing in the slides with webcam video or other sources.   On some slides you want the webcam video to appear in the corner.  Other times you want it to fill the screen and not show the slide.   Other times you don't want to see it at all.  You may want to change its size or grow it etc.      Sometimes greenscreen me into the slides.  Other times, put a background behind me as it doesn't blend well.  Etc.

This tool would allow you to put "clues" in the slides, single pixel clues, as to what scene is right for that slide.   Thus the user would just play the deck and their video would be mixed correctly.   Playing a video -- get rid of my face.  Time to cut to just me, put in a slide with the right colour.  Got a slide where I've left room on the right side for my face -- put in a version that fills that region etc.   Even switch camera angles based on what slide I am showing.

Unless you can think of a better and easier way to signal a scene change.  Since slide programs are different, it's better not to use one tied to powerpoint (though its speaker notes could be used for the clue pixels.)

**Comment by WarmUpTill** [comment]
Just for future reference.
HoneyHazard is working on plugin for this.
https://github.com/HoneyHazard/PixelMatchSwitcher

**Comment by jeske** [comment]
FYI - I was the original requester, and I specced out and funded HoneyHazard's development work, because I think this would be a useful addition to OBS. Pixel Match Switcher is already quite usable. We want to get it out to the community, so hopefully you can help support getting it used and tested and eventually merged into OBS!

**Comment by jeske** [comment]
@bradtem - Assuming the pixel-locations in the slides are stable, you can use PixelMatchSwitcher to do what you want now. I encourage you to give it a try. You could either put small color code in the corner to match on, or you could match on specific "video location boxes" in the slides.

https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.14-alpha

As a future followup, it might not be too hard to make a related but different plugin that looks for a specific chroma-colored rectangle anywhere in a source, and relocates a video source into it... though I suspect it would be a different plugin and development effort... After we get OBS wrapped up I'll talk to HoneyHazard about it.

**Comment by bradtem** [comment]
Good to hear about.     I recently saw somebody who built this a different way -- they used the remote control API for OBS and would read the speaker notes in powerpoint to look for scene name commands, and send them to OBS.   That's very powerpoint specific, but the interface for the user is of course nicer than putting in the coloured dot.      But I don't use powerpoint anyway.

I look forward to this getting out of alpha.  My normal build environment is linux but I run OBS on windows.   Looks like right now it replaces your whole OBS and is not yet a loadable extension?

**Comment by jeske** [comment]
Yes, right now PixelMatchSwitcher requires a custom build of OBS.. because in order to implement the plugin, we needed to add things to the GPU effect language built into OBS. It's basically support for atomic GPU counters, so our effect shader can count matching pixels and communicate that back to the CPU code. 

We hope it won't take long for these patches to be accepted into OBS proper once we publicly announce PixelMatchSwitcher on the forums and initiate a pull request.. once these changes are accepted, PixelMatchSwitcher can be "just a plugin". 

HoneyHazard has been working on PixelMatchSwitcher for a few months now... and we're just about ready to do a public forum post. We're tentatively planning on this coming Tuesday.

For the curious, these patches are in our OBS fork here 

- https://github.com/HoneyHazard/obs-studio-atomic-effects
- https://github.com/obsproject/obs-studio/compare/master...HoneyHazard:single_uav_buffer

**Comment by bradtem** [comment]
I thought one way to do it would be to supply a filter.  Filters get access to the frame buffer and normally modify it, but don't need to. A filter could just examine it, and send messages to a scene switcher so it would be portable, no GPU code.

**Comment by HoneyHazard** [comment]
> I thought one way to do it would be to supply a filter. Filters get access to the frame buffer and normally modify it, but don't need to. A filter could just examine it, and send messages to a scene switcher so it would be portable, no GPU code.

We indeed use a filter, but we use atomic counters in the effect/shader for a greater performance than frame readbacks will ever give us. (frame readbacks are used but only for things like extracting region images from the filter's output, as a source of match image or match mask) @jeske wanted a plugin that is fast, and nothing would beat shaders.

One could mention that OBS already does a lot of specialized GPU things in reaction to effects. We made effects do a little more and we now do more GPU things to support that. Just like before, you write the same effect code that is agnostic to whether D3D11 or OpenGL is used.

> I look forward to this getting out of alpha. My normal build environment is linux but I run OBS on windows. Looks like right now it replaces your whole OBS and is not yet a loadable extension?

Like @jeske said, it is a loadable extention but right now you need a special fork of OBS to support the plugin. 

I fixed a few bugs yesterday and was doing successful builds on Debian 10 yesterday. There are Debian instructions for [building the whole tree](https://github.com/HoneyHazard/PixelMatchSwitcher/wiki/Build-in-OBS-Tree-on-Debian-based-Linux) (atomic effects fork of OBS + plugin). This involved the fork made specifically for this purpose, and it is the easiest way to get things building and installing. You can also build the plugin [outside of the OBS source tree](https://github.com/HoneyHazard/PixelMatchSwitcher/wiki/Building-and-Running-on-Linux), but you still need the atomic-effects fork to support atomic counters.

**Comment by jeske** [comment]
We actually experimented with readback and CPU matching, but this method can't even match a single match rrgion fast enough to switch in the same frame.. and even with complex multithreading it might not be practical to check every frame for matches, and all that CPU use would severely affect laptop battery life.

GPU matching is very efficient...can have many match tests tested every frame, and still match and switch in the same frame. And laptop battery usage is minimal.

Matching every frame and switching in the same frame is important for our primary use case.. which is allowing game streamers to trigger mask coverups the prevent leaking sensitive data into their game stream for even a singlrle frame.

**Comment by WarmUpTill** [comment]
I now added very basic functionality like this to the plug-in with e4bb034303bdf5385f27ecb380890a1bebc08eb8.
It works by continuously making screenshots of the selected source and comparing it to the target image.

@HoneyHazard I hope you don't mind me linking to your plug-in for a much better implementation of this functionality.

**Comment by HoneyHazard** [comment]
> @HoneyHazard I hope you don't mind me linking to your plug-in for a much better implementation of this functionality.

Not at all. Open source all the way! I have learned a lot from your plugin, and will be happy to know if you've found some use for our work.
