### ISSUE TITLE
Client for 2 PC Setup

### ISSUE THREAD

**Issue by cyclemat** [WarmUpTill/SceneSwitcher#133]
hey very good work but i have an idea for 2 PC Setups,
a Client that runs on the Video source PC "Gaming PC" and gives Informations to the sceneswitcher on the Stream PC so when you Start a Programm the scene switcher on the Stream PC can change a Scene ore something else ! is it possible
so you can use OBs only on the StreamPC an when you loose the focus on the game PC you can changs in another scene or activate or deactivate the source

**Comment by WarmUpTill** [comment]
Thanks for the suggestion - I will look into it.

In the meantime it might be an option to use the file tab for this purpose, assuming you have to option to use a network share, which is available to both PCs.
On the stream PC select the option to read the current scene from a file.
On the Gaming PC select to write the current scene to a file.

This of  course assumes that all scenes exist on both OBS instances.

**Comment by WarmUpTill** [comment]
I now implemented a first version of the network tab, which will allow you to synchronize the active scene between two instances of OBS. (Sorry that it took so long)
The network tab allows you to open a websocket or connect to websocket.
The functionality is mostly based on https://github.com/Palakis/obs-websocket.

An OBS instance running a server will send its currently active scene to all connected clients on scene change.
By default all scene switches will trigger a message to be sent to all clients, but you also have the option to limit sending these messages only when an automated scene change is triggered by the advanced scene switcher.

Below you can find a screenshot:

![NetworkTab](https://user-images.githubusercontent.com/19472752/111914491-747a2980-8a72-11eb-94b1-dee8fd309d7c.PNG)



You can find a test build here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/673983471

Any feedback is welcome! :)

**Comment by cyclemat** [comment]
Wtf  that Was fast will test it tomorrow.



WarmUpTill ***@***.***> schrieb am So., 21. März 2021, 21:58:

**Comment by cyclemat** [comment]
Works greate for an 2 PC OBS setup but the little problem is when you
didnt rum obs on the GamePC you need a little client that makes the checks
what the scene switcher need

Config

Game PC
NDI HX Display capture (Why? you can send NDI with 144 hz refreshrate ;) )

Stream PC
OBS Studio with A.S.S Plugin

So A litttle client on the Game PC Must Check what is running where is the
mouse the same as the A.S.S reads Normally and what windows is in focus and
send it to the A.S.S Plugin on the Stream PC

so you have an NDI Scene for the Desktop/Game and a Scene with
a Gamebackground ( Screenshot of COD as sample) as Placeholder when the
game is not showing so you never show your desktop and leak anything !

is that possible ?

then you have a fully Network function for all people.



Am Mo., 22. März 2021 um 02:03 Uhr schrieb Michael Reuter <
***@***.***>:

**Comment by WarmUpTill** [comment]
I am not sure if I understand your request correctly - so let me know if I do not. ;)

What is the issue with running a second instance of OBS on the Game PC?
You don't actually need to recording / stream anything there.

Sending network messages whenever the mouse moves a single pixel or whenever a new window name appears will probably cause way more load then just sending a single message when to switch scenes.
(Not to mention that this would be very impractical for other scene switching methods, e.g. video / audio based scene switching)

So while in theory it would be possible to develop an external tool that is completely independent of OBS I do not think it would be reasonable for me to try to implement it.

**Comment by cyclemat** [comment]
That is it okay i have test it so and you are right the load is Not more
than an other Client. Will test more. 😁

WarmUpTill ***@***.***> schrieb am Mo., 22. März 2021, 14:45:
