### ISSUE TITLE
macOS Catalina support?

### ISSUE THREAD

**Issue by one2gov** [WarmUpTill/SceneSwitcher#14]
Plugin doesn't shows up in the menu bar

**Comment by emigr2k1** [comment]
Download OBS 24.0.2. Go to `OBS(24.0.2).app/Contents` and copy the `Resources` folder. Now go to the latest OBS app folder `OBS(latest).app/` and paste the `Resources` folder there, so it looks like this:
```
OBS.app
    /Contents
    /Resources
```
Now you have to paste the plugin in `OBS.app/Contents/Plugins`.

**Comment by one2gov** [comment]
wow, that actually worked. Amazing, thank you! So it's just old paths, heh
