### ISSUE TITLE
Latest version audio not switching in Windows 10 - OBS 26.1.1

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#142]
I just installed the updated plugin from previous version. Audio switching is not working. Uninstalled and reinstalled previous version working fine.

**Comment by nospam2k** [comment]
My setup looks like yours. I'm wondering if the problem may be related to old settings. Where are the settings stored? I'll try wiping them out. I tried just deleting them and re-configuring but that didn't help. I'm using to Mic sources and cut for transition, but my otherwise config looks the same as yours.

**Comment by WarmUpTill** [comment]
Have you checked the log file for any hints while enabling verbose logging?
There should not be any difference between version 1.9 and 1.10 regarding audio scene switching.

If you want to completely reset the settings of the plugin just create a new file with the following content and import it on the General tab:
``{}``

**Comment by nospam2k** [comment]
I'm not on site but will try playing with it and get some logs.

**Comment by WarmUpTill** [comment]
But just in case there is still a bug hidden somewhere please save your current settings of the plugin by exporting them to a file, before overwriting them! :)

**Comment by nospam2k** [comment]
Ok, so what I did is create two scenes, Test1, Test2. In each scene are two media sources: Audio Source 1, Audio Source 2. They each point to an mp3 that just loops test recorded about a second apart to flip back and forth. I imported a blank file and then set up ONLY the Audio Tab with Source Audio Source 1 above 55% for 0s switch to Test1 using cut. Same for the 2nd entry but Audio Source 2, Test2. Everything else is default, except I enabled verbose logging. I verified that Advance Scene Switcher is active. Where is the log and I will upload that.

<img width="1104" alt="Screen Shot 2021-03-17 at 9 38 56 AM" src="https://user-images.githubusercontent.com/1284287/111504152-9dae5900-8704-11eb-9068-57af037a06fa.png">

<img width="1106" alt="Screen Shot 2021-03-17 at 9 41 52 AM" src="https://user-images.githubusercontent.com/1284287/111504557-07c6fe00-8705-11eb-977c-600d17fd7f3b.png">

**Comment by WarmUpTill** [comment]
You can find the log files here:
![LogFiles](https://user-images.githubusercontent.com/19472752/111505284-c5271500-8748-11eb-90a5-29ef22cf881c.png)

**Comment by nospam2k** [comment]
[adv-ss] started
08:48:50.914: [adv-ss] try to sleep for 300
08:48:50.925: ---------------------------------
08:48:50.925: [DShow Device: 'Jordan Cam'] settings updated: 
08:48:50.925: 	video device: AVer CAM520 Pro
08:48:50.925: 	video path: \\?\usb#vid_2574&pid_09b0&mi_00#8&9d4ebd3&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
08:48:50.925: 	resolution: 1920x1080
08:48:50.925: 	flip: 0
08:48:50.925: 	fps: 60.00 (interval: 166666)
08:48:50.925: 	format: MJPEG
08:48:50.955: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Audio Source 2)
08:48:50.955: 
08:48:51.214: [adv-ss] match for 'audio' - switch to scene 'Test1'
08:48:51.215: [adv-ss] switched scene
08:48:51.215: [adv-ss] try to sleep for 300
08:48:51.246: User switched to scene 'Test2'
08:48:51.514: [adv-ss] match for 'audio' - switch to scene 'Test2'
08:48:51.515: [adv-ss] switched scene
08:48:51.515: [adv-ss] try to sleep for 300
08:48:51.546: User switched to scene 'Test1'
08:48:51.816: [adv-ss] try to sleep for 299
08:48:52.116: [adv-ss] try to sleep for 299
08:48:52.416: [adv-ss] try to sleep for 300
08:48:52.716: [adv-ss] try to sleep for 299
08:48:53.016: [adv-ss] try to sleep for 299
08:48:53.317: [adv-ss] try to sleep for 299
08:48:53.617: [adv-ss] try to sleep for 299
08:48:53.918: [adv-ss] try to sleep for 299
08:48:54.217: [adv-ss] try to sleep for 299
08:48:54.518: [adv-ss] try to sleep for 299
08:48:54.818: [adv-ss] try to sleep for 299
08:48:55.118: [adv-ss] try to sleep for 299
08:48:55.418: [adv-ss] try to sleep for 300
08:48:55.719: [adv-ss] try to sleep for 299
08:48:56.019: [adv-ss] try to sleep for 300
08:48:56.319: [adv-ss] try to sleep for 300
08:48:56.620: [adv-ss] try to sleep for 300
08:48:56.920: [adv-ss] try to sleep for 299
08:48:57.221: [adv-ss] try to sleep for 298
08:48:57.521: [adv-ss] try to sleep for 299
08:48:57.820: [adv-ss] try to sleep for 300
08:48:58.120: [adv-ss] try to sleep for 300
08:48:58.421: [adv-ss] try to sleep for 300
08:48:58.721: [adv-ss] try to sleep for 299
08:48:59.021: [adv-ss] try to sleep for 300
08:48:59.321: [adv-ss] try to sleep for 300
08:48:59.622: [adv-ss] try to sleep for 299
08:48:59.922: [adv-ss] try to sleep for 300
08:49:00.223: [adv-ss] try to sleep for 299
08:49:00.522: [adv-ss] try to sleep for 300
08:49:00.823: [adv-ss] try to sleep for 300
08:49:09.691: Last log entry repeated for 29 more lines
08:49:09.691: ==== Shutting down ==================================================
08:49:09.717: [adv-ss] stopped

**Comment by nospam2k** [comment]
I opened it and let it run for about 30 seconds or so. When it first came up (OBS) I saw Test 1 and Test 2 flick back and forth and that was it.

**Comment by WarmUpTill** [comment]
Well, according to the log file switching scenes based on the audio is working:
```
08:48:51.214: [adv-ss] match for 'audio' - switch to scene 'Test1'
08:48:51.215: [adv-ss] switched scene
08:48:51.215: [adv-ss] try to sleep for 300
08:48:51.246: User switched to scene 'Test2'
08:48:51.514: [adv-ss] match for 'audio' - switch to scene 'Test2'
08:48:51.515: [adv-ss] switched scene
```
What exactly is the issue then?

**Comment by nospam2k** [comment]
It only switched once and then stopped switching back and forth as the previous version.

**Comment by nospam2k** [comment]
https://user-images.githubusercontent.com/1284287/111507022-760cc000-8707-11eb-97dd-3b9e2d1b43ec.mov

Here is a screen recording in mov. I can convert it to mp4 if you prefer

**Comment by nospam2k** [comment]
Ok, so I exported my profile and scene collection and then wiped c:\User\[username]\AppData\Roaming\obs-studio and then reconfigured just the example I gave here and it is now working. I'm not sure where the conflict is but it's working now. I can zip and send you the profile/collection if you are interested.

**Comment by nospam2k** [comment]
[Current-scene-collection.zip](https://github.com/WarmUpTill/SceneSwitcher/files/6158385/Current-scene-collection.zip)

**Comment by WarmUpTill** [comment]
It could have been related to the volume levels you set for Audio Source 1 and 2.
You set these to `"volume": 0.69840127229690552` and `"volume": 0.69333106279373169` respectively.
So for these sources to reach the desired threshold of `0.55` they have to be _very_ loud.

But other than that I could not find any obvious hints as to what could have been the issue.

I will close the issue for now.
Feel free to reopen if there is still something that needs to be clarified.

**Comment by nospam2k** [comment]
Thank you. It did have the YouTube stream key but not critical as we regenerate often anyway.

**Comment by nospam2k** [comment]
Ok, I was putting things back together and it stopped working again. The good news is I found the problem. When I change global audio in settings, it stops working.
