### ISSUE TITLE
Latest version audio not switching when General audio is mono in Windows 10 - OBS 26.1.1

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#144]
Further to #142

Sorry to open this as a new issue but I couldn't find a way to reopen and old issue.

Ok, I was putting things back together and it stopped working again. The good news is I found the problem. When I change General audio in settings, it stops working. I verified this by going into settings and changing back to Stereo and it started working. Ok, not to put too fine a point on it. I restored my old profile and scenes and just changed from mono back to stereo and it is working so that is definitely an issue.

**Comment by WarmUpTill** [comment]
Thanks for investigating this further!

Turns out it was a simple off by one error, as I started counting from "1" while iterating through the audio channels for some inexplicable reason.

You can find a test build here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/666280387

**Comment by nospam2k** [comment]
Interesting that last bit about being always wrong as I was using a previous version that was working with mono! Not sure how far back the version I had.

Error on the build. Process completed with exit code 1.

**Comment by WarmUpTill** [comment]
The build error is nothing serious and only affects the MacOS version. (I will look into this tomorrow)
You can still use the windows artifacts:
 https://github.com/WarmUpTill/SceneSwitcher/suites/2293164775/artifacts/48035743

**Comment by nospam2k** [comment]
Glad you got it ;) I really like the plugin. I've d/led the update. Will try later and report back.

**Comment by nospam2k** [comment]
Tested. Looks like it's fixed!
