### ISSUE TITLE
Wishlist: 3rd camera "fake" cameramen

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#147]
This may be already implementable but I thought I would ask. The idea in my head is for our podcast. Currently we have two cameras switch between speakers as they change speaking (audio trigger). What I'd like to have is the ability to have a relatively random scene of a wide angle third camera that holds for 10 seconds or so and then goes back to the normal switching between the to audio triggered cameras. I'd like this to happen like every several minutes or so. So the trick will be during the time of the wide angle scene the audio triggered cameras are ignored. Also, I'd like it to be able to have some randomness to it so it doesn't just switch every 3 minutes (that's icing on the cake though) like clockwork or stay on the scene for X seconds.

**Comment by WarmUpTill** [comment]
I am not sure if this will work perfectly but you might be able to achieve something similar to what you are looking using Scene Groups, Scene Sequences and the Audio based scene switching.

In my example I used the following two audio sources:
- my microphone
- a random media source

I have the following scenes set up:
- mic-scene
- media-source-scene
- wide-angle-scene
- wide-angle-scene-hold

And added these two scene groups (adjust the timing values to your needs):
![SceneGroup](https://user-images.githubusercontent.com/19472752/111882738-7632e700-89b7-11eb-86ea-ad8c790629b4.PNG)

And have configured the following Sequence settings (adjust the timing values to your needs):
![Sequence](https://user-images.githubusercontent.com/19472752/111882742-83e86c80-89b7-11eb-9620-840e668ee6c6.PNG)

And finally the audio settings:
![Audio](https://user-images.githubusercontent.com/19472752/111882744-8b0f7a80-89b7-11eb-85f8-c01e9a3178c5.PNG)

This should result in the following behaviour:
If the mic or media source are active they trigger a scene switch to their respective scene groups.
The scene groups will cycle through switching to the media-source-scene or mic-scene and the wide-angle-scene.
The wide-angle-scene scene will trigger a scene sequence to wide-angle-scene-hold (which can just be a copy of wide-angle-scene) for 10 seconds and as it is not marked as interruptible the audio based scene switching will be ignored during this time.

But unfortunately this does not achieve your randomness requirement.

**Comment by nospam2k** [comment]
Thanks for the effort. I'm really happy with this as it is. It will get me a long way. It may not appear as scripted with the randomness of the cuts between the two mics so it may work great. I'll give it a try.

**Comment by WarmUpTill** [comment]
I will close this for now as I assume the suggested setup suffices.
But just a small hint.
I plan on adding the "Macro" tab soon, which will allow you to specify random duration for scene switches as well:
![RandomWait](https://user-images.githubusercontent.com/19472752/118339029-f721e100-b517-11eb-8fc9-837588f76c96.PNG)

If you want to give this a try you can download the most recent builds for the master branch.
For example this one:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/843417898

**Comment by nospam2k** [comment]
Sorry, I should have gotten back to you. My apologies. I will keep an eye out for the macro!

**Comment by nospam2k** [comment]
Ok, lol... one, year, later...

I've finally had a chance to mess with this:

My senario: 3 camera scenes. 2 are close ups of 2 people with 2 mics and one is a wide angle.

My goal: at Random times, I want to OVERRIDE the 2 closeups that are switching back and forth with the mics and throw in the wide angle scene just for a few seconds to liven things up.

My test: I tried to use both the general and random tabs and set up using the two idle options, IF no actions are performed and After a match don't perform actions for.

My results: This works, sort of, but the problem is when either of the closeup scenes are active and continuously talking, the wide angle shot won't come up because there is no "idle" time as it is continuously triggering.

I'm not sure how to set up a random scene that ignores everything else going on and will show for say 10 seconds and then let the normal mic triggering resume.

**Comment by nospam2k** [comment]
Ok, I figured this out (kinda). What seems to work well is to use macros with timers. I'll try to explain simply for others:

Scenes - Closeup 1, Closeup 2, Wide Angle 1, Wide Angle 2 (just drop Wide Angle 1 scene as source).

Close up 1 macro - if audio above X and not scene itself and not scene Wide Angle 1 - cut to itself
Close up 2 macro - if audio above X and not scene itself and not scene Wide Angle 1 - cut to itself
Wide angle 1 - if timer random (uncheck save time and auto reset) timer reset self, timer pause self, timer reset scene Wide Angle 2, timer continue Wide Angle 2 (no duration)
Wide angle 2 - if timer random (uncheck save time and auto reset) timer reset self, timer pause self, timer reset scene Wide Angle 1, timer continue Wide Angle 1 (no duration)

Use Wait until transition to target on all Switch Scenes.

What this will to is allow for dialog to switch the closeup SO LONG AS Wide Angle 1 IS NOT ACTIVE. During this time Wide Angle 2 timer is going but the scene is quickly interrupted by one of the Close ups so long as there is volume. If not then it will just stay on Wide Angle 2 and then switch to Wide Angle 1 back and forth which are the same thing. During Wide Angle 1 its timer is active so the Close ups cannot interrupt until Wide Angle 1 switches back to Wide Angle 2.

Hopefully this is clear!
