### ISSUE TITLE
Ubuntu 18.04 build instructions

### ISSUE THREAD

**Issue by FiveBoroughs** [WarmUpTill/SceneSwitcher#15]
The ReadMe file can be misleading, so here are clear instruction on how to build on Ubuntu 18.04

```
cd ~
git clone https://github.com/WarmUpTill/SceneSwitcher.git
git clone https://github.com/obsproject/obs-studio.git
cd SceneSwitcher
mkdir build && cd build
sudo apt install cmake build-essential qt5-default libxss-dev
cmake -DLIBOBS_INCLUDE_DIR="~/obs-studio/libobs/" -DLIBOBS_FRONTEND_INCLUDE_DIR="~/obs-studio/UI/obs-frontend-api" -DLIBOBS_FRONTEND_API_LIB="/usr/lib/libobs-frontend-api.so" -DCMAKE_INSTALL_PREFIX=/usr
make -j4
sudo make install
```

**Comment by WarmUpTill** [comment]
Which compiler are you using?
I have not yet observed this build issue myself.

>But obs doesn't load the plugin, bummer.

Is OBS attempting to load the plugin? (should be visible in the OBS log)

>I was trying to compile this because selecting + in Media crashes OBS. This was for the so in the downloaded version. I'll file a separate issue for that.

More information on that would be much appreciated! :)
