### ISSUE TITLE
Feature Request: Add Start and Stop Virtual Camera to Scene Trigger actions.

### ISSUE THREAD

**Issue by DrumDad** [WarmUpTill/SceneSwitcher#160]

**Comment by WarmUpTill** [comment]
Thanks for the suggestion - I will try to add it during the weekend.

**Comment by WarmUpTill** [comment]
Unfortunately we will have to wait for the next OBS release as the current OBS API does not yet support this functionality.
I have prepared the changes here in the meantime https://github.com/WarmUpTill/SceneSwitcher/pull/162.

If you need this functionality now you will have to use a pre-release version of OBS.

**Comment by DrumDad** [comment]
No rush.
