### ISSUE TITLE
Sequence Transition replaces selected Scene Transition 

### ISSUE THREAD

**Issue by DrumDad** [WarmUpTill/SceneSwitcher#161]
When executing a sequenced switch, the transition defined in the sequence will replace the current Scene Transition.  I then have to manually reset my Scene Transition setting to the state I had prior to the Sequence event.

I was hoping that the sequence transition would be treated as an override and not change my current scene transition.

macOS 10.15.6
OBS v26.1.2

Can't tell which version of SS I'm using.  Maybe you could include that information in the General tab in the Status box?

**Comment by WarmUpTill** [comment]
I will look into adding an option to use transition overrides for transition changes during the weekend.
Thanks for the suggestion!

The version info is part of the log file.
Maybe I should add it to the general tab also, but I was a bit hesitant to do so as I am using the commit hash as the version info, which might confuse some people.

**Comment by WarmUpTill** [comment]
I now implemented an option on the transition tab which lets you choose not use change the active transition and instead rely on transition overrides. (see https://github.com/WarmUpTill/SceneSwitcher/pull/164)

![DisableTransitionChange](https://user-images.githubusercontent.com/19472752/114231397-b401aa80-997a-11eb-8618-89f552f58a96.PNG)

**Comment by DrumDad** [comment]
Awesome!  I'll take a look this weekend when I have a chance.

**Comment by WarmUpTill** [comment]
I will merge these change to the master branch and make a new release.
This will close the issue, but feel free to tell me to reopen it if you find any issues with the current implementation.
