### ISSUE TITLE
Exclude Multiple Scenes in Region Options

### ISSUE THREAD

**Issue by pcbowers** [WarmUpTill/SceneSwitcher#166]
I have really enjoyed the new feature that allows you to apply scene switches based on region unless already in a certain scene. However, often times I would like to exclude more than just 1 scene. How hard would it be to allow for a 'select multiple' rather than a 'single select' when excluding scenes from changing when creating new region frames?

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
At the moment I have not planned to add this.

I think a more general approach, which is not just limited to this single switching method, would make more sense.
It was requested rather frequently as of late to allow combining scene switching conditions. 
This suggestion might fall into that category as well if you think about it as: 
switch to scene 123 [if: cursor in region xyz] and [if not: current scene is abc]
(The conditions being in [] brackets)

Unfortunately implementing such functionality would require the plugin to be reworked quite a bit.
So this is not something that I will manage to add in the near future.

**Comment by WarmUpTill** [comment]
I now implemented a first usable version of the functionality described above in the form of the "Macro" tab.
A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/782720419

I would appreciate if you could give this a try.
But note that there might still a few bugs.
If you discover any please let me know.

Here is an example of what you could configure to achieve what you were looking for originally - switching based on a screen region while unless a number of scenes are currently active:

![MacorRegionExample](https://user-images.githubusercontent.com/19472752/115993579-c3683100-a5d3-11eb-89c8-c90670da8bfe.PNG)

I plan on expanding this functionality but any early feedback would be very much appreciated!

**Comment by pcbowers** [comment]
@WarmUpTill I wasn't expecting such a quick response! I've been taking a look at your code to see if there was potentially a way to implement a select all feature without you having to rework it to add this macro, and had no clue you were going to get it up and running so quickly.

I spent the last 30 minutes testing it out. Essentially, All I've done is placed a video source in the corner of my screen. When I move my mouse into that corner, I want it to move to the next one in a clockwise fashion. This way, my mouse is visible at all times and I can easily place the video in any corner that I desire. This allowed me to use the `If` and `And` logic by specifying the scene region and which scene it should be in. I also tried it with 3 `And Not` just to try another logic option (though I will not use it for my streams: I figure fewer logic operators are better). I then made it switch scenes and just to ensure my transitions could happen fully, I added a wait of a second.

![example](https://user-images.githubusercontent.com/41601975/116007221-b56ade00-a5dc-11eb-9ba3-4ffd9ba7420d.gif)

Thus far, I have not experienced any issues at all. Both the `And` setup and the `And Not` setup worked flawlessly, and I had no hiccups whatsoever. Great work! I was also pleased to see that it was already well-integrated with the import and export functionality.

I know this is an early version, but as far as general feedback and possible improvements: A right click on a general macro to be able to duplicate it would be handy if you need something complex repeated. I also think having the default Logic type set to `And` or something similar rather than `!Select condition type!` would look more professional. It is already clear that it's a dropdown, so people can change it if needed.

Other than that, I could see this one tab replacing all of the others! It makes a lot of sense, and is seemingly much more versatile. I'm incredibly impressed by the speed by which you put this together, and super pleased with how well it works too!

**Comment by WarmUpTill** [comment]
>A right click on a general macro to be able to duplicate it would be handy if you need something complex repeated.

I now got around to implementing this copy functionality - Great suggestion, thanks!
![MacroCopy](https://user-images.githubusercontent.com/19472752/116796151-a0111a80-aada-11eb-90a4-2e9e30c56ed8.png)

>I also think having the default Logic type set to And or something similar rather than !Select condition type! would look more professional. 

Yes indeed. ;)
`!Select condition type!` was just a placeholder string.
I now chose to set the default logic type when adding a new condition to be `Ignore entry`.

My reasoning for not choosing an actual logic type was that I want prevent users accidentally triggering an unintended scene change when they add a new condition entry.

In the meantime I also added additional condition types.

If you want try a build with the changes mentioned above you can find it here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/803051833
