### ISSUE TITLE
Sequence switcher prevents the audio scene switcher from working (Linux)

### ISSUE THREAD

**Issue by knipknap** [WarmUpTill/SceneSwitcher#167]
When trying to switch based on audio input (I'm using a Jack audio source), the scene switcher does not perform the switch. Interestingly, it does seem to trigger and set the new scene internally, it just doesn't vsisibly perform the actual switch. Steps to reproduce:

1. Configure some sequence rules
2. Configure only one audio rule, something like "if source is higher than 15% for 1 second, switch to scene **X**"
3. Ensure that the audio switcher has higher priority than the sequence switcher
2. Switch manually to scene **Y**
3. Say something to trigger the audio rule. Note that nothing happens; scene **Y** stays active
4. Switch manually to scene **Z**. Immediately after this manual switch, scene **X** is suddenly activated - even if audio is completely silent at the time.

Btw., is there any way to see the version number in the UI? I downloaded it two days ago, but can't find any reference to the version number locally.

**Comment by WarmUpTill** [comment]
That seems very strange indeed.
Have you configured any additional settings which might have led to this behavior?
Would you mind exporting your current settings and sharing them with me? (Doesn't have to be here if you don't want to do so publicly)

The current version is not shown in the UI.
It is only visible in the OBS log file in the form of a commit hash.

**Comment by knipknap** [comment]
Ah-ha... it seems to be a conflict with the "Sequence" switcher... when deleting the sequence, the audio based transition starts to function.

I am not sure if I am doing something wrong, as I have set "Audio" to the highest priority. If I set Sequence to highest priority, the audio-based transitions don't happen at all, which I guess is to be expected.

I have attached the configuration export and the OBS logfile.

[ss-settings.txt](https://github.com/WarmUpTill/SceneSwitcher/files/6330883/ss-settings.txt)
[obs-log-2021-04-18 11-24-14.txt](https://github.com/WarmUpTill/SceneSwitcher/files/6330884/2021-04-18.11-24-14.txt)

**Comment by WarmUpTill** [comment]
Can you try if everything works as expected if you mark your scene sequences as interruptible?

The issue is most probably that with your current setup the scene switcher "goes to sleep" for the specified duration whenever a new scene sequence is started.
Manually switching scenes will wake the scene switcher back up, resulting in the behavior you described originally.
Marking the scene sequence as interruptible will mean that the other checks are still performed and can interrupt the current scene sequence.

**Comment by knipknap** [comment]
Ahh, yes, that fixes the issue! Great, Thank you!
