### ISSUE TITLE
Feature Request: Allow to specify transition duration on Transition tab

### ISSUE THREAD

**Issue by knipknap** [WarmUpTill/SceneSwitcher#169]
When adding transition rules like 

> Switch from "Frontal camera" to "Frontal camera zoomed" using "Fade"

It would be great if it were possible to specify a transition duration, too, i.e.:

> Switch from "Frontal camera" to "Frontal camera zoomed" using "Move" **with duration "3000ms"**

In combination with the "move-transition" plugin, this would allow for a "smooth camera zoom" effect that is only used when switching between scenes that have the same camera in them.

**Comment by WarmUpTill** [comment]
Good suggestion!
I will add it to the todo list.

**Comment by WarmUpTill** [comment]
I now implemented this functionality with the linked PR.
![TransitionDuration](https://user-images.githubusercontent.com/19472752/115969099-95cfa900-a53b-11eb-97ab-efbf3dd97fd8.PNG)
Can you give this a try and let me know if everything works as expected for your use case?

**Comment by knipknap** [comment]
Oh wow, so fast, and it looks exactly as I hoped! Awesome, Thanks a lot!

Unfortunately I cannot compile it, because my system needs a specific kernel for which there is no corresponding libc-dev in Ubuntu.

```
~/SceneSwitcher$ sudo apt install gcc-multilib
[sudo] password for sam: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.32-0ubuntu3) but 2.33-0ubuntu4 is to be installed
             Depends: libc-dev-bin (= 2.32-0ubuntu3)
 libc6-i386 : Depends: libc6 (= 2.32-0ubuntu3) but 2.33-0ubuntu4 is to be installed
 libc6-x32 : Depends: libc6 (= 2.32-0ubuntu3) but 2.33-0ubuntu4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

And this is only the start of the problem; I know because I tried to compile OBS from source a few days ago, and gave up eventually. So sorry for being unable to test these changes.

**Comment by WarmUpTill** [comment]
Ah sorry, I forgot to mention where the automated builds are available at.
You can find them here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/781066994

I did not expect you to build the plugin yourself.
I hope I did not waste too much of your time!

**Comment by knipknap** [comment]
Ahh, perfect! I tested it and it works nicely!

I did notice that with longer durations, now it would make sense to include a "interruptible" flag, similar to the transitions on the "Sequence" tab, because during the animation any further transition triggers appear to be ineffective.
Now that I think about it, the original trigger for my transition was "Audio", maybe the interruptible flag should be there instead?

But in any case, the feature is already useful as-is, I just had to ensure that no sequence is triggered when the transition is yet ongoing. Thanks again!

**Comment by WarmUpTill** [comment]
Glad to hear that it is working as expected!
I would then close this issue once I merge the PR.

>I did notice that with longer durations, now it would make sense to include a "interruptible" flag, similar to the transitions on the "Sequence" tab, because during the animation any further transition triggers appear to be ineffective.
Now that I think about it, the original trigger for my transition was "Audio", maybe the interruptible flag should be there instead?

Just to clarify:
The issue you are observing is that no automated scene changes can be triggered until the transition of the previous entry is complete?
I would have just expected the current transition to be canceled and a new transition to be started but maybe that behavior was changed on OBS's side.
I will look into it.

**Comment by knipknap** [comment]
> The issue you are observing is that no automated scene changes can be triggered until the transition of the previous entry is complete?

Yes, this is exactly what happens.

**Comment by WarmUpTill** [comment]
Sorry about the late reply.

I have not been able to reproduce the behaviour you described above with my current build of OBS.
Which version are you using?

Would you mind sharing your settings for the plugin? (The settings can be exported on the general tab)
