### ISSUE TITLE
Feature Request: Hit "Next in Playlist"

### ISSUE THREAD

**Issue by nbcartier4292** [WarmUpTill/SceneSwitcher#174]
Awesome plugin! Thank you! I'm using VLC Source and wondering im we can include the ability for a stream to trigger "Next in Playlist" when audio is inactive for a certain period of time. Sometimes VLC hits a bad file at goes to black screen in my playlist. It'd be cool if Advanced Scene Switcher could detect when it's frozen (audio not playing) and trigger the "Next in Playlist" which gets the stream back up and running. Is this possible?

I'd happily donate to support the project if this is doable! Feel free to message me.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I will add it to the todo-list, butI am not sure when I will get around to implementing such functionality.

**Comment by WarmUpTill** [comment]
I recently implemented the macro actions to control media sources with e4b060976bb610714860160b5162a3ed2e7743a4.
This should allow you to achieve what you were looking for:
![VLCNext](https://user-images.githubusercontent.com/19472752/119262635-2dc4bf00-bbdc-11eb-82f1-5cb0152b61b3.PNG)

You can use any build of the master branch after the mentioned commit to test it.
For example this one:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/868154927

Let me know if this works as expected! :)

**Comment by WarmUpTill** [comment]
I have released a version of the plugin officially which contains this feature so I will close the issue for now.
Feel free to let me know if anything should not work as expected.
