### ISSUE TITLE
Installation via Flatpak

### ISSUE THREAD

**Issue by PanderMusubi** [WarmUpTill/SceneSwitcher#176]
Please offer installation via Flatpak so it can be installed when latest OBS is installed via Flatpak.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

To be honest I am not really familiar with the process of offering installations via Flatpak.
Do you know of any existing OBS plugins offering such functionality, which I could use as a reference?

**Comment by PanderMusubi** [comment]
Don't know yet, hence the link to the other plugin. I do know some applications have similar packaging, see:

    ungoogled-chromium                com.github.Eloston.UngoogledChromium                    90.0.4430.93
    Codecs                            com.github.Eloston.UngoogledChromium.Codecs

and

    Audacity                          org.audacityteam.Audacity                               3.0.2
    Codecs                            org.audacityteam.Audacity.Codecs

**Comment by romen** [comment]
I quickly hacked together an initial attempt to package the plugin for Flatpak.

You can see my code here: https://github.com/romen/com.obsproject.Studio.Plugin.AdvancedSceneSwitcher

As written in the README, this should be considered very experimental.
It's basically a fork of https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay.git with an initial set of changes to compile this plugin instead.
I was actually expecting the local build to fail, as I had yet to tackle the issue of the documented dependencies, yet some way or another things seem to be working (in my very limited tests, which cover almost exclusively starting the plugin and using the `Sequence` tab with 2 scenes.

Even the naming of the package might be wrong, as I went for AdvancedSceneSwitcher, while this repo uses SceneSwitcher and other places refer to it in different ways.
Moreover, I have zero experience with Flatpak packaging: I would expect the com.obsproject.Studio.Plugin to be moderated by the OBS project, so it might be a good idea to ask them to reserve the official name for this project before publishing this anywhere.

I am mentioning it here, where I landed looking for instructions on how to install this plugin when using a Flatpak distribution of OBS Studio, hoping that @WarmUpTill will find it useful to jumpstart the support for Flatpak installations, or that someone else from the community, more knowledgeable about Flatpak than I am, will take over and adopt it.

**Comment by GeorgesStavracas** [comment]
There is some documentation on how to distribute OBS Studio plugins as Flatpak extensions [here](https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#distributing-plugins-on-flathub). It's very generic as it's meant to help people start from scratch, and I think you're one step above that already with your repository, but I'm linking it here nonetheless in case it helps.

I'd love to hear your thoughts on how this documentation can be improved - if you have any general questions that it didn't answer, or problems it didn't predict, please let me know (or, even better, please suggest a change!) and I'll update it.

> Even the naming of the package might be wrong, as I went for AdvancedSceneSwitcher, while this repo uses SceneSwitcher and other places refer to it in different ways

Given this repository is called `SceneSwitcher`, I believe it'd be more appropriate to use this as the Flatpak extension suffix.

> I would expect the com.obsproject.Studio.Plugin namespace to be moderated by the OBS project, so it might be a good idea to ask them to reserve the official name for this project before publishing this anywhere.

Yes, `com.obsproject.Studio.Plugin` is the prefix with which OBS Studio plugins, and only OBS Studio plugins, are included in Flathub. You don't have to reserve it beforehand, the only plugin that can be distributed under the `SceneSwitcher` name is yours (it's a policy of Flathub).

> I am mentioning it here, where I landed looking for instructions on how to install this plugin when using a Flatpak distribution of OBS Studio, hoping that @WarmUpTill will find it useful to jumpstart the support for Flatpak installations

Wearing both my "Flathub packager" and "OBS Studio contributor" hats, I offer you all my support with publishing this plugin there. Unfortunately I don't have the resources to go rampant packaging every plugin out there, but if you have any troubles packaging this, I'd absolutely delighted to help! I'm subscribed to this issue now, but I'm also on OBS Studio's Discord channel under the name `feaneron`.

I believe it'd be wonderful to offer this plugin on Flathub since, starting with OBS Studio 27.2, the Flathub package will be an officially supported distribution mechanism on Linux. [You can read more here](https://github.com/obsproject/obs-studio/pull/5569).

**Comment by romen** [comment]
Thanks @GeorgesStavracas , I actually found the documentation you linked and it was useful as a starting point understanding the manifest format and the pieces of the puzzle, before reading a bit more on the `flatpak-builder` documentation.
It was also the reason why I started from the Input Ovelay plugin repository to hack together what I posted in the repository above.

At the moment I am not in a position to really maintain the plugin distribution over Flatpak, so I hope @WarmUpTill or who will want to carry on this work can take your feedback and apply it on top of the initial content of my repo, or from scratch if they prefer.

One things it was not clear to me was understanding which libraries are bundled in the OBS flathub runtime: I checked the manifest of [OBS](https://github.com/flathub/com.obsproject.Studio), and none of the dependencies of `SceneSwitcher` seem to be listed; I guess some are coming from the underlying [`org.kde.Platform` ](https://invent.kde.org/packaging/flatpak-kde-runtime/-/tree/qt5.15lts-21.08) runtime, but that lists so many modules and extensions that it is too daunting to continue the manual inspection of manifests.
So I guess what I would like to know more about, if I was the author of a plugin looking forward to package for Flatpak, is how to check if a given dependency is already available in the Flatpak runtime or not, before I start adding unnecessary modules to my plugin.

**Comment by GeorgesStavracas** [comment]
> One things it was not clear to me was understanding which libraries are bundled in the OBS flathub runtime

OBS Studio uses the KDE 5.15 platform, so all important Qt / KDE libs should be included. The KDE platform itself is based on the FreeDesktop 21.08 platorm, so it also includes more base libs.

It is, indeed, a lot of libraries to manually track. Sadly, there's no nice looking list of dependencies provided by these platforms - which is not ideal, of course. I usually work around this issue by doing it backwards: list the dependencies of *this* plugin, and search for them in these platforms.

I quickly grepped for `find_package` in this repository, and I believe most of the dependencies here are provided by these platforms, except `OpenCV`. There are a few apps that use OpenCV on Flathub, I think you can pretty much just copy one of these manifests (e.g. [this one](https://github.com/flathub/org.nomacs.ImageLounge/blob/master/org.nomacs.ImageLounge.json#L36)).

**Comment by WarmUpTill** [comment]
@romen Thank you very much for setting up the initial repo and testing the build! This will finally push me to tackle this topic :D
@GeorgesStavracas Thank you very much for the guide and references!

I now created an initial repo:
https://github.com/WarmUpTill/com.obsproject.Studio.Plugin.SceneSwitcher

I would appreciate if you could have a quick look if everything seems to make sense the way it is set up.

One thing I noticed is that libprocps seems to no longer be able to parse /proc filesystem for the running processes.
I assume that this is forbidden for security reasons or is there a way around that?

**Comment by GeorgesStavracas** [comment]
> I would appreciate if you could have a quick look if everything seems to make sense the way it is set up.

I had a brief look into your repository, and didn't test yet, but it looks great already! In fact, I think this is good enough to [start the submission process on Flathub](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app). During the submission process you'll create a pull request, and we can discuss the minutia there.

> One thing I noticed is that libprocps seems to no longer be able to parse /proc filesystem for the running processes.
I assume that this is forbidden for security reasons or is there a way around that?

I **think** that's the case, yes; I'd have to double-check, but I'm pretty sure Flatpak restricts access to /proc. What does this plugin use /proc data for? This is a limitation of the sandbox, but OBS Studio is somewhat special and can already open large holes in the sandbox, so I'm sure we can find ways to do what you're doing withing Flatpak constraints.

**Comment by WarmUpTill** [comment]
Thanks for having a look!

I have now opened a PR (after some confusion about this "new-pr" branch handling):
https://github.com/flathub/flathub/pull/2658

>What does this plugin use /proc data for?

There is functionality on the macro and executable tab to check if a process is running and perform actions accordingly.
It is not a big deal if that single function will not work properly I would assume.

**Comment by GeorgesStavracas** [comment]
Thank you, I'll have a look later today.

> There is functionality on the macro and executable tab to check if a process is running and perform actions accordingly.
It is not a big deal if that single function will not work properly I would assume.

Okay, if you're fine with it not working initially, we can open an issue and think about this case more calmly. It will probably require adding a new kind of XDG portal, this might be related: https://github.com/flatpak/xdg-desktop-portal/issues/653

**Comment by GeorgesStavracas** [comment]
This plugin is now published on Flathub, and users can install it using their favorite app store (or the command line). The best outcome, I may say! I think this bug can be closed now.

@WarmUpTill @romen if you need further help, or have any questions in the future, feel absolutely free to reach out to me - either ping me in any bug, OBS Studio's Discord, or the Flatpak room at Matrix.

**Comment by PanderMusubi** [comment]
Super! Please, add the Linux command line install command to the README.
