### ISSUE TITLE
Select transition duration per transition

### ISSUE THREAD

**Issue by christianlupus** [WarmUpTill/SceneSwitcher#177]
I have a feature request regarding the transition of one scene to another using the automatic scene switcher. Currently, you can only define the type of the transition (swipe, fade, cut, ...) between scenes. I am missing the option to select in that tab the duration of the transition.

As an example, it might be favorable to fade within a few 100ms but a certain swipe should be done within 2s. The 250ms (from the fade) will make the swipe much to fast/stressful/uneasy.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

This was was recently requested and implemented with https://github.com/WarmUpTill/SceneSwitcher/issues/169.
So just try any recent build from the master branch and you will be able to set the duration for the the transitions on the transition tab.

For example this one:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/817870106

**Comment by christianlupus** [comment]
A quick check resulted in a correct behavior as intended. I will have to play with it a bit more.

I am closing as the functionality, in general, seems to be there and functional. If I found a bug, I would open a new issue as a more detailed bug report then.
