### ISSUE TITLE
Feature request: Add a "only in" Scene condition for each Region rule.

### ISSUE THREAD

**Issue by juacas** [WarmUpTill/SceneSwitcher#183]
In the Region panel, it would be very handy to change the "unless in" label into a selection field where you can select "unless in/only in".

This way the rules can be tailored to specific scenes. In a setup where you use a lot of scenes a region trigger will be meaningfull on ly for a set of closely-related scenes but it whould be rather meaningless for the rest.

Even better, it would be a powerful feature to allow the user  to select a set of scenes in which the rule will apply... But maybe the user interface gets too complicated.

**Comment by WarmUpTill** [comment]
You are in luck! ;) 
This was already implemented in the form of the "Macro" tab, but has not been released yet officially.
(Something similar was requested in #166)

You can download a recent build from the master branch to give this a try:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/844483455

Let me know if this works for you as expected.

**Comment by juacas** [comment]
Awesome!, perfect! 
It can wipe out the rest of the tabs!!
