### ISSUE TITLE
Feature Request: Add ability to disable screen region entries, but leave them in place

### ISSUE THREAD

**Issue by brumac** [WarmUpTill/SceneSwitcher#189]
Thanks for this awesome tool.
I currently have seven entries in my "Region" tab, but not all regions always contain material.
If I leave the mouse in an empty region the background shows.  
If there was a checkbox for each region I could turn off the ones I don't want at the moment, and then could turn them back on when needed without having to re-configure them.

I had thought of creating several config files and importing them as needed, but it would be a bear to maintain, and may have unwanted side effects.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

With the introduction of the macro tab I plan to slowly fade out other tabs like the screen region tab. (Long term)
So I do not plan on making any changes there unless they are urgent.

However, I will think about integrating such an option to the macro tab.

**Comment by WarmUpTill** [comment]
I recently implemented the option to pause individual macros with 961ea655fd5baad981a3018bce40a862d1a8de96.

![PauseExample](https://user-images.githubusercontent.com/19472752/119263235-7c735880-bbde-11eb-916c-7288ff820c86.PNG)

You can find a test build containing this change here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/868154927

Let me know if everything is working as you would expect.

**Comment by WarmUpTill** [comment]
Upon request on the OBS forum the functionality was also extended to support setting individual hotkeys to pause or unpause each macro.

You can use following build if you want to give it a try:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/890738481

**Comment by brumac** [comment]
magnificent idea I'll give it a whirl

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if you should run into any issues.
