### ISSUE TITLE
Feature Request - "Window Title Contains"

### ISSUE THREAD

**Issue by Dschogo** [WarmUpTill/SceneSwitcher#19]
Hey ,

Like said in the title i request the feature to switch based on window titles (works already).

But my window titles are changing over time (depends on what i select in the window) (endless possibilities so i cant add every option as new title). The First half of the title is constant so i need the option to switch scenes bases on window title wich contains ".....".

**Comment by WarmUpTill** [comment]
Hello,
this is already in place as the use of "regular expressions" for window titles is supported.
For example ".*Tube.*" means "<anything here>Tube<anything here>" and will match a window with the name "Youtube".

**Comment by Dschogo** [comment]
Hey thanks for the quick answer.
Works like a charm :)
