### ISSUE TITLE
X11 Library not found error

### ISSUE THREAD

**Issue by ijaureguialzo** [WarmUpTill/SceneSwitcher#20]
The plugin is not loading in with this error:

```
error: os_dlopen(/Applications/OBS.app/Contents/PlugIns/advanced-scene-switcher.so->/Applications/OBS.app/Contents/PlugIns/advanced-scene-switcher.so): dlopen(/Applications/OBS.app/Contents/PlugIns/advanced-scene-switcher.so, 257): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Applications/OBS.app/Contents/PlugIns/advanced-scene-switcher.so
  Reason: image not found
```

Setup:
- macOS 10.15.5 beta 2. 
- OBS 25.0.8.
- SceneSwitcher 1.5.

**Comment by WarmUpTill** [comment]
Thanks for the heads up - updated the release to included the fixed .so

Can you please check on your end if it is working as expected?
I can't run OBS on Mac myself to test it unfortunately.

**Comment by ijaureguialzo** [comment]
It's working now.

**Comment by WarmUpTill** [comment]
Not sure if I can do anything about the automatic quarantine, but original issue is resolved, so closing for now.
