### ISSUE TITLE
macOS path outside of executable

### ISSUE THREAD

**Issue by ijaureguialzo** [WarmUpTill/SceneSwitcher#21]
With OBS 25+, the installation path should be `~/Library/Application Support/obs-studio/plugins/advanced-scene-switcher/bin/` so it's not lost on OBS upgrades.

**Comment by WarmUpTill** [comment]
Does this work already and just the installation instructions need to be adjusted or does it require changes on my end?
(Can't test it myself unfortunately)

**Comment by ijaureguialzo** [comment]
It's only the install instructions that has to be changed. I checked where other plugins put their files and seems that in recent version the directory structure has changed.

**Comment by WarmUpTill** [comment]
Install instructions were adjusted
