### ISSUE TITLE
Showing actions entries problem

### ISSUE THREAD

**Issue by tatunts** [WarmUpTill/SceneSwitcher#220]
Hello again :)

It seems that there's something off here:

https://user-images.githubusercontent.com/25224882/120086884-57d52000-c0b9-11eb-8cf6-704e9d39b3a5.mp4

When I click to open/show the entry, the other entries shows their properties info without me clicking on their "show more" button.

Thanks.

**Comment by WarmUpTill** [comment]
Nice find!

Submitted a fix with https://github.com/WarmUpTill/SceneSwitcher/pull/221/commits/6939cf06f0b43d010a399230e8f583fd4ee309c6.

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/889689046

**Comment by tatunts** [comment]
Problem is fixed :) Thanks!
