### ISSUE TITLE
Feature request: Save replay

### ISSUE THREAD

**Issue by tatunts** [WarmUpTill/SceneSwitcher#223]
Hello @WarmUpTill !

It would be nice to have as both trigger and action a "Save Replay" function.

Since Exeldro has released the source record plugin that has replay capabilities (enable by filter, per source), it would be nice to be able to "sync" save replays actions. So if I click on the "main replay" save button, It could trigger the save replay at the specific source and filter. More about that on my next feature request :)

Having a "save replay" to the action would be cool as well...

Thanks.

**Comment by WarmUpTill** [comment]
Hello,
are you referring to the replay buffer functionality?
If so the actions to start, stop and save are already in place.
Unfortunately I do not think there is an API to notify the plugin that the replay buffer is being saved.

**Comment by tatunts** [comment]
Ohhh yes, you are right. I did not read it correctly, yes, there's a save replay buffer action...

No problem, too bad there's no way of knowing that a replay buffer has been saved to use it as a trigger.

Thanks!

**Comment by WarmUpTill** [comment]
>too bad there's no way of knowing that a replay buffer has been saved to use it as a trigger

It looks like I was wrong - there seems to be the following event:
OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED

I must have just missed it last time.
I will reopen this issue.

**Comment by WarmUpTill** [comment]
I implemented the functionality with the linked PR:
![ConditionReplay](https://user-images.githubusercontent.com/19472752/122452326-70927080-cfa9-11eb-843c-164c41391e5b.png)

Branch should be up to date in case you want to give it a try.

**Comment by tatunts** [comment]
Amazing! Thanks

**Comment by WarmUpTill** [comment]
The macro action part of the replay buffer was already implemented.
