### ISSUE TITLE
Feature request: send hotkeys

### ISSUE THREAD

**Issue by tatunts** [WarmUpTill/SceneSwitcher#224]
Hello again :)

A great addition to the actions system would be to send hotkeys locally in OBS. There are many functions, some created by third party scripts and plugins, that only works as a keyboard hotkey.

For example: this amazing [Lower Thirds](https://obsproject.com/forum/resources/animated-lower-thirds-with-dockable-control-panel.1057/) project that you can launch specific graphics using shortcuts or the source record filter from Exeldro, that you can save replays from a specific filter added to a source.

Thanks!

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I will look into it.

**Comment by WarmUpTill** [comment]
I implemented a first version of the hotkey macro action with the linked PR.
![Hotkey](https://user-images.githubusercontent.com/19472752/120701117-c3046500-c4b2-11eb-9d27-5b90a06984a4.PNG)

A build will be available here in a few minute:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/903950501

Still have to clean it up, but let me know if it works as expected and what you think.

Note that it is only expected to work on Windows for now.
I still have to implement the `PressKeys()` function for MacOS and Linux.
So nothing will happen on these platforms.

**Comment by tatunts** [comment]
Hello! Amazing stuff, thank you. I was wondering: does this hotkey is passed only to OBS instance or it will interfere with a foreground running game, for example?

**Comment by WarmUpTill** [comment]
Hi,
it is simulating key presses so it will also act upon other applications and not just OBS.
(E.g. you can let a macro type something into notepad)

**Comment by tatunts** [comment]
Got it, thanks.

**Comment by tatunts** [comment]
Hello! Not sure if there's something wrong I'm doing or it is not working for me.

Here's my test macro:

![image](https://user-images.githubusercontent.com/25224882/120723118-7b2c1080-c4a7-11eb-88ad-967aba0c86f3.png)

Here is the hotkey settings (it works when activated manually)

![image](https://user-images.githubusercontent.com/25224882/120723158-9139d100-c4a7-11eb-8a3f-18e15ec9e802.png)

When I show the source, it starts the macro, waits for 3 seconds and then it hides the source again, no key-press is sent...

This is the log when I hide the source:

```
20:06:50.374: [adv-ss] Macro Ajustar Beat Saber - Saindo returned 0
20:06:50.374: [adv-ss] Macro Ajustar Beat Saber - Saindo is paused
20:06:50.374: [adv-ss] condition scene returned 0
20:06:50.374: [adv-ss] condition streaming returned 0
20:06:50.374: [adv-ss] Macro Fim da live returned 0
20:06:50.374: [adv-ss] condition source returned 1
20:06:50.374: [adv-ss] Macro Hotkey returned 1
20:06:50.374: [adv-ss] running macro: Hotkey
20:06:50.374: [adv-ss] sent hotkey
20:06:50.374: [adv-ss] perform action wait with duration of 3.000000
20:06:53.374: [adv-ss] performed action wait
20:06:53.375: [adv-ss] performed action "AdvSceneSwitcher.action.sceneVisibility.type.hide" for source "Testes" on scene "Testes"
20:06:53.375: [adv-ss] detected busy loop - refusing to sleep less than 1ms
20:06:53.375: [adv-ss] try to sleep for 50
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] condition streaming returned 0
20:06:53.425: [adv-ss] condition recording returned 0
20:06:53.425: [adv-ss] Macro Ajustes iniciais returned 0
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] Macro Ajustar Beat Saber - Entrando returned 0
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] Macro Ajustar Beat Saber - Saindo returned 0
20:06:53.425: [adv-ss] Macro Ajustar Beat Saber - Saindo is paused
20:06:53.425: [adv-ss] condition scene returned 0
20:06:53.425: [adv-ss] condition streaming returned 0
20:06:53.425: [adv-ss] Macro Fim da live returned 0
20:06:53.425: [adv-ss] condition source returned 0
20:06:53.425: [adv-ss] Macro Hotkey returned 0
20:06:53.428: [adv-ss] try to sleep for 498
```

Here is a video:

https://user-images.githubusercontent.com/25224882/120723426-17eeae00-c4a8-11eb-8b37-8d755dec05e7.mp4

Thanks!

**Comment by WarmUpTill** [comment]
In the log it shows that the key press was simulated:
```
20:06:50.374: [adv-ss] Macro Hotkey returned 1
20:06:50.374: [adv-ss] running macro: Hotkey
20:06:50.374: [adv-ss] sent hotkey
```

After running the macro once the macro is not being run again as the source condition is no longer true:
`
20:06:53.425: [adv-ss] Macro Hotkey returned 0
`

Can you maybe open a notepad window and check if maybe the wrong letter is being sent?

**Comment by tatunts** [comment]
Hello!

It seems that the hotkey is sent by the macro:

![image](https://user-images.githubusercontent.com/25224882/120858341-06b1aa00-c559-11eb-8e2a-722f62d84e5a.png)

Not sure why it works when I press shirt + Q manually but not with your macro haha

Thanks.

**Comment by WarmUpTill** [comment]
Hm, very strange indeed.
Do other OBS hotkeys also not work?
I tested on my end by setting up a hotkey to switch to a certain scene and did not find any obvious issues.

**Comment by WarmUpTill** [comment]
I had a look in OBS's hotkey handling code and stumbled upon the setting to only react to hotkeys when the OBS window is in focus.

Could this maybe cause the different behaviour on your end?

![hotkeyDisable](https://user-images.githubusercontent.com/19472752/120929832-e74a8680-c6ea-11eb-80a7-867d6266f11a.PNG)

**Comment by tatunts** [comment]
Hey there!

Seems fine here:

![image](https://user-images.githubusercontent.com/25224882/120931251-1ea73c00-c6c7-11eb-821a-939908f8cf9f.png)

Thanks for help :)

I'll do some further testing but it seems something is wrong here, since the hotkey was sent to my notepad.

I'm now trying to understand and find a way to use F13 to F22 with your plugin but it is harder than I thought to use those "hidden" keys... I think autohotkey could help to only map those keys when the AHK script is running but did not managed to make OBS listen to those new bindings...

Still figuring the best way to do that...

I've also find this great tool: https://github.com/upgradeQ/obs-libre-macros

Maybe this could help if I use it together with a motion filter, so I could trigger it by a scene change (instantaneously) or using your source action hide/show (with the regular "pulling" delay).

Thanks!

**Comment by WarmUpTill** [comment]
After further investigation I think it might just be a timing issue leading to OBS missing the key presses.
I released the keys as soon as I pressed them - I will add a fixed delay and start a test build:

https://github.com/WarmUpTill/SceneSwitcher/actions/runs/912165655

Let me know if that works on your end.

(I couldn't replicate the issue while running with a debugger / no optimization, but with the release build I could. Not sure why it works for notepad though)

**Comment by tatunts** [comment]
Perfect! That solved the issue, macro hotkeys now works flawlessly :)

I'll close the issue now. 

Suggestion: if possible, please remove `key_` from the drop down menu, so we could just type the letter we need to set it up :)

Last question: does this test built has all of the latest stable built code? So I can use it from now on (until the next beta test or stable built).

**Comment by WarmUpTill** [comment]
Glad that this resolved the problem :)
Thanks for testing it!

The branch was not up to date.
I rebased the branch and started a new build:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/912251741

I will reopen the issue and close it when I get around to implementing the functionality for the other platforms also.

**Comment by WarmUpTill** [comment]
Just for future reference:
I gave up on implementing the functionality for MacOS for now due to running into many permission issues. 
(Which I can't solve in a timely manner when running MacOS in a VM)
