### ISSUE TITLE
Feature request: reorder/delete trigger/action entries

### ISSUE THREAD

**Issue by tatunts** [WarmUpTill/SceneSwitcher#225]
Hello!

We had talk about this before, I'm just opening an issue for better tracking :)

This feature would be awesome, to be able to reorder and remove entries from the trigger and action sections.

Thanks!

**Comment by WarmUpTill** [comment]
I finally got around to implementing a first version the requested functionality.
https://user-images.githubusercontent.com/19472752/126016689-466aef85-8a60-42f1-96ba-8663788419c7.mp4

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1039026039

Let me know what you think!

**Comment by tatunts** [comment]
Wow! That is amazing! I'll give it a try ASAP. Looks really good, congrats!

**Comment by WarmUpTill** [comment]
I decided to persist the collapsed / expanded state of each action and condition.
This will prevent them from expanding or collapsing when using these new controls.

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1041144275

**Comment by tatunts** [comment]
Hello! I gave it a try and really liked! This feature is must have, really useful, thanks for creating it :)

I was wondering: what do you think about having mouse scroll enabled for all options and settings in the macro editor window? I was looking at a macro, testing this new feature, scrolling up and down and accidentally, changed a bunch of settings using the mouse scroll haha

Luckily, I've backed up my settings, but thinking there's no undo system, maybe disabling mouse scroll on drop-down settings would be wiser, since you always choose something paying attention at it. This is just a thought...

Thank you!

**Comment by WarmUpTill** [comment]
Thanks for giving it a try!
I am glad you like it! :)

>Luckily, I've backed up my settings, but thinking there's no undo system, maybe disabling mouse scroll on drop-down settings would be wiser, since you always choose something paying attention at it. This is just a thought...

I see what you mean, but on the other hand I think it is quite useful to be able to use the scroll wheel to control some of the settings.
I will check if there is some middle-ground option, which still allows using the scroll wheel when e.g. explicit clicking on a combobox / spinbox but ignoring the input when just hovering over the respective widgets.
Thanks for the suggestion!

**Comment by WarmUpTill** [comment]
Turns out this is way easier to implement than I thought.
A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/runs/3097235434

When scrolling through the conditions or actions by default the focus will be the scroll area and the widgets themselves will ignore the scroll wheel input.
When explicitly selecting a widget like a drop down or spin box it will react to scroll wheel inputs as expected.

**Comment by tatunts** [comment]
Hello! Just gave a try, the scrolling feels much better now. There are so many options and drop-down menus that it was really easy to accidentally change some while scrolling up and down the list. Thanks a lot for implementing this. I think this issue/request is done!

**Comment by WarmUpTill** [comment]
Glad to hear that it improved the situation!

>I think this issue/request is done!

I will probably do some more cleanup and a few reworks in the linked PR before merging it.
So I will keep the issue open a bit longer.

Thanks for your support as usual! :)
