### ISSUE TITLE
Feature Request - Read From Webpage (wget, curl)

### ISSUE THREAD

**Issue by borazslo** [WarmUpTill/SceneSwitcher#23]
I would like to use the Read From File functions with a simple http url. The Plugin would wget / curl the url's content (source) and with regepx find the text.

Could it be possible?

(Thanks for the plugin.)

**Comment by macgiver510** [comment]
Such a feature would be great!
Up-Vote for it!

**Comment by WarmUpTill** [comment]
I added this functionality with d3ab9e01c5c288db15c8bf755075552ffcc14d01.
You can find build artifacts here: https://github.com/WarmUpTill/SceneSwitcher/runs/774033340

Let me know if it is working as expected.

**Comment by macgiver510** [comment]
> I added this functionality with [d3ab9e0](https://github.com/WarmUpTill/SceneSwitcher/commit/d3ab9e01c5c288db15c8bf755075552ffcc14d01).
> You can find build artifacts here: https://github.com/WarmUpTill/SceneSwitcher/runs/774033340
> 
> Let me know if it is working as expected.

I do not understand how to use this linked page. I am not a developer. mostly I am using finished Code/programs like an .exe or something like that. 
Is there something completed for windows x64 I could test?

**Comment by WarmUpTill** [comment]
Under artifacts you can download the built dll / so file.

This is the link to the windows 64 bit build:
https://github.com/WarmUpTill/SceneSwitcher/suites/800164718/artifacts/8622276
