### ISSUE TITLE
feature_request(window_title): wildcard support

### ISSUE THREAD

**Issue by Kristinita** [WarmUpTill/SceneSwitcher#26]
### 1. Summary

It would be nice, if `Window Title` feature will support [**wildcard**](https://www.computerhope.com/jargon/w/wildcard.htm).

[**Related feature request for OBS Studio**](https://ideas.obsproject.com/posts/847/support-wildcards-in-window-capture-source).

#### 2.1. Purpose

**If** I switch to Firefox, where any tab opened:

    OBS Studio will switch to scene `Firefox`.

#### 2.2. Firefox titles

1. `WarmUpTill/SceneSwitcher: An automated scene switcher for OBS Studio - Mozilla Firefox`
1. `Advanced Scene Switcher | OBS Forums - Mozilla Firefox`

All Firefox titles have common part ` - Mozilla Firefox`, but text before it differs.

#### 2.3. Advanced Scene Switcher settings

`Tools` → `Advanced Scene Switcher` → `Window Title`:

1. title ` - Mozilla Firefox`
1. scene `Firefox`

![Advanced Scene Switcher wildcard](https://i.imgur.com/UPAZ1SN.png)

#### 3.1. Common cause

This feature required for **almost everyone apps** that I used on my live streams.

#### 3.2. Details

Examples of my programs:

|Software|Expected wildcard|Example title|
|----|----|----|
|[**ConEmu**](https://conemu.github.io/) + [**Far Manager**](https://farmanager.com)|`* - Far x64 Administrator (Admin)`|`{D:\KiraGoddess} - Far x64 Administrator (Admin)`|
|[**ImageGlass**](https://imageglass.org/)|`* - ImageGlass`|`D:\KiraGoddess\2015-10-12 20.44.57 1094309648423467664_2222931037.jpg  ⎮  9/550 file(s)  ⎮  66.22%  ⎮  1080 ⎮x 1350 px  ⎮  99.36 KB  ⎮  2015/10/12 20:44:57 (m)  - ImageGlass`|
|[**Sublime Text**](https://www.sublimetext.com/) `KiraStreaming` [**project**](https://www.sublimetext.com/docs/3/projects.html)|`* (KiraStreaming) - Sublime Text`|`feature_request(window_title): wildcard (KiraStreaming) - Sublime Text`|
|[**SumatraPDF**](https://www.sumatrapdfreader.org/free-pdf-reader.html)|`* - SumatraPDF`|`KiraGoddess.pdf - SumatraPDF`|

Thanks.

**Comment by WarmUpTill** [comment]
The advanced scene switcher supports the use of regular expressions, which should include the functionality described above.

So for example if you would like to match all windows containing the string "- Mozilla Firefox" anywhere in its title you would use ".*- Mozilla Firefox.*".

Is this what you are looking for?

**Comment by Kristinita** [comment]
**Status: Already implemented** :heavy_check_mark:

### 1. Syntax

Regular expressions.

1. `(.*)` — any quantity of title symbols
1. Regex [**special (non-literal)**](https://www.regular-expressions.info/characters.html) symbols must be escaped.

### 2. Example

For `ConEmu + Far Manager` above:

```text
(.*) - Far x64 Administrator \(Admin\)
```

### 3. Testing environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. OBS Studio 25.0.8 (64-bit)
1. Advanced Scene Switcher 1.5

### 4. Note

I found correct syntax accidentally in [**forum post**](https://obsproject.com/forum/threads/advanced-scene-switcher.48264/page-3#post-222029). I can't found it in Advanced Scene Switcher:

1. UI
1. [**GitHub documentation**](https://github.com/WarmUpTill/SceneSwitcher#sceneswitcher)
1. [**OBS forum Overview**](https://github.com/WarmUpTill/SceneSwitcher#sceneswitcher)

It would be nice, if users can find information about regex in Advanced Scene Switcher in places intended for this.

Thanks.
