### ISSUE TITLE
Macro that shows a scene only when a specific window is in foreground/focused

### ISSUE THREAD

**Issue by bigworld12** [WarmUpTill/SceneSwitcher#261]
This is the condition I want to write:
I have "Scene 1" and "Scene 2"
Scene 1 Should be visible when window X is in foreground/focused
Scene 2 Should be visible when window X is NOT in foreground/focused

**Comment by WarmUpTill** [comment]
If I am not misunderstanding your request this is something that should be achievable via the macro tab.
Have you tried this already?

Let me know if you need guidance on what to configure there.

**Comment by WarmUpTill** [comment]
I will close this for now under the assumption that everything is working as expected.
