### ISSUE TITLE
CMake Configure Failure on Windows

### ISSUE THREAD

**Issue by Davidj361** [WarmUpTill/SceneSwitcher#263]
Followed your README instructions on how to build on Windows but getting a failure on Configure.
CMake is complaining about Libcurl which I don't see any mention of in the README.

Below is what CMake outputs:
```
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (Libobs)
  does not match the name of the calling package (LibObs).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/FindLibObs.cmake:84 (find_package_handle_standard_args)
  CMakeLists.txt:33 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Libcurl (missing: CURL_LIB CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/DJ/source/repos/obs-studio/cmake/Modules/FindLibcurl.cmake:80 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)


Configuring incomplete, errors occurred!
See also "C:/Users/DJ/source/repos/SceneSwitcher/build/CMakeFiles/CMakeOutput.log".
```

Here's a screenshot of Cmake with all the variable set:
![Screenshot](https://i.imgur.com/DdYo3yZ.png)

**Comment by WarmUpTill** [comment]
Just to clarify:
You are trying to build the plugin without building OBS itself right?

The readme is indeed most likely outdated regarding out of tree builds.

I will try to look into updating it in the next couple of days.
Thanks for reporting the issue!

**Comment by Davidj361** [comment]
> You are trying to build the plugin without building OBS itself right?

No, I already built OBS and am using the provided DLLs and LIBs from it.

**Comment by WarmUpTill** [comment]
Then I would recommend following these instructions:

```
Compiling in tree (recommended)

Add the "SceneSwitcher" source directory to your obs-studio source directory under obs-studio/UI/frontend-plugins/:

cd obs-studio/UI/frontend-plugins/
git clone https://github.com/WarmUpTill/SceneSwitcher.git

Then modify the obs-studio/UI/frontend-plugins/CMakeLists.txt file and add an entry for the scene switcher: add_subdirectory(SceneSwitcher)
```

Nevertheless I will of course look into the out-of-tree build also as soon as I am able to.

**Comment by WarmUpTill** [comment]
I have updated the build instructions and reworked the CMakeLists.txt to better support out of tree builds.
You can find the changes on the "out-of-tree-build" branch:
https://github.com/WarmUpTill/SceneSwitcher/tree/out-of-tree-build
Let me know if things are a bit more clear now and work as expected.
(I could build a working version of the plugin out of tree on Windows and Linux during my testing)

**Comment by Davidj361** [comment]
For the out of tree build:
CMake seems to remove the `CURL_LIB` and `CURL_INCLUDE_DIR` variables when I hit configure.

I managed to configure and generate to create a project for Visual Studio 2018 Community, but it was having issues building.
As far as I know, the downloadable Qt libs/include that OBS provides does not come with the Concurrent module [https://github.com/obsproject/obs-studio/wiki/install-instructions#windows-build-directions](https://github.com/obsproject/obs-studio/wiki/install-instructions#windows-build-directions). I confirmed this when trying to implement it in my plugin.

Here's my cmake
![image](https://user-images.githubusercontent.com/10195356/126072946-1bd4d80b-e62f-46eb-b96a-db986f2e6d65.png)
```cmake
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
The C compiler identification is MSVC 19.29.30037.0
The CXX compiler identification is MSVC 19.29.30037.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found Libobs: F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug  
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (Libobs)
  does not match the name of the calling package (LibObs).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/FindLibObs.cmake:84 (find_package_handle_standard_args)
  CMakeLists.txt:78 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Found Libcurl: F:/code/Visual Studio/Visual Studio Community 2019/obs-deps/win64/bin  
Configuring done
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "advanced-scene-switcher" requests linking to directory "F:/code/Visual Studio/Visual Studio Community 2019/obs-studio/build/libobs/Debug".  Targets may link only to libraries.  CMake is dropping the item.
Generating done
```

And Visual Studio build:
```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: advanced-scene-switcher, Configuration: Debug x64 ------
2>Automatic MOC and UIC for target advanced-scene-switcher
2>Generating ui_advanced-scene-switcher.h
2>Building Custom Rule F:/code/Visual Studio/Visual Studio Community 2019/SceneSwitcher/CMakeLists.txt
2>mocs_compilation_Debug.cpp
2>F:\code\Visual Studio\Visual Studio Community 2019\SceneSwitcher\src\headers\switch-network.hpp(16,10): fatal error C1083: Cannot open include file: 'websocketpp/config/asio_no_tls_client.hpp': No such file or directory
2>advanced-scene-switcher.cpp
2>F:\code\Visual Studio\Visual Studio Community 2019\SceneSwitcher\src\headers\switch-network.hpp(16,10): fatal error C1083: Cannot open include file: 'websocketpp/config/asio_no_tls_client.hpp': No such file or directory
2>switcher-data-structs.cpp
2>F:\code\Visual Studio\Visual Studio Community 2019\SceneSwitcher\src\headers\switch-network.hpp(16,10): fatal error C1083: Cannot open include file: 'websocketpp/config/asio_no_tls_client.hpp': No such file or directory
...
2>switch-network.cpp
2>F:\code\Visual Studio\Visual Studio Community 2019\SceneSwitcher\src\switch-network.cpp(6,10): fatal error C1083: Cannot open include file: 'QtConcurrent/QtConcurrent': No such file or directory
2>hotkey.cpp
...
```

**Comment by WarmUpTill** [comment]
>I was trying to use your code to see how hotkeys and various things worked, but I no longer need it. So your call if you want to continue with this endeavour.

Sure! Fixing and improving the build instructions will definitively be worth it! :)

>CMake seems to remove the CURL_LIB and CURL_INCLUDE_DIR variables when I hit configure.

I think they might just be hidden.
Can you check if you see the when activating the "Advanced" checkbox in the CMake GUI?

>I managed to configure and generate to create a project for Visual Studio 2018 Community, but it was having issues building.

The build issue you are encountering seems to be due missing sub modules. (asio and websocketpp)
I will have to adjust the build instructions to include the `--recursive` flag when cloning the repo.

`git clone --recursive https://github.com/WarmUpTill/SceneSwitcher.git`

Thanks for pointing that out!

**Comment by Davidj361** [comment]
> I think they might just be hidden.
> Can you check if you see them when activating the "Advanced" checkbox in the CMake GUI?

Yeah, it was hidden. The advanced tickbox showed it again.

> git clone --recursive https://github.com/WarmUpTill/SceneSwitcher.git

Seemed to fix `'websocketpp/config/asio_no_tls_client.hpp': No such file or directory
2>advanced-scene-switcher.cpp`
Though Concurrent still doesn't exist because OBS's Qt Windows download doesn't have it. I am told you would have to download Qt from elsewhere to get the Concurrent Qt Module.

```
...
2>switch-network.cpp
2>F:\code\Visual Studio\Visual Studio Community 2019\SceneSwitcher\src\switch-network.cpp(6,10): fatal error C1083: Cannot open include file: 'QtConcurrent/QtConcurrent': No such file or directory
...
```

**Comment by WarmUpTill** [comment]
Ah now I get it!
Apparently the OBS build instructions where updated and now include a link to subset of the QT headers and binaries which do not include the concurrent module.
I was not aware of that and confused as to why your QT installation was missing some modules like QtConcurrent.

I will update the build instructions to specify that a full installation of QT is expected.
(https://www.qt.io/download -> Downloads for open source users)
Thanks for the clarification!
