### ISSUE TITLE
Media Source Crash on Exit

### ISSUE THREAD

**Issue by realcoolfriend** [WarmUpTill/SceneSwitcher#27]
OBS crashes on exit whenever I set a scene to change at the end of playback of a media source.

I was able to work around the issue by using the "Scene Sequence" tab to trigger the transition using the source video file's duration instead, but thought I'd drop a comment here to give you a heads up.

Here's a link to the crash report, in case it turns out the problem is specific to my setup:
https://obsproject.com/logs/_h29kG1Y0k_g2WXg

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

Does this only happen with the most recent version I released yesterday or also with the previous one where the media switching was introduced?

**Comment by realcoolfriend** [comment]
Thanks for looking into it!

I used to use exceldro's lua script (found it on the obs forums [here](https://obsproject.com/forum/threads/trigger-after-media-source-playback-ends.118986/)), and had the same problem with that, too. With this plugin, the crashes happened before and after the most recent update.

I was using it on three different video sources. I think two of them were originally in .avi format, and one was a webm from the get-go. I ended up converting the .avi files to webm, too. I tested with each of the videos in isolation, but the issue was still there as long as any one of them was in use.

I want to add that the plugin otherwise performed as expected the entire time, though. The only issue was with OBS crashing after closing the program, so if any users are concerned about the issue, it's definitely still usable (at least for me)!

**Comment by WarmUpTill** [comment]
It was reported to me that the issue is apparently resolved with 9f03264
Can you maybe also give this a try?

Build should be finished in a few minutes
https://github.com/WarmUpTill/SceneSwitcher/runs/742976119

But please not that invalid media switches (containing sources, scenes or transitions that do not exist) will be automatically removed with 5082f59

**Comment by realcoolfriend** [comment]
Checking back in-- I don't have the means to compile the changes you linked to, but I did see that there was a new release since you mentioned them.

I changed my switches from timebase back to "end of media playback" and it looks like the crash is indeed fixed in the latest version.

Thanks so much for your support!
