### ISSUE TITLE
Audio switcher does not override random with multiple items 

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#273]
It appears that using the random tab being enabled in the general tab. If I have a tab set up with multiple items in audio and multiple items in random, the random tab will take over until the time expires in the random item.

Example I have a random scene that shows for 6 seconds, but during that 6 seconds I get an audio trigger to change the scene, it won't change until the 6 seconds are up. It seems to be the case (although I'm not positive) that this happens when there are multiple items in the random tab.

I hope that is clear. I'll be glad to try whatever you wish to resolve this.

**Comment by WarmUpTill** [comment]
I added the option to allow interrupting the wait for random scene switches early with the linked PR.
![RandomWait](https://user-images.githubusercontent.com/19472752/128596150-9af224cd-7f7b-4fdd-8f2d-756e2f760d87.PNG)

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1107584473

Let me know if everything is working as expected.

And sorry about the late reply!

**Comment by nospam2k** [comment]
Thanks! I will give this a try and report back as soon as I can.

**Comment by WarmUpTill** [comment]
I will close this for now as this is probably no longer relevant.

**Comment by nospam2k** [comment]
My apologies. Our use case changed and we haven't messed with random scene switch but it isn't off the table forever so I will come back and report if there is any issue.
