### ISSUE TITLE
What is the %APPDATA%/ Folder used for? / Is there an automatic saving process planned?

### ISSUE THREAD

**Issue by macgiver510** [WarmUpTill/SceneSwitcher#28]
I have seen a Folder in
C:\...\AppData\Roaming\obs-studio\plugin_config\advanced-scene-switcher
but there is nothing stored in.
(OBS 15.0.8 x64 Windows)

What is it used for?

I am asking, because after a restart of OBS my Config about "Scene Sequence" was gone.
I needed to do all the config again, and then I saved the "round Trips to a file".

I was assuming, that this folder was may ment, storing the last known/working config there?

I didn't get the idea how the Advanced Scene Switcher was planned to store the config at all.
Is there a Tutorial or something like this available?

Thanks

**Comment by WarmUpTill** [comment]
This folder will contain hoteys if they are configured.

The rest of the config is stored in your scene collection file C:\Users\<user>\AppData\Roaming\obs-studio\basic\scenes\<name>.json.

>I am asking, because after a restart of OBS my Config about "Scene Sequence" was gone.

This will happen if you delete the underlying scenes / transitions used in the advanced scene switcher.

>I didn't get the idea how the Advanced Scene Switcher was planned to store the config at all.
Is there a Tutorial or something like this available?

What kind of tutorial are you asking for?

>(OBS 15.0.8 x64 Windows)

I assume you are using OBS **2**5.0.8 but in case you really use such an old version I would recommend updating OBS

**Comment by macgiver510** [comment]
Yes, true! I am using 25 not 15 :-)

I definitly did not delete any involved scene. Is it possible, that this happens if I switch the language in OBS Settings?
The reason why I am asking is. I currently play around with another plugin (replay-source) and this one may has trouble with german language. Not sure so far. 
So I switched to EN, and then back to DE, and then I noticed that the sequences were gone.

About the tutorial topic....
I tried to read a TXT File and set a regex as trigger.
This was working somehow, but not as expected.
I had trouble with the regex.

The goal is...
TXT File contains "table 1" and Scene 1 should be triggered
TXT File contains "table 1 player1 vs player2" and also Scene 1 should be triggered
TXT File is empty, Scene 2 should be triggered, 
TXT File contains 
"table 1 player1 vs player2
table 2 player3 vs player4"
>> Scene 1 should be triggered.
TXT File contains something else, except "table 1" Scene 2 shoudl be triggered.

means... whenever the TXT File contains "table 1" + "additional text", the scene 1 should be triggered. else, scene 2 should be triggered.

I used regex101.com without a success to get the right regex for this.

Thanks!

**Comment by WarmUpTill** [comment]
>I definitly did not delete any involved scene. Is it possible, that this happens if I switch the language in OBS Settings?

That is very much possible as the scene switcher stores the names of sources and switching language will probably rename all transitions.

> About the tutorial topic....

"table 1" + "additional text" would translate to:
`^table 1.*`
"else" - meaning file content does not start with "table 1" - would translate to:
`^(?!table 1).*`

But a regex tutorial is not really a scene switcher related issue, so I will close this for now.
