### ISSUE TITLE
Adding, removing, and reordering macro segments causes macro edit section to scroll to top

### ISSUE THREAD

**Issue by WarmUpTill** [WarmUpTill/SceneSwitcher#287]
Reported by @tatunts:

I'm just not sure how confusing it would be for new users, since it creates an exact copy (as intended) and it does not scrolls down, it might ofuscante the result of the action, not giving the visual feedback if the add action was done, making the user click on it again and again, until there are many copies... 

Here's an example:

https://user-images.githubusercontent.com/25224882/130521166-44a337cc-ae36-4a1b-968c-ccd4a4da05e4.mp4

Not sure whats happening, it seems that it scrolls back up when an action is added.

Just a tough, but the requested feature works perfectly, thank you very much!

_Originally posted by @tatunts in https://github.com/WarmUpTill/SceneSwitcher/issues/283#issuecomment-904143387_

The issue lies here:
https://github.com/WarmUpTill/SceneSwitcher/blob/ab5bdb32f59e9693bcb5df01e3403368e94ea644/src/macro-action-edit.cpp#L160
https://github.com/WarmUpTill/SceneSwitcher/blob/ab5bdb32f59e9693bcb5df01e3403368e94ea644/src/macro-condition-edit.cpp#L284
Instead of only inserting, removing or reordering widgets the whole edit window is reloaded.
The reason it was done this way is that it needs to be taken care, that when the conditions or actions of a macro are reordered in any way ...

https://github.com/WarmUpTill/SceneSwitcher/blob/ab5bdb32f59e9693bcb5df01e3403368e94ea644/src/headers/macro.hpp#L107-L108
... that widgets the user interacts with will still reference to the same - now incorrect - memory location.
Recreating every widget from scratch after any reordering will of course not run into this issue, but results in the current scroll position to be lost.

**Comment by nacalai** [comment]
Yea this drives me nuts and I keep deleting and editing the wrong macros because of this.
