### ISSUE TITLE
Macro action request: Put in preview

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#288]
I would love to have a "put in preview" action for the macros. Unless I am missing something, this is not a feature. It would make our production a whole lot easier. Cheers.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I have implemented the requested functionality with the linked PR:
![SwitchPreview](https://user-images.githubusercontent.com/19472752/131721972-ab8f5b2b-b9bf-4585-a03b-ce186e1d556d.PNG)
You can find a build here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1191287612

Let me know if everything works as expected! :)

**Comment by nacalai** [comment]
That was quick. Thank you very much! This plugin is basically responsible
for being able to run the financial news in Norway, so very happy with
these quick builds.
