### ISSUE TITLE
Feature Request: Enable external tempo synchronisation

### ISSUE THREAD

**Issue by laurentNoudohounsi** [WarmUpTill/SceneSwitcher#29]
First thanks for this awesome plugin.

I'm working with musical application and I think it would be a cool idea enable scene switching synch on tempo.
I could implement Ableton Link sdk that enablee to get tempo from musical application and I can convert it in seconds.

My only question is how to update the scene switching timing from an external part of the code, is the only way to update it is to:
- stop advanced scene switcher
- update/add a new scene round trip file
- start advanced scene switcher

I could help on it with pleasure.

**Comment by WarmUpTill** [comment]
It does sound like a cool idea.
But how would you imagine that to work exactly?

Does the tool you mentioned pre-analyse an audio file and somehow generate a scene sequence out of it?
Or does this happen "live" as audio is played?

The Advances Scene Switcher itself does not have an API to influence its behaviour.
It only loads and saves its configuration when interacting with its UI.
So the Advanced Scene Switcher would probably have to link against your code.

Does it make sense to reuse scene sequences for this case or should a completely new switch "type" be introduced?

**Comment by laurentNoudohounsi** [comment]
Thanks for your quick reply and your interest in this feature.

This tool, Ableton Link, is a good candidat for a first try for several reason:
- A lot of musician use Ableton Live (AL) as main audio software for live sessions and stream it. AL has the biggest market share as live audio software.
- It’s really easy to setup thanks to their API and works really well regarding the temp broadcasting between AL and the software that have implemented Link api.

Basically, it’s work like this:
- AL is launched and "link" is enabled.
- every software that has the Link API will automatically receive any tempo change if they are on the same network or the same computer.

We can see this feature something as an external software that could change the delay between scenes in order to change them in tempo.

(Description: https://www.ableton.com/en/link/, api documentation: https://ableton.github.io/link/ and the header with the full Link public interface https://github.com/Ableton/link/blob/master/include/ableton/Link.hpp)

You’re idea to create a new type, let’s call it "Link" is good.
In this mode, the custom time will be deactivated and will be replace with the tempo in sec.

The steps to do this would be:
- Add the Ableton link api to Advanced Scene Switcher so it could receive the broadcasted tempo from AL.
- Add a new type called "Link"
- Update the scene sequence delay every time a new tempo is receive if "Link" type is selected

I don’t think it will be difficult to do it, but i’m new in your codebase. Btw from what I see it a great quality code so I’m quite confident with this kind of change.

**Comment by WarmUpTill** [comment]
Sounds good!
Feel free to contact me here or on the OBS forums if you need any support or anything is unclear.

**Comment by laurentNoudohounsi** [comment]
Thanks @WarmUpTill I really appreciate.

I've one issue when I try to compile the project:
![compilation error](https://user-images.githubusercontent.com/11269572/85523112-d6eaea00-b606-11ea-9278-6a288652aafe.png)

Did I make something wrong or is it something with my configuration? I'm on macOS 10.15.5 and Xcode 11.5

**Comment by WarmUpTill** [comment]
This is a QT function used for translations.
This stems from way back when the scene switcher was still supporting multiple languages. 
(At least theoretically - it was never fully translated and just relied on the translations already completed for the built in scene switcher of OBS)

Feel free to remove the tr() calls in the mentioned files, as they do not serve a purpose anymore.

**Comment by laurentNoudohounsi** [comment]
Thanks you so much for you quick reply @WarmUpTill . I think I found a solution for this issue

I added the line:
`set(CMAKE_AUTOMOC ON)`
into the CMakeList.txt

I'm not used to work with Qt but I installed Qt using `Brew install Qt5`. With the help of this [thread](https://stackoverflow.com/a/37457751/2448287) I think that Qt Application done some stuff in the background with QMake so I needed to run the MOC with `set(CMAKE_AUTOMOC ON)`

It compiles now :)

I will surely come back here for more question regarding the code and where to place mine in the right place :)

**Comment by WarmUpTill** [comment]
I am going to close this for now, feel free to reopen if there are any news.

**Comment by laurentNoudohounsi** [comment]
@WarmUpTill Ok no problems. 
I've been overwhelmed for external reasons. Since I'm new with QT I didn't find time to really explorer it properly. Will come back to this asap.
