### ISSUE TITLE
Intent to package in Debian - Issues and doubts

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#293]
Dear developers,

I am a Debian Developer and I am trying packaging SceneSwitcher to put officially it in Debian. I got the following error:

```
CMake Error at CMakeLists.txt:101 (find_package):
  By not providing "Findcurl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "curl", but
  CMake did not find one.

  Could not find a package configuration file provided by "curl" with any of
  the following names:

    curlConfig.cmake
    curl-config.cmake

  Add the installation prefix of "curl" to CMAKE_PREFIX_PATH or set
  "curl_DIR" to a directory containing one of the above files.  If "curl"
  provides a separate development package or SDK, be sure it has been
  installed.
```
I tried -DCMAKE_PREFIX_PATH without results. I have curl and libcurl (libcurl4-openssl-dev) installed. I well know autotools but I am not familiar with CMake. IMHO, maybe there is a problem with the rule used in CMake to search libcurl. Debian doesn't has curlConfig.cmake or curl-config.cmake. What is the right way to build this plugin?

Regards,

Eriberto

**Comment by WarmUpTill** [comment]
Hello Eriberto,

Thanks for the interest in the plugin and I am sorry to hear that you are running into issues!

To be honest I am not very familiar with Debian, so I am not sure if I am missing something obvious here, which could cause the issues you are facing.

Are you building the plugin together with obs-studio or outside of the obs-studio source tree?
Can you maybe share the exact cmake command you are trying to use?

I quickly set up a VM running "Debian GNU/Linux 11 \n \l" and was able to build obs-studio and the plugin using the following packages:

```
sudo apt-get install \
        build-essential \
        cmake \
        git \
        libmbedtls-dev \
        libasound2-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavfilter-dev \
        libavformat-dev \
        libavutil-dev \
        libcurl4-openssl-dev \
        libfontconfig-dev \
        libfreetype6-dev \
        libglvnd-dev \
        libjack-jackd2-dev \
        libjansson-dev \
        libluajit-5.1-dev \
        libpulse-dev \
        libqt5x11extras5-dev \
        libspeexdsp-dev \
        libswresample-dev \
        libswscale-dev \
        libudev-dev \
        libv4l-dev \
        libvlc-dev \
        libwayland-dev \
        libx11-dev \
        libx264-dev \
        libxcb-shm0-dev \
        libxcb-xinerama0-dev \
        libxcomposite-dev \
        libxinerama-dev \
        pkg-config \
        python3-dev \
        qtbase5-dev \
        qtbase5-private-dev \
        libqt5svg5-dev \
        swig \
        libxcb-randr0-dev \
        libxcb-xfixes0-dev \
        libx11-xcb-dev \
        libxcb1-dev \
        libxss-dev \
        qtwayland5 \
        libgles2-mesa \
        libgles2-mesa-dev \
        libxtst-dev
```

I will take this opportunity to look into improving the build instructions as it is not clearly stated which dependencies this plugin has.

Best regards,
WarmUpTill

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

Thanks for your quick reply.

> Are you building the plugin together with obs-studio or outside of the obs-studio source tree?

To put it in Debian, I need to build outside of the obs-studio, using package libobs-dev provided from Debian. You can see the content of this package here[1].

[1] https://packages.debian.org/sid/amd64/libobs-dev/filelist

> Can you maybe share the exact cmake command you are trying to use?

The `debuild` command in Debian will start the build and it is using the following command:

`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu ..`


> 
> I quickly set up a VM running "Debian GNU/Linux 11 \n \l" and was able to [build obs-studio ](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#debian-based-build-directions)and the plugin using the following packages:

The problem is I need build outside of obs.

Thanks for your help.

**Comment by WarmUpTill** [comment]
Hello @eribertomota,

>The problem is I need build outside of obs.

I see - I noticed that OBS itself seems to provide "libcurl" as a cmake target, which is why the curl issue you are facing does not occur when building inside of the obs source tree.

I have adjusted the CMakeLists.txt with the linked PR and was able able to resolve the curl issue.
I used almost the same cmake call as yours above but added a `-DBUILD_OUT_OF_TREE=1`.

But I struggled to get the libobs-dev package to work nicely with FindLibObs.cmake and ObsPluginHelpers.cmake.
Is this something you managed to work around on your end? If so how?
If not then this is the next area of the CMakeLists.txt that needs to be adjusted on my end.

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

Thanks for your help.

In Debian (and derivatives), the right path for obs.h is /usr/include/obs/.

In my machine, I added /usr/include/obs to PATH. Now I have the following message:

```
CMake Error at external/FindLibObs.cmake:98 (include):
  include could not find load file:

    /usr/include/obs/../cmake/external/ObsPluginHelpers.cmake
Call Stack (most recent call first):
  CMakeLists.txt:77 (include)
```

I am not able to solve this issue.

An extra information. Today, when packaging other plugin, I found a mistake in libobs-dev. The /usr/include/obs/obs-frontend-api.h has two includes pointing to wrong place:

```
--- obs-frontend-api.h.orig     2021-09-06 23:17:30.132174882 -0300
+++ obs-frontend-api.h  2021-09-06 23:17:04.324371729 -0300
@@ -1,7 +1,7 @@
 #pragma once

-#include <obs.h>
-#include <util/darray.h>
+#include <obs/obs.h>
+#include <obs/util/darray.h>

 #ifdef __cplusplus
 extern "C" {
```

**Comment by WarmUpTill** [comment]
Hi @eribertomota,

I pushed some more changes to the linked PR to resolve the CMake issues.
I also noticed that the libobs-dev is still using OBS 26 which does not yet provide the virtual camera related functions.
For this I added some version compatability checks.

I was able to configure cmake using the following command:
`cmake -DBUILD_OUT_OF_TREE=1 -DLIBOBS_FRONTEND_API_LIB=/usr/lib/x86_64-linux-gnu/libobs-frontend-api.so -DLIBOBS_FRONTEND_INCLUDE_DIR=/usr/include/obs -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu ..`

Note that in the command above the frontend library and include has to be specified manually as these are not set by libobs-dev.

>Today, when packaging other plugin, I found a mistake in libobs-dev. The /usr/include/obs/obs-frontend-api.h has two includes pointing to wrong place:

Is this something I need to adjust for on my end or will the libobs-dev package be changed?

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

The libobs-dev package will be fixed soon. 

I am packaging in Debian Sid (unstable) and OBS 27 (in Sid, libobs-dev). You can use a jail to have a similar environment. There are instructions here: https://github.com/sshock/AFFLIBv3/issues/47#issuecomment-903770636

I have the following packages installed: cmake, libcurl4-openssl-dev, libobs-dev, libxtst-dev, qtbase5-dev, x11proto-scrnsaver-dev. When using the same command sent from you, I got:

```
CMake Warning at CMakeLists.txt:68 (find_package):
  By not providing "FindLibObs-frontend-api.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "LibObs-frontend-api", but CMake did not find one.

  Could not find a package configuration file provided by
  "LibObs-frontend-api" with any of the following names:

    LibObs-frontend-apiConfig.cmake
    libobs-frontend-api-config.cmake

  Add the installation prefix of "LibObs-frontend-api" to CMAKE_PREFIX_PATH
  or set "LibObs-frontend-api_DIR" to a directory containing one of the above
  files.  If "LibObs-frontend-api" provides a separate development package or
  SDK, be sure it has been installed.


-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.74.0")  
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find X11 (missing: Xss)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindX11.cmake:414 (find_package_handle_standard_args)
  CMakeLists.txt:123 (find_package)

```

**Comment by eribertomota** [comment]
I will try to make a CI test for GitHub to simulate a build for Debian. I think it will help you to test each commit. Please, wait for a PR up to tomorrow.

**Comment by WarmUpTill** [comment]
That is a good idea - thank you very much!

**Comment by WarmUpTill** [comment]
I will merge the linked PR to master so your CI test can work.
