### ISSUE TITLE
Switch camera / scene based on where I am looking

### ISSUE THREAD

**Issue by MrHinsh** [WarmUpTill/SceneSwitcher#296]
I teach a bunch of training classes and I have 4 monitors that have different content while I am teaching. It's not a good look to be looking away from the camera so I would like to add multiple cameras (as many as I want) to my computer and have OBS switch based on where I am looking. 

Have you thought of adding this functionality to your tool?

https://medium.com/@mdfarragher/find-all-faces-that-are-looking-directly-at-the-camera-with-c-59e8469696c1

**Comment by WarmUpTill** [comment]
I have thought about adding "simple" face detection as I plan on using the opencv libraries anyways - I haven't looked into face rotation at all yet.
But maybe that would suffice already.

I actually already have a branch I am developing this stuff on but face detection is not ready yet.
I will update you once I have something that is usable.

**Comment by WarmUpTill** [comment]
I now implemented a first working version of you requested functionality to the video macro condition.

Using the test images from the linked article I get the following matches:

![example](https://user-images.githubusercontent.com/19472752/132996536-55ca2a60-0006-4ba3-88f9-ea26c0e1b93b.PNG)

As you can see it is does not yet quite achieve exactly what you are looking for as also some rotated faces are detected.

This might be resolved by using a differently trained model for the face detection.
Currently the `haarcascade_frontalface_alt.xml` model is used.

I have added a few more, which came bundled with OpenCV, so maybe others might yield better results.
If you are on Windows you can try renaming the other *xml files to "haarcascade_frontalface_alt.xml" under `C:\Program Files (x86)\obs-studio\data\obs-plugins\advanced-scene-switcher\res`.

You can find a test build here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1226947089
I would appreciate if you could give this a try and report back if you run into issues.

**Comment by WarmUpTill** [comment]
Small update:
I added the option to select the path to the model data to be used via the UI:

![ModelData](https://user-images.githubusercontent.com/19472752/133146944-b25ab832-931b-4769-91ec-df45e30b4c08.PNG)

Looks like `haarcascade_frontalface_alt_tree.xml` does exactly what you are looking for.

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1230989886

**Comment by MrHinsh** [comment]
I was just testing with `haarcascade_frontalface_alt_tree.xml` and it never detects a face. Using `haarcascade_frontalface_alt.xml` it always detects based on things in the background.

1. Is there a way to control sensitivity?
2. Is there a way to reduce the polling? As soon as I enable it my machine starts to get choppy. OBS hits 47% processor usage with the system maxing out. 

![image](https://user-images.githubusercontent.com/5205575/134694618-d7b411c6-7df4-447f-ae87-d135e570d685.png)

**Comment by WarmUpTill** [comment]
Unfortunately there is no way to control the sensitivity of the face detection.
It entirely depends on the data it was trained with.

It would probably work best if you train your own model but that seems to be a rather big task:
https://www.youtube.com/watch?v=XrCAvs9AePM

The interval at which the checks are performed at depends on the interval configured on the general tab. I will look into maybe adding an option to limit just the object detection checks as they are probably the most resource intensive check of the plugin.

Just an idea:
Maybe you can try adding a copy of your camera source (doesn't have to be shown) which is cropped to avoid matching the background.

**Comment by WarmUpTill** [comment]
Actually my previous statement turns out to be wrong.
There are parameters to play around with to affect the models behaviour.
In particular something which might be useful for you is the "minSize" parameter to avoid the false positive detection in the background.

I will check how easy it will be to make these parameters configurable via the plugin UI.

**Comment by WarmUpTill** [comment]
I got around to implementing the additional controls for the object detection parameters:

![MoreControls](https://user-images.githubusercontent.com/19472752/134782834-2e5b5b40-396a-4c48-b731-1195cd493f72.PNG)

A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1273527230

I will update you once I found a decent solution for the "polling" rate.

**Comment by WarmUpTill** [comment]
I now also included the option to perform the object detection steps only every x-th interval.

![Throttle](https://user-images.githubusercontent.com/19472752/134817327-e4741ba4-8bff-47bc-b0c6-24fc459a7a2d.PNG)

A build allowing you to configure this option will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1275628512

Let me know if this improves the situation on your end!

**Comment by MrHinsh** [comment]
Unbelievably awesome!

**Comment by WarmUpTill** [comment]
Just to clarify:
Face detection is now working on your end and the CPU usage is in an acceptable range, correct?

If so, I would merge the changes for the next release.

**Comment by MrHinsh** [comment]
Face tracking is working and I am happy with the CPU usage! Fantastic @WarmUpTill !!!!

**Comment by MrHinsh** [comment]
I have two Elgato Facecams, one at either end of my 49" monitor... I can enable and disable the secondary camera based on where I am looking. This is fantastic work! The CPU usage is also controllable and works well.

My only struggle is getting it to detect my face when I am waring my glasses :) But that's a training problem...
