### ISSUE TITLE
SceneSwitch officially in Debian - issue opened for flux control

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#299]
Hi @WarmUpTill,

After a long work over #297, I think that is time to package your nice plugin and send it to Debian. I opened this "issue" to send information and help you to control and understand the process.

Initially, I will package the plugin. To package is a process to generate the final executable, libraries, manpages, etc, and put it in a .deb file. A .deb is a file compacted by "ar" command. In other words, we provide the executable to the final users. To make it, we use the "debhelper" suite in Debian. When done, the  package will be sent to Debian and will be caught by "New Queue" because it is arriving for the first time in Debian. This package will wait to be inspected by "FTP Masters[2]" to enter in Debian. This wait is from 1 day up to 3 months (packages waiting more than 3 months have serious problems and are waiting for fixes). Note that FTP Masters are volunteers and they work in free time; they don't check the packages using the queue order. Thus, the check is in a random order and a package sent today can be approved today. The next uploads, even if for a new version of the mainstream (upstream for Debian) will occur immediately (no longer need to across New Queue).  

[1] https://ftp-master.debian.org/new.html
[2] https://ftp-master.debian.org/#ftpteam

After approved, the package will enter in Debian Unstable (Sid). Between 2 and 5 days in Sid, a copy of this package will be sent to Debian Testing (the future Stable). If we have a security hole or grave bug in the package, it will be removed from Testing, staying in Sid, waiting for a fix. Every 2 years, all packages in Testing will be copied to the Stable (new Debian release). Ubuntu will catch the package from Sid in some hours. Other 130 distributions derivative of Debian will catch from Sid, or from Testing, or from Stable (Linux Mint Debian Edition is an example of this).

Unstable, Testing and Stable are treated by Debian as releases. There is a release called "Backports"[3]. After arriving to Testing, a package can be rebuilt in a Stable jail using the Stable resources (libraries, etc.). This package can be sent to Debian Backports and some users that like it can use the new package in your Stable (released each 2 years). Note that Backport is not a mandatory process. I am a Debian Developer and I like Backports, so I will try to send interesting packages to backports too. Please, search for "bpo" in my DDPO[4] (Debian Developer's Packages Overview) to see some examples.

[3] https://backports.debian.org
[4] https://qa.debian.org/developer.php?email=eriberto@debian.org

When we send a package to Sid or to Backports, it will be built on all architectures supported by Debian as i386, amd64, arm64 and s390x (over 20 currently[5]).

[5] https://buildd.debian.org/

Finally, when the package arrives to Debian, a tracker page[6] will be created for this package. See an example here[7]. In this page you can see all about the package and your program. There is a subscribe field on this page. If subscribed, anybody will receive email messages about new bugs, new uploads etc.

[6] https://tracker.debian.org
[7] https://tracker.debian.org/pkg/scrot

Thanks for your work. Please, close this issue after the package is approved by FTP Master. I will let you know about it.

**Comment by WarmUpTill** [comment]
Thank you very much for the detailed descriptions, references and your support in general! :)
I really learned a lot!

**Comment by eribertomota** [comment]
Hello @WarmUpTill, 

I just sent obs-advanced-scene-switcher version 1.15.3+git20210913.25cf51a to Debian. The package will be shown in New Queue[1] in 2 hours. I will tell you when the package is accepted by FTP Master Team (I hope in a few days).

[1] https://ftp-master.debian.org/new.html

The current packaging code is available here[2] (see debian/ directory).

[2] https://salsa.debian.org/debian/obs-advanced-scene-switcher

Have a nice day!

Eriberto

**Comment by eribertomota** [comment]
Hi everyone,

The advanced-scene-switcher was accepted today in Debian[1]. I will upload the new version 1.16.3 soon.

[1] https://tracker.debian.org/pkg/obs-advanced-scene-switcher

Cheers,

Eriberto
