### ISSUE TITLE
Allow General and Executable at the same time

### ISSUE THREAD

**Issue by shayne** [WarmUpTill/SceneSwitcher#3]
Looks like executable matches true when not focused, even with "needs to be in focus" is set. This means that any scene switching defined under General is ignored when the executable process is found running.

Would be great to have match set to false if not in focus and needs to be in focus is set.

**Comment by shayne** [comment]
Possible to add build configs to the repo or at least what's required to build?

**Comment by WarmUpTill** [comment]
Both done. Added Priority option and CMakeList.

**Comment by shayne** [comment]
Really appreciate it!
