### ISSUE TITLE
Issues with TIME Tab

### ISSUE THREAD

**Issue by RONCOmke** [WarmUpTill/SceneSwitcher#30]
I have set up a series of scene switches with the TIME tab in the advanced scene switcher. I want to be able to hold at certain scenes longer at certain parts of the stream rather than a cycle like the SEQUENCE tab.

However, when starting the stream, nothing changes.

I am running OBS 25.0.8 on a 2017 MacBook Pro OS X 10.15.4

Please let me know what additional information you may need or how this can be corrected.

**Comment by WarmUpTill** [comment]
The TIME tab is used for switching based on your current local time, not time since starting the recording.
Was this maybe just a misunderstanding as to what the Time tab does exactly?

**Comment by RONCOmke** [comment]
Thank you for clarifying. I was under the impression it was the time into the stream, not the actual time. I'll try adjusting the time for time of day and retest.

Thanks again!

**Comment by RONCOmke** [comment]
That was it! Loving this tool!
