### ISSUE TITLE
Is possible to add CMAKE_INSTALL_LIBDIR?

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#301]
Hi @WarmUpTill,

To finalize the package for Debian, I need to install advanced-scene-switcher.so at `/usr/lib/<architecture, as x86_64-linux-gnu>/`. This is the right path in Debian. I read in Internet the possibility to use something similar to:

`LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}`

I think this line or similar will allow me to pass `-DCMAKE_INSTALL_LIBDIR=/usr/lib/${DEB_TARGET_GNU_TYPE}` to cmake command. Is possible to implement it? If not, I will use a patch in build time to change the file CMakeLists.txt.

Thanks in advance.

**Comment by eribertomota** [comment]
Correcting my words, the right way is  `/usr/lib/<architecture>/obs-plugins/`.

**Comment by WarmUpTill** [comment]
Sure , I will add this.

**Comment by WarmUpTill** [comment]
The following variables are now used for the install locations:

- LIB_OUT_DIR
- DATA_OUT_DIR

They will also respect CMAKE_INSTALL_PREFIX

```
    install(TARGETS advanced-scene-switcher
            LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIB_OUT_DIR})
    install(DIRECTORY data/locale
            DESTINATION ${CMAKE_INSTALL_PREFIX}/${DATA_OUT_DIR})
    install(DIRECTORY data/res
            DESTINATION ${CMAKE_INSTALL_PREFIX}/${DATA_OUT_DIR})
```
Let me know if that works for you.
