### ISSUE TITLE
Warnings when building with GCC 11

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#303]
Dear @WarmUpTill,

The attached file shows the building in Debian Sid with GCC 11. There are some warnings.

Feel free to close this issue it it is not relevant.

Regards,

Eriberto

[obs-advanced-scene-switcher_1.15.3+git20210913.25cf51a-1_amd64.build.gz](https://github.com/WarmUpTill/SceneSwitcher/files/7157235/obs-advanced-scene-switcher_1.15.3%2Bgit20210913.25cf51a-1_amd64.build.gz)

**Comment by WarmUpTill** [comment]
Thanks for sharing the logs!

The deprecation warnings from QT side are known and intended.
I cannot yet switch to the corresponding new methods are not available yet on all platform's default Qt version.

The unused variable in utility.cpp is something I will fix, but that is of course nothing crucial.
