### ISSUE TITLE
Feature request: "Transition" trigger.

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#311]
In our show, we would love to automatically trigger stuff if a certain transition is running.

For example:
Mute Mic 2 if Transition "Cooltransition" is running.

**Comment by WarmUpTill** [comment]
I implemented the macro condition "transition" with the linked PR.
This will let you allow to perform actions when:
* The currently selected transition is the specified one
* The duration of the currently selected transition matches a certain value
* A transition is currently active
* A transition ended

Especially the latter two will be of interested to you.

![Transition](https://user-images.githubusercontent.com/19472752/134561047-bcfd3701-fbec-43fa-badd-eca6230c56e4.PNG)

A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1266956102

Please let me know if everything works as expected.
Especially in regards to the the "Transition active" condition.
It uses some trickery behind the scenes as there is no corresponding event from OBS.

Note that I also added the "transition" action to the macro tab which lets you set the currently active transition type and duration.

**Comment by nacalai** [comment]
Thank you very much! That's fantastic. I'm just wondering if you can choose
the transition? Since we only want to trigger an action if a specific
transition is playing. (each new stinger transition will have a new name
that one can pick).

**Comment by WarmUpTill** [comment]
Yes that should be possible using two of these condition.
One specifying the type and the other stating that the transition needs to be active.

**Comment by WarmUpTill** [comment]
Is everything working as expected?
If so I would merge the changes for the next release.

**Comment by nacalai** [comment]
I feel stupid. How exactly do I get that version. There is no exe. Do I need to download the individual folders and replace?

**Comment by nacalai** [comment]
Ok, so the plugin itself is working. Nice job! But what we want is for an example an audio source to be muted when a specific transition is running. The way it is now it will just trigger when whatever transition is currently playing. So if you could add a dropdown filter menu to "Transition active/ended" as well, that would do it :)

**Comment by WarmUpTill** [comment]
>The "Current transition is..." only accounts for what the global transition is set to, and not to what is currently playing. So therefore your suggestion to use AND logic, does not affect.

Are you using transition overrides to use a different transition type than the currently active global one?

**Comment by nacalai** [comment]
> > The "Current transition is..." only accounts for what the global transition is set to, and not to what is currently playing. So therefore your suggestion to use AND logic, does not affect.
> 
> Are you using transition overrides to use a different transition type than the currently active global one?

Ah right, I am yes.

**Comment by WarmUpTill** [comment]
OK, thanks for the info.

I have to rework the functionality to support transition overrides.
I will update you if / when I find a solution.

**Comment by nacalai** [comment]
Ok thanks! I guess as a workaround for now, is to have our outro-action set
the global type to the transition we want, switch the scene then revert to
normal. That way the trigger will work

Nicolai Solbakk Willumsen

Fotograf & Videoskaper

www.nicolaiwillumsen.no
41006088
***@***.***
www.nicolaiwillumsen.no
Oslo


tir. 28. sep. 2021 kl. 21:36 skrev WarmUpTill ***@***.***>:

**Comment by WarmUpTill** [comment]
I now got around to implementing the mentioned rework of the transition condition.

It now supports specifying the transition type for the "Transition active" and "Transition ended" selection.
Selecting "Any Transition" will result in the behaviour that was already implemented previously.
As requested it also supports the use of transition overrides.

![Rework](https://user-images.githubusercontent.com/19472752/135732055-5d6bcab0-8905-44db-a359-0b1511800674.PNG)

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1299071491
