### ISSUE TITLE
Where is the config stored?

### ISSUE THREAD

**Issue by vjpr** [WarmUpTill/SceneSwitcher#314]
You can import and export, but I could not find out where the config is stored. Can it be modified by another process? Or is import/export the only way?

**Comment by WarmUpTill** [comment]
The plugin settings are stored as part of the scene collection settings.
The location of these depend on the OS and how you configured OBS.

Assuming you are on Windows and have not configured OBS to run in "portable" mode the settings will be located at:
`C:\Users\Username\AppData\Roaming\obs-studio\basic\scenes\Untitled.json
`
(Assuming your Windows login is "Username" and your scene collection is named "Untitled")

**Comment by WarmUpTill** [comment]
I will close this issue for now - let me know if you have further questions regarding this topic.
