### ISSUE TITLE
OBS crash on exit

### ISSUE THREAD

**Issue by ASchneiderBR** [WarmUpTill/SceneSwitcher#316]
Hello my friend! How are you? Long time no see...

I'm now getting this crash now and then when I shutdown OBS.

https://pastebin.com/aMck5nYk

Maybe it is related to your plugin?

Thanks!

**Comment by WarmUpTill** [comment]
Hello :)
Yes, the crash is related to the plugin - thanks for reporting it!
In particular it crashed when comparing the source settings. ("getSourceSettings()")
Would you mind sharing your plugin settings so I can try to reproduce it on my end?

**Comment by ASchneiderBR** [comment]
Hey there!

No problem.

[Settings BKP.txt](https://github.com/WarmUpTill/SceneSwitcher/files/7268603/Settings.BKP.txt)

Thanks!

**Comment by WarmUpTill** [comment]
I think I have identified the problem.
If was trying to create a string from NULL in getSourceSettings().
This could happen if the function was called on a source which was just deleted or on shutdown when all sources / filters are destroyed.

Fix is available with the linked PR.

**Comment by ASchneiderBR** [comment]
Nice! I think I had a scene configured there that was deleted... I'll give it a try, thanks!

**Comment by WarmUpTill** [comment]
Sorry forgot to link the build earlier:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1298634368

Thanks again for reporting the problem! :)
