### ISSUE TITLE
"Priority" works, but is not loaded with obs

### ISSUE THREAD

**Issue by MatheusLynar** [WarmUpTill/SceneSwitcher#32]
Pretty much the title.
I can order the switching methods and the order works and it's even saved into my scene file.
However when I load OBS again, the order is gone while every other configuration seems to be working normally.

**Comment by WarmUpTill** [comment]
Thanks for reporting this issue!
Just to clarify: Are you referring to the thread priority or the priority of the different switching methods?

I will look into it as soon as I can.

**Comment by MatheusLynar** [comment]
Priority of the different switching methods.
It works when I sort them, it even writes the new priority to the scene file config (priority0, priority1, etc)
However when I close and open OBS again, the order is gone.

**Comment by WarmUpTill** [comment]
I think I found the issue and fixed it with cd54cc1.

Builds should be done in a couple of minutes and will be available here:
https://github.com/WarmUpTill/SceneSwitcher/runs/855094467
I would appreciate if you could confirm if it is working as expected on your end also.

Thanks again for reporting the issue!

**Comment by MatheusLynar** [comment]
Yes, it's working perfectly. Thanks!
