### ISSUE TITLE
Feature Request: "Any" and "all" media/source/etc

### ISSUE THREAD

**Issue by DachsbauTV** [WarmUpTill/SceneSwitcher#321]
First off: Thanks for the amazing work on this plugin. This really makes OBS an insanely versatile and professional app.

My main use case for the plugin atm is to switch scenes after media files finished playing (either single files or playlists)

Currently I have to set a macro for every single file to achieve this, but it would be amazing to have the following options:

1. Any: meaning if any source in a scene fulfills the criteria, the macro will trigger
2. All: having the possibility to change attributes of all sources (or all of a kind) in a scene (e.g. hide all media sources after one has finished)

**Comment by WarmUpTill** [comment]
Thank you for the suggestion! :)
I will add it to the to-do list.

**Comment by DachsbauTV** [comment]
Oh and I just figured the best way would be to have a "exclude" or "except" within the macro, as well.

That way one could make a group with every source that shouldn't be included in the "any" or "all" case and could easily separate sources from the macro.

**Comment by WarmUpTill** [comment]
Sorry about the late reply / slow progress.
I got around to implementing the second part of your request ...
>having the possibility to change attributes of all sources (or all of a kind) in a scene (e.g. hide all media sources after one has finished)

... for the scene visibility action:

![Visibility](https://user-images.githubusercontent.com/19472752/141689749-7fe53836-34c4-49bc-a47d-16ee79f500ac.PNG)

What other types of actions did you have in mind?

**Comment by DachsbauTV** [comment]
Amazing I will give it a try next week!

Also it could be great to have it the other way around, e.g.:
- If ANY Media Source in Scene ABC finished playing then ..... (switch scene most likely)

**Comment by CodeYan01** [comment]
> Amazing I will give it a try next week!
> 
> Also it could be great to have it the other way around, e.g.:
> 
> * If ANY Media Source in Scene ABC finished playing then ..... (switch scene most likely)

I also need this hahaha as I have a whole scene (I use it as a nested scene) where most of my videos are, and my Media tab is full of entries from that scene, with the same settings. So having a generic option for videos in the same scene is useful.

**Comment by WarmUpTill** [comment]
I implemented the option to match any / all media sources on a specified scene with the linked PR.
![AnyMedia](https://user-images.githubusercontent.com/19472752/143779652-044261e3-ae2a-4678-8a3d-29b6950cbea8.PNG)
A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1513205248

Please let me know if everything is working as expected! :)

**Comment by WarmUpTill** [comment]
I will merge the change for now - let me know if you run into any issues! :)

**Comment by DachsbauTV** [comment]
Better late then never: It is working flawlessly :)
