### ISSUE TITLE
Cant Pause the gernarally  scene change 

### ISSUE THREAD

**Issue by cyclemat** [WarmUpTill/SceneSwitcher#332]
in the moment our problem is we want to use the generally tab when he nothing find he change to a fullscreen cam but we have an automation for an outro scene so when the outrp scene is outrunning the stream stops but cant the stop the change from the generally tab ! 
![image](https://user-images.githubusercontent.com/6072436/138557314-a6b73bec-e2ad-4689-a1a1-5ff787dfb09e.png)

**Comment by WarmUpTill** [comment]
I assume this works and will close the issue.
