### ISSUE TITLE
Advanced Scene Switcher seems to ignore time based rules

### ISSUE THREAD

**Issue by magnetra7** [WarmUpTill/SceneSwitcher#334]
OBS Version: 27.0.1
Adv. Scene Switcher Version: 1.16.1
Windows 10 ver. 21H1
AMD CPU

I'm using OBS + Adv. Scene Switcher for our local TV station. I currently use sequence based rules with success. Now I want to add time based scene switching rules. I set the Switching Methods Priority to time first, then secquence, then the others. I have added two time based scene switch rules, but SEEM to be ignored.

What I already tried:
- The option: After a match do not switch scenes for... set to 2 seconds
- Setting all sequence based rules to the Scene Transition "cut" as to prevent the fade Transition from interfering with the Time Based Sequence Switching Rules (crazy idea maybe, but also this didn't help).

I'm still figuring out what could be wrong, and maybe I can find a workaround to achieve switching scenes based on the computer time. These rules have to have priority over the sequence based switching rules at our TV station.

Things I can come up with that could be wrong:
- Advanced Scene Switcher uses UTC time instead of the local time zone which in my case is UTC+2 Europe/Amsterdam.

Lastly thank you for the good software.

**Comment by magnetra7** [comment]
Update: I tried setting all the sequence rules to "interruptible", and now the time based scene switch rules partly work. One rule is effective, and the other seems te be ignored.

I will try creating a work around using a macro and a helper program / script.

**Comment by WarmUpTill** [comment]
@magnetra7 shall I close this issue for now or do you want me to investigate any remaining issues?

**Comment by magnetra7** [comment]
I still can't get it fully working, just one time based scene switch rule, not two. But I will try a work around, I can't say for sure if it's the settings or something that are wrong on my PC or that this is a real issue. Up to you if you close it :-)

**Comment by magnetra7** [comment]
When I have some energy left I'll fiddle with it more anyhow :-)

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if there is still something left to do :)
