### ISSUE TITLE
Media Control: Switch to Preview Scene

### ISSUE THREAD

**Issue by Cypris2010** [WarmUpTill/SceneSwitcher#355]
It's possible that I get something wrong. There is an issue I think is related to this, but I don't understand the solution.

Is there a possibilty to switch to the scene, witch is selcete als the preview scene after a Mediaplayback has ended?

**Comment by WarmUpTill** [comment]
That should be possible.
Have you tried something like this?
![MediaPrevious](https://user-images.githubusercontent.com/19472752/142728382-9812b84a-6a61-42ff-b0ec-d06fe6eb8d9e.PNG)

**Comment by Cypris2010** [comment]
I'm not a native speaker.  Doesn't "previous" mean before? I want to switch to the scene selected in the obs preview.

**Comment by WarmUpTill** [comment]
Ah sorry my bad - I misread your question! :)
That is also possible:
![SwapScene](https://user-images.githubusercontent.com/19472752/142728669-bf20bce7-622e-4846-8d0f-e619666f4a90.PNG)

Does that answer your question?

**Comment by Cypris2010** [comment]
Thank you, thats what I'm looking for.
