### ISSUE TITLE
Wish List: Break out the audio switcher as a seperate plugin

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#37]
This would be a great feature on its own. I am doing a podcast and I have to use Zoom, screen grabbed into OBS with two people in the same room just to have this feature. If you have time to do this, it will be a great feature to have.

I know about the node.js SwitchSceneOnAudioOBS and will probably use it, once I customize it, but again, it's more things to have to mess with outside of OBS as it relies on the browser to track volumes and websocket to communicate with OBS.

All in all your audio switcher as a separate plugin would be much more elegant.

Thanks for your work!

**Comment by WarmUpTill** [comment]
Thanks for the suggestion, but I don't quite understand what the benefit would be of moving the audio switching to a separate plugin.
Can you elaborate?

(I don't know "SwitchSceneOnAudioOBS")

**Comment by nospam2k** [comment]
Honestly, I being premature as I haven't even tried the plugin. I just found it today and responded.

As I have a staff that runs OBS for our other presentations as well as the podcast, my thought was "I don't want to have to make sure my staff doesn't screw up switching because they are using the wrong scene switcher". This line from your info is what prompted me thinking this.

```
Additional Information and Notes:

Don't run both, the built in scene switcher and the advanced scene switcher. Otherwise both will try to switch based on their settings and cause many unnecessary scene switches.
```

From looking at the other advanced scene switcher aspects, this is one that I'd really like to use. Hope that explains it.

**Comment by WarmUpTill** [comment]
Ah I see - I guess that makes sense.

The main concern when running both, the built-in scene switcher and the advanced scene switcher, would be that for example one would permanently try to switch to scene1 while the other is trying to switch to scene2, causing the active scene to switch back an forth endlessly.

But this would of course still be possible even if I would separate the audio scene switching for this plugin to a separate one.

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if you run into any issues.
