### ISSUE TITLE
Macro: Pause recording has a delay

### ISSUE THREAD

**Issue by rexelbartolome** [WarmUpTill/SceneSwitcher#371]
When using a Macro and using a Scene change to pause/unpause the recording, the recording won't be paused/unpaused unless OBS is the focused window.

I'll upload a video to show what I mean.

https://user-images.githubusercontent.com/88552647/144761263-b5de6199-1309-424c-aeb9-a3cf270b3f71.mp4

Even if I have the Pause scene as the current scene, the recording won't be paused unless I click on the OBS window. Same thing happens for the Unpause scene, the recording won't unpause unless I click on OBS first.

Current workaround is just use the default lua script available in Tools>Scripts>Add Script>pause-scene.lua and select the intended Pause scene which pauses and unpauses successfully, regardless of the focused window.

**Comment by WarmUpTill** [comment]
I assume what is happening here is that the window title scene check has a higher priority than the macro functionality.
Thus the macros only get to run if no window title condition is met - which is the case if you click on the OBS window.

To resolve your problem you have two options.

1. Adjust the priority on the general tab so macros are executed before any other checks are executed
2. Move the window title check to the macro tab also (using the "window" condition)

I personally would recommend to do the latter as it will be the most flexible if you ever intend to expand upon the condition to switch scenes.

**Comment by rexelbartolome** [comment]
I see, that makes total sense! Though I wish I've understood it sooner, I've made a tutorial on how to use your scene switcher but I just showed my workaround for that tutorial 😆

Here it is if you're interested https://www.youtube.com/watch?v=WNXdWnl0KUU
