### ISSUE TITLE
macOS Catalina not showing menu (does #14 still apply?)

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#38]
I just tried to put the downloaded plugin from obsproject into the suggested folder for macOS. I don't see the menu item. It seems like the info for #14 is not really a good idea 1 year later. Is there any updated info?

I noticed 1.7 is new today. I have time today to work with this if you need testing. I'm not setup to compile but I can test.

```
error: os_dlopen(/Users/david/Library/Application Support/obs-studio/plugins/advanced-scene-switcher/bin/advanced-scene-switcher.so->/Users/david/Library/Application Support/obs-studio/plugins/advanced-scene-switcher/bin/advanced-scene-switcher.so): dlopen(/Users/david/Library/Application Support/obs-studio/plugins/advanced-scene-switcher/bin/advanced-scene-switcher.so, 257): Library not loaded: /tmp/obsdeps/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/david/Library/Application Support/obs-studio/plugins/advanced-scene-switcher/bin/advanced-scene-switcher.so
  Reason: image not found
```
The above is when run from command line

**Comment by nospam2k** [comment]
Ok after messing with this since my last post, I found I could work around this error by the following (obviously not a permanent fix and will need to be addressed)

```
ln -s /Users/david/Applications/OBS.app/Contents/Frameworks tmp/obsdeps/lib
```

This may be related to the fact that I'm not running OBS from /Applications but ~/Applications so not sure what the next move is.

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue.
This is a problem in the build script due to recent changes in regards to the obs-debs.
I triggered a new build and will update the release.

I would appreciate if you could test it as I cannot do so myself.

**Comment by nospam2k** [comment]
Ok, that worked even with OBS.app in ~/Applications. Only thing is that the .so throws a popup error that the plugin cannot be verified. It just requires cancelling the pop up (don't move to trash) and then in preferences > Security & Privacy > General, it should be listed.

**Comment by WarmUpTill** [comment]
Thank you very much for the test!
