### ISSUE TITLE
latest update doesn't have the new options

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [WarmUpTill/SceneSwitcher#386]
Can't see this option any where "Added the option to the "Switch scene" action to wait for the transition to complete before continuing with the next action."

**Comment by WarmUpTill** [comment]
Hm, that seems a bit strange.
Are you sure that the new version was installed correctly / Does it say version 1.17 in the settings window?

I noticed that with the newer versions of OBS a registry key seems to have been removed which was used to indicate where to place the plugin files.
Thus the Windows installer seems to have issues finding the correct location where to place the files on some setups.
So maybe that is causing your problem?

**Comment by WarmUpTill** [comment]
I will close this issue for now - let me know if you need further help investigating the problem.
