### ISSUE TITLE
Feature Idea (not a request): Condition OBS startup/shutdown & plugin controls

### ISSUE THREAD

**Issue by DachsbauTV** [WarmUpTill/SceneSwitcher#392]
**Is your feature request related to a problem? Please describe.**
Yes, I came across the idea because my OBS like thousands of others, crashes on shutdown because of the essential websockets plugin. 

**Describe the solution you'd like**
My idea to solve this was to use your (once again incredible) plugin and to activate the plugin after OBS started and to deactivate the plugin on an OBS shutdown, so it wouldn't crash anymore.

**Describe alternatives you've considered**
Turning it on and off manually :D
The trigger "if process is running obs64.exe" + only on condition change works for startup, however, not for shutdown

**Additional context**
This might be useful in general to have an OBS startup/shutdown trigger, to have OBS automate certain preparations, or even fully automate a standalone OBS system that starts on booting the machine.
e.g. we (mis)use OBS for a signage display, which still needs a couple of clicks to be ready. This could be automated.

Plugin controls could potentially be impossible, as every plugin is completely different i guess. That's why all of this is more of a proposal for discussion as a real feature request :)

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I will look into it, but as you already mentioned, I fear that every plugin will behave differently in that regards.

The "on shutdown" trigger might be useful regardless so I will add it to the todo list.

**Comment by DachsbauTV** [comment]
Don't worry about the websockets thing anymore! OBS 27.2 fixed it finally :)
