### ISSUE TITLE
[Linux] Maximized is treated as fullscreen

### ISSUE THREAD

**Issue by gabrc52** [WarmUpTill/SceneSwitcher#41]
### Steps to reproduce

- Set a "no switch condition is met" to a specific scene A
- Go to "Title" tab and add a condition "only if fullscreen" for a specific window to another scene B
- Make the window maximized but not in full screen

### Expected behavior
Scene A would appear

### Actual behavior
Scene B appears

|Window state|Expected behavior|Current behavior|
|-|-|-|
|Neither maximized nor in full screen|Scene A|Scene A|
|Maximized but not in full screen|**Scene A**|**Scene B**|
|Full screen|Scene B|Scene B|

I'm using Ubuntu 20.04

**Comment by WarmUpTill** [comment]
Thanks for reporting this issue.
This was changed with https://github.com/WarmUpTill/SceneSwitcher/pull/24.

Is this type of behavior something strictly required for your usecase or would it be enough to just change the description to "fullscreen or maximized" ?

**Comment by gabrc52** [comment]
> Thanks for reporting this issue.
> This was changed with #24.
> 
> Is this type of behavior something strictly required for your usecase or would it be enough to just change the description to "fullscreen or maximized" ?

Thanks for your response.

I'm using it to record/stream Microsoft Teams meetings. Teams hides part of its UI when on full screen but not when on maximized, and I have two scenes for both views.

It could be worked around by unmaximizing the window and resizing it to fill the whole screen as it would when maximized, but it's not the best experience.

**Comment by WarmUpTill** [comment]
I have added this functionality with 6e3889d2a44e4e1c0e3a625aabac45af9597c22f.
You can find a build with this change here:
https://github.com/WarmUpTill/SceneSwitcher/pull/40/checks?check_run_id=1161308690

I have not found the time to test it much so if you could try it on your end it would be much appreciated.

In general I implemented it in the way that "maximized" is a subset of "fullscreen" so setting both "maximized" and "fullscreen" at the same time will be equivalent to only selecting "fullscreen".

**Comment by gabrc52** [comment]
Works as a charm, thanks!

**Comment by WarmUpTill** [comment]
Glad to hear that it is working as expected and thanks for testing it!
I will add it with an upcoming release. (No ETA yet)
