### ISSUE TITLE
Implement option to specify rate at which audio fades happen

### ISSUE THREAD

**Issue by WarmUpTill** [WarmUpTill/SceneSwitcher#419]
>Regarding the crossfade I can think of one really nice to have feature. The only thing we can do now is fade from X% to Y% with duration of Z seconds. It would be nice to be able to set 'volume step [%] per second' instead of static duration of Z seconds. 
The use-case for this is again doing crossfade in one direction, then doing the interrupt at some random moment and starting the crossfade in the oposite direction. User might want to move the volume levels with static speed (e.g. 10% / second, so when moving from 0% to 50% the fade duration would be 5 seconds) instead of having every fade to take constant amount of time.
As a result let's say some macro with fade-in action from 0% to 60% with fade speed of 10% / second is running. This macro in interrupted by another macro (Stop action) after 3 seconds (so actual volume level is somewhere around 30%) and fade-out again with fade speed of 10% / second is triggered. Now the fade-out only takes 3 seconds.

_Originally posted by @mutant-industries in https://github.com/WarmUpTill/SceneSwitcher/issues/417#issuecomment-1055202776_

**Comment by WarmUpTill** [comment]
The option to specify the the rate at which a fade is happening was implemented with the linked PR.
![FadeRate](https://user-images.githubusercontent.com/19472752/156642687-f71afc81-9563-42e3-9cfc-a46c964e0103.PNG)


A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1930109623

**Comment by mutant-industries** [comment]
This looks good, there is just one unresolved detail - when I configure fade to go from 100% to 0% with step 8% / second, then the audio level never reaches 0% and stops at (my guess) 4%. Also fade from 0% to 100% with step 8% / second stops at -0.1 dB (I guess at 96%). The limit values should be reached in any case - even when the last step is less than 8%.

**Comment by WarmUpTill** [comment]
Thanks for pointing this out.

Should be fixed with:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1934902073

**Comment by WarmUpTill** [comment]
I was able to identify a few minor bugs.
Additionally I now also added the option to cancel any active audio fades as an option directly to the audio action:
![FadeAbort](https://user-images.githubusercontent.com/19472752/156845770-0b31edac-b9b8-48ee-b13a-6364b0e72f64.PNG)

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1936009401

**Comment by mutant-industries** [comment]
This time it works flawlessly and the 'Abort already active fade' makes the configuration a lot nicer and clear. Once again thanks for excellent support.
