### ISSUE TITLE
Only "executable" GUI present

### ISSUE THREAD

**Issue by omegahacker** [WarmUpTill/SceneSwitcher#429]
On both my test and productions machines, with the latest (1.17.4) I get only the configuration section for executable-triggers, without any of the other trigger types at the top.  I thought it might be caused by my older OBS version (26.1.1, wasn't any reason to upgrade) but even after upgrading to the latest (27.2.3) I still get the same.  I'd really like to make use of this plugin to automate things, any ideas what's going on here...?

![obs-switcher-execonly](https://user-images.githubusercontent.com/2560137/159096925-15657a5a-ba4d-4ede-aeda-7ce6dc3cc3b9.png)

**Comment by WarmUpTill** [comment]
This is not the advanced scene switcher plugin but instead the built-in scene switcher that comes with OBS.

I assume you do not have the option to start the **Advanced** scene switcher in the Tools menu, do you?

If not can you please share an OBS log file?
This might give hints as to what is going wrong while loading the plugin / whether the plugin is found at all.

**Comment by omegahacker** [comment]
Derp, yeah, that's the problem.  I saw the Automatic Scene Switcher entry and missed the *Advanced* entry.  Must have mixed the name of the plugin up in my head, it's been that kind of ... year? ....
Thanks!
