### ISSUE TITLE
Video condition "Area selection" not showing up

### ISSUE THREAD

**Issue by amg2nd** [WarmUpTill/SceneSwitcher#430]
Not sure if this is a bug or just not implemented yet in the latest version of SceneSwitcher. Looking at the Wiki under [Video condition](https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition), there is "Area selection", but it's not showing up for me when I try to use any of the video conditions

 - OS: Windows 11
 - OBS Version: 27.2.3
 - Plugin Version: 1.17.4

**Comment by WarmUpTill** [comment]
Ah, that functionality is not released yet.
If you want to give it a try you can use the latest build from the master branch:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2006202875

Sorry about the confusion - wanted to prepare the wiki before releasing the new version.

**Comment by amg2nd** [comment]
I thought that might be the case. Thank you for everything you do. Have a good weekend.
