### ISSUE TITLE
Macro action for Media - set position

### ISSUE THREAD

**Issue by mutant-industries** [WarmUpTill/SceneSwitcher#435]
Macro actions in Media category include Play, Pause, Stop, Restart, Next and Previous. Several media sources (e.g. VLC media source, local file media source) also support setting position of playback within OBS UI
![media_position](https://user-images.githubusercontent.com/9576228/160286724-abd671e1-9859-4d8a-9dd3-79aa280176fc.png)
 It would be really nice to have this function accessible also via macro action. At the moment when I need to start some audio track from some specific position on scene switch, I must cut the audio track beforehand and I must use some media source, that points to this adapted audio track.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion.
The option to "seek to ..." a specific time point was implemented already with 1b63978acbf39b4a02cba89c3cb431dc70318048, but not yet released officially.

So if you want to give this a try already you can use any recent release from the master branch - e.g.:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2045969083

**Comment by mutant-industries** [comment]
Very nice, thanks a lot!
