### ISSUE TITLE
Unable to run cmd, bat, shell files

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#437]
Greetings! I am trying to have a macro run a cmd file, but it's just not working. If I double click the cmd file, it does what I want it to do. But when trying to run it from advanced scene switcher, nothing is happening. Running normal programs/exe works fine. Is there something I am missing? Should there be any arguments added?

Appreciate any help :)

**Comment by WarmUpTill** [comment]
>Is there something I am missing?

I don't think so.

I assume you are using Windows as you are mentioning *.bat scripts, correct?
If so I don't see what the issue might be.
I can run the follow sample without issues:
```
@echo off
echo "Hello">C:\Users\Till\Desktop\new.txt
```
![Run](https://user-images.githubusercontent.com/19472752/160667173-5ac75257-dd19-46fc-a02c-5df9ed839387.PNG)

The `new.txt` file is created every time I run the macro.
Is this simple setup working on your end or does it also show the same issues?

>Should there be any arguments added?

Arguments are only needed if you script takes arguments.

**Comment by nacalai** [comment]
@WarmUpTill Weird, it must be the script itself then. Because I was able to run a simple bat like you did, no problem. But running a bat with this code, nothing happens.
`echo let imageNamesStr = ` > images/images.js
dir images /b /O:D >> images/images.js
echo ` >> images/images.js`

any idea why? I have tried creating shortcuts, using .cmd, and different stuff but nothing works.

**Comment by nacalai** [comment]
I even tried converting to an exe and run it. Doesn't work. Really weird

**Comment by nacalai** [comment]
Yea, I already thought about using absolute paths. It seems that cmd is a bitch when it comes to that stuff, so I just chose the easy way by just putting the folder into the obs folder lol. Thanks anyway. Great work on the plugin :)
