### ISSUE TITLE
Installation on M1 Mac

### ISSUE THREAD

**Issue by fabltd** [WarmUpTill/SceneSwitcher#445]
I have tried to install this on a M1 Mac running the preview M1 native OBS build.

The install goes to plan but the files don't appear in the plugins. 

Any idea where there might be?

I therefore cannot test if it works with M1 OBS.

**Comment by WarmUpTill** [comment]
Unfortunately you cannot mix a native M1 installation of OBS (ARM) with a plugin compiled for x86.

I myself do not have access to an ARM based build environment for MAC so I cannot compile the plugin this way.
So unless you find someone who can compile the plugin for you you cannot use the available versions when running a native ARM version of OBS.

I know that in the past there used to be a rather active thread related to running ARM builds of OBS on MacOS where some user(s) also provided natively compiled version of the plugin.
The last version I could find however is quite old already, but maybe it will suffice for your use case:
https://obsproject.com/forum/threads/obs-on-apple-silicon.133606/page-10#post-556210

**Comment by WarmUpTill** [comment]
I am happy to report that first builds of the plugins for *_OBS 28*_ are available that should (in theory) work on M1 Macs.

A build can be found here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2854375930

You can either use the SceneSwitcher-macos-arm64-* or the 
SceneSwitcher-macos-universal-* artifact.

I would appreciate if you could give this a try and report back if you encounter any issues.

**Comment by pkej** [comment]
I'm happy to report that it worked flawlessly. I was offered a backup of the old settings, and all my macros were ready when using it.

Excellent job.
