### ISSUE TITLE
How save time value?

### ISSUE THREAD

**Issue by Jamyz** [WarmUpTill/SceneSwitcher#448]
**Describe the bug**
I cant save time value, every time i launch obs time value is set on default

**Expected behavior**
Save when close obs

**Comment by WarmUpTill** [comment]
Are all settings affected or just a particular option?

**In case of the latter**:
Which setting are you referring to exactly with "time value"?

**In case of the former:**
The setting are saved as part of the scene collection.
That means that most likely something is preventing OBS from writing to the scene collection json-file.

So the questions would be:
* Is the file set to read-only mode for some reason?
* Is your current user allowed to write to the file? (E.g. file is only writable by admin)

Unfortunately the location for the scene collection files differs for each OS and whether or not you are running OBS in portable mode.

(E.g. Window non-portable mode the files are saved under `%appdata%\obs-studio`)

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if you need further assistance!
