### ISSUE TITLE
[BUG] OBS Crashes on start. macOS Catalina

### ISSUE THREAD

**Issue by mal4i6ka** [WarmUpTill/SceneSwitcher#45]
## Platform

Operating system and version: macOS Catalina 10.15.7 (19H2)
OBS Studio version: 26.0.0-e24aaa0b

## Expected Behavior

OBS App Starts
## Current Behavior

Crash dialog is displayed
## Steps to Reproduce

1. Run App

## Additional information

[Crash log on pastebin](https://pastebin.com/Y43WY8rV)

This crash appears to be coming from the advanced scene switcher plugin, you'll need to report it to the developer of that plugin:

> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   advanced-scene-switcher.so    	0x00000000331d5d82 SwitcherData::saveGeneralSettings(obs_data*) + 818
> 1   advanced-scene-switcher.so    	0x000000003319d791 SaveSceneSwitcher(obs_data*, bool, void*) + 257

**Comment by mal4i6ka** [comment]
The advanced-scene-switcher.so file is in ~/Library/Application Support/obs-studio/plugins/ i delete that folder and OBS starts

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
Do you happen to have the settings of the plugin saved somewhere still or can you remember what you configured?

**Comment by mal4i6ka** [comment]
I wish I remembered. I guess I was made some tweaks turn auto switch on and have a crash. Sorry.
