### ISSUE TITLE
Threshold with more digits

### ISSUE THREAD

**Issue by SomeoneElsexx32** [WarmUpTill/SceneSwitcher#450]
**Is your feature request related to a problem? Please describe.**
I'm trying to record a pet with cameras in my house. While testing the Threshold of 0.99 wasnt really able to detect such a "small" change in the picture.

**Describe the solution you'd like**
The easiest way is to add 1 or 2 more digits after the point and or make the field editable and keep the slider only locking to 0.0X00 values

**Describe alternatives you've considered**
I've tried not to use the pattern matching and instead going for a time based change but this would i believe also trigger when the light from outside changes in brightness.

Also exporting the configuration and changing the values in the cfg file works.

Oh and you could add some keywords like motion detection somewhere in your repo - i was looking for these keywords but didnt find this project. I got your plugin suggested by someone

**Comment by WarmUpTill** [comment]
Sure that is possible - for now I just increased the precision of the slider to unblock you.
A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2234374801

It is also possible to export / import settings to a file on the General tab.
If you should want to manually modify the settings the value you have to look for is the following:

```
	"macros": [
		{
...
			"conditions": [
				{
...
					"id": "video",
...
					"threshold": 0.993,  # <- this is the value of interest
...
				}
			],
			"name": "Macro 1",
...
		}
	],
```
It is much easier to read the file if you format the json string.

**Comment by SomeoneElsexx32** [comment]
First of all thanks for the fast change and build :)

For my usecase i would actually need a sensibility of 0.000X (my current threshold is 0.9985) - i think the slider was good to with the stepping of 0.01 (thats probably perfect for most people) - Making the slider number editable in the program would be the best i think... 

Just an idea :) 

It works for me right now by editing the config file 👍

**Comment by WarmUpTill** [comment]
>Making the slider number editable in the program would be the best i think...

I fully agree - the previous build was just a quick hack to unblock you :)

A new build where you have the option to edit the number directly will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2241034033

![pattern](https://user-images.githubusercontent.com/19472752/165817198-07879c50-dbc0-4d41-8ea8-480f7587e59e.PNG)

**Comment by SomeoneElsexx32** [comment]
And if you are looking for ideas: It would be nice to show the current change level on screen so you could adapt the threshold without guessing :)

**Comment by WarmUpTill** [comment]
Maybe I am misunderstanding you but isn't this already possible using the "Show match" button? (Assuming you are using the "matches pattern" check type)

**Comment by SomeoneElsexx32** [comment]
Oh no I'm using the 'has changed' check type. Since im not having such a "static" envinronment to use a pattern.

**Comment by WarmUpTill** [comment]
For these purposes I would recommend enable the visual indicators to show whether or not a condition is currently true:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Troubleshooting#visual-indicators-of-macro-activity-and-status

**Comment by SomeoneElsexx32** [comment]
Thanks I'll try that
