### ISSUE TITLE
(Feature request) "Game capture is capturing" and "game capture is not capturing" conditions

### ISSUE THREAD

**Issue by matoi974** [WarmUpTill/SceneSwitcher#452]
**Is your feature request related to a problem? Please describe.**
I want to be able to automatically switch scenes if game capture's target window no longer exists to avoid accidentally recording an empty scene.
**Describe the solution you'd like**
I'd like a new "Macro" condition for Game capture sources for when they aren't actively capturing anything.

**Describe alternatives you've considered**
It's possible to check their transform properties and trigger the action when transform is 0x0, as game capture sources reset to a size of 0x0 when not capturing anything, but this can be awkward to work with because then I won't be able to use any other transform properties, such as "Fit to screen". I think I'll stick to this for now.
It's also possible to create two references, place one of them out of bounds of the canvas, and check that other reference's size while also using another reference for actual recording.

**Additional context**
I'm using "capture foreground window by hotkey" and recording a wide variety of applications with game capture, so checking whether a given process exists will not help.

**Comment by nacalai** [comment]
I'm on mobile now and can't see if this is the case at the moment, but could you use get settings from game capture source, then trigger alert if settings doesn't/does match?

**Comment by matoi974** [comment]
No, game capture properties do not change after losing their target window. They do change upon initially capturing the window and will include the most recently captured executable, but quitting said executable will not cause another change.

**Comment by WarmUpTill** [comment]
The video condition type might be well suited for this use case.
It supports checking whether or not a particular video source has any valid output:

![NoOutput](https://user-images.githubusercontent.com/19472752/166658280-31c7958e-ca39-43f1-8535-37af21aa3d50.PNG)

Does this solve your issue?

**Comment by matoi974** [comment]
Thank you, this does resolve my issue.
