### ISSUE TITLE
Scene switcher wasting memory on Mac Intel 

### ISSUE THREAD

**Issue by digitalchou** [WarmUpTill/SceneSwitcher#461]
**Description**
When scene switcher is active, even with no macros running nor other conditions, 
memory usage of OBS incrases and never release, resulting in huge swapfiles on disk
after few hours of use, even not streaming nor recrding. On disk full OBS crashes.
The rate of ram occuped is about 1 MB /s ons standard "check conditions every" value of 200 ms.
with a value of 2 seconds on "check cnditions every " the amount of ram decreases to 0.1 MB/s.
When scene switcher is stoped, ram stops increasing, but dont release the amount ocuped.

**Steps to reproduce the behavior:**
1.-open OBS with an empty scene, no sources ,not streaming, not recording.
2. open advanced scene switcher and pres "start"
3. Look at "Memory usage" in "stats" window on OBS
 
**log:**

[2022-05-09 19-41-18.txt](https://github.com/WarmUpTill/SceneSwitcher/files/8653956/2022-05-09.19-41-18.txt)

and log without verbose loggin:

[2022-05-09 19-45-48.txt](https://github.com/WarmUpTill/SceneSwitcher/files/8654093/2022-05-09.19-45-48.txt)

**Expected behavior**
scene switcher releasing ram.

**Version information**
 - OS: Macos High Sierra 10.13.6
 - OBS Version 27.2.4 
 - Plugin Version 1.17.5

**Additional context**
Scene Switcher Settings

[adv-ss-1-2022.05.09.22.41.52.txt](https://github.com/WarmUpTill/SceneSwitcher/files/8655198/adv-ss-1-2022.05.09.22.41.52.txt)

**Comment by digitalchou** [comment]
> Thanks for reporting the issue - I will try to look into it as soon as I can. Just in case it is relevant: Can you share the settings you are using? (Can be exported to a file on the General tab)

Thanks to you!
 On my test the only relevant thing is the time on "check conditions every" .
If I set it on 50 ms , in 6 hours of stream OBS memory usage is 16GB of RAM.
Seting to 2000 ms makes the grow slower, but even dont stop to increase.
Theres no matter if there are a lot of macros or none, as you see in my config file.
On this check there are many obs plugns loaded, but theres no matter.
If you want i can repeat the test without plugins, is exactly the same,
I spent a couple of days on testing before reporting the issue.

**Comment by WarmUpTill** [comment]
A build with a fix should be available here in a few:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2327255538
You will have to be logged into GitHub to be able to download it.

Let me know if that solves the issue on your end also!
(Sorry that it took so long to fix)

**Comment by digitalchou** [comment]
Many thanks! I tried some of your test yesterday. Im trying this now, it seems to work. My stream is online now , tomorrow in the morning I will tell you . Many thanks for your work. ASS is wonderfull

**Comment by digitalchou** [comment]
After 10 hours of stream, Memory usage reported by OBS is 1200 MB, mac sistem monitor reports that OBS have 1.04GB in use, and OBS helper 84MB . Looks nice. 
 Test is still online, my proyect is a channel to stream in continuity,when not live it plays a ist of videos. I have an RTMP server on the same machine, so when it receives an incoming RTMP stream advanced scene switcher flips to my live stream , and when the incoming stream ends it returns to play videos. Before my machine crashed after a few hours because swap files filled my HDD. 
Ill tell you about test result at 48 hours of stream, but i think this is pretty solved.
Many thanks for your efforts!

**Comment by digitalchou** [comment]
48 hours test was interrupted by a power outage, but I kept an eye on it  from time to time , and up to 34 hours memory consumption varied between 1400MB and 1200MB. I guess it will depend on the multimedia content that is being played at a time. Check condition time is now on 200ms, thats the value that before makes memory grow out of control.
Another thing was that when Advanced Scene Switcher interface was open , the memory grows even quickly
For me it runs perfect now, many thanks!!!
