### ISSUE TITLE
Option tabs are missing on macOS

### ISSUE THREAD

**Issue by Lumbra74** [WarmUpTill/SceneSwitcher#469]
Not all option tabs are visible on macOS

Version information

- OS: macOS 12.4
- OBS Version 27.2.2
- Plugin Version 1.17.
<img width="832" alt="Screenshot" src="https://user-images.githubusercontent.com/90106480/170873769-a45fb228-4848-4c4a-a782-f0f6fabb1e48.png">
5

**Comment by WarmUpTill** [comment]
Uncheck "Hide tabs which can be represented via macros" in the lower left corner of the General tab.

**Comment by Lumbra74** [comment]
Sorry, I missed that option.
