### ISSUE TITLE
Tabs not showing up

### ISSUE THREAD

**Issue by jmikeneedham** [WarmUpTill/SceneSwitcher#477]
**Describe the bug**
Only 4 tabs on interface showing on Arch based Linux.  Have installed plug-in both manually and via flatpak.  Tans are general, macro, network, scene groups.

**To Reproduce**
1. Go to plug-in in OBS from tools menu
2. Only 4 tabs on interface

**Expected behavior**
Expected to look like screenshot with many tabs at top.

**Logs**
No error, just tabs not showing.

**Version information**
 - OS: EndeavourOS (Arch based) Linux
 - OBS Version 27.1.3
 - Plugin Version latest stable

**Additional context**
Not sure if there is a file in the wrong place but need a little help to find where the problem lies.

**Comment by gogg03** [comment]
I've had same issue since 1.17.5 and now with 1.17.7. 
![image](https://user-images.githubusercontent.com/107894488/174688278-5fe2c122-a03e-46b2-9782-550492ea27da.png)

**Comment by jmikeneedham** [comment]
Still present on openSUSE too.  Still not resolved.

**Comment by WarmUpTill** [comment]
To show the old tabs **uncheck** the option "Hide tabs which can be represented via macros" in the lower left corner of the General tab.

![174688278-5fe2c122-a03e-46b2-9782-550492ea27da](https://user-images.githubusercontent.com/19472752/175113964-fd4c50b7-aac8-4b50-84bf-ecd8f8eb39b3.png)


I apologize about replying so late! (I did not have access to the internet the last week)

**Comment by jmikeneedham** [comment]
Solved my issue, thanks.  Might make a note of this in the install docs.  Appreciate the reply and np on the "lateness".  Internet probs happen :-)  Thanks again.  -- Michael

**Comment by gogg03** [comment]
Now we're cooking with grease. I mostly use the 'Random' tab and have yet to learn all the other functionality. Most of the tutorials online are based on the old tabs as well. Why not just have it unchecked by default? Or is this a push to get users to use the Macro functionality?

**Comment by WarmUpTill** [comment]
Glad to hear that everything is working as expected!
And sorry about the trouble in the first place. 

> Why not just have it unchecked by default? 

It was like that for a few months, but other users convinced me that it would be better to guide new users to the Macro tab by hiding the "old" tabs by default.

> Or is this a push to get users to use the Macro functionality?

It is indeed.
While I don't plan on removing the old tabs any time soon I also don't plan on expanding their functionality.

> Most of the tutorials online are based on the old tabs as well.

Just in case you are curios, the wiki has quite a few guides and examples on how to use the Macro tab:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Macros#what-are-macros

I will close this issue for now, but I will make sure to pin it for visibility, in case more people run into the same problem.

**Comment by jmikeneedham** [comment]
Thank you for that.  I suppose macros could be setup to do sequencing instead, but like most creators, the tab is so much of a time saver.  However, you as a developer ultimately decide the direction your application should go.

I appreciate all your work and your help.


Regards,
Michael Needham
