### ISSUE TITLE
Match pattern: No match unless manually adding .png.

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#480]
Hey there. I was wondering why I got no match when using the match pattern with video source, so I had to fiddle around for a bit.

By default, when creating a screenshot of a source to be used as a pattern match trigger, it's just saved as a file with no fileformat (all files). And no match is found when it uses that file. 
![image](https://user-images.githubusercontent.com/4357694/175376607-b0f8a19b-a1c6-45f2-80d6-183417b41973.png)
![image](https://user-images.githubusercontent.com/4357694/175376722-e73a79ae-8470-4073-93c6-77e085bf3196.png)

When I added .png to the end of my saved screenshot, then it worked.
![image](https://user-images.githubusercontent.com/4357694/175376642-6b8dc2ae-dbd1-4a89-bcfc-8735534d0764.png)
![image](https://user-images.githubusercontent.com/4357694/175376680-a510b327-c55e-4216-a0e8-88fd255bd707.png)

**Comment by WarmUpTill** [comment]
Thanks for the hint!
I will set the default file extensions for the screenshots to *.png with the linked PR.
