### ISSUE TITLE
Text Prompt

### ISSUE THREAD

**Issue by DanielLester83** [WarmUpTill/SceneSwitcher#486]
**Is your feature request related to a problem? Please describe.**
I've built a macro that uses a browser source that I would like to change on each run.

**Describe the solution you'd like**
I would like a simple text input prompt whose value could be used later to modify the url parameter of the browser source. Ideally it would allow a csv list of urls and would run the macro for each of them. 

**Describe alternatives you've considered**
Alternatively I can modify the browser source manually.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I will look into it when I find the time.

(And sorry about the late reply)

**Comment by WarmUpTill** [comment]
I somehow forgot to let you know that the requested change was implemented in one of the last releases.
I apologize for that!

![Variable](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/175d055c-c80f-433e-9fea-8715a527dec6)

Thus I will close this issue for now.
