### ISSUE TITLE
BUG: Duration modifier resets after restart OBS

### ISSUE THREAD

**Issue by Bugnutiy** [WarmUpTill/SceneSwitcher#494]
There is a duration modifier in the macro settings. I have to set it up after every OBS restart because it resets to 0.00

![img](https://user-images.githubusercontent.com/46416776/180743181-3457c804-13ed-4d90-aa1c-3135826f9ff8.png)

**Comment by WarmUpTill** [comment]
Thanks for reporting that problem!
I have a few more questions:

Is only this single duration modifier affected or are others affected as well?
Does the issue depend on the value you have set before exiting OBS?
Can you reproduce the problem if create a new macro with the same settings?

Would you mind sharing the settings you are using that are causing the issues?

**Comment by WarmUpTill** [comment]
I think I might have identified the issue.
The time field of the media condition was conflicting with the time field of the duration modifier.

A build with a fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2746522342

Let me know if that works for you.
