### ISSUE TITLE
Restore backwards-compatibility to older versions of OBS

### ISSUE THREAD

**Issue by WarmUpTill** [WarmUpTill/SceneSwitcher#499]
Hi @eribertomota,

This issue is mostly meant as a heads up for you:

I am currently working on reworking the build scripts and the plugin in general to support the new OBS 28 beta and QT6.
This will probably mean that backwards-compatibility to older versions of OBS will no longer be given and it will likely break the debian build.

I intend to look into restoring backwards-compatibility, however and will track this with this issue.
I am just not sure yet when I will get around to it.

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

Thanks a lot for your warn.

**Comment by WarmUpTill** [comment]
Maybe a quick follow-up question.
What is the oldest OBS version I would need to support?

**Comment by eribertomota** [comment]
The best option for me is 26.1.2. It will allow me to make available your plugin for Debian Stable. The minimum option is 27.2.4, to make your plugin available for Debian Testing.

**Comment by WarmUpTill** [comment]
I mostly finished the backwards compatibility changes in the linked PR.
I now tried running the workflow file you provided to me in the past to test the Debian build, but unfortunately this seems to require a version older than OBS 26.1.2.

Should I add additional checks for this OBS version also?

I was able to build the "version" branch of the plugin successfully for OBS 26 the  by running:
```
cmake \
  -DLIBOBS_LIB=~/obs-studio/plugin_build_x86_64/libobs/libobs.so \
  -DLIBOBS_INCLUDE_DIR=~/obs-studio/libobs/ \
  -DLIBOBS_FRONTEND_API_LIB=~/obs-studio/plugin_build_x86_64/UI/obs-frontend-api/libobs-frontend-api.so \
  -DLIBOBS_FRONTEND_INCLUDE_DIR=~/obs-studio/UI/obs-frontend-api/ \
  -DCMAKE_INSTALL_PREFIX=~/tmp/usr \
  -DLINUX_PORTABLE=OFF \
  ..
```

**Comment by eribertomota** [comment]
Hi @WarmUpTill 

I am not remembering about this workflow. Could you point me it? Currently, Debian uses the version 26.1.2 in Stable[1]. The Unstable and Testing are using version 27.2.4[1], that is broken. I can see efforts to package the version 28.0.0[2] to be uploaded to Unstable. Consequently, I think version 27 will be dropped soon. Don't worry if you is not able to produce a new plugin compatible with 26.1.2 because we already has the 1.17.7 working fine on Stable Backports[3]. A new version for Stable Backports is a very good idea, but dispensable.

[1] https://tracker.debian.org/pkg/obs-studio
[2] https://salsa.debian.org/multimedia-team/obs-studio
[3] https://tracker.debian.org/pkg/obs-advanced-scene-switcher

**Comment by WarmUpTill** [comment]
Hello @eribertomota,
the workflow can be found here:
https://github.com/WarmUpTill/SceneSwitcher/blob/version/.github/workflows/build-debian.yml

After adding additional version check it is now building successfully - so I would assume this branch _should_ be compatible with your build system once again.
(I assume the additional version check were necessary as the "ubuntu-latest" runner is still stuck an an older OBS version.)

Do you want me to perform any additional checks before merging my changes to the master branch, or does the mentioned workflow suffice?

The binaries themselves look fine but I am not sure if the file and folder structure in the *.deb file looks as expected.

**Comment by eribertomota** [comment]
I am a bit confuse. I cloned your current master repo and I added all changes from PR #521. When building the package in Debian Unstable (OBS 27.2.4), I got:

```
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher/src/macro-core/macro-ref.hpp:26:48: error: ‘vector’ in namespace ‘std’ does not name a template type
   26 | void SaveMacroList(obs_data_t *obj, const std::vector<MacroRef> &macros,
      |                                                ^~~~~~
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher/src/macro-core/macro-ref.hpp:5:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
    4 | #include <obs-module.h>
  +++ |+#include <vector>
```

Including vector as shown above, I got:

```
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher/src/utils/websocket-helpers.cpp:6:10: fatal error: obs-websocket-api.h: No such file or directory
    6 | #include <obs-websocket-api.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I don't found obs-websocket-api.h in Debian repository. Is this a specific file for OBS 28? I think these 2 issues are broking the backwards-copatibility.

**Comment by WarmUpTill** [comment]
> I don't found obs-websocket-api.h in Debian repository. Is this a specific file for OBS 28? I think these 2 issues are broking the backwards-copatibility.

You will have to clone the submodules also to solve this particular issue.

>error: ‘vector’ in namespace ‘std’ does not name a template type

Sorry about that.
Not sure why I don't see the vector error in my or the CI build environment.
I added the include now.

**Comment by eribertomota** [comment]
Where are the submodules?

**Comment by WarmUpTill** [comment]
They are all in the `deps/` folder.

If you clone the repo you can get them with:
`git clone --recursive https://github.com/WarmUpTill/SceneSwitcher.git`
Otherwise with:
`git submodule update --init`

**Comment by WarmUpTill** [comment]
I went ahead and merged the changes for now - let me know if further changes are required :)

**Comment by eribertomota** [comment]
Hi @WarmUpTill 

Sorry for my delay. The big issue is the packaging on Debian uses the tarball only, so a checkout from git is a problem for me. What you think about include these modules in final tarball or provide a separate tarball for them?

**Comment by WarmUpTill** [comment]
Ah I see.
For the other dependencies it is not an issue as these are available via some sort of deb package, right?

I went ahead and added the obs-websocket header file directly to the repo instead in PR https://github.com/WarmUpTill/SceneSwitcher/pull/541.

Will this work for you?

**Comment by eribertomota** [comment]
Is version your current devel tree? If I would to test the current code, should I clone version?

**Comment by WarmUpTill** [comment]
> I think that advanced-scene-switcher-opencv.so and advanced-scene-switcher-lib.so are local dependencies for advanced-scene-switcher.so, right?

Exactly - everything looks like it is supposed to :)

>I am a bit busy in this week, but I will try to package a new version for Debian after next Monday.

No rush - glad to hear everything is working again!
Thank _you_ very much!
