### ISSUE TITLE
Linux Arch, Plasms 5

### ISSUE THREAD

**Issue by romanlex** [WarmUpTill/SceneSwitcher#5]
Hello. 
In my case Cursor is currently at: always has 0x0 (tab Screen Region)
SceneSwitcher not work((
![image](https://user-images.githubusercontent.com/3369304/32618894-128e0a58-c58a-11e7-895e-ab1058a2ccdb.png)

**Comment by WarmUpTill** [comment]
Sorry I never came around to investigating this issue further.
Closing for now - please let me know if the issue still exist in recent versions of the plugin.
