### ISSUE TITLE
Scene Groups

### ISSUE THREAD

**Issue by GavMcBride** [WarmUpTill/SceneSwitcher#518]
Hello,

I'm trying to cycle through a scene group every x seconds, but I cannot get the thing started.

Does it need a macro to initiate it and if so, which settings will start it?

Kind regards!
Gav

**Comment by WarmUpTill** [comment]
Scene Groups are probably not exactly what you are looking for here.
Have a look at this guide for details on how to automatically cycle through a list of scenes:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Automatically-cycle-through-a-list-of-scenes
