### ISSUE TITLE
Feature Request: Support For Image Slide Show Conditions

### ISSUE THREAD

**Issue by Zhaph** [WarmUpTill/SceneSwitcher#527]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up a automatic scene transition when an Image Slide Show completes. At the moment I can do this based on a timer (i.e. multiply number of slides by display time), but it would be great if this could work in a similar way to the VLC Playlist and Media sources where it knows when they've finished, otherwise I have to keep changing the calculation when I add or remove images.

**Describe the solution you'd like**
Option to add "Image Slide Show" as a condition source, so that I can select an Image Slide Show source, and then select a state of "Ended" to trigger the action.

**Describe alternatives you've considered**
Timer based on number of images multiplied by duration.

**Additional context**
None

**Comment by WarmUpTill** [comment]
Seems like OBS internally the image slide show is treated as a media source.
That means adding image slide show can be added to the media condition type very easily.

A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3017811988

![SlideShow](https://user-images.githubusercontent.com/19472752/189211609-75aa3558-6ceb-4176-9827-e60a0ad2c860.PNG)

Let me know if this works as expected :)

**Comment by Zhaph** [comment]
Cheers @WarmUpTill I've installed that version, and can see the Image Slide Show showing up, the macro doesn't appear to fire on "Ended" or "Ended(Playlist)".

In the logs below:
Welcome - Empty scene
Scene 2 - Scene containing the Image Slide Show
Camera - Scene that is set as the switch to target of the action

![Macro Setup](https://user-images.githubusercontent.com/1271482/189457155-0d625c03-c42e-4c5a-a246-b181ab149806.png)

![Image Slide Show Setup](https://user-images.githubusercontent.com/1271482/189457296-6297e95f-2368-4f46-ab8d-65dcfc1027b0.png)


Standard logs just show:

```
00:03:01.221: User switched to scene 'Welcome'
00:03:04.782: User switched to scene 'Scene 2'
00:03:06.431: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:03:18.504: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:03:20.893: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:03:35.738: [adv-ss] detected busy loop - refusing to sleep less than 1ms
```

Enabling Verbose Logging:
```
00:05:21.345: User switched to scene 'Welcome'
00:05:21.495: [adv-ss] condition media returned 0
00:05:21.495: [adv-ss] Macro FirstSlideShow returned 0
00:05:21.596: [adv-ss] try to sleep for 199
00:05:21.649: [adv-ss] current scene:  Welcome
00:05:21.649: [adv-ss] previous scene: Camera
00:05:21.797: [adv-ss] condition media returned 0
00:05:21.797: [adv-ss] Macro FirstSlideShow returned 0
00:05:22.336: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:05:22.336: [adv-ss] try to sleep for 50
00:05:22.386: [adv-ss] condition media returned 0
00:05:22.386: [adv-ss] Macro FirstSlideShow returned 0
00:05:22.440: [adv-ss] try to sleep for 245
00:05:22.688: [adv-ss] condition media returned 0
00:05:22.688: [adv-ss] Macro FirstSlideShow returned 0
00:05:22.767: [adv-ss] try to sleep for 220
00:05:22.988: [adv-ss] condition media returned 0
00:05:22.988: [adv-ss] Macro FirstSlideShow returned 0
00:05:23.057: [adv-ss] try to sleep for 231
00:05:23.291: [adv-ss] condition media returned 0
00:05:23.291: [adv-ss] Macro FirstSlideShow returned 0
00:05:23.304: User switched to scene 'Scene 2'
00:05:23.349: [adv-ss] try to sleep for 240
00:05:23.589: [adv-ss] condition media returned 0
00:05:23.589: [adv-ss] Macro FirstSlideShow returned 0
00:05:23.615: [adv-ss] current scene:  Scene 2
00:05:23.615: [adv-ss] previous scene: Welcome
00:05:23.774: [adv-ss] try to sleep for 115
00:05:23.891: [adv-ss] condition media returned 0
00:05:23.891: [adv-ss] Macro FirstSlideShow returned 0
00:05:24.032: [adv-ss] try to sleep for 158
00:05:24.191: [adv-ss] condition media returned 0
00:05:24.191: [adv-ss] Macro FirstSlideShow returned 0
00:05:24.267: [adv-ss] try to sleep for 224
00:05:24.491: [adv-ss] condition media returned 0
00:05:24.491: [adv-ss] Macro FirstSlideShow returned 0
00:05:24.562: [adv-ss] try to sleep for 229
00:05:24.794: [adv-ss] condition media returned 0
00:05:24.794: [adv-ss] Macro FirstSlideShow returned 0
00:05:25.067: [adv-ss] try to sleep for 25
00:05:25.093: [adv-ss] condition media returned 0
00:05:25.093: [adv-ss] Macro FirstSlideShow returned 0
00:05:25.507: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:05:25.507: [adv-ss] try to sleep for 50
00:05:25.563: [adv-ss] condition media returned 0
00:05:25.563: [adv-ss] Macro FirstSlideShow returned 0
00:05:25.573: [adv-ss] try to sleep for 291
00:05:25.866: [adv-ss] condition media returned 0
00:05:25.867: [adv-ss] Macro FirstSlideShow returned 0
00:05:25.918: [adv-ss] try to sleep for 247
00:05:26.165: [adv-ss] condition media returned 0
00:05:26.165: [adv-ss] Macro FirstSlideShow returned 0
00:05:26.226: [adv-ss] try to sleep for 239
00:05:26.467: [adv-ss] condition media returned 0
00:05:26.467: [adv-ss] Macro FirstSlideShow returned 0
00:05:26.545: [adv-ss] try to sleep for 221
00:05:26.766: [adv-ss] condition media returned 0
00:05:26.766: [adv-ss] Macro FirstSlideShow returned 0
00:05:26.864: [adv-ss] try to sleep for 202
00:05:27.066: [adv-ss] condition media returned 0
00:05:27.067: [adv-ss] Macro FirstSlideShow returned 0
00:05:27.104: [adv-ss] try to sleep for 263
00:05:27.369: [adv-ss] condition media returned 0
00:05:27.369: [adv-ss] Macro FirstSlideShow returned 0
00:05:27.782: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:05:27.782: [adv-ss] try to sleep for 50
00:05:27.833: [adv-ss] condition media returned 0
00:05:27.833: [adv-ss] Macro FirstSlideShow returned 0
00:05:28.133: [adv-ss] detected busy loop - refusing to sleep less than 1ms
00:05:28.133: [adv-ss] try to sleep for 50
00:05:28.185: [adv-ss] condition media returned 0
00:05:28.185: [adv-ss] Macro FirstSlideShow returned 0
00:05:28.320: [adv-ss] try to sleep for 164
00:05:28.484: [adv-ss] condition media returned 0
00:05:28.485: [adv-ss] Macro FirstSlideShow returned 0
00:05:28.565: [adv-ss] try to sleep for 219
```

**Comment by WarmUpTill** [comment]
It looks like, the media state is always "Playing" when "Hide when slideshow is done" is not set, as the media source is always outputting an image.

![Hide](https://user-images.githubusercontent.com/19472752/189473376-5ae11ce2-597b-42d9-8911-54440f6784dc.PNG)

I will see if I can find workaround, but I don't have high hopes.

**Comment by Zhaph** [comment]
Thanks for looking. I'm struggling to get it to behave "more than once" - with the video the macro state would reset when I switched back to the scene and the video starts up again, with the Image Slide Show it seems to stay in a perpetual `Ended` state after the first run? - I.e. I can see the condition flashing green even when the slide show has started back up again.

Thanks for the suggestion about the "Video Has Not Changed" option, I'll use that for this afternoon, as I'm not really doing much too else on the machine running OBS for this one.

**Comment by WarmUpTill** [comment]
> Thanks for looking. I'm struggling to get it to behave "more than once" - with the video the macro state would reset when I switched back to the scene and the video starts up again, with the Image Slide Show it seems to stay in a perpetual `Ended` state after the first run? - I.e. I can see the condition flashing green even when the slide show has started back up again.

You are right.
I checked the code and state is just never set back to OBS_MEDIA_STATE_PLAYING even when the source is reactivated.
This seems to be an inconsistency on OBS' side, so there is not much I can do on the plugin's side unfortunately.

I will probably not merge these changes yet, as currently this seems to be rather confusing.

I will leave the issue opened as it might get fixed in future on OBS side.

**Comment by Zhaph** [comment]
I'll raise an issue with OBS later ;)

Thanks for your help.

**Comment by Zhaph** [comment]
Wow. Thank you @WarmUpTill, you're [massively ahead of the game](https://github.com/obsproject/obs-studio/pull/7335) here - raising a PR over there is much better than me raising an issue later.
