### ISSUE TITLE
Plugin not showing up on OBS Tools

### ISSUE THREAD

**Issue by eduardochaves1** [WarmUpTill/SceneSwitcher#536]
**Describe the bug**
First time I used this plugin all worked well, but after I uninstalled my OBS and tried to download it again using the `.deb` package it isn't showing up on OBS tools list. I checked the OBS source files and the plugin files are there, tried uninstalling OBS & plugin and installing again, reboot, nothing works and I have no idea why it is happening.

**To Reproduce**
1. Try to install the plugin with the `.deb` package using Linux Pop_Os

**Expected behavior**
The plugin won't show up on OBS Tools list

**Logs**
[Logs](https://obsproject.com/logs/VUJxV46Wh7sxIoML)

**Version information**
 - OS: Pop!_OS 22.04 LTS
 - OBS Version: 28.0.1 (64 bit)
 - Plugin Version: 1.0.0

**Comment by WarmUpTill** [comment]
Installing plugin's on Linux can be quite complicated unfortunately if you are not for example using the flatpak or snap version.
The easiest way I have found to check for the correct location to put the files is orient myself at location of the default plugins OBS is shipped with.

For example what does the following command return for you?
`find -name obs-transitions.so 2>/dev/null`

Examples of valid install paths on various Linux platforms are:
```
/usr/lib/obs-plugins/
/usr/lib/x86_64-linux-gnu/obs-plugins/
~/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/
~/.local/share/flatpak/app/com.obsproject.Studio/x86_64/stable/active/files/lib/obs-plugins/
/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/active/files/lib/obs-plugins/
```

**Comment by eduardochaves1** [comment]
> if you are not for example using the flatpak or snap version.

I tried installing the Deb and Flatpak versions and both of them didn't work. I didn't know there was a snap version, so I installed it here and now it is working fine. In snap version it is sill on OBS 27. versions. Maybe the 28. may have some incompatibilities with Linux distros and this plugin. Thank you for the advice!
