### ISSUE TITLE
Scenes JSON clogged by the scene switcher

### ISSUE THREAD

**Issue by Ithilion** [WarmUpTill/SceneSwitcher#539]
**Describe the bug**
I had an issue where somehow the `macroActionConditionSplitterPosition` and `macroListMacroEditSplitterPosition` lists in the scenes collections JSON would get filled with a huge amount of `pos` variables (making the files several megabytes in size). This would in turn make scene collection switches extremely slow. Emptying those lists restored the usual performance.

**To Reproduce**
N/A (don't know how this happened)

**Expected behavior**
Those lists don't get filled with infinitely repeated variables

**Version information**
 - OS: Win 10 latest x64
 - OBS Version 28.0.1
 - Plugin Version 1.18.0

**Additional context**
I use the `--multi` switch and launch multiple instances of OBS at the same time, maybe that's what caused it?

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
Would you be able tos hare one of these scene collection files with me?

**Comment by Ithilion** [comment]
Ok so i did a few more testing and i noticed a few aspects of this bug:
- It has nothing to do with `--multi`, as it also happens on with a single OBS instance
- When you switch let's say from collection A to collection B, what happens is the entire content of those lists from collection A is appended to the existing content of collection B. As you can imagine, going back and forth between scenes will then cause an exponential growth of data.

**Comment by WarmUpTill** [comment]
I see .. thank you very much for the hint! :)
I version with a fix should be available here in a few minutes:

https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3093591727

The problem was that when settings were loaded the old splitter sizes were not discarded.
Each time the scene collection is changed the loading of settings is triggered leading.

**Comment by Ithilion** [comment]
Great! Is the fix also going to sanitize existing JSONs after updating? What may be happening is that people are experiencing terrible performances and have no idea where that's coming from

**Comment by WarmUpTill** [comment]
It should get cleared as soon you open, but more importantly close the advanced scene switcher window at least once, as this triggers the values to be written again.

**Comment by Ithilion** [comment]
Yeah i was almost editing my message adding that i found that out. That should be enough for everyone hopefully.
