### ISSUE TITLE
Bug on video macro with browser source not updating

### ISSUE THREAD

**Issue by ronerfbpr** [WarmUpTill/SceneSwitcher#551]
**Describe the bug**
Hi i'm having a bug after OBS 28 update with the video macro when using a browser source.
It's not updating when the source is not visible, it seens this bug is happening only with the browser source.
If i choose pattern match and look on show match, the source is frozen on the last refresh when it was visible.

**To Reproduce**
1.Create a scene with a browser source with some dynamic content like a clock
2.Create another scene and select it as the active scene
3.Create a Video Macro
4.Select the browser source
5.Select match pattern
6.Select show match
7.This show match is not uptading the browser source

**Expected behavior**
Update browser source to look for a match even with not visible sources

**Logs**
https://obsproject.com/logs/KfFZCe0csGKw0ckp

**Version information**
 - OS: Tested on Windows 10 and 11
 - OBS Version 28.0.0.2
 - Plugin Version 1.18.0

**Additional context**
The browser option disable source when not visible is NOT checked

**Comment by WarmUpTill** [comment]
Not rendering sources that are not visible is an intended feature of OBS.
To work around this limitation in combination with the video condition you can open windowed projector of the source to make sure it is being rendered all the time.

![Projector](https://user-images.githubusercontent.com/19472752/193106961-70f2337b-cf83-4ae0-8bab-9a0b5588e0d9.png)

**Comment by ronerfbpr** [comment]
> Not rendering sources that are not visible is an intended feature of OBS. To work around this limitation in combination with the video condition you can open windowed projector of the source to make sure it is being rendered all the time.
> 
> ![Projector](https://user-images.githubusercontent.com/19472752/193106961-70f2337b-cf83-4ae0-8bab-9a0b5588e0d9.png)

First thank you very much for your reply.

I tried this workaround but with windowed source projector i get a blank window, it only works with windowed scene projector then it refreshes for me.

So you saying this is a new intended OBS behavior after v28 ? because it used to work before

**Comment by WarmUpTill** [comment]
>I tried this workaround but with windowed source projector i get a blank window, it only works with windowed scene projector then it refreshes for me.

Hm, that seems strange - not sure what could lead to this.
Maybe an OBS bug?

>So you saying this is a new intended OBS behavior after v28 ? because it used to work before

I am not aware of any changes in OBS 28 in that area.
The limitation regarding invisible sources not being rendered has been in place even before OBS 28.
It was already the case when the "Video" tab was first introduced as well.
