### ISSUE TITLE
What is the latest release version compatible with 27.2.4

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#565]
I noticed that the latest version has a minimum version of 28. I have plugins not compatible with 28 yet so I'm stuck on 27.2.4. What is the latest release version compatible with 27.2.4?

**Comment by WarmUpTill** [comment]
The last version compiled for OBS 27 is 1.17.7.
https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.17.7

**Comment by nospam2k** [comment]
Thx
