### ISSUE TITLE
Darkness indicator

### ISSUE THREAD

**Issue by SomeoneElsexx32** [WarmUpTill/SceneSwitcher#568]
**Is your feature request related to a problem? Please describe.**
I would like to have the option for a "darkness level"

**Describe the solution you'd like**
A macro option with a darkess level. if the image is too dark it triggers the macro.

**Describe alternatives you've considered**
I've tried the compare feature with a full black image and something like 0,99 similarity but it will only trigger when its set to 100% and then it's like always triggering 😅

**Additional context**
I'm using it with cameras and when the light is too dark the camera obviously produces more noise and triggers the change detection. 

I hope my description was clear :)

**Comment by WarmUpTill** [comment]
I implemented this feature on the linked PR - let me know if it works as expected.

![BrightnessCheck](https://user-images.githubusercontent.com/19472752/195993806-eb0dab5a-a67e-4555-b528-fe068e2870ed.PNG)

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3256151140

**Comment by WarmUpTill** [comment]
I merged the changes for now - let me know if you find any issues :)

**Comment by SomeoneElsexx32** [comment]
Thanks a lot! I'm sorry i haven't had the time to implement that into my project yet :) but i will report if i find any problems.
