### ISSUE TITLE
Missing settings on new install

### ISSUE THREAD

**Issue by LinuxIsCool** [WarmUpTill/SceneSwitcher#577]
![image](https://user-images.githubusercontent.com/31582215/199150245-a263efaa-c69b-44e7-ae6c-849b87c49fa4.png)

Trying this plugin for the first time. The settings do not look like they do in the wiki.

OBS version: 28.1.0 Installed on Pop!OS Linux using flatpack

$ flatpak install com.obsproject.Studio.Plugin.SceneSwitcher
Looking for matches…
        ID                                         Branch Op Remote  Download
 1. [✓] com.obsproject.Studio.Plugin.SceneSwitcher stable i  flathub 151.8 MB / 152.0 MB

Installation complete.

**Comment by WarmUpTill** [comment]
The screenshot you shared is from the built-in OBS plugin "_Automatic_ Scene Switcher".
You will have to select "_Adavanced_ Scene Switcher" in the tools menu.

Or does the latter not show up for you?
If that is the case please share a log file of an OBS startup.
