### ISSUE TITLE
Title in installers don't get updated.

### ISSUE THREAD

**Issue by CodeYan01** [WarmUpTill/SceneSwitcher#580]
**Describe the bug**
Installers don't show the correct version.
![image](https://user-images.githubusercontent.com/65320293/200023857-e48a6d1b-8942-4305-b1c7-7c2758a8a4c4.png)

**To Reproduce**
1. Download windows installer from releases or nightly.

**Expected behavior**
Should show the version in the installer title.

**Version information**
 - OS: Windows 10

**Additional context**
https://github.com/WarmUpTill/SceneSwitcher/blob/master/CMakeLists.txt#L3
The version should be set here.

**Comment by WarmUpTill** [comment]
Should be fixed with the linked PR.

**Comment by CodeYan01** [comment]
Thanks!
