### ISSUE TITLE
"OBS's main output" in video macro not working

### ISSUE THREAD

**Issue by Slopz** [WarmUpTill/SceneSwitcher#584]
I tried making OBS show a notification when the output is blank, as I need this on a global basis and not per scene so I set the video match to "OBS's main output" to "has no output" but it doesn't look like it's working for me. I assume that's what "OBS's main output" is for? I haven't found anything in the documentation for it. I also made sure the macro and the notification were working using any other scene.

Running latest OBS and plugin builds on Windows.

**Comment by WarmUpTill** [comment]
The "has no output" option cannot be used for what you are trying to achieve.
"No output" would mean that no image at all - so a "0x0" resolution image - was captured from the selected source.

I don't think that is possible for OBS's main video output.
A blank OBS video output is still a valid, but completely black, image.

Maybe you could check for an exact match of a completely black image instead?
Or maybe you could check if the output has not changed for a certain amount of time?

I will add a note to the wiki.
