### ISSUE TITLE
When plugin v.1.19.2 is active OBS Studio 28.1.2 hangs if I switch to another scenes collection

### ISSUE THREAD

**Issue by Seamas73** [WarmUpTill/SceneSwitcher#586]
**Describe the bug**
When Advanced Scene Switcher v.1.19.2 is active OBS Studio 28.1.2 hangs if I switch to another scenes collection

**To Reproduce**
1. Set in plugin settings "check switching conditions every" field to 4700 milliseconds or less and turn off system tray notification, or set "check switching conditions every" field to 8000 milliseconds or less and turn on system tray notification. Then start plugin (from settings window, or from doc panel).
2. Create another scenes collection, fill it with some scenes with different sources. Set in new scenes collection in plugin settings "check switching conditions every" field to 4700 milliseconds or less and turn off system tray notification, or set "check switching conditions every" field to 8000 milliseconds or less and turn on system tray notification. Then start plugin (from settings window, or from doc panel).
3. Switch to previous scenes collection from scenes collections menu.
5. OBS Studio hangs, and not responding: name of scenes collection in OBS window title does not change to selected scenes collection name, scenes and sources doc panels are clear. Sometimes error appears on second, third, fourth switch etc. When in both scenes collection "check switching conditions every" field is set to 8100 milliseconds and system tray notification turned on, error doesn't appear, but OBS Studio crashes on exit. Also error doesn't appear if Advanced Scene Switcher is off in both scenes collection.

**Expected behavior**
Switching between scenes collections without hangs and crashes

**Logs**
Below

**Version information**
 - OS: Windows 10 Pro 22H2;
 - OBS Version: 28.1.2;
 - Plugin Version: 1.19.2
[2022-11-15 14-10-16.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10013133/2022-11-15.14-10-16.txt)

**Comment by Seamas73** [comment]
I assume the cause of this bug is that the plugin stops and then starts again while I switch between scenes. Maybe bug disappears if you make plugin settings global, not scenes-collection-depengdent.

**Comment by Seamas73** [comment]
Update: OBS also hangs if I switch between scenes collections right after any change in plugin settings.

**Comment by Seamas73** [comment]
I tried to switch between scenes collections with new version of plugin several times, even reduced value in "check switching conditions every" field to 2000 milliseconds and keep system tray notification on - OBS doesn't hang or freeze. Then I closed OBS and it crashed (after changing plugin settings). I started OBS again and switched between scenes collections another several times (keeping plugin settings unchanged) - no freezes again, hurrah! Then I closed OBS, and it closed without crash.

**Comment by Seamas73** [comment]
But when I make changes in plugin settings OBS keep crashing on closing.

**Comment by WarmUpTill** [comment]
Can you please share the crash log(s) just so I can check that the plugin is not causing the crash?
Thanks!

**Comment by WarmUpTill** [comment]
Thankfully none of the crashes seem to be caused by the scene switcher.
I will merge the changes to the master branch.

Thanks for the quick feedback!

Just FYI:
Almost all of the crashes are caused by "tiny_tubular_task_thread".
So I guess if you remove this plugin your crashes will likely all be gone.

**Comment by Seamas73** [comment]
> Almost all of the crashes are caused by "tiny_tubular_task_thread".
> So I guess if you remove this plugin your crashes will likely all be gone.

Fast googling shows that "tiny_tubular_task_thread" can refer to any third party plugin. But a clean reinstallation of OBS and sequential addition of third party plugins in it to check which one crashes the program on exit will take too much time. So I'll wait, maybe OBS developers will fix the cause, or, at least, shows, wich plugin or plugins causes crash (I sent them bug report).
