### ISSUE TITLE
Why have to make for everything so difficult?

### ISSUE THREAD

**Issue by laszkris** [WarmUpTill/SceneSwitcher#587]
Why have to make for everything so difficult????!!! Where is the settings for if i want only mondays to use the switch? The old version was a perfect, this is a big sh@t!

**Comment by WarmUpTill** [comment]
Just uncheck the following checkbox on the General tab.
![](https://user-images.githubusercontent.com/19472752/200110831-02c6dce9-4f20-4c91-be41-e8d9fdebcb55.PNG)

**Comment by laszkris** [comment]
thx
