### ISSUE TITLE
Fail to build with procps 4.0.1

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#590]
Hi @WarmUpTill,

The procps project is changing the libprocps library.  The old API found in libprocps8 is very different to what is found in libproc2. Consequently, SceneSwitcher will not build from source soon on Debian. Please, check this bug[1] in Debian Project.

[1] https://bugs.debian.org/1024223

I made a test in my machine and I confirm that plugin will not build with the new libproc-2-dev, libproc-2 and procps, all available here[2].

[2] https://deb.debian.org/debian/pool/main/p/procps/

Thanks in advanced.

Cheers,

Eriberto

**Comment by WarmUpTill** [comment]
Thanks for the heads up!
I will try to look into this on the weekend.

**Comment by WarmUpTill** [comment]
The linked PR should be compatible with libproc2.

**Comment by eribertomota** [comment]
Worked fine in my machine. I just sent it to 'experimental'[1] release in Debian to test in other architectures because experimental is using procps 4.0.1. I will see the results tomorrow. Thanks!

[1] https://buildd.debian.org/status/package.php?p=obs-advanced-scene-switcher&suite=experimental

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

The build was successful over amd64, armel, armhf and i386 on Debian Experimental[1]. Over other archs, the system was not able to build because procps 4 is failing[2] (this is not a problem in your plugin).

Please, go ahead and commit the PR.

[1] https://buildd.debian.org/status/package.php?p=obs-advanced-scene-switcher&suite=experimental
[2] https://buildd.debian.org/status/package.php?p=procps&suite=experimental

Cheers,

Eriberto

**Comment by WarmUpTill** [comment]
Thanks for the confirmation!
PR is merged.
