### ISSUE TITLE
Tabs after update (No Scene Sequence)

### ISSUE THREAD

**Issue by sashaorbeat** [WarmUpTill/SceneSwitcher#592]
Hello dear @WarmUpTill,
After update the OBS and the plugin all tabs disappeared except for Macro. Scene Sequence cannot be configured.
<img width="749" alt="Снимок экрана 2022-11-19 185425" src="https://user-images.githubusercontent.com/10693016/202860011-a63e5da6-5624-4682-8625-e82f4a96d243.png">

Could't find any instructions to solve this issue

 - OS:  Windows 11 Pro (21H2 22000.1219)
 - OBS Version 28.1.2
 - Plugin Version 1.19.2
 
Best, Alex

**Comment by WarmUpTill** [comment]
Uncheck this checkbox:
![](https://user-images.githubusercontent.com/19472752/200110831-02c6dce9-4f20-4c91-be41-e8d9fdebcb55.PNG)
