### ISSUE TITLE
Allow more types in “Scene item visibility” action

### ISSUE THREAD

**Issue by Bombe** [WarmUpTill/SceneSwitcher#594]
Hi!

In the scene item visibility action I’d like to be able to hide everything, not only “any colour source,” ”any browser,” or “any media source.” Alternatively “any scene” would be great. :)

Thanks!

**Comment by WarmUpTill** [comment]
The linked PR should implement the functionality to allow you to select all possible source types in the scene item visibility action.
A build with this change should be finished in a few minutes and be available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3506241066

Please let me know if this works as you expect! :)

**Comment by Bombe** [comment]
It does work exactly as I would expect it to! 🎉

Thank you very much!
