### ISSUE TITLE
Time Based Scene changes option not showing

### ISSUE THREAD

**Issue by Vidiem** [WarmUpTill/SceneSwitcher#596]
Time Based Scene changes option not showing this version. how to enable this option

**Comment by WarmUpTill** [comment]
I assume you are referring to the old "Time" tab.
To re-enable it imply uncheck this checkbox on the General tab:
![](https://user-images.githubusercontent.com/19472752/200110831-02c6dce9-4f20-4c91-be41-e8d9fdebcb55.PNG)

This is also listed in the wiki FAQ:
https://github.com/WarmUpTill/SceneSwitcher/wiki/FAQ

Alternatively you could use the [Date condition](https://github.com/WarmUpTill/SceneSwitcher/wiki/Date-condition) in combination with macros.

Hope that helps! :)
