### ISSUE TITLE
1.19.2. crashes OBS 28.1.2 on Win10 x64

### ISSUE THREAD

**Issue by Fred-DTV** [WarmUpTill/SceneSwitcher#599]
**Describe the bug**
The current release makes my OBS crash in multiple different ways. The 1.18 version works fine.

**To Reproduce**
There are different scenarios in which OBS crashes, some of them are:
1. Opening the advanced scene switcher settings
2. Changing active media file (I have a media macro)
3. Changing scene collections or any other ressource intense task (My PC is overpowered, so never had that)

**Logs**
Logs are attached, however, this is really weird, because OBS doesn't give me a crash report in this case only the regular log file

[adv-ss-Github2022.11.25.10.42.23.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10090475/adv-ss-Github2022.11.25.10.42.23.txt)

[2022-11-25 10-38-23.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10090479/2022-11-25.10-38-23.txt)

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
A similar problem was recently reported in #586.

Can you please test if the following build already solves the problem?
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3517413978

**Comment by DachsbauTV** [comment]
Hey Till

Unfortunately it still crashes :/

**Comment by Fred-DTV** [comment]
Hi @WarmUpTill 

After further testing I was able to find some more hints qhat could cause this:
1. The problem seems to be an issue how the plugin uses the RAM. Everytime I am having the issue i can see how the RAM usage on my PC ramps up real fast all the way to the max of 64GB as soon as I hit the start button of the plugin.
2. I was able to find the macro which includes the reason for this. It is the one with "any media in scene". I've attached my setup file.
3. The media item seems to load a significant amount of memory when used. Even when just one media file is chosen for a trigger (no matter if "ended" or "time remaining shorter") It will already block a GB of RAM, for a video which is just a couple of seconds long. So I am assuming, that the "any media" option just loads all of the media items in at the same time, which causes the massive rise in RAM usage.

I hope you can work with this info

[adv-ss-Downdays-2023.02.16.17.08.22.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11017389/adv-ss-Downdays-2023.02.16.17.08.22.txt)

**Comment by Fred-DTV** [comment]
Maybe it could be solution to go from "any" to "current playing" (there is a OBS variable for it) ?

**Comment by WarmUpTill** [comment]
I _believe_ this was finally fixed with 1.27.0 (or newer) as a major spike in RAM usage was fixed when using the "any" / "all" option in the media condition.

So, I will close this for now.
Feel free to re-open, if you are still facing the issue.
