### ISSUE TITLE
Missing Tabs on new version

### ISSUE THREAD

**Issue by kpdillon** [WarmUpTill/SceneSwitcher#604]
I only see General and Macro Tab, other tabs are no longer displaying.
<img width="900" alt="Screen Shot 2022-11-29 at 9 29 46 AM" src="https://user-images.githubusercontent.com/4956145/204572367-396794aa-7baa-4937-87b5-a0e3ab057e8d.png">

**Comment by nacalai** [comment]
You can enable them in General tab again

**Comment by kpdillon** [comment]
Got it, thanks,
