### ISSUE TITLE
Difficulty with and crash when using "Select area"

### ISSUE THREAD

**Issue by vertigo220** [WarmUpTill/SceneSwitcher#608]
**Describe the bug**
This is a two-part issue. The first isn't a bug but a design issue, which is that the window that opens to select an area is small, only showing a small portion of the video, and even when enlarged (which has to be done manually, as there's no maximize or fullscreen button) to take up the whole screen, still doesn't show the entire video. The second issue, which is a bug, is that it crashed twice on me while working with the select area function. First, it crashed when resizing the window. Then, it crashed when I had an area selected and tried selecting a new area (would be easier to be able to resize, move, and cancel the current selection) starting within the already selected area.

**To Reproduce**
1. Add a macro
2. Add a condition
3. Check "Perform check only in area" and click "Select area" button
4. Resize window (only crashed once, so not sure how repeatable it is) or select an area then select a new area (same, also not sure if it mattered that when I was selecting a new area I started dragging from a point within the already selected area)

**Expected behavior**
Don't crash

**Logs**
It only logged the first crash, and verbose logging wasn't enabled since I wasn't expecting a crash.
[Crash 2022-11-29 20-51-47.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10127919/Crash.2022-11-29.20-51-47.txt)

**Version information**
 - OS: Win 10
 - OBS Version 28.1.2
 - Plugin Version 1.19.2
 
**Additional context**

**Comment by WarmUpTill** [comment]
The crashing should be fixed in the inked PR.
Same build also mentioned in your other issue should contain those fixes.

I would appreciate if you could give this a try and report back if you still observe crashes.

**Comment by vertigo220** [comment]
I was waiting for a new release with this PR in order to test this and only just noticed the actions/runs link in the other issue. I'm unfamiliar with that. Am I supposed to use the artifact?

**Comment by WarmUpTill** [comment]
Sorry for not explaining this better.
Yes, the intention was to use the build artifacts of the linked PR.

But the changes have since been merged to the master branch so you could also simply use the latest build to make sure all recent fixes are included:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3918661604

I plan on releasing a new build soon(ish).
If you prefer to wait that is completely fine :)

Let me know if you have any questions!
