### ISSUE TITLE
Improve "Select area" feature for high resolution (video doesn't fit in window, making selection difficult)

### ISSUE THREAD

**Issue by vertigo220** [WarmUpTill/SceneSwitcher#609]
**Is your feature request related to a problem? Please describe.**
The window that opens to select an area is small, only showing a small portion of the video, and even when enlarged (which has to be done manually, as there's no maximize or fullscreen button) to take up the whole screen, still doesn't show the entire video. And after selecting an area, it would be easier to be able to resize, move, and cancel the current selection.

**Describe the solution you'd like**
Add the ability to shrink the video to fit the window, and add an option to do so automatically as well as a button to do it manually. Another possibility is to add a zoom function. Add a maximize button to the window so it doesn't have to be manually enlarged. Consider also adding a fullscreen button.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by WarmUpTill** [comment]
Thanks for creating the issue!

I agree that the dialog for selecting the area / showing the matches is in a pretty rough state at the moment.
I will try to improve it at least a bit, but I cannot promise I will get around to it soon, unfortunately.

**Comment by WarmUpTill** [comment]
In the linked PR a maximize button was added and initial the size of the preview dialog window will now be inherited from the size of the scene switcher's settings window.

Scaling the image was not yet implemented.

A build with these changes should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3719933898
