### ISSUE TITLE
Run macro (by button or other macro) - if (query) not works - Bug?

### ISSUE THREAD

**Issue by dasToshy** [WarmUpTill/SceneSwitcher#611]
Sorry, my english is very bad. So i must use often Translater (google). please ask me, if you not understand or i must write other thinks. I only speaks german.

first: Thanks for your great plugin.

*** Bug or /and just a misunderstood function? *** (checkbox in macro list paused automatic working, oder deactivat it totaly?, b

Screenshots with "alt" od "print + alt" not works at my obs, black screen on place of obs. (i use obs by remote control from other maschine)

i use ofter 20 macros

If create an macro with an "if query" like "date -- monday" (an real day is wednesday) it works correct if i activate with the checkbox (the commands to be executed below in the macro do not start on wednesday). if i change the "if query" to wednesday,the comands will be executed. (if checkbos of macro is activated / checkbox in macrolist)

Error / Bug:
a)
But if i use in other macro the "macro - run" command to start this date macro (over button or ofter automatic start,--> one macro start other macro) The  query "if" is ignored and the execution commands are always executed.

**To Reproduce**

1. create 2 macros. (checkbox of both macro is activated / checkbox in macrolist)
2. first macro run 2nd macro.
3. the second macro uses an if query that does not apply (false)
4. are always executed.

b) 

if macro paused / deactivated in macro list an macro 1 starts macro 2 by "macro run command) the commands never executed (if date is set to wednesday, and today is wednesday, the commands are not executed.
i dont know if this is correct or not. i think, die checkbox in list is only vor "automatic macro start", not for manually or "marco run by other macro".

**Expected behavior**

**Logs**
Please provide a log of your issue with verbose logging enabled (See General tab of the plugin).  
See [here](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/) for a description where to find the log files and how to share them.  
Please share the currently used plugin settings by exporting them them to a file (See General tab of the plugin).  

**Version information**
 - Windows 10
 - OBS Version 28.0.3
 - Plugin Version 1.19.1 and 1.19.2

**Additional context**

----->
----->
----->

1st addendum. I installed obs on a second local computer and the error also occurs there.

![bug obs 1](https://user-images.githubusercontent.com/109924400/204941780-4fb5852c-76d0-4026-8a8a-2e02beef3b58.jpg)
![bug obs 2](https://user-images.githubusercontent.com/109924400/204941785-89026e03-c156-45ba-93fe-c5acbeca5744.jpg)
![bug obs 4](https://user-images.githubusercontent.com/109924400/204941789-1b2e6fcd-ad1e-4d2b-9fab-86b5f1fdc866.jpg)
![bug obs 3](https://user-images.githubusercontent.com/109924400/204941791-99607efc-8cb2-4481-be6a-5d5794e357cb.jpg)

Here screenshots of "one Problem".

the other problem actually i cant create short cut. no keyboard on remote pc an macro a little more complex to create fast at local computer.

2nd addendum.

I'm testing a lot of possibilities.
I try to take screenshots these days.
With the second problem, I noticed that some commands are executed when a macro is switched off in the macro list (no check mark in the box), others not.

I call e.g.
"media - stop - vlc..." .... and then a "run xxx.wav", the sound is never played.
I call
"run xxx.wave" and then "media - stop - vlc", the sound will be played.

Both with "kept tick" in the macro list.
I activate the macro with a tick, the sound is always played.

Something isn't quite right there.

3nd addendum.

a) i can hear the audio
![bug obs 5](https://user-images.githubusercontent.com/109924400/204943876-f9bf7ede-d2af-475d-a60f-5ba74ef588ae.jpg)

b) i can't hear the audio
![bug obs 6](https://user-images.githubusercontent.com/109924400/204943890-34cb7fac-f1c5-48b2-86b7-2b792cc76207.jpg)

c) i can hear the audio
![bug obs 7](https://user-images.githubusercontent.com/109924400/204943898-72e9618e-1bf4-4ed6-82fe-05e28ecc9bd4.jpg)

for a) and b) I just changed the order

**Comment by WarmUpTill** [comment]
>But if i use in other macro the "macro - run" command to start this date macro (over button or ofter automatic start,--> one macro start other macro) The query "if" is ignored and the execution commands are always executed.

That is intended.
The conditions are not checked if you explicitly tell the plugin to run the actions a specific macro using the "Macro" action.
If you want to reuse the conditions of another macro you can use "Macro" condition type.

>if macro paused / deactivated in macro list an macro 1 starts macro 2 by "macro run command) the commands never executed (if date is set to wednesday, and today is wednesday, the commands are not executed.
i dont know if this is correct or not. i think, die checkbox in list is only vor "automatic macro start", not for manually or "marco run by other macro".

A macro being paused does indeed also affect the "Run" action of the "Macro" action type.
A paused macro will not execute its actions.

But this is indeed a bit inconsistent at the moment, as the first action of the macro will be executed regardless of if the macro is paused or not.
I will adjust this so _none_ of the actions are executed if a macro is paused.

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3609007044

Does that answer your questions?

**Comment by dasToshy** [comment]
Yes, that helps. Thank you very much.

Especially the inconsistency had irritated me when it worked. Now I understand a little more.

----------

However, I would like to talk a bit more about the matter. I hope this is allowed here.

Due to my bad English I'll try to explain it like this:

* If you want to create something more complex sequences (e.g. a completely automatic changing program sequence with different changing conditions), this is not easy. "if - then - else" conditions, especially nested conditions, are difficult to replicate.

* Example to emulate in macros (letters as example for conditions) (my macro queries are considerably more complex)

if (a=1 and b=1) OR ((c=1 and d=1) and (a=0 and b=0))

else

final

* This cannot be reproduced directly in macros, since there is probably NO "Else" or "ElseIf".
This is not so bad in itself, I can theoretically reproduce it (split into different macros).

"Problem:
a)
It is not known how the macro conditions ("if") are processed internally.
I can use AND and OR, but when multiple AND and OR are used I don't know how to handle them. I'm already testing here. An explanation from the programmer would be helpful here. (how the AND and OR are linked logically / order of processing)

b) I'm trying to easily split nested conditions into macros.
In a macro A I check the first condition (c=1 and d=1)
If this applies, I call a second macro B and want to check (a=0 and b=0).
Then I check the conditions again in another macro.
All this to safely process "else" or nested "AND / OR" queries.

I do this because it happened that everything was running for a few days and then the process got stuck because the dependencies were too complex just to replicate it.

(now I can fix some issues at least due to the fixed inconsistency)

* issue:
If I call the macro via MACRO RUN, the IF query is not processed (you explained that this is intentional).
This is problematic, but I can theoretically avoid it (workaround).
Oh, it's problematic that a paused macro is NOT executed by "marco run". Because it may be that some MACros only start with "run", but should NOT be processed automatically. Ensuring this via "security variables" / "status variables" is quite complicated.

c)
Suggestion / request:

Is this possible:
In the future, maybe change the program structure like this:

* "IF" conditions are ALWAYS checked, even with "macro run".
This is not a probelm, because you can always create a macro that has no conditions to check. This would give more programming possibilities and simplify everything
* "macro run" should be allowed to run a macro even if it is paused by checkbox. This is also NOT a problem, since everyone can query the "Paused" status themselves and the Marco would only be executed if it was started with "run".

This change shouldn't require much work (I hope) and could allow for much more complex macro control.

[I'm building a playlist that changes by day and time and pays attention to different conditions, such as the end of the playlist, individual titles and other things. This is hardly possible or not possible at all if the "if" checks are not possible with "macro run" or paused macro. Bypassing this via "auxiliary variables" is really time-consuming and triggers other problems.]

Maybe this will be possible in the near future. It shouldn't be a big change for users either.

What do you make of it?

Thank you very much for your work and help so far.

greeting
toshy
ps. I hope you can understand my text sufficiently.

**Comment by WarmUpTill** [comment]
>It is not known how the macro conditions ("if") are processed internally.
I can use AND and OR, but when multiple AND and OR are used I don't know how to handle them. I'm already testing here. An explanation from the programmer would be helpful here. (how the AND and OR are linked logically / order of processing)

The conditions are evaluated from top to bottom.
So the following example would be `(((scene AND Media) OR NOT Date) AND File)`
![Example](https://user-images.githubusercontent.com/19472752/206177533-6685fc48-b11d-49e9-894c-f69b435b7ed2.PNG)

>"IF" conditions are ALWAYS checked, even with "macro run".
This is not a probelm, because you can always create a macro that has no conditions to check. This would give more programming possibilities and simplify everything

This would probably break quite a few existing setup so I would rather avoid it.
You can simply achieve the same effect this would have by checking the conditions of the macros explicitly at the end of which ever macro you are trying to run.

For example, this would only run the actions of "Macro that is executed" if the conditions of "Macro that is executed" are true.
![Example2](https://user-images.githubusercontent.com/19472752/206178749-c794780a-c496-4d7d-9ebe-db84fd28a73e.PNG)

>"macro run" should be allowed to run a macro even if it is paused by checkbox. This is also NOT a problem, since everyone can query the "Paused" status themselves and the Marco would only be executed if it was started with "run".

But this would make it inconsistent with the other action types (Sequence, Random) where paused macros are not executed.
To solve your problem you can create a proxy macro that only handles the execution of the actions but has no conditions itself.

For example the actions of macro "Original" can be moved to a new macro "Proxy".
![Step1](https://user-images.githubusercontent.com/19472752/206180256-768b1788-e44c-4ed3-a54e-8b0698d5019a.PNG)
![Step2](https://user-images.githubusercontent.com/19472752/206180264-eac198ea-68db-4e5f-b150-0599f342f68b.PNG)

In "Original" you can now simply run "Proxy".
![Step3](https://user-images.githubusercontent.com/19472752/206180285-1ff9a2c1-b94b-4cc0-8a60-aa3f3b727a43.PNG)

I hope that helps!
