### ISSUE TITLE
Bug "if Date" / "match behaviior" - with a lot of macros only every second "run" is executed

### ISSUE THREAD

**Issue by dasToshy** [WarmUpTill/SceneSwitcher#621]
Windows 10
    OBS Version 28.0.3
    Plugin Version 
    from hier https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3609007044)
 
Hello.

Next Problem

If i use "date" and "repeat loop" it works fine, if i use only one macro. every loop-time (every 30) i can hear a audio.
but if i use a lot of macros (see my list on image) only every 2nd call works. (every 60 seconds).

![bug obs 8](https://user-images.githubusercontent.com/109924400/206093718-7ffd651f-e7a2-4442-b6d3-fb3a589ebb10.jpg)
![bug obs 9](https://user-images.githubusercontent.com/109924400/206093721-6746ed3e-8caa-4bfc-adec-15d6fe239f6e.jpg)

now i import my macro list on an other pc (without scenes, pc with obs i use only for this bug).
there exist same problem.

if i upload here my export data from your plugin, can i or u later delete this file from this website?

**Comment by dasToshy** [comment]
[adv-ss-Telegram - Zusatz.Info - TV-Stream-2022.12.07.05.49.57.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10173079/adv-ss-Telegram.-.Zusatz.Info.-.TV-Stream-2022.12.07.05.49.57.txt)

with this macro list on one pc every 2nd time comes a audio / sound.

on the other pc most every 5-20 times (of loops) it comes a sound (run not works)

If i paused all other macros (only unpaused the "Macro 1" macro) i have the same problem. (i test with loop with 10 second in other pc)

**Comment by dasToshy** [comment]
I figured out something through a lot of testing and thinking, the problem occurs depending on the setting from this screensho
![bug obs 10](https://user-images.githubusercontent.com/109924400/206101157-68951172-713e-42b8-8b8b-a5d9a292e536.jpg)
t.
The commands will not be executed if the time for the scene change has not yet been reached.

**Comment by WarmUpTill** [comment]
>I figured out something through a lot of testing and thinking, the problem occurs depending on the setting from this screenshot

That setting is basically doing what you described.
If there was a match with the last X seconds do not perform any other actions.

I think the translation does not really fit any more when comparing to the English one "After a match don't perform actions for ...".

So I think if you set this value back to 0 seconds the problem will be gone.

**Comment by dasToshy** [comment]
okay.

but the text "nach einem automatischen Scenenwechsel" means in english "after an automatic scene change".

This means that the function should refer to a SCENE CHANGE.
But the macros are NOT processed after a scene change.
The time specification refers to each loop pass and each execution.
The setting at the top of the "General" tab (300ms) has no effect at all because the macros are NOT processed every 300ms.

I've been able to narrow down the problem now, just haven't put it online yet. it also occurs to me now if i remove ALL macros except the one for testing.

One of the two settings on the page is either useless or one is not working properly.

show:
no scene changing, no other macros. 
"after an automatic scene change" basically does what the function of "test all conditions" should be.
The execution of the commands is always prevented (regardless of a scene change).

And this is probably not what you planned (it has nothing to do with a change of scenery)

https://user-images.githubusercontent.com/109924400/206243259-af1a2ccc-0b81-4287-92b1-fcc9df4ecaac.mp4

**Comment by dasToshy** [comment]
Regardless of these issues for me, as an OBS beginner, your plugin is wonderful.
It enables (although with a lot of manual work when creating macros) an incredible number of program design options that are otherwise only possible with expensive, huge programs.

Thank you very much for that.

**Comment by WarmUpTill** [comment]
>no scene changing, no other macros.
"after an automatic scene change" basically does what the function of "test all conditions" should be.
The execution of the commands is always prevented (regardless of a scene change).

>And this is probably not what you planned (it has nothing to do with a change of scenery)

The option was added back when macros did not exist yet and the plugin was only focused on scene switching.
That is when the German translation for this setting was added.
The German translation was not updated when macros where introduced to make it clear it not only affects scene switches but all macro actions in general.

I will try to update the German translation of this setting.
