### ISSUE TITLE
Feature Request: Cursor click trigger

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#622]
Hello. I'm making good use of the 'Cursor is in region' trigger. But I wonder if it'd be possible to have a trigger based on a cursor/mouse left-clicking?

My use case is I have an ATEM that feeds its multiview into OBS via a capture card. I then display that ATEM multiview on a Dell touchscreen. Then I've build some macros that if the cursor is in the region of cam 1 multiview it triggers HTTP to tell Companion to switch to cam 1 on the ATEM. Then if the cursor is over cam 2 Companion cuts to cam 2 etc. It's rather cool. However, if you accidentally move the mouse around you end up cutting to cameras by accident. To avoid this I set up another action that moves the mouse back to the previous monitor using a run command. This gets me by. However, trigging based on left-clicking would be a much better method, and allow for simply clicking with a mouse to change cam angles, instead of using a touchscreen.

Also having triggers based on double-clicking would open up a few more opportunities.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

Unfortunately I think this is trickier to implement than it sounds, as I think only the window where the click happened is notified about the event.
But I will try to look into it once I find the time to do so.

**Comment by WarmUpTill** [comment]
I managed to implement the functionality at least for Windows in the linked PR.

![Cursor](https://user-images.githubusercontent.com/19472752/208304471-5200e713-b9f6-4a4c-82a2-f74f6f574866.PNG)

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3725304533

Let me know if everything works as expected! :)

**Comment by BenJamesAndo** [comment]
Wow, you managed to pull it off. Christmas has come early!
I've done some quick testing and it seems to work perfectly. I'll play with it some more tomorrow when I'm at work.
Thank you so much!

**Comment by BenJamesAndo** [comment]
Did some more testing yesterday and I didn't run into any problems. I appreciate your work on this. If you have a donate link please send it through.
