### ISSUE TITLE
Cannot use the same hotkey in multiple macros

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#625]
**Describe the bug**
I'm trying to use the same hotkey in different macros in order to use the hotkey as a toggle

**To Reproduce**
1. Create a macro  with if condition on hokey and source shown and then action to set source to hide.
2. Create a macro  with if condition on hokey and source hidden and then action to set source to show.
3. In settings > hotkeys you will see that two hotkeys with same name are shown instead of just one.

**Expected behavior**
Source should toggle hide and show with every press of hotkey

**Version information**
 - OS: Mac OS Monterey
 - OBS Version 27.2.5
 - Plugin Version 1.17.7

**Comment by WarmUpTill** [comment]
I have implemented the behaviour of combining hotkeys with the same description into a single hotkey with the linked PR.
A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3664801877

Please let me know if everything works as expected!

**Comment by nospam2k** [comment]
I assume this will only be applied to v28 compatible version? If so, I'm going to testing things out soon but it may be a few weeks.

**Comment by WarmUpTill** [comment]
Yes correct, this build is for OBS 28.

**Comment by WarmUpTill** [comment]
Merged the changes to master.
