### ISSUE TITLE
CANNOT INSTALL ON MAC

### ISSUE THREAD

**Issue by oneadamj** [WarmUpTill/SceneSwitcher#650]
When I try to install this plugin I am getting 3 errors. 
1. Cannot verify developer.
2. The.pkg is broken or damaged. 
3. The file cannot be installed on this computer. 

I have tried to install on two different computers and I am having the same issue.
I have turned off my firewall on both computers and nothing has changed.

Please fix as I do need this plugin ASAP! 
Thanks.

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

Just to exclude an incompatibility issue:
Which version of the plugin are you trying to install on which OBS version?

> 1. Cannot verify developer.

Unfortunately, I cannot justify spending 99$ a year to avoid this message from popping up.
So I am afraid this message will have to stay.

> 2. The.pkg is broken or damaged.
> 3. The file cannot be installed on this computer.

I am not sure what is causing this.

As a workaround you could try remove the quarantine flag from the plugins folder by running `xattr -r -d com.apple.quarantine ~/Library/Application\ Support/obs-studio/plugins/advanced-scene-switcher.plugin` in a Terminal.

Or manually install the plugin files to `~/Library/Application Support/obs-studio/plugins` as described in https://github.com/WarmUpTill/SceneSwitcher/discussions/567.

I will try to add the generation of the zip files for manual installation on Mac to the CI scripts.

**Comment by oneadamj** [comment]
-xattr: No such file: ~/Library/Application\

-xattr: No such file:
Support/obs-studio/plugins/advanced-scene-switcher.plugin


[Process completed]



VERSION 29.0.0. When I "install" and search for the plugin I find nothing
except the .pkg.

Looks as if I'm not the only one with this issue.


[image: Screen Shot 2023-01-11 at 9.32.33 PM.png]


[image: Screen Shot 2023-01-11 at 9.30.58 PM.png]



[image: Screen Shot 2023-01-11 at 9.27.52 PM.png]



[image: Screen Shot 2023-01-11 at 9.28.57 PM.png]



Thank you for your help!


- Adam J.

**Comment by WarmUpTill** [comment]
It seems like you accidentally split the command on multiple lines. 
(I guess the formatting might look different on your mail)
The whole command needs to be entered on a single line in the terminal application:

`xattr -r -d com.apple.quarantine ~/Library/Application\ Support/obs-studio/plugins/advanced-scene-switcher.plugin`

In the linked PR I have added the zip files for manually installing the plugin.
The archives can be found here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3863980093
Note that you have to be logged into GitHub to be able to download them.

Let me know if you need assistance!
