### ISSUE TITLE
Stinger transition awareness 

### ISSUE THREAD

**Issue by Supermagnum** [WarmUpTill/SceneSwitcher#652]
**Is your feature request related to a problem? Please describe.**
Introduction scene:
I have a introduction video with music embedded in it. 

Chat scene:
This has a picture as a background and a looping audio file.

I also have a short video without any audio that I use as a stinger, but I  have to build in transparency functions in the stinger clip since it seems that OBS studio doesn't have the ability to fade things in and out of stingers.

**Describe the solution you'd like**
I want OBS to be more "stinger aware",- cross fade both audio and video on the beginning and the end of the stinger. It should be possible to set a time when to start the fading to the stinger for a specific scene if it contains a video clip that ends at a certain time.

It should also be possible to set the time used for fading in or out for the stinger.

**Describe alternatives you've considered**
Do the fading on both start and end of the stinger video in a video editor. Add fading to the end of the introduction video in a video editor.

**Comment by WarmUpTill** [comment]
If I understand your request correctly, you can already achieve this effect with a macro triggering when a stinger transition is started with a combination of "Wait" and "Audio" actions.
So something similar to this:

![Stinger2](https://user-images.githubusercontent.com/19472752/212443171-a5103ccf-c9bf-40c8-9029-95ae10dff383.PNG)

But I assume you might have some more "generic" solution I mind.
(For example, "At start of stinger fade X to 0% over 1 second and 1 second before end of transition fade Y to 100%)
Unfortunately, I don't think something like this is possible with the current OBS API.

------

Just to mention it:
The settings menu of a stinger transition already offers a limited set of audio fade style options:

![Stinger](https://user-images.githubusercontent.com/19472752/212443519-e3cf4d08-45e3-478b-8277-2fd0863a7475.PNG)

**Comment by Supermagnum** [comment]
Thats unfornate.
