### ISSUE TITLE
Cursor click option not in dropdown?

### ISSUE THREAD

**Issue by RoyceRemix** [WarmUpTill/SceneSwitcher#653]
Hello!  I see in the documentation for Cursor conditions that there should be an option for Cursor Click on Windows.  I am on Windows 10, using Advanced Scene Switcher 1.19.2 on OBS 28.1.2 and my dropdown for "Cursor is" only includes "is in region" and "is moving" 
![image](https://user-images.githubusercontent.com/97641735/211807036-c1507ee4-c0f8-4904-90f5-19ccef25e517.png)

Am I doing something wrong maybe?  I tried adding it as an AND after a cursor region condition but it's still not in the list.

**Comment by WarmUpTill** [comment]
You are not doing anything wrong :)
The functionality was simply not yet released, but I decided to update the documentation already.

You can however download the current pre-release version of the plugin if you want to use this functionality:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3863654660

Sorry about the confusion!

**Comment by RoyceRemix** [comment]
Oh sick, that's awesome!  Thanks for continuing to add great functionality!  o7
