### ISSUE TITLE
Feature Request: Image Search & Match Condition

### ISSUE THREAD

**Issue by RoyceRemix** [WarmUpTill/SceneSwitcher#654]
I've used various mouse macro programs that have this functionality, but to have it built into the Advanced Scene Switcher would be pristine!  So the idea is that you would specify a region of the screen for the plugin to watch and search for an image (probably with some level of tolerance to makeup for image/video compression & artifacts).  An example would be looking for a button or piece of text that pops up at a time when you'd want to make a change.  This would be amazing for changing obs layouts based on being in various menus in a game - For instance moving streamer cam to avoid covering up UI elements in menu vs lobby vs gameplay.  Remembering to change each time manually can be hard to do with all the distractions of streaming (think how many streamer have an !overlay command), so to have it automated would be amazing!

A couple programs that have this ability are:
https://www.jitbit.com/macro-recorder/
https://sourceforge.net/projects/pulovers-macro-creator/

**Comment by RoyceRemix** [comment]
Looks like this was abandoned, but perhaps much of the work is done already?
https://github.com/HoneyHazard/PixelMatchSwitcher

**Comment by WarmUpTill** [comment]
That should be possible already be possible using the "Video" condition.
I assume you are particularly interested in the pattern matching:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition#matches-pattern

Let me know if you have any questions! :)

**Comment by RoyceRemix** [comment]
You're amazing!  My fault for not exploring all the conditions more - It works perfectly!  Incredible versatility you've built into this plugin 🙏⭐⭐⭐⭐⭐

**Comment by RoyceRemix** [comment]
One other question about this feature, would it be possible to add to "Video - Matches Pattern" the option to have it match a source?  I have created an obs scenes package that I want to distribute, but it has several match pattern conditions... So if it uses sources for pattern matching, then users could use OBS's Check for Missing Files to quickly relink all the sources upon import, rather than having to manually relink each Matching Pattern file inside the filter individually.

Also I didn't know if this was the best place to ask such things - Do you have a Discord, Twitter, or other place that's a preferred option?  Thank you so much for your time 🙏

**Comment by WarmUpTill** [comment]
>Also I didn't know if this was the best place to ask such things - Do you have a Discord, Twitter, or other place that's a preferred option? Thank you so much for your time 🙏

Asking on GitHub or on the OBS forums is fine. :)

> One other question about this feature, would it be possible to add to "Video - Matches Pattern" the option to have it match a source? I have created an obs scenes package that I want to distribute, but it has several match pattern conditions... So if it uses sources for pattern matching, then users could use OBS's Check for Missing Files to quickly relink all the sources upon import, rather than having to manually relink each Matching Pattern file inside the filter individually.

While theoretically possible, I don't really see this finding much of use and it could potentially cause some confusion.

Maybe you can rework the Macros slightly so you will only have to adjust the path in a single condition?
If you are using the exact same settings for each of the of your "Video - Matches Pattern" conditions you could simply reference it via the "Macro" condition type.

For example:

![Video1](https://user-images.githubusercontent.com/19472752/212743204-37c0e8c1-2866-4373-8d98-f97581e7d14d.PNG)
![Video2](https://user-images.githubusercontent.com/19472752/212743209-c67d25cc-f947-4227-8b45-9b8ddc82c281.PNG)

Especially in the case of the Video condition this also has the upside of saving system resources.
The same "trick" is also used in this example:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Activate-overlay-to-hide-parts-of-the-screen

Let me know if you have any questions! :)

**Comment by RoyceRemix** [comment]
Hello, thanks for the in-depth answer!  I'm afraid each of the macros match different images, but that's okay.  It's not that big a deal, it just made me wonder about the possibility to utilize that media finding feature, but I wouldn't want to cause potential issues with the plugin.  Thanks again for your dedication to this awesome tool!  o7
