### ISSUE TITLE
Cursor Region frame too big crashes

### ISSUE THREAD

**Issue by RoyceRemix** [WarmUpTill/SceneSwitcher#655]
**Describe the bug**
I was building a cursor click region with the preview frame turned on to see the area, and while trying to reduce a value of 1050 to 900, I thought I had drag-selected the number text and was going to be *replacing* it while typing, but i guess it wasn't selected, so i was typing the numbers in front, resulting in it trying to draw a frame 901k tall, which froze and ultimately crashed obs, losing about 15-20 minutes of macro building.

![image](https://user-images.githubusercontent.com/97641735/212001938-257af66e-d038-4f1e-9853-11699f86cd47.png)

**To Reproduce**
Make a "Cursor is in region" condition and type a 6-digit number for X or Y values.  I don't know if the crash would happen if you typed the number with the "Show frame" option turned off, but I had it on at the time.

**Expected behavior**
There should probably be a max range that can by typed, maybe defined by the total combined monitor(s) area? Since you can't click outside of that.

**Version information**
 - OS: Windows 10
 - OBS Version 28.1.2
 - Plugin Version: pre-release fd4476c

**Additional context**
Whoopsie!

**Comment by WarmUpTill** [comment]
Thank you very much for reporting the issue!
I will try to look into it on the weekend.

**Comment by WarmUpTill** [comment]
Should be fixed withe linked PR.
