### ISSUE TITLE
Possible bug with 'FILE' 'Local File' 'Matches' option

### ISSUE THREAD

**Issue by SuitYourself** [WarmUpTill/SceneSwitcher#662]
Hi @WarmUpTill , during the 'beta' (when you added the left click cursor option) my macros were working.
I've just updated to your latest version (1.20.0) and now they don't.
I think there is a problem in  the 'File' > Local File > filename.txt' Matches' VALUE IN BOX.

When running it picks up the left clicking (macro box glows green) but the expression below (And File) doesn't glow green, so I presume that is what isn't working now.

![image](https://user-images.githubusercontent.com/25052021/213183559-d1d5f742-9dd6-451a-93e4-58e11fee0b1a.png)
![image](https://user-images.githubusercontent.com/25052021/213183736-45af9cbc-1dbe-4a7f-b79a-cad1bbe446a3.png)

My Browser Focus/Unfocus macros work perfectly, all they do is pause and unpause certain other macros, such as when browser in focus, all the NONE, YOUTUBE, TWITCH etc macros unpause and when browser unfocused, those pause and the game macro unpauses.

Each of these has the if cursor is clicked (had to put within last 5 seconds to get it working in previous version so it had time to run through all the different macros and check if the text within the local file matched or not (which was working on previous 'beta' version)

Wondering if you could look in to the "local file match" option and see if there's a problem or not.

Cheers mate.
Great work as usual.

**Comment by WarmUpTill** [comment]
Thanks for reporting the problem - I think I found the issue and it will be fixed in the linked PR.
