### ISSUE TITLE
Set more info into Variables

### ISSUE THREAD

**Issue by pkej** [WarmUpTill/SceneSwitcher#664]
**Is your feature request related to a problem? Please describe.**
When I'm streaming I'm using Tuna to get info about the songs playing from my royalty free playlist. To proper credit the musicians I would like to read info from the same files I read from the text fields in the Scene that creates the overlay.

Then I would like to write them into an EDL list which would need time and date, and or elapsed time since start of stream and/or recording.

**Describe the solution you'd like**
I would like to be able to have three new options in Variable which would be "set to file contents", "set to current time" and "set to elapsed time". The two latter would need to be able to set the format of the time string in some way, or provide several sub-variables, an example:

Variable
Set to elapsed time - MyVariable

could be used like this when appending to my songlist:

`${MyVariable:ElapsedTime:YYYY}-${MyVariable:ElapsedTime:MM}-${MyVariable:ElapsedTime:DD} ${MyVariable:ElapsedTime:HH}:${MyVariable:ElapsedTime:MM}:${MyVariable:ElapsedTime:SS}:${MyVariable:ElapsedTime:FF} - ${SongTitle} by ${SongArtist} url: ${SongURL} `

or:

`${MyVariable:TimeNow:YYYY}-${MyVariable:TimeNow:MM}-${MyVariable:TimeNow:DD} ${MyVariable:TimeNow:HH}:${MyVariable:TimeNow:MM}:${MyVariable:TimeNow:SS}:${MyVariable:TimeNow:FF} - ${SongTitle} by ${SongArtist} url: ${SongURL} `

**Describe alternatives you've considered**
I am considering "Execute Command Source" which will let me create my own batch scripts that I can call from inside the song overlay.

I've also considered using "Info Writer Plugin", but it can't get any info from outside.

Tunas own logging doesn't add the timestamp, which is needed for an EDL

Alternatively there could be global variables for the timeing available everywhere.

**Additional context**
Being able to read variables from file would make it easy to get data from other programs running on the computer. Being able to use time from variables would also benefit file creation, if file names could use them to create new files each time streaming and/or recording.

**Comment by WarmUpTill** [comment]
Thank you for your suggestion!
I will add it to the list, but I am not yet sure when I will get around to it.

>I would like to be able to have three new options in Variable which would be "set to file contents", "set to current time" and "set to elapsed time".

Just in case it is already of use to you:
The first two point were made possible with the latest release with some limitations.

![FileExample](https://user-images.githubusercontent.com/19472752/213526893-3b6346cc-bd18-4e14-8ef9-b0bc34bee57a.PNG)
![DateExample](https://user-images.githubusercontent.com/19472752/213526902-44c9ce3c-f81b-42d2-8aa4-46269d5fe40c.PNG)

The date format cannot be changed and will use the Qt default.

**Comment by WarmUpTill** [comment]
One of the last releases added the option to modify the current value of variables using regular expressions.
So you can split the date string you receive from the Date condition into multiple variables.

For example, this setup would only assign the time section of the current date to a variable:

![GetTime](https://user-images.githubusercontent.com/19472752/216426291-a0feec05-35ca-4514-bb9c-e61d57e0b194.PNG)

The variable "Time string" would contain `20:04:26` at the moment of the screenshot.

I assume this mostly covers your requirements, except for the the "time elapsed" part.
Are you referring to the time since the broadcast / recording / media playback was started or something else?

**Comment by pkej** [comment]
It would be the start time, I can see how that can be done using what you’ve described.
