### ISSUE TITLE
Verbose log Output stops after 1 minute - sleep for xxx

### ISSUE THREAD

**Issue by Trouffman** [WarmUpTill/SceneSwitcher#67]
Overview : 
When verbose logging is activated the emssage will not repeat past 1 minute:
"time: [adv-ss] sleep for 2000"

Detail:
- 2000 ms refresh timer
- OBS and ASS are runnign for few hours already.
the verbose will stop display the same message after a minute (that could be after 30/31 occurences as well)
- No message display that this is cut becasue of "repeated messages X times"

Changing the selected scene or so will make the log be updated again. for the same number of time.

System : 
- Windows 10
- OBS 26.0.2 (64bit)
- ASS - 64 bit- latest as of today (could not easily find a version in the file)

**Comment by WarmUpTill** [comment]
Thank you for reporting the issue!
I have noticed this myself before.

I would assume this is some sort of buffering (?) or maybe safeguard by OBS so the log file does not grow too fast.
But I never confirmed that / looked into it deeper.

I will investigate it once I find the time to do so.

**Comment by WarmUpTill** [comment]
It looks like this is indeed intended behaviour by OBS.
https://github.com/obsproject/obs-studio/blob/2902cdb2ff04ab19a304826765f275728a410602/UI/obs-app.cpp#L381-L383

Once a new message arrives OBS will log how many times the log was repeated:
https://github.com/obsproject/obs-studio/blob/2902cdb2ff04ab19a304826765f275728a410602/UI/obs-app.cpp#L332-L337

I could increase the log level of the sleep messages but I do not think that would be justified.
Or do you happen to rely on seeing these messages repeatedly?

**Comment by Trouffman** [comment]
This is a built-in feature indeed. what create the confusion is:
- This "last message repeated XXX times" appears only when there is a new message in the log.
- This does not appear in the Log-viewer either.

No need to extend the sleep message nor a special build, this is not justified.

We rely on this to check / make sure that the check are done. This will not be needed after few usage of the plugin.

That can can be dismissed then.
