### ISSUE TITLE
Add "Screen Orientation" condition

### ISSUE THREAD

**Issue by AllenJackC** [WarmUpTill/SceneSwitcher#676]
**Is your feature request related to a problem? Please describe.**
I want to be able to switch scenes based on which screen orientation I'm on. I use a Windows Surface tablet computer, and I'd like to be able to switch between my landscape and portrait scenes automatically.

**Describe the solution you'd like**
I'd like a condition which detects when Windows switches to a new orientation.

**Describe alternatives you've considered**
I'm currently switching scenes manually. I thought I could look at screen size for a specific window or process, but I don't believe that's possible. Hotkeys would be the same as me switching manually.

**Additional context**
https://user-images.githubusercontent.com/51028531/216771073-254354df-f0e5-48a6-85e6-ee2cccbda5d1.mp4

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

What type of source is used to capture video in OBS?
Does this particular source react to the rotation of the screen automatically? (E.g. changing its size / resolution)

**Comment by AllenJackC** [comment]
> What type of source was used to capture the video?

I'm using window capture.

>Does this particular source react to the rotation of the screen automatically? (E.g. changing its size / resolution)

Yes, the source's aspect ratio changes almost immediately when rotation the screen; in other words, the window's size goes from 2:3 to 3:2 without direct user input.

I was thinking I could track the change in the window's horizontal/vertical size as a trigger, but I couldn't find that in the actions list either.

**Comment by WarmUpTill** [comment]
> I'm using window capture.

In that case this should already be possible using the "Scene item transform" condition type as it will allow you to check for the size of a given source.

To configure this condition first select the scene and window capture source and click the button to get the current transform state (1).
Delete all parts that are not related to the size block.
Next enable the use of regular expressions (2).
Click the small gear icon that just appeared to configure the settings for the regular expression (3).
Uncheck all settings except "Allow partial match" (4) and close the dialog. 

Finally add the desired action - in this case switching to scene "Landscape scene".

![Landscape](https://user-images.githubusercontent.com/19472752/217615498-fa1e896d-2cb0-467c-9d21-dae29b093f74.PNG)

To automatically switch to the corresponding portrait scene simply create a macro similar to this (unless of course you want to handle each possible resolution specifically):

![Portrait](https://user-images.githubusercontent.com/19472752/217615507-0ea19d0d-09cd-4d1e-be0e-b8a986dbe928.PNG)

Let me know if that works or if you have any questions! :)

**Comment by AllenJackC** [comment]
That works perfectly! I guess I didn't look hard enough.
