### ISSUE TITLE
AdvSS leaks handles while checking for scene changes

### ISSUE THREAD

**Issue by KaleidonKep99** [WarmUpTill/SceneSwitcher#677]
**Describe the bug**

**To Reproduce**
1. Install Advanced Scene Switcher
2. Set up multiple scenes for different capture methods (Screen, Game View etc)
3. Create some macros to handle the switching between scenes
4. Advanced Scene Switcher starts leaking handles

**Expected behavior**
Advanced Scene Switcher should not leak handles

**Logs**
Log: https://obsproject.com/logs/UO3Zzhs70a5qxH96
AdvSS config: [adv-ss-Instant Replay-2023.02.06.12.40.03.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10662636/adv-ss-Instant.Replay-2023.02.06.12.40.03.txt)
Video of the issue: 
[![IMAGE ALT TEXT](http://img.youtube.com/vi/O7alOo8TmBM/0.jpg)](http://www.youtube.com/watch?v=O7alOo8TmBM "AdvSS 1.20.4 - Handle leak")

**Version information**
 - OS: Windows 11 22H2 (22621.1194)
 - OBS Version: 29.0.2
 - Plugin Version: 1.20.4 (I had it on 1.19.2 too)

**Additional context**
I do know that running checks 24/7 isn't something I'm supposed to do, but it's the only way to ensure a successful scene change, in case two macros collide with each other.

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!

I gave importing your settings at try but am not able to observe the same behaviour (yet).
So I assume I am missing a crucial step.

Were you able to narrow it down to any particular action / condition?

**Comment by KaleidonKep99** [comment]
I can share my scene collection too, maybe to narrow it down more.
[Instant_Replay.zip](https://github.com/WarmUpTill/SceneSwitcher/files/10668476/Instant_Replay.zip)

I'll check it myself too to see what's causing it.

**Comment by KaleidonKep99** [comment]
I think I managed to nail it down.
Enabling this causes the handle leak.
![image](https://user-images.githubusercontent.com/11065274/217069188-a746ea41-f309-49e5-93fa-51a69a8fa53d.png)

Here's the video:
![2023 02 06 @ 08 43 29 PM (DampShelduckd7a9dba0b4113523)](https://user-images.githubusercontent.com/11065274/217069348-d0643d31-96de-47ed-916b-a19ae073be42.gif)

**Comment by WarmUpTill** [comment]
First of all thank you very much for your support in tracking this issue down!

Unfortunately even after importing your scene collection I cannot reproduce the issue.
I even tried using different versions of OBS but it made no difference.

![2023-02-08 13-01-21](https://user-images.githubusercontent.com/19472752/217525341-8c921b69-092e-4c8b-8a84-2e1c867e1b1f.gif)

To be honest I can't really think of anything that would be causing this.
Do you observe the same issue on an empty scene collection?
Is maybe some other plugin somehow interfering with the scene switcher and that is causing the issue?

**Comment by KaleidonKep99** [comment]
Ok this is getting weird.

I tested with a completely clean OBS install (portable, no plug-ins aside from AdvSS) and an empty macro, and running it manually still triggers the leak?... I don't know what's going on, this could very well be a Windows 11 bug at this point.

I'll test on a Windows 10 VM with the same portable OBS, to rule out any possibility of a bug in the plug-in.

https://user-images.githubusercontent.com/11065274/217531689-ccb5793d-619b-4473-858a-2032679e866f.mp4

**Comment by KaleidonKep99** [comment]
Apparently it seems to be a problem on Windows 11 only.

https://user-images.githubusercontent.com/11065274/217532987-0c9eb3c5-7aa3-4bde-ae14-cbe16e79964b.mp4

**Comment by WarmUpTill** [comment]
Oh ok - very interesting!
I guess I will have to try to switch to W11 / set up a VM to investigate this further.

**Comment by KaleidonKep99** [comment]
Here's an update from Windows 11 22621.1702.
The issue is still present, even on the latest version of Advanced Scene Switcher.

I did some poking around, and it seems to be a handle leak of two types: semaphores and timers.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/11065274/7cbbccbd-97bd-4ccc-a89a-6f0ff0be8792)

**Comment by WarmUpTill** [comment]
I apologize for not getting around to looking in to this yet.
There is just always too much to do in and not enough time :)

I categorized it as a low priority topic as it is unlikely to break any functionality.
If that assumption was incorrect please do let me know.

**Comment by KaleidonKep99** [comment]
The issue is not present anymore in Windows 11 version 22621.1992.
Some Windows component used by OBS probably broke in an update, and got fixed in a later patch.

**Comment by WarmUpTill** [comment]
Thanks for the update! :)
