### ISSUE TITLE
[Screen Region] Remove the last one region when showing guide frame will cause crash

### ISSUE THREAD

**Issue by shugen002** [WarmUpTill/SceneSwitcher#68]
Recurrent Flow :
1、show guide frame
2、delete all screen region (if didn't exist one ,create one and remove it)

Looks like it will not auto hide when switch to tab , it may also happen when import setting (haven't test yet).

**Comment by WarmUpTill** [comment]
Thank you very much for reporting the problem and the steps to reproduce it!

I will look into it as soon as I can.

**Comment by WarmUpTill** [comment]
The crashing should be resolved with https://github.com/WarmUpTill/SceneSwitcher/pull/70/commits/96bc477d77c230ce42934d67cc49bcf12945c6c5

I will look into automatically hiding the guide at a later point.

**Comment by WarmUpTill** [comment]
Switching to a different tab should now hide the guide frames. (4af7540497b55b6305dd614051c674b5f35a5989)

**Comment by WarmUpTill** [comment]
I will close this for now - feel free to reopen if there are still issues with the current implementation.
