### ISSUE TITLE
Macro not starting consistently on time

### ISSUE THREAD

**Issue by kpdillon** [WarmUpTill/SceneSwitcher#684]
**Describe the bug**
Installed Advanced Scene Switcher on fresh Windows 11 pro machine.  Scheduled a macro to start at specific time, for example if date Monday 12:35, start streaming.... Very basic.  Not working consistently no rhyme or reason.  Verbose logging shows no error codes.

**To Reproduce**
- I am only experiencing this on one machine, not others I run this on so I am perplexed as to why this isn't working consistently.

**Expected behavior**
For the simple macro to work consistently.

**Logs**
https://obsproject.com/logs/Pp8FdE37PYPOPlcr

**Version information**
 - OS: [e.g. Windows 11]
 - OBS Version [e.g. 29.0.2]
 - Plugin Version [e.g. 1.19.2]

**Additional context**

Macro Export
{"Address":"","ClientEnabled":false,"ClientPort":55555,"LockToIPv4":false,"SendPreview":true,"SendSceneChange":true,"SendSceneChangeAll":true,"ServerEnabled":false,"ServerPort":55555,"active":true,"adjustActiveTransitionType":false,"audioFallbackDuration":0.0,"audioFallbackEnable":false,"audioFallbackScene":"","audioFallbackTargetType":0,"audioFallbackTransition":"","audioSwitches":[],"audioTabPos":11,"autoStartEvent":0,"connections":[],"cooldown":0.0,"cooldownUnit":0,"defTransitionDelay":0,"defaultTransitions":[],"disableHints":false,"displayUnit":0,"downMacroSegmentHotkey":[],"exeTabPos":3,"executableSwitches":[],"fileSwitches":[],"fileTabPos":6,"generalTabPos":0,"hideLegacyTabs":false,"idleEnable":false,"idleSceneName":"","idleTabPos":9,"idleTargetType":0,"idleTime":60,"idleTransitionName":"","ignoreIdleWindows":[],"ignoreWindows":[],"interval":300,"macroActionConditionSplitterPosition":[{"pos":173},{"pos":247}],"macroListMacroEditSplitterPosition":[{"pos":160},{"pos":813}],"macroProperties":{"highlightActions":false,"highlightConditions":false,"highlightExecuted":false,"newMacroRegisterHotkey":false},"macroTabPos":1,"macros":[{"actions":[{"action":1,"collapsed":false,"id":"streaming"},{"blockUntilTransitionDone":true,"collapsed":false,"displayUnit":0,"id":"scene_switch","sceneSelection":{"name":"Mass Intro Live Stream Auto Start (hidden)","type":0},"seconds":300.0,"transition":"Fade","transitionType":0},{"blockUntilTransitionDone":true,"collapsed":false,"displayUnit":0,"id":"scene_switch","sceneSelection":{"name":"Camera","type":0},"seconds":1.0,"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"condition":0,"dateTime":"Mon Feb 20 12:40:00 2023","dateTime2":"Mon Feb 20 12:06:19 2023","dayOfWeek":1,"dayOfWeekCheck":true,"displayUnit":0,"durationModifier":{"displayUnit":0,"seconds":0.0,"time_constraint":0},"id":"date","ignoreDate":true,"ignoreTime":false,"logic":0,"repeat":false,"seconds":0.0,"updateOnRepeat":true}],"name":"Monday  Mass Start","onChange":false,"parallel":true,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"displayUnit":0,"id":"scene_switch","sceneSelection":{"name":"Black Screen","type":0},"seconds":5.0,"transition":"Fade","transitionType":0},{"action":0,"collapsed":false,"id":"streaming"}],"conditions":[{"collapsed":false,"condition":0,"dateTime":"Mon Feb 20 11:16:00 2023","dateTime2":"Mon Feb 20 10:49:17 2023","dayOfWeek":1,"dayOfWeekCheck":true,"displayUnit":0,"durationModifier":{"displayUnit":0,"seconds":0.0,"time_constraint":0},"id":"date","ignoreDate":true,"ignoreTime":false,"logic":0,"repeat":false,"seconds":0.0,"updateOnRepeat":true}],"name":"Monday Mass Stop","onChange":false,"parallel":true,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]}],"mediaSwitches":[],"mediaTabPos":5,"networkTabPos":13,"noMatchDelay":0.0,"noMatchDelayUnit":0,"non_matching_scene":"","pauseEntries":[],"pauseTabPos":16,"priority0":10,"priority1":0,"priority10":3,"priority2":2,"priority3":8,"priority4":6,"priority5":9,"priority6":7,"priority7":4,"priority8":1,"priority9":5,"randomSwitches":[],"randomTabPos":7,"readEnabled":false,"readPath":"","regionTabPos":4,"removeMacroSegmentHotkey":[],"saveWindowGeo":false,"sceneGroupTabPos":14,"sceneGroups":[],"sceneRoundTrip":[],"sceneTransitions":[],"screenRegion":[],"sequenceTabPos":10,"showSystemTrayNotifications":false,"startHotkey":[],"startup_behavior":0,"stopHotkey":[],"switch_if_not_matching":0,"switches":[],"tansitionOverrideOverride":false,"threadPriority":3,"timeSwitches":[],"timeTabPos":8,"titleTabPos":2,"toggleHotkey":[],"transitionTabPos":15,"triggerTabPos":17,"triggers":[],"upMacroSegmentHotkey":[],"variables":[],"verbose":true,"version":"9bcced524bc456f3095b977f3af5966dfe14703e","videoSwitches":[],"videoTabPos":12,"windowHeight":600,"windowPosX":210,"windowPosY":112,"windowWidth":1000,"writeEnabled":false,"writePath":""}

**Comment by kpdillon** [comment]
Maybe I just solved my own issue and it is because I have to deactivate and activate advanced scene switcher every time I adjust the time?

**Comment by WarmUpTill** [comment]
I can see one anomaly in the provided log that likely explains what you are experiencing:
```
12:40:00.271: [adv-ss] condition date returned 1
12:40:00.271: [adv-ss] Macro Monday  Mass Start returned 1
12:40:00.271: [adv-ss] condition date returned 0
12:40:00.271: [adv-ss] Macro Monday Mass Stop returned 0
12:40:00.271: [adv-ss] running macro: Monday  Mass Start
12:40:00.271: [adv-ss] macro Monday  Mass Start already running
```

The last line indicates that while all of the conditions of a given macro were true it was intentionally not ran again, as a previous instance of the given macro is already active.

The last execution of the macro seemed to happen at:
```
12:39:00.134: [adv-ss] running macro: Monday  Mass Start
```
So roughly a minute before.

When looking at the settings you shared it seems that you are using an action to switch to a scene with the name "Mass Intro Live Stream Auto Start (hidden)" with a transition that is taking 300s to complete.
Additionally you have selected the option to wait for the transition to complete before continuing with the next action (to start streaming):
```
                    "blockUntilTransitionDone":true,
                    "collapsed":false,
                    "displayUnit":0,
                    "id":"scene_switch",
                    "sceneSelection":{
                        "name":"Mass Intro Live Stream Auto Start (hidden)",
                        "type":0
                    },
                    "seconds":300.0,
                    "transition":"Fade",
                    "transitionType":0
```

So what I assume is happening is that the transition is still ongoing for another four minutes since it was started at roughly 12:39 and thus at 12:40 the macro will not be started again.

> Maybe I just solved my own issue and it is because I have to deactivate and activate advanced scene switcher every time I adjust the time?

If you stop and restart the scene switcher all macros that are still running are aborted.

Let me know if you have any questions! :)

**Comment by kpdillon** [comment]
Thank you for taking the time to explain all this.  That makes perfect sense.  I really appreciate your help!
