### ISSUE TITLE
[Feature Request] Set http headers for a post request? / Get body from file

### ISSUE THREAD

**Issue by andrewcartwright1** [WarmUpTill/SceneSwitcher#686]
**Is your feature request related to a problem? Please describe.**
On my stream, I have a python script that I use to poll the openxbl api to find out what achievement I have recently unlocked, I then save the new achievement information in a text file - I have a macro set up which checks for any changes to this file, which then changes the visiblity of a scene item and hides it after a period of time.

It has been requested that a bot posts in chat what achievement has just been unlocked incase the prompt is missed.

**Describe the solution you'd like**
I am looking at adding a http action to the macro that will make the streamelements bot post the information from this file, the issue that I have is..

1. It requires a auth header: https://dev.streamelements.com/docs/api-docs/ae133ffaf8c1a-personal-access-using-jwt-secert-token-to-access-the-api
2. I havn't looked too much into the http action yet, but I am guessing that the body is manually configured when reading the docs here:  https://github.com/WarmUpTill/SceneSwitcher/wiki/Http-action , I was wondering if it would be possible to get the body of the request from a file - I can have the python script update a file with the body required for the message: https://dev.streamelements.com/docs/api-docs/1e22a4ed3ad16-channel-say

**Describe alternatives you've considered**
The only alternative that I can see here is, Instead of using the macro to read a file for changes and do all the actions, change it so that it checks for if the scene element's visibility has changed so that it can run through all the actions, and do the post request to streamelements via the python script.

The reasoning behind this is because I would like the notification to show on stream and the bot message to show at roughly about the same time but ideally would like one place to manage it all!

Now that I'm reading this back to myself aloud, the right way to probably do this is to make the python script update the scene item visibility and make the request to the streamelements api, leaving the macro to take care of hiding the element after the visibility change..

**Comment by WarmUpTill** [comment]
Thank you very much for the suggestion! :)

>I havn't looked too much into the http action yet, but I am guessing that the body is manually configured when reading the docs here: https://github.com/WarmUpTill/SceneSwitcher/wiki/Http-action , I was wondering if it would be possible to get the body of the request from a file - I can have the python script update a file with the body required for the message: https://dev.streamelements.com/docs/api-docs/1e22a4ed3ad16-channel-say

This part should already be possible.

The http action does support using variables in body text area.
So you could use a macro setup similar to this one to assign the file contents to a variable named "File content":

![Var](https://user-images.githubusercontent.com/19472752/220629753-2bd19d54-91be-4692-877b-f74ceb7c94f7.PNG)

You can then reference the variable in a Http action using the syntax `${variable name here}`.
So using the example from above something similar to this:

![VarHttp](https://user-images.githubusercontent.com/19472752/220630139-6aaee2e7-1374-49c9-be0f-35544435f34f.PNG)

>It requires a auth header

That I think is not yet possible at the moment and would have to be implemented.
I will add it to the todo list, but I am not sure yet when I will get around to it.

**Comment by WarmUpTill** [comment]
I implemented the option to set headers for the get and post requests in the http action.

![Header](https://user-images.githubusercontent.com/19472752/222934402-affce4bb-7ed2-4722-83e9-20806e5aeb11.PNG)

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4333431636

I would appreciate if you could give this a try and report back if you run into any issues :)
