### ISSUE TITLE
Feature: Detect if game is hooked or not (Game capture)

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#692]
Hey there. After seeing a reddit thread about someone wanting to auto start/stop recording based on playing and quitting games in fullscreen, it gave me the idea to post a feature request about it. I suggested using if process exists and so on, but he wants a more automated way of detecting.

So the idea is basically just to detect if a game source has hooked a game, or not. Currently, the "show settings" outputs nothing, so can't go down that route.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

If I am not mistaken that should already be possible using something similar to this:

![Example](https://user-images.githubusercontent.com/19472752/223203744-c1dc8f66-998a-45be-9c47-cb3c35e64081.PNG)

The condition basically translates to "If the current foreground window is in fullscreen mode and has _any name_", with `.*` being a regular expression which matches every window title.

Does that suffice or is any additional functionality needed?
