### ISSUE TITLE
Feature Request:dock macro botton

### ISSUE THREAD

**Issue by umbrella-k** [WarmUpTill/SceneSwitcher#697]
I would like an option to add a button to the dock to manually run a macro.
There are times when you want to execute at your own discretion with no particular conditions.
For now, I run Macro by pressing the "Run Macro" button on the settings screen.
If this is in the dock, it is convenient because I can execute the macro with a single touch.

**Comment by WarmUpTill** [comment]
Great suggestion! 👍 
I will try to look into it on the weekend!

**Comment by WarmUpTill** [comment]
A first version of the plugin supporting this functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4505090473

The dock will allow you to run a given macro or adjust its pause state.

![DockExample2](https://user-images.githubusercontent.com/19472752/227354041-f0edb251-4035-405a-9fae-23b98e5cda8e.PNG)

You can enable or disable the option to create a dock for a given macro in the settings dialog of a given macro:

![DockExample](https://user-images.githubusercontent.com/19472752/227354025-f04fb4c2-7351-464b-a4ca-47bda6dc0dd1.PNG)


Please note that I did not have the chance to perform many tests there might still be some bugs.
Let me know if you run into any issues!

**Comment by WarmUpTill** [comment]
I now also added the option to hide / show the run or pause button in case only a single functionality is needed in this new build:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4516071313?pr=700
This should allow shrinking the docks to a smaller size so they don't take up so much space in the OBS UI.

I will _probably_ merge this PR soon as I pan on releasing a new version of the  plugin.
