### ISSUE TITLE
Crash when changing scene collection

### ISSUE THREAD

**Issue by Emilgardis** [WarmUpTill/SceneSwitcher#7]
When changing collection, OBS crashes after some time. This doesn't always happen however and I'm not sure why, I do know that Advanced Scene Switcher is at fault however.

Version 2e7ea7d downloaded from releases
[gist of crash log(s)](https://gist.github.com/Emilgardis/d88ad1b0ff3d4c8bb7b021d1ae4bcb29)
I've attached two crash logs that are similar in nature.

**Comment by WarmUpTill** [comment]
Sorry about the very slow response. It should be fixed now with https://github.com/WarmUpTill/SceneSwitcher/commit/dd2d70bb9c481b06c4684ade3487f71683a30734

Thanks for pointing out the issue!
