### ISSUE TITLE
when I switch scene collection, all macro button docks are hidden

### ISSUE THREAD

**Issue by pingval** [WarmUpTill/SceneSwitcher#714]
**Describe the bug**
New macro button dock feature is cool.
However, when I switch scene collection, all macro button docks are hidden. And even when I switch back to the original scene collection, they remain hidden.

**To Reproduce**
Video: https://www.youtube.com/watch?v=YH31A6UfE1k

**Expected behavior**
Macro button docks should go back if scene collection is switched back?

**Logs**
OBS log: https://obsproject.com/logs/QHd2EnrC0osI79JM
Plugin settings: [adv-ss-Scene Collection 1-2023.04.08.18.03.44.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11182875/adv-ss-Scene.Collection.1-2023.04.08.18.03.44.txt)

**Version information**
 - OS: Windows 10 Home
 - OBS Version: 29.1 Beta 3, Portable Mode
 - Plugin Version: 1.21.0

**Comment by WarmUpTill** [comment]
Thanks - I will try to look into it!

**Comment by WarmUpTill** [comment]
In the linked PR I have fixed the issue of the dock widgets not being restored correctly when changing scene collections.
A build with this change should be available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4651901985

Unfortunately however, it seems like only the rough area (e.g "top", "left" , ...) where the widget was docked can be restored when changing scene collections.
There does not seem to be a way to restore the exact location _within_ those dock areas.
