### ISSUE TITLE
"Use patternmatching mode" value is not persisted between restarts

### ISSUE THREAD

**Issue by danmusk** [WarmUpTill/SceneSwitcher#718]
**Describe the bug**
"Use patternmatching mode" does not correctly store the value for "Correlation coefficient".
When closing and re-opening OBS Studio, this macro-setting changes to "Cross correlation".

**To Reproduce**
1. Create Macro with "If video"...
2. Select "Use pattern matching"
3. Select "Correlation coefficient" in "Use patternmatching mode"
4. Close "Advanced Scene Switcher Settings"
5. Restart OBS Studio
6. Go to "Advanced Scene Switcher Settings" and edit the macro created in step 1
7. The "Use patternmatching mode" is not "Cross correlation"

**Expected behavior**
The "Use patternmatching mode" setting should store the selected mode between OBS Studio restarts.

**Version information**
 - OS: Windows 10 (10.0.19045)
 - OBS Version 29.0.2
 - Plugin Version 1.21.0

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue! :)

I think that should be fixed the [latest release](https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.21.1).
Can you please test if you still observe the issue after updating?

**Comment by danmusk** [comment]
That was fast!
Can confirm that it now works as expected.
Thank you very much for this awesome plugin!
