### ISSUE TITLE
Feature Request - Set filename and path

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#719]
If possible it'd be great to have the ability to have an action that changes the recording filename and recording path as specified in the settings. 

My use case is I want to record some lecturers and on different days the lecture is different so I want the filename to reflect that. I also want to dynamically add in info based on what term it is, as sourced via a text file. I can specify a different file name via profiles but then I'd end up with heaps and heaps of profiles, and wouldn't have as much fine control over the name. Editing the basic.ini file is possible, but the changes only apply on OBS restart.

Thanks for your consideration.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4771975757?pr=722
(Note, that you have to be logged into GitHub to be able to download it)

![Record](https://user-images.githubusercontent.com/19472752/233775124-7d6b7cbc-4d79-41a9-85d3-7c56692d31e2.PNG)

Let me know if you run into any issues! :)

**Comment by BenJamesAndo** [comment]
Tested and works perfectly. Thanks so much for helping make my life more efficient and easier!
