### ISSUE TITLE
'If Idle' Loop glitch?

### ISSUE THREAD

**Issue by joshua-whitney** [WarmUpTill/SceneSwitcher#720]
So this might be my bad here but I'm trying to automatically switch to a scene when my mouse and keyboard are idle for 2 seconds:
![image](https://user-images.githubusercontent.com/41597293/233724930-3dc55fbf-d25a-46cb-81f4-c72dc59bbfbf.png)
That works!
_BUT_ when I do it from Blender or any other piece of software that I have plugged in to automatically switch it glitches out. It will cut to the right scene but then instantly cut back. (It creates a loop.) I've been messing with this for a while now. Not sure if it's a bug or my fault haha.

I'm on Linux Mint - latest versions of both OBS and the Advanced Scene Switcher :)

Here are my settings... (yikes! That's long!)

{"Address":"","ClientEnabled":false,"ClientPort":55555,"LockToIPv4":false,"SendPreview":true,"SendSceneChange":true,"SendSceneChangeAll":true,"ServerEnabled":false,"ServerPort":55555,"active":true,"adjustActiveTransitionType":true,"audioFallbackDuration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"audioFallbackEnable":false,"audioFallbackScene":"","audioFallbackTargetType":0,"audioFallbackTransition":"","audioSwitches":[],"audioTabPos":11,"autoStartEvent":0,"connections":[],"cooldown":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"defTransitionDelay":0,"defaultTransitions":[],"disableHints":false,"downMacroSegmentHotkey":[],"exeTabPos":3,"executableSwitches":[],"fileSwitches":[],"fileTabPos":6,"generalTabPos":0,"hideLegacyTabs":true,"idleEnable":false,"idleSceneName":"","idleTabPos":9,"idleTargetType":0,"idleTime":60,"idleTransitionName":"","ignoreIdleWindows":[],"ignoreWindows":[],"interval":300,"lastImportPath":"","macroActionConditionSplitterPosition":[{"pos":112},{"pos":179}],"macroListMacroEditSplitterPosition":[{"pos":143},{"pos":493}],"macroProperties":{"highlightActions":false,"highlightConditions":false,"highlightExecuted":false,"newMacroRegisterHotkey":false},"macroTabPos":1,"macros":[{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Blender","type":0},"transition":"","transitionType":0}],"conditions":[{"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":5.0},"version":1},"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"id":"idle","logic":1},{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"id":"scene","logic":101,"pattern":".*Scene.*","sceneSelection":{"name":"Face Cam","type":0},"type":0,"useTransitionTargetScene":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Macro 1","onChange":false,"parallel":false,"pause":true,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Face Cam","type":0},"transitionType":1}],"conditions":[{"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":2.0},"version":1},"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"id":"idle","logic":0}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Cut to face","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Blender","type":0},"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"focus":true,"fullscreen":false,"id":"window","logic":0,"maximized":false,"window":"Blender","windowFocusChanged":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Blender","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Fade In","type":0},"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"focus":true,"fullscreen":false,"id":"window","logic":0,"maximized":false,"window":"Fade In","windowFocusChanged":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Fade In","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"PDF","type":0},"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"focus":true,"fullscreen":false,"id":"window","logic":0,"maximized":false,"window":"Betty Fleetfoot Shooting Script April 20, 2023 Blue Revisions.pdf \u001B%G—\u001B%@ BETTY FLEETFOOT","windowFocusChanged":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"PDF script viewer","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Audacity","type":0},"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"focus":true,"fullscreen":false,"id":"window","logic":0,"maximized":false,"window":"Audacity","windowFocusChanged":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Audacity","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Blender","type":0},"transition":"Fade","transitionType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":120.0},"version":1},"time_constraint":2},"id":"scene","logic":0,"pattern":".*Scene.*","sceneSelection":{"name":"Face Cam","type":0},"type":0,"useTransitionTargetScene":false}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"30 sec rule","onChange":false,"parallel":false,"pause":true,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"blockUntilTransitionDone":true,"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"scene_switch","sceneSelection":{"name":"Blender","type":0},"transition":"Fade","transitionType":0},{"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":5.0},"version":1},"duration2":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"id":"wait","version":1,"waitType":0}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":5.0},"version":1},"time_constraint":2},"id":"scene","logic":0,"pattern":".*Scene.*","sceneSelection":{"name":"Face Cam","type":0},"type":0,"useTransitionTargetScene":false},{"collapsed":false,"duration":{"unit":0,"value":{"type":0,"value":5.0},"version":1},"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"id":"idle","logic":103}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Kill Face Cam","onChange":false,"parallel":false,"pause":false,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]},{"actions":[{"action":4,"collapsed":false,"id":"macro","macro":"Cut to face"}],"conditions":[{"collapsed":false,"durationModifier":{"seconds":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"time_constraint":0},"id":"scene","logic":0,"pattern":".*Scene.*","sceneSelection":{"name":"Face Cam","type":0},"type":0,"useTransitionTargetScene":true}],"dockSettings":{"hasPauseButton":true,"hasRunButton":true,"register":false},"group":false,"name":"Macro 2","onChange":false,"parallel":false,"pause":true,"pauseHotkey":[],"registerHotkeys":false,"togglePauseHotkey":[],"unpauseHotkey":[]}],"mediaSwitches":[],"mediaTabPos":5,"networkTabPos":13,"noMatchDelay":{"unit":0,"value":{"type":0,"value":0.0},"version":1},"non_matching_scene":"","pauseEntries":[],"pauseTabPos":16,"priority0":10,"priority1":0,"priority10":3,"priority2":2,"priority3":8,"priority4":6,"priority5":9,"priority6":7,"priority7":4,"priority8":1,"priority9":5,"randomSwitches":[],"randomTabPos":7,"readEnabled":false,"readPath":"","regionTabPos":4,"removeMacroSegmentHotkey":[],"saveWindowGeo":false,"sceneGroupTabPos":14,"sceneGroups":[],"sceneRoundTrip":[],"sceneTransitions":[],"screenRegion":[],"sequenceTabPos":10,"showSystemTrayNotifications":false,"startHotkey":[],"startup_behavior":2,"stopHotkey":[],"switch_if_not_matching":0,"switches":[],"threadPriority":3,"timeSwitches":[],"timeTabPos":8,"titleTabPos":2,"toggleHotkey":[],"transitionOverrideOverride":false,"transitionTabPos":15,"triggerTabPos":17,"triggers":[],"upMacroSegmentHotkey":[],"variables":[],"verbose":false,"version":"9bedbf6fb826700944c3136f34504cc9a89c39cb","videoSwitches":[],"videoTabPos":12,"warnPluginLoadFailure":true,"windowHeight":600,"windowPosX":0,"windowPosY":178,"windowWidth":1000,"writeEnabled":false,"writePath":""}

Any help would be really appreciated, I'm not sure what else to put here 😅

The gist of what I wanted to do was to be able to share the screens of the different applications I was using (Blender, Autacity, etc...) and then automatically switch over to my 'face cam' when I'm talking (by not moving my mouse around.)

**Comment by joshua-whitney** [comment]
I'm an idiot... I literally waited like an hour to ask this and 5 minutes later:
![image](https://user-images.githubusercontent.com/41597293/233728268-f2552bfd-6457-4d34-a7f0-b92d7ecad4e5.png)

For anyone who is struggling with something with a problem like this, you just tick this box and you get a bunch of hidden tabs. 
![image](https://user-images.githubusercontent.com/41597293/233728523-43363d9b-fad8-43f0-81c3-7bef1e210828.png)
hehe! Have a nice day :)

**Comment by joshua-whitney** [comment]
UPDATE:
That must have been good luck... It's back 😱 
I literally tested it and then it broke once I posted this...

**Comment by WarmUpTill** [comment]
So the issue you have here is that you only want the non-idle scene switches to happen if you are not idle.
In the current setup multiple macros can be true and will all be executed, leading to this scene switch "flickering" effect.
(For example if "Blender" is in focus and you are idle at the same time)

You have multiple ways to solve this:

* You can extend your idle macro to [pause](https://github.com/WarmUpTill/SceneSwitcher/wiki/Pausing-macros) the other macros when you are idle so they won't trigger.
So something similar to this:
![Pause1](https://user-images.githubusercontent.com/19472752/233763649-3def9dfc-79c6-4980-ba53-1511addf69b9.PNG)
But you will of course also have to add the equivalent steps to unpause those macros if you are *not* idle.

* You can use a variable to indicating which scene to switch to and only switch scenes if its value changed, instead of actively switching the scene in each macro.
An example on how to set this up can be found here:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Variables#example-podcast

* You can extend the condition list of your non-idle macros to include the check if you are idle.
To make it easier to maintain I would suggest to simply reference the macro containing the idle check by using the "Macro" condition.
This will make it much easier to change e.g. the idle duration without having to readjust the values in the idle condition X different macros.
Here is an example of what I mean:
![MacorCondition](https://user-images.githubusercontent.com/19472752/233763814-a3f78606-802f-4b01-b291-791b8ce7b442.PNG)

I hope that helps! :)
Let me know if you have any questions or something is not working as you would expect!

P.S.: In general I would advise against using the "old" tabs, especially in combination with macros.
They are very limited in functionality and less flexible.

**Comment by joshua-whitney** [comment]
That worked! Thank you so much!! I honestly wish I found out about this awesome plugin a while ago lol. I've been doing everything manually for a bit now 🤣.
