### ISSUE TITLE
API For other Plugins

### ISSUE THREAD

**Issue by HealingArcYT** [WarmUpTill/SceneSwitcher#726]
Developers that would want to use something like your drag and drop programming for their plugin but know that this plugin is used by a lot of people that uses their plugin should have the option to add stuff to Advanced Scene Switcher so that Advanced Scene Switcher can get stuff from that plugin and do something or can send stuff back to the plugin

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

I do think in general something like this should be possible.
I am just not really sure yet how to best approach this.

Can you elaborate a bit on how you would imagine this to work (in case you have concrete use case in mind)?

**Comment by HealingArcYT** [comment]
I think everything that would be needed would be an option to send a signal for each action Advanced Scene Switcher has, like switching a scene, Activating/deactivating specific sources or others, and to tell Advanced Scene Switcher which Actions the Plugin might want to receive, like sending a Message. One Thing you could do like that is create a remote control using a mobile phone or maybe even for viewers using Twitch chat to interact with the stream, of course in boundaries set by the streamer.

**Comment by HealingArcYT** [comment]
One Thing might be that you have a scene for each game you are streaming, and when you switch the game you have it set up so that ASS switches the scene automatically and that that could in turn then trigger another plugin that has a Twitch Bot Connected to it to Send a Message in Chat, Modify title and/or Game Played on Twitch and maybe even update what you can do with channel points, even though i dont know if a bot is able to do that by twitchs bot guidelines

**Comment by WarmUpTill** [comment]
Hm, I am not sure about that.

Wouldn't it be safer / better to simply allow the registering of arbitrary condition types?
This way the user still has control over what exactly happens if a given plugins sends its "signal".

**Comment by HealingArcYT** [comment]
What i meant was that the plugin sends a signal that something happened, and then you have to tell ASS what should happen if that signal happens, if anything should happen at all

**Comment by HealingArcYT** [comment]
And Actions you can use too

**Comment by nacalai** [comment]
I found a nice trick to enable ASS to interact with practically any application out there that Zapier / Integromat (Make) supports. So, you could in fact have for example a twitch event trigger something in/within ASS. 

This is a no-code solution and pretty simplified, and not sure if it entirely is what you need, but maybe you can get something out of it :)

https://www.youtube.com/watch?v=O-QwiIInZqM

**Comment by HealingArcYT** [comment]
It can do what i was meaning, but not as easy as i meant it to be for a user, for a programmer for that plugin it shouldnt make a real difference what he uses for the plugin, an api by you or this workaround

**Comment by WarmUpTill** [comment]
I consider this issue as closed with the introduction of an interface to register custom condition / action types with can even be used by [OBS scripts](https://github.com/WarmUpTill/SceneSwitcher/wiki/Scripting). (https://github.com/WarmUpTill/SceneSwitcher/commit/36201cbfb46a84b75b00d6142b52b43b0dbabe88)
