### ISSUE TITLE
Feat: Title & Icon for tray notifications

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#728]
I see a lot of great potential for the tray notification. Currently, it only supports adding a message with the window title always being "Advanced Scene Switcher." Being able to edit the title, and perhaps also the icon, would allow for more customiziations and will make it easier to know what the notification is, at a glance.

Also, I really love the nvidia style notification that this plugin features: https://github.com/DmitriySalnikov/OBSNotifier
It would be cool to have the option to use a similiar style in addition to the traditional windows notification. But I guess perhaps you can't do this solely from a OBS plugin, and would require something to run outside of obs? I'm not sure :) His plugin only features notifications of obs events. I want it to be customizable with stuff from ASS.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

Modifying the title and the icon should be doable without too much effort.
I am not so sure about the custom styles, however.

I will try to look into it once I find the time to do so :)

**Comment by nacalai** [comment]
Thanks, appreciate that!

**Comment by WarmUpTill** [comment]
A build with the option to change title and icon of the notification will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4855370910/jobs/8653849164?pr=736

![Systray](https://user-images.githubusercontent.com/19472752/235540082-b81f5eb5-0716-4896-8210-fd30dd71aacf.PNG)

Let me know if you run into any issues! :)

**Comment by nacalai** [comment]
Seems to work nicely :) Thanks

**Comment by nacalai** [comment]
Question. Can the icon file path be relative to the portable folder?

**Comment by nacalai** [comment]
Question 2. Can the notification stay on screen/be persistent as an option?

**Comment by WarmUpTill** [comment]
> Question. Can the icon file path be relative to the portable folder?

I think it would be relative to the OBS binary, so the obs.exe file in case of windows.



> Question 2. Can the notification stay on screen/be persistent as an option?

Unfortunately it seems like adjusting the duration is not always possible on Windows.
https://doc.qt.io/qt-6/qsystemtrayicon.html#showMessage
`On Windows, the millisecondsTimeoutHint is usually ignored by the system when the application has focus.`
