### ISSUE TITLE
Adding more docks features - Custom naming & several buttons in one dock

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#740]
Hi there. I see great potential for the newly added docks feature. As it is now, the docks feature is simply a way to pause/unpause/run macros. This could also be used to create a series of custom buttons which could do whatever you want.

I'd love to see some further additions which would really complete our OBS streaming setup:
- Be able to add several buttons/macros to a single dock window.
- Be able to name the buttons.

So for example I have this dock which opens a website. I'd rather have the button itself say "Open CWC". So, be able to just remove the dock window title text and have several buttons inside this dock, with custom names on the buttons as well.
![image](https://user-images.githubusercontent.com/4357694/236317118-894f8578-a666-4e8d-a44f-749cb16a91b3.png)

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

**Comment by WarmUpTill** [comment]
I added the option to rename the buttons of the macro dock in the linked PR:

![Dock](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/e25a2231-6cc3-4558-a246-9ce6d7f6e851)

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4968826458?pr=748

I am not sure when I will get around to the combination of multiple macro docks into one.
