### ISSUE TITLE
Feature Request - set stream settings

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#756]
The ability to have an action to change the stream URL, stream key and if applicable, authentication with username and password.

It's currently possible to achieve with Bitfocus Companion's OBS module but I'd prefer to do it directly in Advanced Scene Switcher for simplicity, reliability and extra flexibility.

My use case is that YouTube allows scheduled events to have different stream keys. I'm going to have 6 different events running once a week. Each set of events will share a stream key. So I'd like e.g. on Monday OBS to use Monday's stream key, Tuesday use Tuesday's stream key etc. It'd allow for more automation and faster setups.

**Comment by nacalai** [comment]
You could easily achieve this with profiles, and have ASS switch between them automatically, or do it manually. But, it's a nice feature to have in the plugin anyway

**Comment by BenJamesAndo** [comment]
Yes indeed. But because profiles save other information as well, if I want to make a change to OBS and it's a profile related setting, I'd then have to manually load up each profile and make the change.

**Comment by WarmUpTill** [comment]
The linked PR adds the option to configure the requested stream settings.

![StreamKey](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/3663bff7-cd77-4d06-9937-de3e824b6dcd)

A build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5072202387?pr=759

I would appreciate if you could give this a try and report back if you encounter any issues, as my testing was basically limited to just checking if the OBS settings menu updated correctly.

**Comment by BenJamesAndo** [comment]
Thanks for this. I've done extensive testing and it works great!
An observation is if I set a username & password, it doesn't automatically tick the Use authentication option in the Stream settings tab. If I then manually tick it the username & password has in fact been filled out, just not activated. Obviously if I then leave it activated it's fine. But perhaps a better UX would be that if a username & password is set then AdvSS would auto-tick the Use authentication option.
I personally don't use authentication but just thought to test it anyway.

Finally instead of saying `Set server` perhaps it should be `Set server URL` for extra clarification, as a user may put `YouTube` as the server rather than the full streaming URL.

**Comment by BenJamesAndo** [comment]
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/44917135/e0494186-da7a-4e10-8838-a1ed1599e1ea)
Just a small thing, but I've noticed the width of the streaming options dropdown to be full width, whereas before this update it was much less wide. It'll probably be adjusted before the next release, but just thought I'd let you know just in case.
