### ISSUE TITLE
Auto Scene Switcher Crash

### ISSUE THREAD

**Issue by vicvanblack** [WarmUpTill/SceneSwitcher#761]
**Describe the bug:**
OBS crashed after I choose scene in plugin

**Steps to reproduce the behavior:**
1. Open OBS 29.1.1
2. Open Advanced Scene Switcher 1.22.1
3. Advanced Scene Switcher is Active
4. I create a macro
5. (i want my scene 1 with media source to start. When the video is finished I want it to switch to scene 2 with the webcam)
6. I create a macro like: If - Scene - Current Scene is - Scene Intro
7. I create the consequence: Switch Scene - Switch Scene To: Scene 1 - using: select transition:
8. CRASH! Obs ha crasched! 

**Expected behavior:**
the OBS crash resets everything to zero and the plugin still doesn't work. So it's impossible to use it.

**Logs**
Unhandled exception: c0000005
Date/Time: 2023-05-26, 10:20:11
Fault address: 7FFE231EF1E0 (c:\program files\obs-studio\bin\64bit\obs.dll)
libobs version: 29.1.1 (64-bit)
Windows version: 10.0 build 22621 (release: 22H2; revision: 1702; 64-bit)
CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

[https://www.neurographix.it/Crash%202023-05-26%2010-20-12.txt](url)

**Version information:**
 - OS: [e.g. Windows 11]
 - OBS Version [e.g. 291.1]
 - Plugin Version [e.g. 1.22.1]

I hope u can solve it or contact me for tell me how do. Thanks.

**Comment by WarmUpTill** [comment]
Can you please attach the complete crash log file?
Without it I cannot really do much.

**Comment by vicvanblack** [comment]
I have write the link in the message on github. There you can see the
complete file. Cant you open it?

Il Ven 26 Mag 2023, 20:23 WarmUpTill ***@***.***> ha scritto:

**Comment by WarmUpTill** [comment]
Ah sorry about that - clicking the link simply redirected me to this page again.
Manually entering it seemed to do the trick.

I think I understand what the issue is.
I will try to provide you with a fix tomorrow.

Thanks for reporting the problem!

**Comment by WarmUpTill** [comment]
A build with a fix for the crash is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5100137536?pr=762

Let me know if that resolves your issue! :)

**Comment by vicvanblack** [comment]
Thank you very much.  I will write to you in any case.  Thanks also for any
future corrections.
A.C.

Il Sab 27 Mag 2023, 23:24 WarmUpTill ***@***.***> ha scritto:

**Comment by vicvanblack** [comment]
I'm sorry to write you again, I would not bother you but I still get crashes. I uninstalled the plugin and then reinstalled it completely. i did a test.
I told the plugin that if the current scene is scene1 Countdown then it switches to scene2.

What I want to achieve is that at the end of the Timer script of scene 1, scene 2 starts. But everything explodes.
I attach crash file.

A.C.
[Crash 2023-05-28 10-06-05.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11584027/Crash.2023-05-28.10-06-05.txt)
[Crash 2023-05-28 10-07-52.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11584028/Crash.2023-05-28.10-07-52.txt)

**Comment by WarmUpTill** [comment]
What type of transition are you using?
Can you also share an OBS log file?

**Comment by vicvanblack** [comment]
From scene 1 to scene 2 i dont use  transition.
Name:macro1
If scene1 is there
So scene 2
Run
Crash. I dont know what say...
In other scene i use stinger is video (2 seconds)

Il Dom 28 Mag 2023, 19:53 WarmUpTill ***@***.***> ha scritto:

**Comment by vicvanblack** [comment]
I dont know if tomorrow i have time but maybe i can try to record video and
give you with my link. :s

Il Dom 28 Mag 2023, 20:10 Antonio Cesario ***@***.***> ha
scritto:

**Comment by WarmUpTill** [comment]
A video is not strictly required but can't hurt.
I think the most useful information for me right now would be an export of your settings (General tab) and a log file running the build I shared (not to be confused with the crash logs).

Thanks a lot for your help in getting this sorted out! :)

**Comment by vicvanblack** [comment]
I am attaching the plugin settings file that I exported and a screenshot of the error including the crash.
As for "a log file running the build I shared (not to be confused with the crash logs)" I honestly don't know how to provide it to you, I haven't figured out how to recover it. If I can do anything else let me know. Thanks,.

[Crash 2023-05-29 17-00-04.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11592680/Crash.2023-05-29.17-00-04.txt)

[adv-ss-Vicvanblack_2023.05.29.16.54.47.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11592682/adv-ss-Vicvanblack_2023.05.29.16.54.47.txt)

![2023-05-29 170039](https://github.com/WarmUpTill/SceneSwitcher/assets/134687245/c3c99996-e654-4a12-ae06-7ba796c56bb9)

**Comment by WarmUpTill** [comment]
Hm ... have you maybe mixed something up by accident?
The settings file shows that you are still using version 1.22.1 and not the [build ](https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5100137536?pr=762) I linked to above, which contains the fix.
