### ISSUE TITLE
Can MIDI read as a Variable to change other thing>

### ISSUE THREAD

**Issue by KalamityStorm** [WarmUpTill/SceneSwitcher#774]
hi,i've found this version of Scene Switcher can read MIDI Signal.
but it only can read by a fixed number.
eg. in the past i uses OBS-MIDI plugin,it can read MIDI slider(0-127) as a variable to change sound or as a transition position.
now i can only uses keys to change ON/OFF,not as a variable number.

is there anyway can let Scene Switcher read as a variable number? thx!

**Comment by WarmUpTill** [comment]
Here is an example how to use the values of a MIDI control change message to control the volume of an audio source in OBS:

![MidiVolume](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/cfc5668d-08dc-4a15-a82c-dc7bc40a4cb0)

Here it is in action:

![example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a5c26961-04cf-4437-98c6-ab8e46b6005e)

The exact values to use will of course differ for your setup.
Let me know if you have questions!

**Comment by WarmUpTill** [comment]
I agree that assigning values to variables is not really set up intuitively at the moment.
Unfortunately I could not yet think of a good solution which does not involve too much work.

I will try to think of something again, but I can't promise anything soon.

>Math
Change Y(0-128) to Z(0 to 100)
(if set volume to 128,it will be large than default max volume 100,so i suggestion change to 100)

The value ranging from 0-128 instead of from 0-100 is just a consequence of how midi messages are structured.

You can scale this value to a 0-100 scale by performing the following operation.
![Variable](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/72baf217-61da-47aa-94b6-8f2bcdf45f98)

**Comment by KalamityStorm** [comment]
yeah,thanks for your help
i'm trying this version od MIDI first.

**Comment by DFWJunior** [comment]
hi did this function failed in latest version?
i cannot use this

**Comment by WarmUpTill** [comment]
There were some changes in how the plugin handles MIDI messages.
They are now buffered to avoid messages being missed.

I assume all you need to do is to lower the interval value (1) to e.g. 10ms on the General tab to ensure that the buffer is processed quickly enough.

![](https://private-user-images.githubusercontent.com/19472752/287486727-ff136e4b-cc35-47ba-b439-7a573e2eefd2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU0NjcsIm5iZiI6MTcxODQ1NTE2NywicGF0aCI6Ii8xOTQ3Mjc1Mi8yODc0ODY3MjctZmYxMzZlNGItY2MzNS00N2JhLWI0MzktN2E1NzNlMmVlZmQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMzAzYjBmNjA2NTg0ZjNmMjM4ZTJlZWMyMmM2YjNjMDkzODhmNzk3M2JmOWM2NDhjMDE5OWFiMjBjNzNjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuGAoGoY7SfFHiNE9kR-D2LTyVeW86Q_zg6BFLJSe6Q)

**Comment by DFWJunior** [comment]
> There were some changes in how the plugin handles MIDI messages. They are now buffered to avoid messages being missed.
> 
> I assume all you need to do is to lower the interval value (1) to e.g. 10ms on the General tab to ensure that the buffer is processed quickly enough.
> 
> ![](https://private-user-images.githubusercontent.com/19472752/287486727-ff136e4b-cc35-47ba-b439-7a573e2eefd2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU0NjcsIm5iZiI6MTcxODQ1NTE2NywicGF0aCI6Ii8xOTQ3Mjc1Mi8yODc0ODY3MjctZmYxMzZlNGItY2MzNS00N2JhLWI0MzktN2E1NzNlMmVlZmQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMzAzYjBmNjA2NTg0ZjNmMjM4ZTJlZWMyMmM2YjNjMDkzODhmNzk3M2JmOWM2NDhjMDE5OWFiMjBjNzNjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uuGAoGoY7SfFHiNE9kR-D2LTyVeW86Q_zg6BFLJSe6Q)

i've check it
but it still can be stucked in sometimes
not as well as old version

**Comment by DFWJunior** [comment]
i'll record my test result later
the fact is the newest version's MIDI function isn't really smooth as old version
is this caused by new buffed system?

**Comment by DFWJunior** [comment]
well i've test this version
MIDI Audio Function is totally failed.
