### ISSUE TITLE
Please, add a way to disable calls to external projects when building

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#779]
Hi @WarmUpTill,

Yesterday I uploaded the version 1.22.1 to Debian. Debian build servers can't catch any file from Internet (network isolation for the build process). Thus, I got the following error in all architectures:

```
CMake Error at src/macro-external/midi/CMakeLists.txt:13 (add_subdirectory):
  The source directory

    /<<PKGBUILDDIR>>/deps/libremidi

  does not contain a CMakeLists.txt file.
```

![buildd](https://github.com/WarmUpTill/SceneSwitcher/assets/6435502/1c8acbf8-a204-4bc0-8d6d-929ec4a581cf)

The right way is to package the project "jcelerier/libremidi" in Debian, but I don't intend to package it (maybe I make it in a future, but the project has no releases and I think this project may be a bit abandoned). To make the build possible, I made a patch to disable the call for libremidi:

```
--- obs-advanced-scene-switcher.orig/src/macro-external/CMakeLists.txt
+++ obs-advanced-scene-switcher/src/macro-external/CMakeLists.txt
@@ -17,6 +17,6 @@ install_advss_plugin_dependency(...)
 ... to install the plugin and its dependencies.
 #]]
 
-add_subdirectory(midi)
+#add_subdirectory(midi)
 add_subdirectory(openvr)
 add_subdirectory(video)
```

Could you to add an extra option to CMakelist.txt to ignore external calls?

**Comment by WarmUpTill** [comment]
Hello,
sorry about the trouble on your end and the the delayed reply!

I will add the option to disable individual plugins with https://github.com/WarmUpTill/SceneSwitcher/pull/783/commits/71d36f84f9ecaa0afd2cda497a09d4915edc0824.
That should work for you, right?

Just a note regarding libremidi.
I chose this library as it was also used by [a different OBS plugin](https://github.com/nhielost/obs-midi-mg/).
I am however open to suggestions regarding the use of a different MIDI library.

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

Sorry for my delay, I was travelling. Yes, the 71d36f8 is a solution for me. However, I saw that you changed this solution and the libopencv isn't needed to build from now, unless we add an external code. Could you confirm this status?

**Comment by WarmUpTill** [comment]
No worries!

Yes, OpenCV has not been a strict requirement for a while.
But without it some functionality will be lost.

However the issue you encountered above was not related to OpenCV, but "libremidi" instead. (which should be resolved with the linked PR)

**Comment by eribertomota** [comment]
Thanks for the clarification. I will keep the opencv as a build dependency.
