### ISSUE TITLE
[feature request] Add device (dis)connected condition/event

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#788]
**Is your feature request related to a problem? Please describe.**
There's no way to automatize device switches, when e.g. headphones battery runs out and the device switches to something else.

**Describe the solution you'd like**
Would be nice if there was a condition/event that allows you to detect device (dis)connection and execute some actions like scene switches or source visibilit change based on it.

**Describe alternatives you've considered**
I can't think of any.

**Comment by WarmUpTill** [comment]
The requested functionality was implemented for USB devices.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/041b0751-052f-49e7-ae93-4f75dbb96ac0)

Support for non-USB devices might be tricky to implement cross-platform.
But if it is required I might look into it.

Sorry for not getting around to this sooner.

**Comment by Destroy666x** [comment]
BlueTooth would be great too at some point, but USB covers most streaming related devices indeed, thanks
