### ISSUE TITLE
HTTP Header character limit too short

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#791]
**Describe the bug**
The Http action Headers only allow for 170 characters max. This is too short for me to be able to use a very long, long live token for authentication.

Also when the characters are long enough that it creates a horizontal scroll bar, you can no longer easily see additional headers.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/44917135/811770c8-7660-41c2-b7d1-189247f634a1)

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/44917135/599eda6f-8727-40d6-8dc4-3a55fce8bf40)

**To Reproduce**
1. Insert a header longer than 170 characters, and it will only insert the first 170 characters.
2. Create a second header and you'll no longer be able to easily see the first header and vice versa.

**Additional context**
I'm trying to use the Home Assistant REST API and I have to use a bearer authentication token. Home Assistants long live tokens are very long, as such I can't authenticate using the Http action due to these constraints with character limit.

A minor thing worth mentioning as well is that the action should probably be called HTTP not Http.

I'm using Windows 11, OBS 29.1.3 and AdvSS build a17d8f7

**Comment by WarmUpTill** [comment]
Thanks for raising the issue!

A fix for the functional limitation will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5615275995?pr=793

I will try to look into the UI issue on the weekend.

**Comment by WarmUpTill** [comment]
A build with a fix for the UI issue should become available here in about 30 minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5626428755

**Comment by BenJamesAndo** [comment]
Thanks. Works great now.
