### ISSUE TITLE
[feature request] Support for custom Websocket URLs

### ISSUE THREAD

**Issue by ellitedev** [WarmUpTill/SceneSwitcher#795]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to send websocket messages from SS to [VNyan](https://suvidriel.itch.io/vnyan). VNyan has it's receiving URL at `ws://localhost:port/vnyan` and takes no password. With the way URLs are constructed right now, it's impossible to connect.

**Describe the solution you'd like**
I'd like to be able to send Websocket messages to programs like VNyan that use a similair URL. Or to be able to toggle advanced or simple mode for websocket settings UI. Let users choose if they want the URL built for them, or if they want to supply it themselves as is.

**Describe alternatives you've considered**
I've considered using hotkeys instead, but they seem to be quite error prone and more like a band-aid fix than an actual solution.

**Additional context**
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/46927093/66fbbd20-2e62-4cba-97dc-8083ad7f64a9)

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!
I will look into it (hopefully in the next few days).

**Comment by WarmUpTill** [comment]
A first build with the requested functionality is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5668811327

Let me know if this works as you would expect it to! :)

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/289fff20-9f03-42af-b5ec-851c52050ef0)

**Comment by ellitedev** [comment]
That works perfectly!

**Comment by ellitedev** [comment]
Small issue i noticed, when adding a new websocket action, it'll first claim the connection is invalid:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/46927093/6aed6547-396b-493f-a818-28c126bdcfbf)

Clicking add new and cancelling the dialogs fixes this issue:
![obs64_wOQXeartn3](https://github.com/WarmUpTill/SceneSwitcher/assets/46927093/1147dcba-5f8b-4d21-bc60-4164804cdbaf)

**Comment by WarmUpTill** [comment]
> That works perfectly!

That is good to hear! :)
Thanks for the fast feedback!


> Small issue i noticed, when adding a new websocket action, it'll first claim the connection is invalid: ![image](https://user-images.githubusercontent.com/46927093/256489076-6aed6547-396b-493f-a818-28c126bdcfbf.png)
> 
> Clicking add new and cancelling the dialogs fixes this issue: ![obs64_wOQXeartn3](https://user-images.githubusercontent.com/46927093/256489446-1147dcba-5f8b-4d21-bc60-4164804cdbaf.gif)

Thanks for letting me know.
That is a known issue that is fixed on a separate branch.
I will give you a ping here once a build with both changes is available.

**Comment by WarmUpTill** [comment]
A build with the aforementioned fix will be available here in about one hour:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5684497934
