### ISSUE TITLE
OBS build fail on rhel7. 

### ISSUE THREAD

**Issue by firefish13** [WarmUpTill/SceneSwitcher#8]
GLIBCXX_3.4.20 (Latest supported version is GLIBCXX_3.4.19) is not supported in CentOS7 so it is inevitable that whomever what to used this plugin should be download the source and build it. 

OBS build fails on CentOS7 with SceneSwitcher due to missing package. 
I suggest that if the readme include dependent packages. 

In troubleshoot, i found out that libXScrnSaver has to be installed. 
Just leaving comment as if someone might come across the same problem.

**Comment by WarmUpTill** [comment]
info addded to readme - closing (sorry for leaving this open for so long)
