### ISSUE TITLE
[bug]cannot set macro's group correctly.

### ISSUE THREAD

**Issue by KalamityStorm** [WarmUpTill/SceneSwitcher#801]
**Describe the bug**
sometimes when set a macro's group,it will not set the group correctly.

**Logs**
i'll update logs later.

**Version information**
Windows 10 22H2+OBS 29.1.3 +ASS 1.22.1

**Additional context**

**Comment by WarmUpTill** [comment]
There were some recent changes / fixes in regards to group behaviour.
Can you please check if the current development already resolves the problems you are facing?

You can find it here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5694347309
(Note that you have to be logged into GitHub to be able to download it)

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if the problem still persists with the newest release and I will reopen the issue :)
