### ISSUE TITLE
Tick "Perform actions only on condition change" by default in new macros

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#804]
**Is your feature request related to a problem? Please describe.**
`Perform actions only on condition change` is the more popular option there in general, I'm pretty sure. All of my macros so far have it ticked.

Ticking it can also prevent some nasty "soft locks" if the user forgets to tick it themselves. I had that situation yesterday. I set up 2 macros, 1 with a condition of stopped streaming, 1 with stopped recording. The 1st used `cmd /c start link` action, the 2nd `cmd /c start dir`. In the 1st one I ticked the checkbox and it was fine. In the 2nd I forgot and when I ran the macro to test, it hung my entire system, as it was attempting to launch Explorer with some error message infinitely with no easy way to stop it as the Ctrl + Alt + Del menu also hung.

**Describe the solution you'd like**
Tick `Perform actions only on condition change` chckbox by default in new macros.

**Describe alternatives you've considered**
An alternative is to never forget to tick it yourself ofc, but I just fail to see why the fact that it's not ticked is better.

**Additional context**
-

**Comment by WarmUpTill** [comment]
I agree :)
The change will be included in the next release.
