### ISSUE TITLE
Built in variables?

### ISSUE THREAD

**Issue by tarnis** [WarmUpTill/SceneSwitcher#808]
I don't know that my problem is my perceived problem...but at least supply an example on this one.  It seems like basic functionality.

I'm trying to create a screenshot, but it keeps naming them and same and overwriting the old ones.  I'm suspecting I need a variable in the name that provides a counter or better yet the date...looking at the help I'm not getting too far on variables and my use case though which seems like something that should just be included.

**Comment by WarmUpTill** [comment]
Variables are supported. :)
Have a look at this discussion for an example:
https://github.com/WarmUpTill/SceneSwitcher/discussions/796

**Comment by tarnis** [comment]
Thankyou!  I get where you're going...it's sorta what I was thinking but I'm not getting there :)  If I put quotes in the path for the file name on the screenshot it won't grab a screenshot...tried it with curly brackets, single quotes and nothing has worked.  Most of the variable examples are using double quotes in curly brackets that I see.

Here's what I have:
![time var](https://github.com/WarmUpTill/SceneSwitcher/assets/22822314/c1889dc4-c414-4672-a9b1-86d1c5d02aff)


![screenshot](https://github.com/WarmUpTill/SceneSwitcher/assets/22822314/d4d1f056-a24c-497a-a6d6-c28e8ac938f0)

**Comment by WarmUpTill** [comment]
Almost there, just a few minor problems :)

* In the macro named "Time Variable" you are modifying the variable named "counter".
In the "Screenshot Display 1" macro you not using the variable named "counter". 
(You seem to have tried to use the name of the _macro_ instead)
* The [syntax ](https://github.com/WarmUpTill/SceneSwitcher/wiki/Variables#using-variables)for using variables is a bit different to what you are doing.
You should start with `${`, then follow it up with the name of the variable, then use a `}`.
So in your specific example it would be: `C:/Users/Sim/Videos/map/map_${counter}.jpg`.

  In case you used the quotation marks intentionally, please note that Windows does not allow using them for filenames.

**Comment by tarnis** [comment]
Thankyou for your response,

I get it but I don't get it :)  It sounds like I'm just changing the path to reflect counter.  I had actually tried that initially along with a bunch of different "formatting options" none of which worked and I took a screenshot of what I did in the end.

Either way, by just changing the file path to C:/Users/Sim/Videos/map/map_${counter}.jpg it doesn't save anything...I'm guessing it doesn't like the syntax for a file path?

Thanks again!

**Comment by WarmUpTill** [comment]
> I had actually tried that initially along with a bunch of different "formatting options" none of which worked and I took a screenshot of what I did in the end.

The plugin only supports this the `${variable name here}` syntax.
It does not support the `%` placeholders used elsewhere in OBS.

>Either way, by just changing the file path to C:/Users/Sim/Videos/map/map_${counter}.jpg it doesn't save anything...I'm guessing it doesn't like the syntax for a file path?

Unfortunately, it is a bit difficult to say what is going wrong.

Depending on what is stored in the "counter" variable the path might once again be invalid and thus writing the screenshot could fail.

Windows forbids the use of the following characters in paths:
```
<
>
:
"
/
\
|
?
*
```

It might also be a permission issue.
Can the screenshot be written successfully if you use a path without any variable?

**Comment by tarnis** [comment]
Thankyou, I got it now.  Had it also print the variable to the status window and it had : in it.  I added a find/replace action at the bottom to replace the : with a -.

Appreciate your help!
