### ISSUE TITLE
When OBS is set to "Always on top" and you delete a macro, if the warning dialogue box is under the Advanced Scene Switcher box, the program softlocks

### ISSUE THREAD

**Issue by moswald14** [WarmUpTill/SceneSwitcher#813]
**Describe the bug**
When OBS is set to "Always on top" and you delete a macro, if the warning dialogue box is under the Advanced Scene Switcher box, the program softlocks

**To Reproduce**
1. Go to view in obs and click on "Always on top"
2. Open advanced scene switcher and delete a macro
3. Program softlocks and has to be terminated forcibly.

**Expected behavior**
the dialogue box should be on top

**Version information**
Windows 10 22H2

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
A build with a fix should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5776081816?pr=814

Can you please test this on your end and confirm that it resolves the problem?

What happened is that the confirmation dialog shown when macros are being deleted was created _behind_ the OBS window, as it was configured to be always on top.
Those confirmation dialogs have the input focus with no obvious way to interact with them, leading to the impression that OBS is frozen. (Interacting with them using the keyboard would still work)

**Comment by moswald14** [comment]
tested the build and it's fixed! thanks!
