### ISSUE TITLE
obs crashes macro runs to start streaming

### ISSUE THREAD

**Issue by vital121** [WarmUpTill/SceneSwitcher#816]
**Describe the bug**
obs crashes macro runs

**To Reproduce**
goto tools
choose advanced scene switcher
add macro
if streaming 
stream stopped
and video
source game capture has changed
tick use patten match
add action
streaming start streaming

**Expected behavior**
start streaming when motion detected on video

**Logs**
Please provide a log of your issue with verbose logging enabled (See General tab of the plugin).  
https://obsproject.com/logs/pMOnW4Sp7lyfk7Be

Please share the currently used plugin settings by exporting them them to a file (See General tab of the plugin).  
{"sceneGroups":[],"macroProperties":{"highlightExecuted":false,"highlightConditions":false,"highlightActions":false,"newMacroRegisterHotkey":false},"macros":[{"name":"auto start","pause":true,"parallel":false,"onChange":true,"group":false,"dockSettings":{"register":false,"hasRunButton":true,"hasPauseButton":true,"hasStatusLabel":false,"highlightIfConditionsTrue":false,"runButtonText":"Run","pauseButtonText":"Pause","unpauseButtonText":"Unpause","conditionsTrueStatusText":"Conditions are true.","conditionsFalseStatusText":"Conditions are false."},"registerHotkeys":false,"pauseHotkey":[],"unpauseHotkey":[],"togglePauseHotkey":[],"conditions":[{"collapsed":false,"id":"video","logic":0,"durationModifier":{"time_constraint":0,"seconds":{"value":{"value":3.0,"type":0},"unit":0,"version":1}},"videoInputData":{"type":2,"source":{"type":0,"name":""},"sceneSelection":{"type":3}},"condition":3,"filePath":"--enter path--","blockUntilScreenshotDone":false,"brightnessThreshold":{"value":0.5,"type":0},"patternMatchData":{"useForChangedCheck":true,"threshold":{"value":0.94999999999999996,"type":0},"useAlphaAsMask":false,"matchMode":3,"version":1},"objectMatchData":{"modelPath":"../../data/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt.xml","scaleFactor":{"value":1.1000000000000001,"type":0},"minNeighbors":3,"minSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"maxSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"version":1},"ocrData":{"pattern":"--enter text--","regexConfig":{"enable":false,"partial":true,"options":0},"language":"eng","textColor":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.29999999999999999,"type":0},"pageSegMode":6,"version":1},"colorData":{"color":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.10000000000000001,"type":0},"matchThreshold":{"value":0.80000000000000004,"type":0}},"throttleEnabled":false,"throttleCount":3,"areaData":{"enabled":false,"area":{"x":{"value":0,"type":0},"y":{"value":0,"type":0},"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1}}}],"actions":[{"collapsed":false,"id":"streaming","enabled":true,"action":1,"keyFrameInterval":{"value":0,"type":0},"stringValue":""}]},{"name":"auto stop","pause":true,"parallel":false,"onChange":true,"group":false,"dockSettings":{"register":false,"hasRunButton":true,"hasPauseButton":true,"hasStatusLabel":false,"highlightIfConditionsTrue":false,"runButtonText":"Run","pauseButtonText":"Pause","unpauseButtonText":"Unpause","conditionsTrueStatusText":"Conditions are true.","conditionsFalseStatusText":"Conditions are false."},"registerHotkeys":false,"pauseHotkey":[],"unpauseHotkey":[],"togglePauseHotkey":[],"conditions":[{"collapsed":false,"id":"video","logic":0,"durationModifier":{"time_constraint":1,"seconds":{"value":{"value":3.0,"type":0},"unit":0,"version":1}},"videoInputData":{"type":2,"source":{"type":0,"name":""},"sceneSelection":{"type":3}},"condition":2,"filePath":"--enter path--","blockUntilScreenshotDone":false,"brightnessThreshold":{"value":0.5,"type":0},"patternMatchData":{"useForChangedCheck":true,"threshold":{"value":0.94999999999999996,"type":0},"useAlphaAsMask":false,"matchMode":3,"version":1},"objectMatchData":{"modelPath":"../../data/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt.xml","scaleFactor":{"value":1.1000000000000001,"type":0},"minNeighbors":3,"minSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"maxSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"version":1},"ocrData":{"pattern":"--enter text--","regexConfig":{"enable":false,"partial":true,"options":0},"language":"eng","textColor":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.29999999999999999,"type":0},"pageSegMode":6,"version":1},"colorData":{"color":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.10000000000000001,"type":0},"matchThreshold":{"value":0.80000000000000004,"type":0}},"throttleEnabled":false,"throttleCount":3,"areaData":{"enabled":false,"area":{"x":{"value":0,"type":0},"y":{"value":0,"type":0},"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1}}}],"actions":[{"collapsed":false,"id":"streaming","enabled":true,"action":0,"keyFrameInterval":{"value":0,"type":0},"stringValue":""}]},{"name":"Macro 1","pause":false,"parallel":false,"onChange":true,"group":false,"dockSettings":{"register":false,"hasRunButton":true,"hasPauseButton":true,"hasStatusLabel":false,"highlightIfConditionsTrue":false,"runButtonText":"Run","pauseButtonText":"Pause","unpauseButtonText":"Unpause","conditionsTrueStatusText":"Conditions are true.","conditionsFalseStatusText":"Conditions are false."},"registerHotkeys":false,"pauseHotkey":[],"unpauseHotkey":[],"togglePauseHotkey":[],"conditions":[{"collapsed":false,"id":"streaming","logic":0,"durationModifier":{"time_constraint":0,"seconds":{"value":{"value":0.0,"type":0},"unit":0,"version":1}},"state":0,"keyFrameInterval":{"value":0,"type":0}},{"collapsed":false,"id":"video","logic":101,"durationModifier":{"time_constraint":0,"seconds":{"value":{"value":0.0,"type":0},"unit":0,"version":1}},"videoInputData":{"type":1,"source":{"type":0,"name":"Game Capture fd"},"sceneSelection":{"type":0,"name":""}},"condition":3,"filePath":"--enter path--","blockUntilScreenshotDone":false,"brightnessThreshold":{"value":0.5,"type":0},"patternMatchData":{"useForChangedCheck":true,"threshold":{"value":0.80000000000000004,"type":0},"useAlphaAsMask":false,"matchMode":3,"version":1},"objectMatchData":{"modelPath":"../../data/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt.xml","scaleFactor":{"value":1.1000000000000001,"type":0},"minNeighbors":3,"minSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"maxSize":{"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1},"version":1},"ocrData":{"pattern":"--enter text--","regexConfig":{"enable":false,"partial":true,"options":0},"language":"eng","textColor":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.29999999999999999,"type":0},"pageSegMode":6,"version":1},"colorData":{"color":{"red":0,"green":0,"blue":0},"colorThreshold":{"value":0.10000000000000001,"type":0},"matchThreshold":{"value":0.80000000000000004,"type":0}},"throttleEnabled":false,"throttleCount":3,"areaData":{"enabled":false,"area":{"x":{"value":0,"type":0},"y":{"value":0,"type":0},"width":{"value":0,"type":0},"height":{"value":0,"type":0},"version":1}}}],"actions":[{"collapsed":false,"id":"streaming","enabled":true,"action":1,"keyFrameInterval":{"value":0,"type":0},"stringValue":""}]}],"connections":[],"variables":[],"switches":[],"ignoreWindows":[],"screenRegion":[],"pauseEntries":[],"sceneRoundTrip":[],"sceneTransitions":[],"defaultTransitions":[],"defTransitionDelay":0,"ignoreIdleWindows":[],"idleTargetType":0,"idleSceneName":"","idleTransitionName":"","idleEnable":false,"idleTime":60,"executableSwitches":[],"randomSwitches":[],"fileSwitches":[],"readEnabled":false,"readPath":"","writeEnabled":false,"writePath":"","mediaSwitches":[],"timeSwitches":[],"audioSwitches":[],"audioFallbackTargetType":0,"audioFallbackScene":"","audioFallbackTransition":"","audioFallbackEnable":false,"audioFallbackDuration":{"value":{"value":0.0,"type":0},"unit":0,"version":1},"videoSwitches":[],"ServerEnabled":false,"ServerPort":55555,"LockToIPv4":false,"ClientEnabled":false,"Address":"","ClientPort":55555,"SendSceneChange":true,"SendSceneChangeAll":true,"SendPreview":true,"triggers":[],"interval":300,"non_matching_scene":"","switch_if_not_matching":0,"noMatchDelay":{"value":{"value":0.0,"type":0},"unit":0,"version":1},"cooldown":{"value":{"value":0.0,"type":0},"unit":0,"version":1},"active":false,"startup_behavior":0,"autoStartEvent":0,"verbose":false,"showSystemTrayNotifications":false,"disableHints":false,"warnPluginLoadFailure":true,"hideLegacyTabs":true,"priority0":10,"priority1":0,"priority2":2,"priority3":8,"priority4":6,"priority5":9,"priority6":7,"priority7":4,"priority8":1,"priority9":5,"priority10":3,"threadPriority":3,"transitionOverrideOverride":false,"adjustActiveTransitionType":true,"lastImportPath":"","startHotkey":[],"stopHotkey":[],"toggleHotkey":[],"upMacroSegmentHotkey":[],"downMacroSegmentHotkey":[],"removeMacroSegmentHotkey":[],"generalTabPos":0,"macroTabPos":1,"transitionTabPos":15,"pauseTabPos":16,"titleTabPos":2,"exeTabPos":3,"regionTabPos":4,"mediaTabPos":5,"fileTabPos":6,"randomTabPos":7,"timeTabPos":8,"idleTabPos":9,"sequenceTabPos":10,"audioTabPos":11,"videoTabPos":12,"networkTabPos":13,"sceneGroupTabPos":14,"triggerTabPos":17,"saveWindowGeo":false,"windowPosX":2262,"windowPosY":1197,"windowWidth":1000,"windowHeight":600,"macroActionConditionSplitterPosition":[{"pos":147},{"pos":236}],"macroListMacroEditSplitterPosition":[{"pos":144},{"pos":829}],"version":"666c52556e241357554b56a8d33eed78d483f426"}

**Version information**
 - OS: Windows 11
 - OBS Version 29.1.3
 - Plugin Version 1.23.0

**Comment by vital121** [comment]
doent crash if it uncheck use patten matching

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue!
Can you also share the _crash_ log? (not just the log itself)

**Comment by vital121** [comment]
[Crash 2023-08-07 14-35-00.txt](https://github.com/WarmUpTill/SceneSwitcher/files/12282468/Crash.2023-08-07.14-35-00.txt)

**Comment by WarmUpTill** [comment]
I think I found the issue.
A build with a fix will be available here in about 30 minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5787814390?pr=817

I would appreciate if you could give this a try and confirm if the problem is resolved on your end as well!

Thanks again for reporting the crash!

**Comment by vital121** [comment]
says This job was skipped

**Comment by vital121** [comment]
found it and installed fixed crash

but seems to not start streaming when motion on video heres the settings im using

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/123862035/89e3dbf4-668a-483e-9fb6-cbfe32864399)

**Comment by vital121** [comment]
also if i check "Perform check only in area" then select the area it crashes since installing patched version

**Comment by vital121** [comment]
hi 
thanks its not crashing now.
but its not detecting motion with these settings
![Screenshot 2023-08-09 205931](https://github.com/WarmUpTill/SceneSwitcher/assets/123862035/9fa9f48a-d033-4de1-8415-84dd55d44a80)
![Screenshot 2023-08-09 210101](https://github.com/WarmUpTill/SceneSwitcher/assets/123862035/07b9f41e-0642-42e0-8947-695014fab1b2)

**Comment by WarmUpTill** [comment]
>thanks its not crashing now.

Thanks a lot for the confirmation!

>but its not detecting motion with these settings

As mentioned before the "Threshold" value should be much closer to "1" in that case - a value of "0.8" is way to lenient for motion detection in a video stream.

Try something like "0.99" to start with and only if that detects too much motion (i.e. the condition is true too often for your use case) move it down to "0.98" and so on.
