### ISSUE TITLE
[Feature Request] Open/Close Application

### ISSUE THREAD

**Issue by andrewcartwright1** [WarmUpTill/SceneSwitcher#820]
**Is your feature request related to a problem? Please describe.**
This is more of a nice to have to help me out when it comes to raiding out to someone, but would be cool!

Would it be possible to create an action to fully close an application? I can see that there is a window condition?

The context for my request is... When I raid out to another streamer, I struggle to multi task in saying hi to the streamer and listening to what they have to say because pretzel is still playing music - I use streamer.bot to stop obs after my raid has been sent, so then once it has been sent and stream is stopped a macro could run to kill pretzel

EDIT: Updated to include Open - https://obsproject.com/forum/threads/obs-autostarter.142827/ , I've been using this to open apps such as pretzel, streamer.bot and touch portal - would be nice if this plugin managed that too instead of another script, also wondering if we'd be able to open apps minimized?

**Describe the solution you'd like**
I would like to be able to create a macro with the following conditions

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/10059155/2270b89d-059b-4e0c-90af-083faf36a3b9)

and as an action I would like to be able to terminate a application - in this case pretzel rocks

**Describe alternatives you've considered**
I noticed touch portal has a event for when obs is stopped so I tried that, but I found that it kept closing Pretzel in advance. I've also thought about writing a method for streamer.bot to do this, but it would require me to wait and there is a possibility that the stream is not yet in the "stopped" status

Thank you very much for such an amazing obs plugin!

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

You can already open and close applications using the "Run" action type.

The first action in the screenshot below starts the Notepad application.
The second action closes all open Notepad windows.

![OpenClose](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/43e2f398-5c91-4268-8b9a-1295b5bd0da9)

Note that if you are on MacOS or Linux the commands will be slightly different of course.

Does this already solve your issue?
Let me know if you have any questions!

**Comment by andrewcartwright1** [comment]
Hero!

Thank you very much :D
