### ISSUE TITLE
Small redesign suggestion - open macros by default, show the start/stop button always on top

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#824]
**Is your feature request related to a problem? Please describe.**
Going back and forth between configuration and OBS can be a little annoying and time-taking with unnecessary step(s).

**Describe the solution you'd like**
I think it'd be better for optimal testing speed to save time with:
- `Macros` tab opened by default instead of `General`, which you usually configure only once or once a while
- plugin (de)activation button moved to the top/bottom globally, e.g. here:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/3606072/0b6ed504-8ac1-4aed-a670-fd97519ae2ff)

**Describe alternatives you've considered**
I think this would be the cleanest design.

**Comment by WarmUpTill** [comment]
>Macros tab opened by default instead of General, which you usually configure only once or once a while

The plugin does remember the last opened tab.
It only resets the last opened tab to the general tab when OBS is restarted or the scene collection is changed.

>plugin (de)activation button moved to the top/bottom globally, e.g. here

Have you considered relying on the "Advanced scene switcher" dock widget instead?

![OpenSettings](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/b310c7fe-5ed2-4caa-90d6-ff7a8af4e7ab)

Sorry about the delayed reply!

**Comment by Destroy666x** [comment]
No problem. It doesn't seem to remember it for me, at least sometimes. Could it be also done cross-session between OBS launches?

**Comment by WarmUpTill** [comment]
>Could it be also done cross-session between OBS launches?

The main reason why I have not yet done this, is that I would need to handle the "legacy tabs" as well.
But that shouldn't be too difficult, so I will look into it.

**Comment by Destroy666x** [comment]
I think the state is remembered now or Macro tab opened by default, so closing, as the stop/start button isn't that important and can't be done in a dock.
