### ISSUE TITLE
Weird docker file system question

### ISSUE THREAD

**Issue by specked** [WarmUpTill/SceneSwitcher#826]
Hi, I'm using someones existing docker as a base and have been modifying it. I'm trying to get this plugin installed but the file structure is nothing like what I'm able to find in the closed tickets or form posts. My plugins folder is at /usr/lib/x86_64-linux-gnu/obs-plugins/

I've created a "advanced-scan-switcher" folder in this location and placed the 64bit folder and the data folder under that (see screen shot)

Could you advise me on what to try? Thank you

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/1870392/a8ec3d49-de07-459f-bbc7-22de8cc0b072)

**Comment by WarmUpTill** [comment]
I would suggest to install the *.deb file if that is an option for your docker environment:
`sudo apt install /path/to/advanced-scene-switcher-linux-x86_64.deb `

If you must manually install the plugin I would _assume_ the the correct location for the files is:
```
/usr/
/usr/lib/
/usr/lib/x86_64-linux-gnu/
/usr/lib/x86_64-linux-gnu/obs-plugins/
/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/
/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-midi.so
/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so
/usr/lib/x86_64-linux-gnu/obs-plugins/advanced-scene-switcher-lib.so -> advanced-scene-switcher-lib.so.1
/usr/lib/x86_64-linux-gnu/obs-plugins/advanced-scene-switcher-lib.so.1
/usr/lib/x86_64-linux-gnu/obs-plugins/advanced-scene-switcher.so
/usr/share/
/usr/share/obs/
/usr/share/obs/obs-plugins/
/usr/share/obs/obs-plugins/advanced-scene-switcher/
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/de-DE.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/en-US.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/es-ES.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/ru-RU.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/tr-TR.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/locale/zh-CN.ini
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_eye.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_eye_tree_eyeglasses.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt2.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_alt_tree.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_frontalface_default.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_fullbody.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_lefteye_2splits.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_lowerbody.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_profileface.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_righteye_2splits.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/cascadeClassifiers/haarcascade_upperbody.xml
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkAdvanced.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkDoubleDown.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkDoubleUp.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkGroup.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkNote.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkRegex.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/DarkTime.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightAdvanced.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightDoubleDown.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightDoubleUp.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightGroup.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightNote.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightRegex.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/images/LightTime.svg
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/ocr/
/usr/share/obs/obs-plugins/advanced-scene-switcher/res/ocr/eng.traineddata
```

Hope that helps! :)

**Comment by specked** [comment]
@WarmUpTill Thank you for the good idea! I performed the installation by adding these commands to my dockerfile:

`# Add Advanced Scene Switcher to OBS
RUN wget -P /tmp/ https://github.com/WarmUpTill/SceneSwitcher/releases/dow>
RUN add-apt-repository ppa:okirby/qt6-backports && apt update
RUN apt install -y libqt6core6 libqt6gui6 libqt6widgets6 /tmp/advanced-sce>
RUN rm /tmp/advanced-scene-switcher-linux-x86_64.deb
`
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/1870392/b3d5629a-806b-477e-9900-10b2f0b2e6fe)
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/1870392/e73489f8-47c4-47b8-87fa-e5c79ef6ab25)


However, I still don't see it from OBS:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/1870392/5cc8e59f-2d46-4914-9ae8-40e2027cece6)

Any additional suggestions will be appreciated. Thank you.

**Comment by specked** [comment]
`
18:36:21.764: Using EGL/X11
18:36:21.764: CPU Name: AMD Ryzen Threadripper 1920X 12-Core Processor
18:36:21.764: CPU Speed: 2168.290MHz
18:36:21.765: Physical Cores: 12, Logical Cores: 24
18:36:21.765: Physical Memory: 64153MB Total, 14249MB Free
18:36:21.765: Kernel Version: Linux 6.1.38-Unraid
18:36:21.766: Distribution: "Ubuntu" "20.04"
18:36:21.766: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
18:36:21.767: Qt Version: 5.12.8 (runtime), 5.12.8 (compiled)
18:36:21.767: Portable mode: false
18:36:21.809: OBS 29.1.3 (linux)
18:36:21.809: ---------------------------------
18:36:21.810: ---------------------------------
18:36:21.810: audio settings reset:
18:36:21.810:   samples per sec: 48000
18:36:21.810:   speakers:        2
18:36:21.810:   max buffering:   960 milliseconds
18:36:21.810:   buffering type:  dynamically increasing
18:36:21.819: ---------------------------------
18:36:21.819: Initializing OpenGL...
18:36:21.868: Loading up OpenGL on adapter Mesa/X.org llvmpipe (LLVM 12.0.0, 256 bits)
18:36:21.868: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 21.2.6, shading language 4.50
18:36:22.068: ---------------------------------
18:36:22.068: video settings reset:
18:36:22.068:   base resolution:   1920x1080
18:36:22.068:   output resolution: 1920x1080
18:36:22.068:   downscale filter:  Bicubic
18:36:22.068:   fps:               30/1
18:36:22.068:   format:            NV12
18:36:22.068:   YUV mode:          Rec. 709/Partial
18:36:22.069: NV12 texture support not available
18:36:22.069: P010 texture support not available
18:36:22.078: Audio monitoring device:
18:36:22.078:   name: Default
18:36:22.078:   id: default
18:36:22.079: ---------------------------------
18:36:22.085: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so->/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so): /usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so: undefined symbol: __libc_single_threaded
18:36:22.085:
18:36:22.086: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so' not loaded
18:36:22.091: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so->/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so): /usr//lib/x86_64-linux-gnu/obs-plugins/aja.so: undefined symbol: __libc_single_threaded
18:36:22.091:
18:36:22.091: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so' not loaded
18:36:22.093: Failed to load 'en-US' text for module: 'decklink-captions.so'
18:36:22.095: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
18:36:22.097: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
18:36:22.097: Failed to initialize module 'decklink.so'
18:36:22.246: v4l2loopback not installed, virtual camera disabled
18:36:22.249: [obs-browser]: Version 2.21.1
18:36:22.249: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
18:36:22.307: FFmpeg VAAPI H264 encoding not supported
18:36:22.307: FFmpeg VAAPI HEVC encoding not supported
18:36:22.319: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.2.3 | RPC Version: 1)
18:36:22.319: [obs-websocket] [obs_module_load] Qt version (compile-time): 5.12.8 | Qt version (run-time): 5.12.8
18:36:22.319: [obs-websocket] [obs_module_load] Linked ASIO Version: 101202
18:36:22.326: [obs-websocket] [obs_module_load] Module loaded.
18:36:22.339: [vlc-video]: VLC 3.0.9.2 Vetinari found, VLC video source enabled
18:36:22.341: ---------------------------------
18:36:22.341:   Loaded Modules:
18:36:22.341:     vlc-video.so
18:36:22.341:     text-freetype2.so
18:36:22.341:     rtmp-services.so
18:36:22.341:     obs-x264.so
18:36:22.341:     obs-websocket.so
18:36:22.341:     obs-vst.so
18:36:22.341:     obs-transitions.so
18:36:22.342:     obs-outputs.so
18:36:22.342:     obs-libfdk.so
18:36:22.342:     obs-filters.so
18:36:22.342:     obs-ffmpeg.so
18:36:22.342:     obs-browser.so
18:36:22.342:     linux-v4l2.so
18:36:22.342:     linux-pulseaudio.so
18:36:22.342:     linux-jack.so
18:36:22.342:     linux-capture.so
18:36:22.342:     linux-alsa.so
18:36:22.342:     image-source.so
18:36:22.342:     frontend-tools.so
18:36:22.342:     decklink-output-ui.so
18:36:22.343:     decklink-captions.so
18:36:22.343: ---------------------------------
18:36:22.343: ==== Startup complete ===============================================
18:36:22.387: All scene data cleared
18:36:22.388: ------------------------------------------------
18:36:22.413: Switched to scene 'Scene'
18:36:22.413: ------------------------------------------------
18:36:22.413: Loaded scenes:
18:36:22.414: - scene 'Scene':
18:36:22.414: - scene 'BRB':
18:36:22.414:     - source: 'clips' (vlc_source)
18:36:22.414: ------------------------------------------------
`

**Comment by WarmUpTill** [comment]
Unless I am missing something the plugin is _not_ being loaded.
So I assume that the binaries are still in the wrong location.

I would suggest to try to move the *.so files into the directory of the plugins that are attempted to be loaded. (So directly into`/usr/lib/x86_64-linux-gnu/obs-plugins/` without any sub directories)

Does that change anything?

**Comment by specked** [comment]
Thank for your help. I'm going to just create a docker from scratch and do it clean. Thanks.

**Comment by WarmUpTill** [comment]
No worries - le me know if you still run into issues and I will try to support!
