### ISSUE TITLE
Request: Audio Scene Switching

### ISSUE THREAD

**Issue by KJThaDon** [WarmUpTill/SceneSwitcher#83]
Hello, I've been trying to find a solution for this for almost a year now, so I'm hoping you can help

Would it be possible to have a scene auto switch when no audio is detected for x amount of time? then scene it switches to will play a media file and and switch back to the original scene after the file has completed.

Or it could switch to the media scene when no audio is detected for x amount of time and switch back when audio is detected from that audio input source again.

Thank you!

**Comment by WarmUpTill** [comment]
Adding a "if no audio is played" condition seems like a good idea.
I will investigate if that is feasible. 

Thanks for the suggestion!

>then scene it switches to will play a media file and and switch back to the original scene after the file has completed.

At least that part should be working already, I think :)

**Comment by KJThaDon** [comment]
Awesome, looking forward to it. Thank you!

**Comment by WarmUpTill** [comment]
I added a first draft of this functionality here with https://github.com/WarmUpTill/SceneSwitcher/pull/85/commits/b95f1c85daea6066174461e2f71655453ce37953. 

![audio](https://user-images.githubusercontent.com/19472752/102772732-4a886c80-4388-11eb-8083-2687f6dade8f.PNG)

A test build should be available in a couple of minutes here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/435642159

Any feedback would be much appreciated! :)

**Comment by KJThaDon** [comment]
Thank you! Will check it out shortly and let you know. Appreciate it
