### ISSUE TITLE
[feature request] Add "settings changed" Source condition

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#830]
**Is your feature request related to a problem? Please describe.**
Currently you can only match when a settings matches something, with regex partial match, for example. I would like to only know if e.g. `text` property of a text source changed at all, to any value possible.

**Describe the solution you'd like**
Add "settings changed" Source condition that would allow you to enter/choose one or few settings to track and execute actions once all of them change values compared to last execution.

**Describe alternatives you've considered**
I thought matching:
```
"text":\s*".*?"
```
would work for a single setting, but it does nothing, as the condition is always true with `Perform actions only on condition change` checked and false with that checked as the regex is always met.

**Comment by WarmUpTill** [comment]
Sure - a build with the functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5907415021?pr=831

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/4362a4d0-a266-4a72-8b31-d3d3993c3dac)

Let me know if you are facing any issues! :)

**Comment by Destroy666x** [comment]
Seems fine! I noticed no issue. That was a quick one :P Would be great if specific settings were also targettable as mentioned in the issue, though.

**Comment by WarmUpTill** [comment]
Thanks for the test!

In that case I would suggest to assign the current settings to a variable, strip its value down to required region, and finally use the variable condition to check if the value changed.

Let me know if you need more details!
