### ISSUE TITLE
Window action's dropdown doesn't include all windows

### ISSUE THREAD

**Issue by KopiasCsaba** [WarmUpTill/SceneSwitcher#832]
First and foremost, dear developer(s), thank you very much for this truely awesome, well thought through plugin.
We just started to use it, and we are super super happy.

Really appreciate it! Keep up the good work!

**Describe the bug**
Our HDMI setup is quite complex and sometimes changing (devices come online too late, breaking everything), so sometimes we need to re enable the fullscreen projectors. The OBS setting: "save projectors on exit" sadly doesn't help us in this case.

So I thought to make a macro that runs every 10 second, checks if the Full-Screen projector window exists or not, and would start the projector if it isn't  active.

But it's not visible in the dropdown, and the regexp functionality didn't get it either. But on the windows taskbar it definitely has a title, and it is definitely some kind of a window.

So the main bugreport is about this.

The solution could be many fold for our usecase:
 - Have a trigger/watch that checks if a projector exists  on a device (that might be a feature request then)
 - Have the projector action check if it is active already, and not open another one. (If i enable obs' one projector/screen, then it flickers every time it tries to reopen-it)

**To Reproduce**
  1. Open a full-screen projector on a screen
  2. Add a macro
  4. Add a watch that checks for windows

**Expected behavior**
The full-screen projector (might not technically be a window, but acts and looks like that somewhat on the taskbar) window should be listed.
Or the regexp should match it.

**Version information**
 - OS: Windows 10
 - OBS Version 29.1.3
 - Plugin Version 1.23.0 I think.

**Additional context**

Thank you!

**Comment by WarmUpTill** [comment]
Thanks for the suggestion! :)

Last time I checked there there no OBS API to directly check if a projector window already exists, unfortunately.

So I likely will have to go the route of supporting checking the window title of windows created by OBS itself.
I recall that I tried this already in the past, but could not figure out how to get access to the OBS windows in a safe way.
I either ran into deadlocks when calling `GetWindowText` or into crashes when using Qt's `topLevelWidgets`, which is why I resorted to simply [hardcoding the window title to "OBS"](https://github.com/WarmUpTill/SceneSwitcher/blob/master/src/win/advanced-scene-switcher-win.cpp#L136) in such cases.

I will experiment and see if I can maybe find some alternative solution / maybe I am missing something obvious.

**Comment by KopiasCsaba** [comment]
Dear @WarmUpTill,

You are awesome!

Thank you for the swift response, will test it, and get back to you this week!

Cheers,
Csaba

**Comment by KopiasCsaba** [comment]
Dear @WarmUpTill,

Thank you very much, I have tested the build! 

Sadly the Fullscreen projector isn't in the dropdown, see:
![IMG_20230823_185324](https://github.com/WarmUpTill/SceneSwitcher/assets/7661267/df2d5322-39a4-463a-b6a8-0acc9f9fbb3c)

Also when I first installed, the plugin froze OBS, so I think it went like this:
 * Had 1.23.0
 * Installed the new one from your build (With the installer)
 * Upon selecting tools -> Advanced Theme switcher  it immediately froze, even the menu stayed there IIRC.
 * Killed OBS
 * Installed the 1.23.0 again (with the installer)
 * OBS and the plugin was working again
 * Installed your new build again
 * OBS and the plugin was working again
:)


I've started to experiment with a script rather to run that lists the available windows.

`tasklist /fi "windowtitle eq Full-Screen*" | find "obs64.exe"`

Should return 0 or 1 depending if it found the window, but then I hit other issues (#841 and #842).  

Thank you very much!

**Comment by WarmUpTill** [comment]
The implementation I used for the build above once again ran into the freeze issue I originally described.
Sorry about that! I should have spotted that earlier!

I gave it another shot with this build:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5967837322?pr=836

This should now try to get the OBS window list asynchronously and thus avoid the freeze issue with the downside of being slightly delayed.

I would appreciate if you could give this a try.

**Comment by KopiasCsaba** [comment]
Dear @WarmUpTill ,

I have checked it out, and it works great!
I also see now the "Fullscreen Projector (Program)" on the list, which is super awesome! I'm not sure why I didn't saw it previously when I tested on the church machine. I hope it's unrelated, thatn now I tested it on a windows 10 VM :)

So it doesn't freeze, and it seems to work too! I'm excited to test it on the streaming computer too.

One little thing I noticed, that accidentally I installed ASS first and OBS after, so then OBS didn't find the plugin. Just starting the installer of  ASS again didn't solved it, but when I uninstalled with the uninstaller, and installed again, that did the trick. I'm not sure if you want to spend time on this minor thing, just mentioned.:)

Thank you, I will try it on the real machine too and will get back to you!

**Comment by WarmUpTill** [comment]
Thanks a lot for reporting back that it now works! :)

>One little thing I noticed, that accidentally I installed ASS first and OBS after, so then OBS didn't find the plugin. Just starting the installer of ASS again didn't solved it, but when I uninstalled with the uninstaller, and installed again, that did the trick. I'm not sure if you want to spend time on this minor thing, just mentioned.:)

Thanks!
I will not it down, but will probably not get around to it soon.

**Comment by KopiasCsaba** [comment]
Hi! Apparently the latest release does not see the fullscreen projector! What happened what do you think?

**Comment by WarmUpTill** [comment]
The latest official release does not yet contain these changes.
