### ISSUE TITLE
Installer File In Microsoft Download

### ISSUE THREAD

**Issue by Weed420Baby** [WarmUpTill/SceneSwitcher#833]
**Describe the bug**

I just cant find the installer file in the Microsoft download file in the 64 zip. Also when i tried the installer file, it flagged it. even after allowing it through, nothing useful came up. Please help.   

**To Reproduce**
1. Go to '...' https://obsproject.com/forum/resources/advanced-scene-switcher.395/
2. Click on '....' Go To Download
3. Scroll down to '....' Windows x 64 Installer and or Zip

**Expected behavior**

I just want to download the file and it just plugs into OBS. I just need an auto scene change after about 13 seconds. 

**Logs**
Please provide a log of your issue with verbose logging enabled (See General tab of the plugin).  
In case of a crash, please also include the corresponding crash log.  
See [here](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/) for a description where to find the log files and how to share them.  
Please share the currently used plugin settings by exporting them them to a file (See General tab of the plugin).  

**Version information**
 - OS: [e.g. Windows 10]
 - OBS Version [e.g. 27.1.3]
 - Plugin Version [e.g. 1.17.1]
Im on Windows 11

**Additional context**

**Comment by WarmUpTill** [comment]
I _think_ you accidentally downloaded the wrong file.
You will have to download the file named "[advanced-scene-switcher-windows-x64-Installer.exe](https://github.com/WarmUpTill/SceneSwitcher/releases/download/1.23.1/advanced-scene-switcher-windows-x64-Installer.exe)", if you want to use the installer.

See the highlighted area in the screenshot below:

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/3a016b02-f6c5-4600-a7e0-33652ecd7e9f)

Does that help, or do you need further assistance?

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if you need further help! :)
