### ISSUE TITLE
[feature request] Allow parsing variables in Source -> Set Settings (or maybe text input settings in general)

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#838]
**Is your feature request related to a problem? Please describe.**
You currently can't set the source settings in a dynamic way, based on e.g. file content.

**Describe the solution you'd like**
Parsing a `%varName%`, `$varName$` or similar syntax into variable values would be nice and if it was done in all fields where you can enter text that would be awesome, but ofc that would require much bigger changes.

**Describe alternatives you've considered**
I don't see any way of getting around it.

**Comment by WarmUpTill** [comment]
Sorry if I am misunderstanding the request.
Are just intending to use variables to _modify_ the settings of a given source?

In that case, then this is already [possible](https://github.com/WarmUpTill/SceneSwitcher/wiki/Variables#using-variables) using the `${variable name here}` syntax.
Here is an example:

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/9938f5a1-2b9f-47de-8b3e-631de99d8592)

**Comment by Destroy666x** [comment]
Ah, didn't see that mentioned anywhere. Is that usable in all text fields?

**Comment by WarmUpTill** [comment]
>Is that usable in all text fields?

I cannot guarantee that it works for all, but most of them should do :)
