### ISSUE TITLE
macOS wrong install path

### ISSUE THREAD

**Issue by andynameistaken** [WarmUpTill/SceneSwitcher#839]
When installed by .pkg program is placed in `"/Library/Application Support/obs-studio/plugins"` instead of `"$HOME/Library/Application Support/obs-studio/plugins"`, which makes it invisible for OBS

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue! :)

The plugin being installed in the root `/Library` was indeed the case for quite old versions of the plugin.
But in the past they were still picked up by OBS regardless.
For more up to date versions of the plugin the installer should place the files under `~/Library` instead.

Which version of the plugin are you using?

I am not sure if it is the case for you, but just to mention it:
The most common cause for the plugin not being loaded on MacOS is the wrong version being installed (e.g. x86 variant in combination with ARM / M1 version of OBS). This could be verified with a log file, if you are willing to share one.

**Comment by WarmUpTill** [comment]
I will close this for now.
Let me know if you need further support for this topic! :)
