### ISSUE TITLE
Projector action's target is changed if it doesn't exist

### ISSUE THREAD

**Issue by KopiasCsaba** [WarmUpTill/SceneSwitcher#842]
**Describe the bug**
I had set up a projector action to make a fullscreen projector on a specific screen.
Now, if that device does not exist (I guess at the time of starting obs), then it is just resets it to a different device.

**To Reproduce**
1. Connect an external monitor
2. Setup a macro with an action to open a fullscreen projector on that monitor
3. Stop obs/the plugin
4. Unplug the monitor
5. Start obs, and check the target for the projector.

**Expected behavior**
I would expect it to retain the set target, as right now it just opens the projector on the wrong screen in this case.

**Version information**

-     OS: Windows 10
-     OBS Version 29.1.3
-     Plugin Version 1.23.1

**Additional context**
I wonder that might be UI wise it would be better to have a textbox for a pattern or an exact name.
And then the selector that lists the current one would be only used to fill that textbox in.
Then you'd not have the chicken-egg problem, as the selector would only be a helping tool to fill in the pattern textbox.
And the plugin can emit some error message and not do anything if the pattern did not match any of the screens.

**Comment by KopiasCsaba** [comment]
I also wonder if the same issue might be present on other triggers (I think there is one caleld Display or smtg), please check that one too once upon a while:)

**Comment by WarmUpTill** [comment]
The projector action does not process the name of a given display (as you could have multiple displays with the same name connected).
It simply identifies the screen to use based on its index in the list of available [screens](https://doc.qt.io/qt-6/qguiapplication.html#screens).

So if you change the screen configuration, which screen corresponds to which index also changes.
I am not sure how I would be able to solve that.

>I also wonder if the same issue might be present on other triggers (I think there is one caleld Display or smtg), please check that one too once upon a while:)

The "Display" condition type does not use the screen index, so there should not be an issue.

**Comment by KopiasCsaba** [comment]
I'd say, that the projector action could store the name of the device rather, and noop if it doesn't exist.

**Comment by WarmUpTill** [comment]
I added additional checks to detect if the monitor setup changed with the linked PR and will reset the display selection in that case.
I think that should solve the problem.

**Comment by KopiasCsaba** [comment]
Thank you! I assume it is in the latest release (aug 9, merged sept 3), so I will just update it! Thank you very much!
