### ISSUE TITLE
Select preview scene

### ISSUE THREAD

**Issue by KopiasCsaba** [WarmUpTill/SceneSwitcher#843]
Dear Developer,

I'd like to assign hotkeys for making scenes active in the preview. 
Currently I'm using a [LUA script](https://obsproject.com/forum/resources/next-scene-and-previous-scene-hotkeys.1018/) to select next/prev scenes with two buttons on a small external keyboard.

But I have ordered a bigger one, to have a button for each scene. 

Cheers & Thank you, this is awesome stuff!

**Comment by WarmUpTill** [comment]
Thanks for the suggestion - I will try to look into during the weekend! :)

**Comment by WarmUpTill** [comment]
Ah, just noticed that I misread your request.
I thought you needed support the the "next scene / previous scene" functionality of the LUA script.

You can already achieve scene switches to a given preview scene by hotkey by using the "Hotkey" condition in combination with the "Studio mode" action.

(I plan on moving the preview scene switch to the "Switch scene" action to make it easier to find.)

**Comment by KopiasCsaba** [comment]
Oh, you are awesome!

Yes indeed, that is it! (I thought studio mode switches the studio mode on and off, so i didn't bothered clicking on it):)

Cheers!
