### ISSUE TITLE
Dynamically create recording folders if it doesn't exist

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#847]
Is it possible for the plugin to dynamically create recording folders? For example, I'd like use variables in this way: /Videos/${recordingfolder}. 

Out of the box, OBS will just spit out "folder doesn't exist" etc when trying to record in a folder that hasn't been created. Perhaps a small workaround can be done with your plugin where it will actually create the folder..?

**Comment by WarmUpTill** [comment]
You can rely on the "Run" action for this.
Assuming you are on Window something like this should do the trick:

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a84e828d-7cbb-43c2-a8c3-204d424db5e0)

In case you want to copy the example here is the [import code](https://github.com/WarmUpTill/SceneSwitcher/wiki/Exporting-and-importing-individual-macros):
```
{"macros":[{"name":"Example","pause":false,"parallel":false,"onChange":true,"skipExecOnStart":false,"group":false,"dockSettings":{"register":false,"hasRunButton":true,"hasPauseButton":true,"hasStatusLabel":false,"highlightIfConditionsTrue":false,"runButtonText":"Run","pauseButtonText":"Pause","unpauseButtonText":"Unpause","conditionsTrueStatusText":"Conditions are true.","conditionsFalseStatusText":"Conditions are false."},"registerHotkeys":false,"pauseHotkey":[],"unpauseHotkey":[],"togglePauseHotkey":[],"conditions":[],"actions":[{"collapsed":false,"id":"run","enabled":true,"processConfig":{"path":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","workingDirectory":"","args":[{"arg":"mkdir"},{"arg":"C:\\some\\testing\\folders"}]}}]}],"version":"577808f"}
```

Hope that helps! :)

**Comment by nacalai** [comment]
Thanks, I did in fact already try this way after I posted the issue. However it seems I cannot run cmd nor powershell, even if OBS has admin privileges. Any ideas? Nothing happens.

**Comment by nacalai** [comment]
Well I figured it out :)
1) The path argument (for cmd at least) has to be enclosed in "" since my path has spaces in it. Doing that, it worked
2) I didn't know cmd would run silently. Awesome

So, it works just fine now :) Thanks for implementing the change!
