### ISSUE TITLE
Pre-populate variable input field

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#848]
A few requests from me now, sorry about that hehe. Just eager to get my little thing going.

I am making an input box upon opening OBS, prompting the user to enter the recording name for the current session. That is more effective than remembering going into settings - output etc and change it there.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/4357694/3ee7995f-7a35-48ce-a73d-51693a1d13bb)

That's all good, however if the person restarts OBS, the prompt box will open again. It would be nice if the input field could already be populated with the current variable. So, if the name is supposed to stay the same, the person can just click OK.

**Comment by WarmUpTill** [comment]
A build with the requested functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/6003548595?pr=849

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/bac4bd87-8d1d-437f-983b-fcb2d6c08dcb)

Let me know if everything works as you expect it to! :)

**Comment by nacalai** [comment]
Yes, super :D
