### ISSUE TITLE
SceneSwitcher marked as virus

### ISSUE THREAD

**Issue by spenceradolph** [WarmUpTill/SceneSwitcher#86]
A few days ago I started OBS up and the plugin was missing. I checked the plugin folder and indeed it was gone. Windows Defender marked the file as a trojan. I re-downloaded the SceneSwitcher.zip but chrome marks the file as potentially dangerous and recommends discarding it.

Is there an easy way to confirm the validity of the download? Perhaps some check-sum hash or similar? I don't mind using the downloaded version if I can verify it matches what gets built from this repo. 

The other alternative might be to download the cmake tools and build the plugin locally and see if that also marks it as a virus, but I am currently unfamiliar with cmake and perhaps someone else could verify it.

**Comment by WarmUpTill** [comment]
There were indeed multiple reports of the plugin being flagged as a trojan.
For some reason only windows defender seemed to have flagged it and I have no clue why or what part of the plugin was triggering that.
Other antivirus software seems to have no problem with it.
And strangely enough it just started happening yesterday.

The plugin is built using "github actions" workflow whenever changes are submitted.
I use these automated builds for the releases, so you could theoretically compare the checksums of these automated build results with the one of the release. (But that is of course very cumbersome)

Just rebuilding the plugin with a different version tag seemed to have resolved the issue and I updated the 1.8.1 release to contain these new binaries.
They were built using this github actions run:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/419084368

**Comment by spenceradolph** [comment]
I downloaded the artifacts from the recent build and so far so good, I'm not sure if there's a manual way to trigger an explicit Windows Defender on files or directories.

Downloading the artifacts directly from the build pipeline is probably a really good suggestion as downloading files from seemingly outdated forums can be sketchy.

**Comment by WarmUpTill** [comment]
Thank you very much for the confirmation!

I also double checked whether the issue was introduced on my machine by downloading the offending artifact once again and sure enough the artifact already shows the issue and is instantly being blocked by Windows Defender. (run 413774326)

I will try to somehow submit this false positive so that at least something useful comes out of this issue.

**Comment by WarmUpTill** [comment]
Oh, that was a way quicker response by Microsoft than I expected:



```
Analyst comments:


                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.
```
 
I will close the issue for now but I will leave it pinned in case others still run into this problem.
