### ISSUE TITLE
Fail to build if deps/libremidi/ is empty

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#868]
Hi @WarmUpTill,

**Describe the bug**

If deps/libremidi/ directory is present and if it is empty, the configure stage will fail. From Debian: Sid

```
CMake Error at src/macro-external/midi/CMakeLists.txt:13 (add_subdirectory):
  The source directory

    /PKGS/obs-advanced-scene-switcher/1/obs-advanced-scene-switcher-1.23.1/deps/libremidi

  does not contain a CMakeLists.txt file.
```

Regards,

Eriberto

**Comment by WarmUpTill** [comment]
Hi @eribertomota,
Thanks for reporting the issue!
This was already solved with https://github.com/WarmUpTill/SceneSwitcher/commit/1a8c894ddf7588efebf8038f5621d09b95ab5f47.

I plan on releasing a new version / adding new version tag once OBS 30 is released.

**Comment by eribertomota** [comment]
Thanks!!!
