### ISSUE TITLE
Feature request: Window Title switch if condition is NOT met

### ISSUE THREAD

**Issue by whiten01se** [WarmUpTill/SceneSwitcher#87]
It would be nice being able to invert the title switch conditions, so as to (for instance) switch to a blank scene if the required window title is NOT met.

That would make a nice privacy feature.

**Comment by WarmUpTill** [comment]
You could use regular expressions for that if I am not mistaken.
So for example the following should match any window not containing "Notepad ++":
`^((?!.*Notepad\+\+).)*$`

**Comment by whiten01se** [comment]
You're right. This one makes the title match work negatively. Thank you!
