### ISSUE TITLE
Trigger on Presentation/PowerPoint Slide Change [with Time Interval]

### ISSUE THREAD

**Issue by ukiews** [WarmUpTill/SceneSwitcher#875]
When capturing a PowerPoint from an external PC, it would be helpful to have a macro that triggers on the image change.
So the plugin will detect when the next slide is advanced. 
In many cases, a powerpoint is run on an external pc and then capture in OBS, so it is not possible to monitor the OBS PC for presentation remote clicks. 

Is it possible to have a macro trigger based on how much the pixel preview of a scene changes, such that it would be possible to switch to the "presentation" scene in OBS when a powerpoint has advanced to the next slide?

Trigger parameters:
1. monitor interval [in seconds] (the interval that the plugin will sample and compare the current image preview to what was there before)
2. percent change [0-100%] (If the parameter is set to "50," the plugin will only trigger if the two images being compared are different by 50%)

I imagine you could downscale the images before running the comparison so it is not CPU heavy.

**Comment by WarmUpTill** [comment]
I think the [Video condition](https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition) - in particular the "[has changed](https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition#has-changed)" check - might be able to do what you are trying to set up.

Feel free to ask any questions! :)

**Comment by ukiews** [comment]
Oh, great!
It did not work initially, but I enabled "reduce matching latency" and it is working now.
However, the CPU does ramp up quite a bit.
Which pattern matching mode is least intensive?

**Comment by WarmUpTill** [comment]
I would say they are all about equally resource intensive.
The main way to reduce the load on the system is reduce the area to be checked and the interval at which to check the selected area.

**Comment by ukiews** [comment]
How can the interval at which the check is performed be changed? I only see "reduce matching latency" option.

**Comment by WarmUpTill** [comment]
You can set up a second macro that periodically pauses and unpauses the macro using the video condition.
For example:

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/1458613d-dab2-4c4b-8187-e0d2b123e064)

If you want to use that example you can [import](https://github.com/WarmUpTill/SceneSwitcher/wiki/Exporting-and-importing-individual-macros) it using this code:
```
{"macros":[{"name":"Macro 1","pause":false,"parallel":true,"onChange":false,"skipExecOnStart":false,"group":false,"dockSettings":{"register":false,"hasRunButton":true,"hasPauseButton":true,"hasStatusLabel":false,"highlightIfConditionsTrue":false,"runButtonText":"Run","pauseButtonText":"Pause","unpauseButtonText":"Unpause","conditionsTrueStatusText":"Conditions are true.","conditionsFalseStatusText":"Conditions are false."},"macroActionConditionSplitterPosition":[{"pos":133},{"pos":520}],"macroElseActionSplitterPosition":[{"pos":482},{"pos":0}],"registerHotkeys":false,"pauseHotkey":[],"unpauseHotkey":[],"togglePauseHotkey":[],"conditions":[{"collapsed":false,"id":"plugin_state","logic":0,"durationModifier":{"time_constraint":0,"seconds":{"value":{"value":0.0,"type":0},"unit":0,"version":1}},"condition":2,"version":1}],"actions":[{"collapsed":false,"id":"wait","enabled":true,"duration":{"value":{"value":10.0,"type":0},"unit":0,"version":1},"duration2":{"value":{"value":0.0,"type":0},"unit":0,"version":1},"waitType":0,"version":1},{"collapsed":false,"id":"macro","enabled":true,"macro":"Other macro","actionIndex":{"value":1,"type":0},"action":1},{"collapsed":false,"id":"wait","enabled":true,"duration":{"value":{"value":0.5,"type":0},"unit":0,"version":1},"duration2":{"value":{"value":0.0,"type":0},"unit":0,"version":1},"waitType":0,"version":1},{"collapsed":false,"id":"macro","enabled":true,"macro":"Other macro","actionIndex":{"value":1,"type":0},"action":0}],"elseActions":[]}],"version":"a166813"}
```

**Comment by ukiews** [comment]
But if the macro is paused for 10 sec, how will it know if within that time a change of image has occurred?
For example, say the screen is on SLIDE-1, the macro is then paused for 10 sec and within that period the slide is switched to SLIDE-2. Once the macro is unpaused, will it be able to detect a change in image?

**Comment by ukiews** [comment]
Would it be possible to add an interval field into the condition itself?

**Comment by WarmUpTill** [comment]
You are right - what I suggested does not really make sense in your scenario.

> Would it be possible to add an interval field into the condition itself?

Yes, a build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/6209768964?pr=879
![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/5f6a66b2-2bde-464c-be7e-c6d2d12a5bb0)
