### ISSUE TITLE
Trigger Based on Recording/Streaming Time

### ISSUE THREAD

**Issue by ukiews** [WarmUpTill/SceneSwitcher#878]
Would it be possible to add a trigger based on Livestream or Recording duration?
Basically, if the livestream/recording has been happening for [mm:ss], trigger.

**Comment by WarmUpTill** [comment]
Sorry if I am simply misunderstanding your request but have you considered looking into [duration modifiers](https://github.com/WarmUpTill/SceneSwitcher/wiki/Macro-duration-modifiers) of conditions?
They will enable you to check how long a condition is true.
For example:
![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/997fd4eb-52c9-43a8-b071-840fd31b58e8)
