### ISSUE TITLE
[Feature Request] Publish/"Feature" A Twitch Clip

### ISSUE THREAD

**Issue by DanielLester83** [WarmUpTill/SceneSwitcher#881]
**Is your feature request related to a problem? Please describe.**
I can't automatically Publish or "Feature" a clip on Twitch.

**Describe the solution you'd like**
A new option to be added to the existing action.

**Describe alternatives you've considered**
Doing it manually, painstakingly.

**Additional context**
It would be helpful if the create clip action explains that, by default, twitch arbitrary selects up to 30 seconds of the 85 seconds before/5 seconds after the action is run.
(So you should time it accordingly).

Also it would be nice if there was an option to set the duration (5-60 seconds).

There is a "is_featured" value in the api, though it may be read only.

**Comment by Destroy666x** [comment]
This isn't possible right now, you can upvote this: https://twitch.uservoice.com/forums/923368-video-features/suggestions/45503026-an-api-to-create-a-twitch-clips

**Comment by WarmUpTill** [comment]
Thanks again @Destroy666x for checking this! :)
I will close this _for now_.

**Comment by Destroy666x** [comment]
Or rather this is better to upvote now that I'm viewing what's in there: https://twitch.uservoice.com/forums/310213-developers/suggestions/38855326-create-clip-enhancements
