### ISSUE TITLE
[Feature Request] Add A Twitch Video/Clip to a Collection

### ISSUE THREAD

**Issue by DanielLester83** [WarmUpTill/SceneSwitcher#882]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add a Twitch Video or Clip to a "Collection".

**Describe the solution you'd like**
A new action be created.

**Describe alternatives you've considered**
Manual Addition through Twitch.

**Additional context**
If this is possible, then an "collection_exists?" condition and a "create_collection" action would be also helpful.

**Comment by Destroy666x** [comment]
There are no publicly documented endpoints for collection management, unfortunately, as of now.

**Comment by WarmUpTill** [comment]
Thanks @Destroy666x for already checking this!

In that case I will close this issue for now.
If Twitch decides to add the necessary API this can of course be reconsidered.
