### ISSUE TITLE
Macro Scene Transition Changes Default Scene Transition

### ISSUE THREAD

**Issue by hoga2443** [WarmUpTill/SceneSwitcher#883]
**Describe the bug**
Changing the transition using Advanced Screen Switcher changes the default transition rather than only using the transition for the defined scene change

**To Reproduce**
1. Create a second scene.
2. Leave the default scene transition as fade.
3. Configure a scene transition macro switching back to the first first scene using a different transition (e.g. cut).
4. Switch to the second scene.
5. When the macro is executed returning to the first scene, the default scene transition will now be the transition defined by the scene transition macro (e.g. cut) rather than the default fade transition.

**Expected behavior**
The scene transition specified in the macro should use the specified transition for the specified scene change but the default scene transition should remain unchanged.

**Logs**
https://obsproject.com/logs/lBnCsY3ymyWNgYmd

**Version information**
 - OS: Windows 10
 - OBS Version 30.0.0-beta3
 - Plugin Version 1.23.1

**Additional context**
[adv-ss-Loggers-2023.09.28.23.22.27.txt](https://github.com/WarmUpTill/SceneSwitcher/files/12761564/adv-ss-Loggers-2023.09.28.23.22.27.txt)

**Comment by WarmUpTill** [comment]
You can adjust this behaviour on the General tab using the checkboxes below:

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a082dc2a-2691-4c9d-ac4f-b566dfd42f08)

I assume what would work for you is to only check the "Set transition overrides" option and uncheck "Change active transition type".
Hope that helps! :)
