### ISSUE TITLE
Pipeline script: Rundir copies data files in wrong subdirectory

### ISSUE THREAD

**Issue by Oekn5w** [WarmUpTill/SceneSwitcher#884]
**Describe the bug**
As I don't have a fully set up development environment for OBS, I am using the buildscripts from the Github actions to compile and install the plugin for testing.

For Windows using the RelWithDebInfo configuration the locale files are installed to
```
build_<arch>\rundir\<config>\data\obs-plugins\advanced-scene-switcher\data\locale
```
The expected directory is:
```
build_<arch>\rundir\<config>\data\obs-plugins\advanced-scene-switcher\locale
```

Interestingly, the `release` folder has the correct file structure for the resources and locale definitions.

The effect is that the plugin cannot find the translation tables if not copied manually to the correct folder.
("Failed to find plug-in's 'data' directory." warning)

**To Reproduce**
1. On Windows run `.github\scripts\Build-Windows.ps1`
2. Copy the rest of OBS into the rundir directory accordingly and start OBS
3. Go to the tools' settings

**Expected behavior**
Not needing the manual copy operation.

**Logs**
N/A

**Version information**
 - OS: Windows 10
 - OBS Version 29.1.3
 - Plugin Version 1.24.0-beta1-2-gb1489d98

**Additional context**
I'd happily fix this myself, but I don't have sufficient cmake knowledge and I could not identify the relevant definitions.

**Comment by WarmUpTill** [comment]
I _think_ this might just be the behaviour of the [ObsPluginHelpers.cmake](https://github.com/WarmUpTill/SceneSwitcher/blob/master/cmake/ObsPluginHelpers.cmake) helpers.
I will try to look into it if I find the time to - just have to make sure that I am not breaking the "in-tree" builds with any changes there.
