### ISSUE TITLE
[Feature request] switch scene based on face detection moving out of bounding box

### ISSUE THREAD

**Issue by nospam2k** [WarmUpTill/SceneSwitcher#898]
https://github.com/WarmUpTill/SceneSwitcher/issues/296
This Issue mentions you were working on face detection in 2021. I don't know if I've just missed this feature, but just in case.

My idea is to have a face bounding box and an "acceptable range" bounding box. When the face box crosses the "acceptable range" switch the scene. If on the left, switch to "a" scene. If on the right, switch to "b" scene.

I really appreciate this plugin and have been using it for years now. Thanks for all you work!

**Comment by WarmUpTill** [comment]
You _should_ be able to achieve what you are looking to do using the [video condition](https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition#contains-object).

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/71451123-239e-49ee-b691-d18895b15d1f)

Select "contains object" as the check type at (1).
Play around with the different model types to find what works best for your use case at (2).
Select the "bounding box" at (3).

Let me know if you have any questions! :)

**Comment by nospam2k** [comment]
So the "bounding box" in #3 is an "if true" condition? For example. I set a box on the right side of a camera view and when the subject moves into that area it will switch. Is that correct? Otherwise, I don't see how to differentiate between a right and left move. I'm going to test this in the mean time and I will report back.

**Comment by WarmUpTill** [comment]
Only if the selected area of the video source contains a face will the condition be true.

So you would set up two separate macros each with a video condition, but the area each condition will check will be different.
One macro will switch to scene "a" and the other to scene "b".

I apologize I am misunderstanding what you mean by bounding box.

**Comment by nospam2k** [comment]
Just a block area that determines the boundaries of the event. It's called area in the plugin. But I see you are confirming my question. I'm going to try it out and I'll get back. Thx!

**Comment by nospam2k** [comment]
Ok, just had some time to play with this and kind of working. I'm going to play more but one thing; is it possible to ignore the face detection when there is more than one face? Thanks again for your amazing plugin!

**Comment by nospam2k** [comment]
I'm running into an issue here on windows. First I install the "latest 1.24.2" and when it comes up it says "1.19.2". Also there is no option for Video on the windows version, but on the Mac version there is (it's 1.24.2)

**Comment by nospam2k** [comment]
UPDATE: So it seems that the zip file for windows x64 is not updated. I downloaded the installer file and it was 1.24.2.

I still don't see an option for Video in the drop down for the if condition on Windows. It is there for Mac.

**Comment by WarmUpTill** [comment]
With 43967f5dedc57b5ed3025195ff7dac4de1ebebbe I added the macro property "Object count", which should allow you to check how many faces were detected.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/46713ab3-6a76-480b-a3da-9696cf3260e4)

This should be included in 1.24.1 and 1.24.2.
I will close this issue for now.
Sorry for not getting back to you earlier!

**Comment by nospam2k** [comment]
I thought I would add this because I am thinking out loud. Is it possible to actually detect a specific face? For example if the face is being tracked ok, but another face comes into the tracking area, is it possible to ignore the new face? In my situation, only one face will be moving around and there will be musicians standing behind but not moving around. Like I said, I don't know if this is even possible but just a thought. Thanks again!

**Comment by WarmUpTill** [comment]
It is _possible_ to do something like this _if_ you have a custom trained model which only detects the specific face in question.
But you would have to create this face detection model yourself which is probably way too much work.
(I personally have never tried this either)

**Comment by nospam2k** [comment]
Yes, I thought something like that. Thanks though!

**Comment by nospam2k** [comment]
I would like to revisit this a little bit. We have a need now to try and fully automate our OBS Livestream with minimal supervision for our church services. Before I start really digging into to this, I have some questions that are just yes or no or maybe a small response (I don't want to take a bunch of your time unnecessarily) so here goes:

1. You mentioned the idea of a custom trained model to detect a specific face. I have played a little with doing AI training for voice and have been able to setup python implementations of AI on my local machine, so I have some background of simple sample related training. Given that, do the think that it is possible to obtain a reliable face detection to say, for example, only follow the song leader and not get caught on band members?

2. Do you think that, using the above, it is possible to have a reliable solution that doesn't require human intervention? I'm talking in relationship to using things like microphone detection to switch scenes, etc.

3. Is there any documentation on the specifics of the xml parameters so I can really customize the specifics of how I want the switching to perform?

That's it for now. Hopefully I have been concise enough to keep the answers simple. I have to say (I've said several times before) this is singularly the greatest plugin to OBS that I am using and has automated so much of what I do that we literally start up OBS and streaming for our live podcast and I NEVER have to touch a thing. Camera switching, include random wide angle shots are all handled by your plugin. I am very grateful for your work. I have a lot of development background and if there is anything I can do to test a feature or debug a sticky problem, feel free to throw it at me, I'll do my best to help.

**Comment by nospam2k** [comment]
Thank you for your feedback! I have been looking into leveraging opencv and am going to first get the whole thing working with Python and then move the training file into SceneSwitcher. Your suggestions will be a great help for handling control.

**Comment by nospam2k** [comment]
I've figure out how to use opencv to do face recognition, but the data is yml not xml. Is it possible to either convert the data or modify your plugin to use yml files as yml is default for opencv recognizer.

**Comment by WarmUpTill** [comment]
Which type of algorithm / model have you used for the face detection?
(I am unsure what the `yml` file contains)

**Comment by nospam2k** [comment]
```python
import cv2
import numpy as np
from PIL import Image
import os

recognizer = cv2.face.LBPHFaceRecognizer_create()

path="datasets"

def getImageID(path):
    imagePath = [os.path.join(path, f) for f in os.listdir(path)]
    faces=[]
    ids=[]
    for imagePaths in imagePath:
        faceImage = Image.open(imagePaths).convert('L')
        faceNP = np.array(faceImage)
        Id= (os.path.split(imagePaths)[-1].split(".")[1])
        Id=int(Id)
        faces.append(faceNP)
        ids.append(Id)
        cv2.imshow("Training",faceNP)
        cv2.waitKey(1)
    return ids, faces

IDs, facedata = getImageID(path)
recognizer.train(facedata, np.array(IDs))
recognizer.write("Trainer.yml")
cv2.destroyAllWindows()
print("Training Completed............")
```
