### ISSUE TITLE
Wrong token logic in Twitch conditions

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#905]
**Describe the bug**
Just noting that down since I missed it earlier on a phone (oops) and now I'm not following the code when checking something else on PC. This: https://github.com/WarmUpTill/SceneSwitcher/blob/890792c27084d008cbd484bba2cbbd1371895916/src/macro-external/twitch/macro-condition-twitch.cpp#L554 doesn't seem to be correct, in terms of logic, like I attempted to code it.

**To Reproduce**
1. In Twitch condition enable only one of required options for a token.
2. A message will be shown stating that token doesn't support the condition.

**Expected behavior**
The condition should allow only one of defined scopes. The list should be "or" rather than "and" as per Twitch specification of requirements. I think you misunderstood my code (which I'm not sure was fully correct either) @WarmUpTill and made it work the other way round.

**Logs**
\-

**Version information**
 - OS: Windows 10
 - OBS Version: 29.1.3
 - Plugin Version: WIP

**Additional context**
\-

**Comment by Destroy666x** [comment]
Let me know if I'm missing anything, otherwise I'll include a fix in next PR.

**Comment by WarmUpTill** [comment]
Ah ok - I indeed misunderstood the requirement to be that all token options need to be set.

Feel free to include it in your next PR and maybe add a quick comment that it should indeed be "or" logic so I don't "fix" it again :D

**Comment by Destroy666x** [comment]
I'll move the logic to a function with `Any` so that shouldn't be a problem.
