### ISSUE TITLE
[feature request] only allow audio scene switching on specific scenes

### ISSUE THREAD

**Issue by adjstreams** [WarmUpTill/SceneSwitcher#914]
**Is your feature request related to a problem? Please describe.**
I'd like to use the Audio scene switch but only on certain scenes. I have two versions of a scene - one with the camera at a closer zoom. When the mic volume is silent for a second it switches to the zoomed-in scene, and when I talk again it switches back to the original scene.  We're talking like half a second of silence before it zooms in, and an even quicker switch when I start talking again.

**Describe the solution you'd like**
The ability to make an audio trigger apply only to specific scenes. OR the ability to **Pause** Audio checks when scene is INACTIVE.

**Describe alternatives you've considered**
I've tried setting up a source clone of my mic source which doesn't go to any audio tracks, and just acts as a sound detector. I added that to the scenes I want it to trigger on. However, it's stopping me from transitioning to other scenes, probably because the source is still active until the transition completes.

**Comment by WarmUpTill** [comment]
This should be possible already :)
Would you be willing to [share](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) what you have set up already so I can show you what you have to change?

**Comment by adjstreams** [comment]
Like this?

[adv-ss-ADJStreams-2023.11.17.23.58.49.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13398410/adv-ss-ADJStreams-2023.11.17.23.58.49.txt)

**Comment by adjstreams** [comment]
My work-around for now is that when I use my touch portal to switch scenes, I disable the audio detector source before switching, and turn it back on when I return. If I'm not streaming and just editing scenes I just have to remember to turn off the audio detector source before I can move freely between scenes. No big deal, but interested to see if there's a way to handle it inside the plugin.

**Comment by WarmUpTill** [comment]
What you are trying to do is possible using [macros](https://github.com/WarmUpTill/SceneSwitcher/wiki/Macros#what-are-macros).
I would recommend to not use the old tabs and instead only rely on macros.

I have attached a modified settings file based on your existing settings which should have everything set up.
Simply import it on the General tab and give it a try.
But please make sure to back up your current setting just in case something goes wrong.

[macros.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13400970/macros.txt)

Here is a screenshot of one of the macros which enable you to only perform the audio checks on a given scene.
Note the "And not" section, which will make sure that the action is not executed if you are on a given scene.
(You might have to adjust the scene -I just picked the "Scene - BRB - Socials" one as an example)

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/a2e8107b-366d-4e08-b21b-2cec9b384eec)

Hope that helps!

**Comment by adjstreams** [comment]
Yes! Thanks, looks like that works, and is easier and more consistent than how I was trying to do it. Thanks!
