### ISSUE TITLE
 install problem Ubuntu studio 23.10 all working but can t install libprocps-dev

### ISSUE THREAD

**Issue by Viezovv** [WarmUpTill/SceneSwitcher#925]
hello

Fresh install ubuntu 23.10, obs 30.0.0, last version sceneSwitcher. 
When trying install dependencies  libprocps-dev, I get an error E: Unable to locate package libprocps-dev. I looked at https://packages.ubuntu.com/ and this package is not yet updated. 

OBS is spitting out an error:

os_dlopen(/home/viez/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/advanced-scene-switcher.so->/home/viez/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/advanced-scene-switcher.so): libprocps.so.8: cannot open shared object file: No such file or directory
19:54:23.866: 
19:54:23.869: os_dlopen(/home/viez/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/advanced-scene-switcher.so->/home/viez/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/advanced-scene-switcher.so): libprocps.so.8: cannot open shared object file: No such file or directory
19:54:23.869: 
19:54:23.869: Module '/home/viez/.config/obs-studio/plugins/advanced-scene-switcher/bin/64bit/advanced-scene-switcher.so' not loaded

**Version information**
 - OS: Ubuntu studio 23.10 x64
 - OBS Version 30.0.0
 - Plugin Version [last]

**Comment by WarmUpTill** [comment]
Unfortunately I don't have a VM set up with Ubuntu 23 at the moment.
Can you try running `sudo apt install libprocps8`?
Or does that also not exist?

**Comment by Viezovv** [comment]
> Unfortunately I don't have a VM set up with Ubuntu 23 at the moment. Can you try running `sudo apt install libprocps8`? Or does that also not exist?

Unable to locate package libprocps8

**Comment by flexiondotorg** [comment]
Since Ubuntu 23.04 the package name changed. You need to install `libproc2-dev` to satisfy the build dependency and `libproc2-0` to satisfy the runtime dependency.

**Comment by WarmUpTill** [comment]
I know that it is not really a solution to your problem, but you could also install OBS _and the plugin_ using flatpak.
Although that also comes with some downsides as the plugin won't be able to use all of its  functionality in that environment.

I will _try_ to find a solution to support both versions of the libproc at runtime.

**Comment by WarmUpTill** [comment]
Can you please give this build a try and check if (1) the plugin loads and (2) the process condition works in any way on your setup?
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7147205430?pr=939

In this build the plugin will try to resolve both libprocps and libproc2 symbols at runtime and use the one that is available instead of directly linking against either of them.
