### ISSUE TITLE
Install on Ubuntu not working?

### ISSUE THREAD

**Issue by decentropy** [WarmUpTill/SceneSwitcher#926]
**Describe the bug**
I've installed OBS on Ubuntu using FlatPak... but Scene Switcher does not appear under tools

**Version information**
 - OS: Ubuntu 22.04.3 LTS
 
:~$ flatpak list
Name                                            Application ID                                                Version           Branch               Installation
OBS Studio                                      com.obsproject.Studio                                         29.1.3            stable               system
Advanced Scene Switcher                         com.obsproject.Studio.Plugin.SceneSwitcher                    1.24.0            stable               system

**Comment by WarmUpTill** [comment]
You will have to upgrade OBS to version 30.
