### ISSUE TITLE
[Bug] Macro conditions

### ISSUE THREAD

**Issue by 0rangeFox** [WarmUpTill/SceneSwitcher#929]
Hey folks :wave:! I'm here to report another bug, why is this happening to me or is it just because I'm the only one overthinking it? So as the title says, I'm going to go into detail about the scenario I intend to do.

So here's what I want to do: when I click on that application the one I defined and focus on it, it changes the visibility of the _source_ and when I focus on another application other than the one I defined, it changes the visibility of the _source_ again.

In the following image, we can see that we have two conditions, one with `if` and the other with `or not`, by programming logic, this would be something like `if (xyz || !xyz)`. 
![Captura de ecrã 2023-12-02, às 18 24 36](https://github.com/WarmUpTill/SceneSwitcher/assets/38193239/89a02d04-b88a-48ea-8bc9-bca61c8eac02)
Now in the following image, we have the same thing as above but in separate _Macros_, which in programming logic becomes `if (xyz)` and `if (!xyz)`, which is completely the same as above, and why do they both behave differently?
![imgonline-com-ua-twotoone-4nvBp7sZKbX0](https://github.com/WarmUpTill/SceneSwitcher/assets/38193239/93691ea8-8361-405a-9f25-2e35d8a16569)
Anyway, I recorded a [video](https://youtu.be/BJZbzVJHdZw) to get an idea, but is this normal behavior and is this how you should act? That's because this isn't making any sense to me.

**Comment by Destroy666x** [comment]
Some of the "if not" conditions work not as how you'd expect indeed. That's why "else" was added. You have to drag it from the bottom edge of actions list. It should likely be more visible with e.g. a "Show else segments" kind of button.

**Comment by WarmUpTill** [comment]
The "or not" condition type being a noop is indeed a bug - thanks for pointing that out!
Should be fixed with the linked PR.

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7078234725?pr=927
