### ISSUE TITLE
Feature request: switch scene if several audio conditions are met

### ISSUE THREAD

**Issue by FOLLGAD** [WarmUpTill/SceneSwitcher#94]
For podcasts etc. it can be very useful being able to switch to another camera angle in order to capture everyone when more than 1 person is talking at once.

I'm thinking this could be done by including a toggleable option in the "audio" tab, saying something like: "switch to {{scene}} if several conditions are met". It would be fairly simple but also very useful.

**Comment by WarmUpTill** [comment]
I implemented a first version of your suggestion with https://github.com/WarmUpTill/SceneSwitcher/pull/95/commits/7f9e1b1b0c5f620a28d1396213fa943f9ee4721f.

A build with this change should be available in a couple of minutes here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/464605771

While I did not find any issues in my (very limited) testing I would appreciate if you could give this a try, as an extra pair of eyes is always helpful to spot problems! :)

If everything looks good on your side also I will merge this change and create a new release as there seems to be a lot of demand for this feature.

**Comment by FOLLGAD** [comment]
Wow, that's great! The new feature seems to be working perfectly, didn't find any issues so far.
Thanks a lot! :)

**Comment by WarmUpTill** [comment]
Great! Thanks for the feedback!
