### ISSUE TITLE
Macro date trigger show advanced settings changes expected macro behavior

### ISSUE THREAD

**Issue by Wanderwardr** [WarmUpTill/SceneSwitcher#945]
**Describe the bug**
When setting a macro with a date trigger for a day of the week/time selecting the "show advanced settings" button automatically selects the specific date box, adding the current date and time as a requirement for the trigger.  In order to remove the current date as a requirement, unchecking the date box and then selecting the time requirement is needed.  Once unchecked in advanced settings it is not re-checked upon closing and re-opening advanced settings.

This is not desirable because other users operating with the same workstation may select show advanced features for troubleshooting or curiosity and unintentionally alter the behavior of the macro, preventing it from triggering as expected during future dates/times.

**To Reproduce**
1. Menu --> Tools --> Advanced Scene Switcher
2. Select Macros tab
3. Create new menu
4. Create new condition
5. Condition type --> Date
6. See that the date condition has the current time active
7. Select "Show Advanced Settings"
8. See that the active date checkbox is checked.  the active time now has an active date as well. 

**Expected behavior**
Clicking the "show advanced settings" button would show the date checkbox as unchecked, not adding a date restriction to the condition.

**Logs**
[2023-12-10 16-26-29.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13629802/2023-12-10.16-26-29.txt)

**Version information**
 - OS: Windows 10
 - OBS Version 29.1.3
 - Advanced Scene Switcher 1.24.1

**Additional context**
This is a minor issue as far as these things go.  It caused an problem once before I caught it, and now that the specific date trigger has been unchecked in advanced options it should be solved for that macro.  Until the date checkbox is unchecked by default this is easily solved by taking the time to open up advanced options and uncheck the specific date box manually to prevent future users from getting into trouble.

**Comment by WarmUpTill** [comment]
Just to clarify:
You are referring to this checkbox, are you not?

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/1478ed56-89eb-4c3b-ae41-f42bfb539747)

Your expectation would be that this setting is always reset to being checked after toggling the advanced settings view, right?

To be honest I do not fully understand yet how this setting could affect the functionality of the "simple" settings.
The weekday selection is completely independent of the calendar date selection field as far as I remember.

Can you give a concrete example how having that setting checked / unchecked affects the "simple" settings?

**Comment by WarmUpTill** [comment]
I will close this for now - let me know if you want this to be reopened :)
