### ISSUE TITLE
Macros not triggering when using Date condition

### ISSUE THREAD

**Issue by RMNB** [WarmUpTill/SceneSwitcher#951]
**Describe the bug**

I've been using the following condition to start/stop streams at the same day/time of the week. It was working with a much older version of the scene switcher, but no longer triggers after updating to 1.24.2.

If Date [Day of week, e.g. Sunday] at [hh:mm:ss]

**To Reproduce**
1. Create macro with time and day of the week. The action for the macro can be to switch scenes or shut down OBS.
2. Wait for macro to the executed.
3. Macro is usually not executed, sometimes it is.
4.  Occasionally when executing the task to shut down OBS, the warning screen with 10 second timeout is not presented. As a result, at next start, OBS warns that shutdown was not clean and gives the option to start in safe mode.

**Expected behavior**
Macros were executed on much earlier version of advanced scene switcher.

**Logs**
https://obsproject.com/logs/HQewblpAVOBgvrUk

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: 1.24.2

**Comment by WarmUpTill** [comment]
Can you please share a log file with [verbose logging](https://github.com/WarmUpTill/SceneSwitcher/wiki/Troubleshooting#logging) enabled, which shows the problem of a given macro not executing its actions?
Depending how complex your setup is it might also help if you could [export your settings to a file](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings)? (If it is just a few simple macros I should be fine without it)

**Comment by RMNB** [comment]
Hi,

I tried to make the log file as short as possible by launching right before it should fire. The Macro "START - 8:01 am" was changed to trigger at 10:46 PM on Tuesdays. The log does show that the condition returned 1, but the action did not fire (scene did not switch). After some more testing, the scene does switch if I trigger it manually, and while macro window is open.


[2023-12-19 22-45-57.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13722678/2023-12-19.22-45-57.txt)
[adv-ss-Main Collection-2023.12.19.22.48.18.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13722679/adv-ss-Main.Collection-2023.12.19.22.48.18.txt)

**Comment by WarmUpTill** [comment]
You seem to have accidentally modified the "After performing actions skip performing actions for ..." setting [on the general tab](https://github.com/WarmUpTill/SceneSwitcher/wiki/General-tab-overview#Match-behavior).
Please reset that to 0 seconds and I believe everything should work.
Also remember to disable verbose logging or your OBS log files will be very large.

**Comment by RMNB** [comment]
That seems be working. Thank you for the help.
