### ISSUE TITLE
Add the ability to set volume (dB) on scene switch

### ISSUE THREAD

**Issue by sgtquagmire** [WarmUpTill/SceneSwitcher#956]
I noticed there is a way to set volume of an audio source but only by percentage, looking to have it set to a specific dB.

**Comment by WarmUpTill** [comment]
A build with the option to use db values as an input will be available here in few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7359730440?pr=960

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/c1469ea0-1dfd-4645-8634-ef9f8b6c0644)

Let me know if you run into any issues! :)

**Comment by sgtquagmire** [comment]
Hell yeah bad ass! Is the code up already? The release I see is from 2 weeks ago.

**Comment by WarmUpTill** [comment]
You can find a build with this functionality under this link:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7359730440?pr=960

Note that you have to be logged into GitHub to be able to download it.
Once I get your OK that everything works I will merge it into the master branch.

**Comment by WarmUpTill** [comment]
I assume everything is working as expected so I will merge the changes :)

**Comment by sgtquagmire** [comment]
> I assume everything is working as expected so I will merge the changes :)

Yes! Everything worked as expected. Sorry I thought I had responded
