### ISSUE TITLE
[Bug Report] Duplicated entries on Points Reward Redeemed

### ISSUE THREAD

**Issue by MinecraftNight4** [WarmUpTill/SceneSwitcher#957]
**Describe the bug**
When you open the dropdown to use the "Set to macro property" option, it shows the option "User login redeeming reward" twice.

**To Reproduce**
1. Create a Macro of type "Twitch", in the "Points reward redeemed" mode and select a reward.
2. Create an action (e.g. "Variable").
3. Use the "Set to macro property" mode and open the Twitch options dropdown.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/57530b44-d410-49cc-b95b-af4968796324)

**Expected behavior**
It should appear "User login redeeming reward" and "User name redeeming reward", but instead it only appears "User login redeeming reward" repeated twice, although if the 2nd option is selected, it works as "User name...".

**Logs**
https://obsproject.com/logs/So8MZLVB1XcIML6L

**Version information**
 - OS: Windows 10
 - OBS Version 30.0.2
 - Plugin Version 1.24.2

**Additional context**
N/A

**Comment by WarmUpTill** [comment]
Ah, thanks for pointing that out! :)
