### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by flleeppyy** [WarmUpTill/SceneSwitcher#961]
**Describe the bug**
I don't know if this is a bug. I don't see the same menu that's shown in the wiki, so I either forgot to do something, or something is wrong with the plugin.

**To Reproduce**
1. open the scene switcher menu under tools

**Expected behavior**
I'm not sure?

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/18307183/097f6bdb-c356-4223-af25-163dd27a0de2)

**Version information**
 - OS: Windows 10
 - OBS Version 30.0.2
 - Plugin Version: f0df9ea

**Additional context**

**Comment by WarmUpTill** [comment]
That is not the advanced scene switcher plugin.
That is the built-in "automatic scene switcher" tool.

I assume that the plugin was not installed correctly.

How did you install the plugin?
Manually via the zip file or using the installer?

Do you have multiple installations of OBS?

**Comment by flleeppyy** [comment]
I installed it with the exe installer from the latest commit (because I thought it would fix whatever issue there was if there was any). I then realized that I had to use tue dock to activate it then it showed up in tools. bit confusing but I got it to work. Also I only have one obs install.

**Comment by WarmUpTill** [comment]
Glad to hear that you got it to work :)

>I then realized that I had to use tue dock to activate it then it showed up in tools.

That seems a bit strange.
There shouldn't be any dependency between the tool menu entry and the dock widget.
But I will try to look into it.

**Comment by WarmUpTill** [comment]
I wasn't able to replicate the dock / tools behavior issue up to now, so I assume this topic can be closed.
