### ISSUE TITLE
Media macro option does not support Image Slideshow for "Any/All media source on"

### ISSUE THREAD

**Issue by miko3ed** [WarmUpTill/SceneSwitcher#965]
**Describe the bug**
When using the Media parameter to check the state of Image Slideshow sources using "Any media source" or "All media sources" in a scene are in a state the system does not seem to detect them. I have tried multiple states, but importantly the Playing & Stopped states are not functioning. If I use the "Source" option and specify an Image Slideshow it detects the state accurately, and also the Any/All options seem to work on Media Source types.

**To Reproduce**
1. Create a scene with multiple Image Slideshow sources and populate them with any number of images
2. Create a new Macro and select "Perform actions only on condition change"
3. Create a Macro parameter using Media for the parameter type
4. Specify "Any Media source on" and select your scene with Image Slideshows
5. Set state to "Playing"
6. Create any action that you would like to execute, I tested using System Tray Notification with a message of "Test"
7. Enable one of the Image Slideshows in your scene

**Expected behavior**
When an Image Slideshow is enabled in the scene I would expect the macro to run once.

**Logs**
I do not know how to log this for you

**Version information**
 - OS: [e.g. Windows 11]
 - OBS Version [e.g. 30.0.2]
 - Plugin Version [e.g. 1.24.2]

![Screenshot 2024-01-01 163356](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/3ea3740b-89ba-417c-af16-191d716389f4)

**Comment by miko3ed** [comment]
For your information, this screenshot shows the macro working if you specify a specific Image Slideshow source in the scene 
![Screenshot 2024-01-01 163535](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/b08ea689-6ab1-4582-a5fa-ec76e44c1f94)

**Comment by WarmUpTill** [comment]
Thanks for pointing out the issue!

The problem should be fixed with the linked PR.
A build with a fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7385618388?pr=966

**Comment by miko3ed** [comment]
Thanks much @WarmUpTill!!! Do you know when the release will be available for download?

**Comment by WarmUpTill** [comment]
A build is available at the link I shared above.
I am not yet sure when I will publish a next release officially.

**Comment by miko3ed** [comment]
oh Gotcha! Thanks, sorry I just saw that step 3 wasn't done and got confuzzled. The quick fix is MUCH appreciated
