### ISSUE TITLE
focus window action

### ISSUE THREAD

**Issue by markonop93** [WarmUpTill/SceneSwitcher#975]
pls add action to focus window
if title or process match

**Comment by WarmUpTill** [comment]
Can you please provide an example just so I can better understand what the intended use case is?

> if title or process match

I assume this is unrelated to the requested action, is it not?
The "Process" and "Window" conditions already let you check for those conditions.

**Comment by WarmUpTill** [comment]
I implemented the option to set the focus window, maximize, minimize, or close a window with the linked PR.
![Focus](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/997001e3-fde6-4cfc-a142-11a99e12b4cd)

A build with this functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/8054462921?pr=1035

**Comment by Destroy666x** [comment]
Works fine for me personally. Just a small tip - "Set focus window to" doesn't quite make sense gramatically and is confusing, I'd change to either "Set focused window to" or even simplier "Focus window"

**Comment by WarmUpTill** [comment]
Thanks for testing it!

>"Set focus window to" doesn't quite make sense gramatically and is confusing, I'd change to either "Set focused window to" or even simplier "Focus window"

Agreed! Thanks for the feedback! :)
