### ISSUE TITLE
macOS Window title matches are not grabbing the right name of the window

### ISSUE THREAD

**Issue by mv-stns** [WarmUpTill/SceneSwitcher#979]
**Describe the bug**
When trying to configure a scene switch by focusing a specific window by its name, the plugin is not able to get the correct name

**To Reproduce**

1. Open Arc (Chromium-based browser) and VSCode.
2. Open Advanced Scene Switcher and create a macro based on window name.

See the following image for further bug explanation:
![Image](https://github.com/WarmUpTill/SceneSwitcher/assets/21103251/36ced578-cfb3-4657-b0aa-4ffa87510ad9)

(Arc Web Browser is also being recognized as "Window.")

**Expected behavior**
VSCode appearing when focused to i can switch between scenes based on the correct name.

**Logs**
[https://obsproject.com/logs/swBBn9zG3m1Ya31l](https://obsproject.com/logs/swBBn9zG3m1Ya31l)

**Version information**
 - OS: [macOS Sonoma 14.0]
 - OBS Version [30.0.2]
 - Plugin Version [1.24.2]

**Additional context**
-

**Comment by Annunakitty** [comment]
I recommend using "Process" for the condition instead of "Window" for switching scenes when a window is focused, it is more reliable.  Try this instead:

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/36653700/add6ad4c-606e-423a-9613-8cecc49a4908)

**Comment by mv-stns** [comment]
Thats definetly a nice workaround! tyvm!

**Comment by tvongerlach** [comment]
This workaround works great @Annunakitty. Thank you
