### ISSUE TITLE
Media Action - STOP all Media sources in a scene

### ISSUE THREAD

**Issue by miko3ed** [WarmUpTill/SceneSwitcher#981]
**Describe the solution you'd like**
I would like an action that can initiate a STOP command to all media sources in a specific scene.
Right now you have to manually set the Macro action to specific sources to initiate STOP commands, and I have a use case where I need to STOP Media playback for all Image Slideshow sources in a scene

**Comment by WarmUpTill** [comment]
A build with the requested functionality will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7511701783?pr=985

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/e2dd0194-0521-4d05-a25e-2802b7fd4996)

Note that this build does not contain the show / hide transition changes pointed out in your other issue.
Let me know if you need a build containing both.

**Comment by miko3ed** [comment]
This does appear to work with video media sources. I should have clarified in my original request that I am hoping to use this with Image Slideshow sources as well

**Comment by miko3ed** [comment]
Also, if it isn't too much trouble, I need a build with this enhancement, https://github.com/WarmUpTill/SceneSwitcher/issues/965, and https://github.com/WarmUpTill/SceneSwitcher/issues/982 if it's possible to get a build with all three

**Comment by WarmUpTill** [comment]
Sure that is possible!
Should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7545926888
