### ISSUE TITLE
Strange behavior using Transition for setting a source transition to fade

### ISSUE THREAD

**Issue by miko3ed** [WarmUpTill/SceneSwitcher#982]
**Describe the bug**
When I use the Transition action to set a source's show/hide transition it creates a graphical anomaly with the fade type whereby an image or image slideshow (those are the only types I tested with) on fade out the image temporarily transforms to a smaller version of the image. If I set the show/fade transition manually it works as expected. You can see this behavior in the video file I am attaching to this ticket. I show the correct functioning of the source transitions and then execute a macro that changes them (starting at 20seconds in the video) and then I activate and deactivate the source to show the anomaly, I then reset the transitions manually and it goes back to the expected behavior.

**Additional context**
If I specify the source that needs to be adjusted then it works correctly. I have tried using Source Name, Sources of Type, Sources in Index Range, Source Name matches pattern, as well as Source with Index. It seems like the behavior only occurs for an instance where multiple sources are modified. If any of these modified a single source the behavior worked as expected.

**To Reproduce**
1. Create a scene with multiple IMAGE sources
2. Create a macro with the Transition action set to Modify source show transition targeting your created scene and set to All Sources
3. Add another action set to Modify source hide transition targeting your created scene and set to All Sources
4. Execute the macro
5. enable a source, wait 1 second, disable a source

**Version information**
 - OS: [e.g. Windows 11]
 - OBS Version [e.g. 30.0.2]
 - Plugin Version [[SceneSwitcher-windows-x64-01384bdfd](https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7433201365/artifacts/1151855467)]

[2024-01-12 14-21-22_1.webm](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/bc390797-0745-428e-97a4-9c05bd4cee63)

**Comment by WarmUpTill** [comment]
Thanks for pointing out this issue!
It should be fixed with this build:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7511557263?pr=984

Let me know if that resolved the issue on your side! :)

**Comment by miko3ed** [comment]
awesome! much appreciated. I have an unrelated question, these builds you have been doing for the tickets I open, are they just the current version plus the fix/enhancement for that particular ticket or is it a cumulative build that includes other fixes/enhancements from other tickets as well?

**Comment by WarmUpTill** [comment]
They are based on the "master" branch + fixes for the particular issue at hand.
The "master" branch is not the same as the last official release and additional changes.

Hope that clears things up! :)

**Comment by miko3ed** [comment]
Thanks, yeah, I understand. I'll keep an eye out for the next release :)

**Comment by WarmUpTill** [comment]
Just to confirm:
Does the mentioned build resolve your problem?
In that case I will merge the changes / close this issue :)

**Comment by miko3ed** [comment]
Yes, looks to be fixed, thank you
