### ISSUE TITLE
Invalid account used for Twitch chat action right after switching accounts

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#988]
**Describe the bug**
I chose my bot account to send a Twitch message, but my main account is sending it:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/3606072/328ead9b-1dbd-429f-be26-387ef70e305e)

**To Reproduce**
1. Set different account to send message to your Twitch channel
2. Message is sent as main account (or channel owner?)
3. Restart OBS and it'll work fine

**Expected behavior**
Message should be sent by chosen account

**Logs**
No logs, but I'm pretty sure what's missing is that chat connection isn't reset when account/token changes

**Version information**
 - OS: WIndows 10
 - OBS Version: 30.0.2
 - Plugin Version: a40f175af537397f8970fb5253d8393df1d4acac

**Comment by Destroy666x** [comment]
Yep, `ResetConnection` is missing in few places:
- https://github.com/WarmUpTill/SceneSwitcher/blob/master/src/macro-external/twitch/macro-action-twitch.cpp#L537
- https://github.com/WarmUpTill/SceneSwitcher/blob/master/src/macro-external/twitch/macro-action-twitch.cpp#L726

**Comment by WarmUpTill** [comment]
Ah thanks for finding that issue and fixing it! :)
