### ISSUE TITLE
Opencv library fails with new install of AdvSS and OBS

### ISSUE THREAD

**Issue by actor125** [WarmUpTill/SceneSwitcher#991]
Just did as fresh install of OBS from the official repository (30.0.1) and a fresh install of Advanced Scene Switcher 1.24.2. (.deb) When I attempt to open Adv Scene Switcher I get an error:

Loading of the following plugin libraries was unsuccessful, which could result in some Advanced Scene Switcher functions not being available:
/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so

As Many of my Macros rely on opencv, I would like to fix the problem. When I do try to write a new macro Video is no longer an option in The "Source" drop down menu.

I have checked the directory and  the opencv.so file is there.
I have tried uninstalling and reinstalling AdvSS with the 1.24.1 release with the same results.
I have tried uninstalling OBS and AdvSS and reinstalling with the same results.

**Comment by actor125** [comment]
Thank you for your help! I was away from my computer for the weekend. I didn't have open cv installed. 
I didn't have to install it when i built my stream before so I thought it was bundled with Ubuntu. I had probably installed it as a dependency for something else on the computer a long time ago.
After installing the opencv- dev from Ubuntu's repos and restarting obs it worked! Thanks for helping me see what had missed!

**Comment by WarmUpTill** [comment]
Great! Glad to hear that everything is working! :)
