### ISSUE TITLE
"Wait process to exit" is gone?

### ISSUE THREAD

**Issue by themegaxandy** [WarmUpTill/SceneSwitcher#993]
**Describe the bug**
I have updated the plugin to the latest version, and the option for "wait process to exit" (#954) doesn't exist anymore.

**To Reproduce**
1. Create a macro with any name
2. Create a "run" action.
3. Click on advanced.
4. See that the "wait process to exit" (#954) isn't there.

**Version information**
 - OS: Windows 11 22H2
 - OBS Version 29
 - Plugin Version 1.24.2

**Comment by WarmUpTill** [comment]
This functionality was not part of any official release yet.
So if you downloaded the last official release it is to be expected that you cannot find this option.

You can use the latest build from the master branch instead:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7602660776

**Comment by themegaxandy** [comment]
Ok, thank you.
