### ISSUE TITLE
[Feature Request] Add temp variable support to Websocket condition 

### ISSUE THREAD

**Issue by BenJamesAndo** [WarmUpTill/SceneSwitcher#996]
I'd like to be able to store a Websocket Request value as a variable. I've tried via Set to macro property and Set to condition value, but neither do anything.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/44917135/a54f23d5-5bdd-4ce4-af81-b89fdb6d1571)

If there's a better way of doing this let me know. My use case is to use Bitfocus Companion to grab a bunch of info from various integrations and then feed that info into OBS. Because the Websocket Request may change a bit, it's not realistic to set up a separate macro for each different piece of information that would get sent.

**Comment by WarmUpTill** [comment]
A build with the option to set a variable to the received websocket message will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7672727072

![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/54f726a5-7b2d-4406-a1de-5c750f4e2e8a)

The "Set to condition value" option should work as well, but is quite confusing to use as the "Current value" field will _only_ display the current value (which will be empty most of the time unless you are constantly receiving messages matching the given pattern) and not the _last_ value non-empty value.

**Comment by BenJamesAndo** [comment]
Tested and works really well. Thank you!
Yes I'm fine to use Set to macro property instead of Set to condition value. Reading through other discussions it seems Set to macro property is the better and newer way of doing it anyway.
