### ISSUE TITLE
Advanced Scene Switcher cr

### ISSUE THREAD

**Issue by ohheyitsak** [WarmUpTill/SceneSwitcher#997]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Please provide a log of your issue with verbose logging enabled (See General tab of the plugin).  
In case of a crash, please also include the corresponding crash log.  
See [here](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/) for a description where to find the log files and how to share them.  
Please share the currently used plugin settings by exporting them them to a file (See General tab of the plugin).  

**Version information**
 - OS: [e.g. Windows 10]
 - OBS Version [e.g. 27.1.3]
 - Plugin Version [e.g. 1.17.1]

**Additional context**

**Comment by WarmUpTill** [comment]
I think you accidentally created an incomplete issue.
At the moment it only contains the template data.
